import type { QuizQuestion } from "@/lib/quizTypes";

function q(
  id: string,
  question: string,
  options: [string, string, string, string],
  correctIndex: 0 | 1 | 2 | 3,
  explanation: string
): QuizQuestion {
  return { id, question, options, correctIndex, explanation };
}

/** 200 hard questions — randomized section/chapter/course/final draws */
export const CYBERSECURITY_BASICS_BANK: QuizQuestion[] = [
  q("cyber-ch01-q01", "A payroll outage during month-end threatens which CIA pillar most directly?", ["Availability","Confidentiality only","Integrity only","None—outages are confidentiality issues"], 0, "Service interruption is primarily an availability impact."),
  q("cyber-ch01-q02", "An attacker alters invoice bank details in the ERP. Primary harm:", ["Integrity—data was modified without authorization","Availability","Confidentiality only","Physical security"], 0, "Unauthorized modification is integrity failure."),
  q("cyber-ch01-q03", "Customer PII posted on a paste site indicates loss of:", ["Confidentiality","Availability","Integrity only","Accountability"], 0, "Unauthorized disclosure is confidentiality breach."),
  q("cyber-ch01-q04", "Risk = threat × vulnerability × impact in qualitative models helps:", ["Prioritize controls where combinations are highest","Eliminate all threats","Avoid documentation","Replace MFA"], 0, "Risk models focus limited resources."),
  q("cyber-ch01-q05", "Residual risk after controls is:", ["Risk remaining accepted or transferred","Zero always if compliant","Only legal risk","Unmeasurable"], 0, "Perfect security is unattainable; residual remains."),
  q("cyber-ch01-q06", "A BIA finds RPO 1 hour for billing DB. Meaning:", ["Max acceptable data loss is one hour of transactions","Recovery must finish in one hour always","One backup per year","Password rotation hourly"], 0, "RPO defines tolerable data loss window."),
  q("cyber-ch01-q07", "Compensating control when patching legacy OT is impossible:", ["Network isolation and monitoring at boundaries","Connect OT to guest Wi-Fi","Disable safety interlocks","Share admin password"], 0, "Compensating controls reduce risk when primary fix lags."),
  q("cyber-ch01-q08", "Single point of failure in auth IdP affects:", ["Availability and potentially all apps relying on SSO","Only printers","DNS TTL","Coffee supply"], 0, "Central IdP failure is widespread outage."),
  q("cyber-ch01-q09", "Defense in depth means:", ["Multiple independent controls so one failure does not collapse security","One very strong firewall only","Security through obscurity","Removing layers for speed"], 0, "Layers contain failures."),
  q("cyber-ch01-q10", "Least privilege limits:", ["Access rights to minimum needed for role","Password length only","Internet speed","Log retention"], 0, "Least privilege reduces abuse blast radius."),
  q("cyber-ch01-q11", "Risk acceptance requires:", ["Documented approval by risk owner with rationale","Verbal nod only","Ignoring risk","Automatic for all high risks"], 0, "Acceptance is a governed decision."),
  q("cyber-ch01-q12", "Threat modeling STRIDE 'Information Disclosure' maps to:", ["Confidentiality loss","Availability","Repudiation only","Elevation of desk"], 0, "Information disclosure is confidentiality."),
  q("cyber-ch01-q13", "Quantitative risk annual loss expectancy (ALE) = SLE × ARO. Use:", ["Budgeting control investments with dollar estimates","Replacing qualitative entirely always","Eliminating IR","Disabling logs"], 0, "ALE helps financial justification."),
  q("cyber-ch01-q14", "Shared admin account violates accountability and:", ["Increases integrity/confidentiality risk via untraced actions","Improves availability","Required for zero trust","Fixes SPF"], 0, "Shared creds obscure actor identity."),
  q("cyber-ch01-q15", "Downtime cost $50k/hour makes availability controls:", ["Financially justified at higher priority","Irrelevant","Less important than posters","Optional"], 0, "Impact drives prioritization."),
  q("cyber-ch01-q16", "Regulatory fine risk is part of:", ["Overall risk impact alongside operational harm","Only legal dept unrelated to security","SPF configuration","Printer speed"], 0, "Compliance consequences are impact factors."),
  q("cyber-ch01-q17", "Kerckhoffs's principle implies algorithm details may be public if:", ["Key secrecy is maintained","No keys exist","Security through obscurity suffices","MD5 is used"], 0, "System security should not rely on secret design alone."),
  q("cyber-ch01-q18", "An asset inventory supports risk management by:", ["Knowing what to protect and value","Decorating office","Slowing patches","Removing MFA"], 0, "You cannot protect unknown assets."),
  q("cyber-ch01-q19", "Third-party processor breach affects your risk as:", ["Potential confidentiality/availability impact to your customers","No relationship","Automatic patch","SPF only"], 0, "Vendor incidents become your business risk."),
  q("cyber-ch01-q20", "Heat map 5×5 risk matrix plots:", ["Likelihood vs impact for prioritization","Coffee vs tea","Desk color","DNS TTL"], 0, "Heat maps visualize prioritization."),
  q("cyber-ch02-q01", "MITRE ATT&CK tactic 'Initial Access' includes:", ["Phishing and exploitation of public-facing apps among others","Only impact","Only recovery","Only printing"], 0, "Initial Access is entry to environment."),
  q("cyber-ch02-q02", "Technique T1059.001 is:", ["PowerShell execution","DNS tunneling only","Physical theft","WEP cracking"], 0, "T1059.001 subtechnique is PowerShell."),
  q("cyber-ch02-q03", "APT groups differ from opportunistic criminals by:", ["Objectives, resources, and sustained campaigns","Never using malware","Only attacking printers","Always announcing themselves day one"], 0, "APTs are defined by persistence and capability."),
  q("cyber-ch02-q04", "Cyber kill chain 'actions on objectives' is:", ["Achieving attacker goals like exfiltration","Patching systems","User training","SPF alignment"], 0, "Final stage realizes intent."),
  q("cyber-ch02-q05", "Diamond Model infrastructure vertex captures:", ["C2 servers, domains, IPs used","Office seating","Coffee brands","HR titles"], 0, "Infrastructure is adversary tooling."),
  q("cyber-ch02-q06", "Nation-state actor stealing defense designs prioritizes:", ["Confidentiality/espionage over quick ransom","Gift card fraud only","Website defacement only","Printer repair"], 0, "Espionage seeks secrets."),
  q("cyber-ch02-q07", "Ransomware operator MITRE tactic at encryption stage:", ["Impact","Reconnaissance only","Resource development only","None"], 0, "Encryption affects availability/data—Impact tactic."),
  q("cyber-ch02-q08", "MITRE mitigation M1049 recommends:", ["Antivirus/EDR on endpoints","Disable logging","Public RDP","Shared passwords"], 0, "M1049 is anti-malware deployment."),
  q("cyber-ch02-q09", "T1566 phishing subtechniques include:", ["Spearphishing attachment and link","Only physical theft","Only BGP hijack always","Only TLS downgrade"], 0, "T1566 covers multiple phish delivery modes."),
  q("cyber-ch02-q10", "Threat intel enriches ATT&CK with:", ["Campaign IOCs and actor TTP mappings","Coffee recipes","Desk manuals","SPF only"], 0, "Intel operationalizes framework."),
  q("cyber-ch02-q11", "Living off the land maps to:", ["Execution using legitimate system tools","Only custom malware","Only hardware implants","Only fax"], 0, "LOTL abuses trusted binaries."),
  q("cyber-ch02-q12", "MITRE ICS ATT&CK relevant when:", ["Protecting OT/SCADA environments","Only marketing sites","Only HR surveys","Never"], 0, "ICS matrix covers OT threats."),
  q("cyber-ch02-q13", "Defender uses ATT&CK for:", ["Gap analysis of detection coverage","Replacing firewalls only","Eliminating training","Disabling SIEM"], 0, "Matrix shows uncovered techniques."),
  q("cyber-ch02-q14", "T1078 valid accounts technique highlights:", ["Stolen or default creds bypassing malware defenses","Only zero-days","Only USB drops","Only WEP"], 0, "Valid accounts are stealthy access."),
  q("cyber-ch02-q15", "Campaign uses Cobalt Strike beacons mapped to:", ["Command and Control tactic","Only exfiltration","Only patching","Only awareness"], 0, "Beacons are C2."),
  q("cyber-ch02-q16", "Threat actor motivation 'financial' aligns with:", ["Fraud, ransomware, credential markets","Espionage of state secrets only","Academic research only","Improving SPF"], 0, "Financial actors monetize access."),
  q("cyber-ch02-q17", "MITRE technique metadata includes detection ideas to:", ["Guide SIEM rule creation","Replace IR","Disable MFA","Remove logs"], 0, "Detection fields help defenders."),
  q("cyber-ch02-q18", "ATT&CK Navigator layers show:", ["Coverage heatmaps per technique","Physical office maps","Coffee strength","DNS only"], 0, "Navigator visualizes coverage."),
  q("cyber-ch02-q19", "Supply-chain as initial access increasing means defenders should:", ["Verify software integrity and vendor security","Trust all updates blindly","Disable code signing","Stop patching"], 0, "Supply-chain needs integrity controls."),
  q("cyber-ch02-q20", "Mapping incident findings to ATT&CK aids:", ["Consistent reporting and control selection","Marketing only","Hiding TTPs from SOC","Deleting tickets"], 0, "Common language improves response."),
  q("cyber-ch03-q01", "OAuth authorization code flow exchanges code for tokens:", ["After user authenticates at IdP—client never sees user password","Without TLS","Using MD5","By emailing password"], 0, "Code flow keeps user creds at IdP."),
  q("cyber-ch03-q02", "MFA TOTP 30-second window accepts small skew to handle:", ["Clock drift between phone and server","Eliminating seed secrecy","Disabling HTTPS","Publishing OTP"], 0, "Time windows accommodate drift."),
  q("cyber-ch03-q03", "FIDO2/WebAuthn resists phishing because:", ["Private key signs challenge bound to origin","Password sent in email","Uses SMS only","Shares seed"], 0, "Cryptographic origin binding stops replay on fake sites."),
  q("cyber-ch03-q04", "SAML assertion must be validated for signature and:", ["Audience, NotOnOrAfter, and issuer","User favorite color","Desk number","Printer speed"], 0, "Assertion validation prevents token abuse."),
  q("cyber-ch03-q05", "Refresh token rotation limits:", ["Replay window if refresh token stolen","All phishing","Need for TLS","Logging"], 0, "Rotation shrinks stolen token utility."),
  q("cyber-ch03-q06", "Kerberos ticket-granting ticket (TGT) proves:", ["User authenticated to domain for service ticket requests","Internet speed","SPF alignment","Coffee quality"], 0, "TGT is core Kerberos auth artifact."),
  q("cyber-ch03-q07", "Conditional access policy blocks legacy auth protocols because:", ["They bypass MFA","Improve latency","Required by printers","Fix DNS"], 0, "Legacy protocols often lack MFA support."),
  q("cyber-ch03-q08", "OAuth scope `Mail.ReadWrite` excessive for calendar app means:", ["Violates least privilege—request minimal scopes","Better security","Required always","Fixes ransomware"], 0, "Minimize scopes."),
  q("cyber-ch03-q09", "Password spraying avoids lockout by:", ["Few passwords across many accounts","Many passwords one account until lock","Disabling MFA","Using Argon2"], 0, "Spray distributes guesses."),
  q("cyber-ch03-q10", "Passkey synced via platform cloud relies on:", ["Vendor secure enclave/encryption design","Plaintext upload","ROT13","Public posting of keys"], 0, "Understand provider security model."),
  q("cyber-ch03-q11", "SAML XML signature wrapping attack exploited:", ["Improper signature validation implementations","TLS 1.3","Strong MFA always","SPF"], 0, "Implementation flaws enabled XML attacks historically."),
  q("cyber-ch03-q12", "OAuth implicit flow deprecated because:", ["Tokens exposed in browser—use code flow with PKCE","Too secure","Required for FIDO","Fixes Wi-Fi"], 0, "Implicit flow unsafe for modern apps."),
  q("cyber-ch03-q13", "PKCE protects mobile/public OAuth clients by:", ["Proof key for code exchange preventing interception","Sharing client secret in app","Disabling TLS","MD5 challenge"], 0, "PKCE secures public clients."),
  q("cyber-ch03-q14", "Smart card auth provides:", ["Strong multi-factor (something you have + PIN)","Weaker than password only","No audit trail","SPF fix"], 0, "Cards are strong factors."),
  q("cyber-ch03-q15", "Session fixation prevented by:", ["Regenerating session ID after login","Reusing same ID","Disabling HTTPS","Long-lived ID forever"], 0, "New session ID post-auth stops fixation."),
  q("cyber-ch03-q16", "IdP session timeout reduces:", ["Window for hijacked session abuse","Need for MFA","Logging","Patches"], 0, "Timeouts limit stolen session use."),
  q("cyber-ch03-q17", "OAuth consent phishing grants:", ["Malicious app access tokens to user data","Hardware keys","Firewall rules","Backups"], 0, "Consent abuse steals API access."),
  q("cyber-ch03-q18", "AD password spray detection:", ["Many account failures with few passwords from one IP","One failure total","SPF fail","TLS expiry"], 0, "Pattern distinguishes spray."),
  q("cyber-ch03-q19", "Break-glass accounts require:", ["Monitoring, rare use, and strong storage","Daily use","Posting in chat","No MFA"], 0, "Break-glass is emergency only."),
  q("cyber-ch03-q20", "Authentication assurance level (NIST 800-63B AAL3) approximates:", ["Hardware-based phishing-resistant MFA","Password only","Security questions","Email OTP alone"], 0, "AAL3 is highest authenticator assurance."),
  q("cyber-ch04-q01", "TLS 1.3 removes:", ["Weak ciphers like RSA key exchange in favor of forward secrecy","All encryption","Certificates","MFA"], 0, "TLS 1.3 improves crypto defaults."),
  q("cyber-ch04-q02", "Certificate pinning in mobile app mitigates:", ["Fraudulent CA-issued certs for MITM","Phishing email","Ransomware","Weak passwords only"], 0, "Pinning trusts only expected cert/public key."),
  q("cyber-ch04-q03", "HSTS header protects:", ["Users from SSL stripping by forcing HTTPS","Email SPF","DNS cache","Printer"], 0, "HSTS reduces downgrade attacks."),
  q("cyber-ch04-q04", "VPN IPsec ESP provides:", ["Confidentiality and integrity for IP packets","Only routing","Password storage","SPF"], 0, "ESP encrypts tunnel payloads."),
  q("cyber-ch04-q05", "Split horizon DNS in VPN ensures:", ["Internal names resolve correctly when tunneled","Public DNS for corp domains always","Attacker DNS","Disable DNS"], 0, "Split DNS supports hybrid access."),
  q("cyber-ch04-q06", "Firewall default deny with allowlist:", ["Permits only required services","Allows all then block","Disables logging","Open RDP worldwide"], 0, "Allowlist minimizes exposure."),
  q("cyber-ch04-q07", "WAF blocks SQLi by:", ["Inspecting HTTP for injection patterns","Encrypting database","Rotating passwords only","SPF"], 0, "WAF is app-layer filter."),
  q("cyber-ch04-q08", "Network segmentation limits:", ["Lateral movement after initial compromise","Phishing email","User training","Coffee"], 0, "Segmentation contains spread."),
  q("cyber-ch04-q09", "DNS over HTTPS (DoH) corporate policy may:", ["Force corporate resolver to maintain visibility","Ignore DNS entirely","Disable all DNS","Publish passwords"], 0, "DoH can blind corporate monitoring if unmanaged."),
  q("cyber-ch04-q10", "BGP route leak impact:", ["Availability and potential traffic interception","Only confidentiality of disks","MFA","Argon2"], 0, "BGP issues affect routing/trust."),
  q("cyber-ch04-q11", "TLS inspection requires:", ["Enterprise trust of re-signing CA on endpoints","Disabling TLS","Sharing private keys online","Removing MFA"], 0, "Inspection needs trusted MITM CA."),
  q("cyber-ch04-q12", "Zero trust reduces implicit trust in:", ["Flat internal networks","Encrypted TLS","MFA","Backups"], 0, "Internal LAN trust is reduced."),
  q("cyber-ch04-q13", "Port 445 SMB exposed to internet is:", ["Critical misconfiguration—block immediately","Required for cloud","Best practice","SPF fix"], 0, "SMB should not be internet-facing."),
  q("cyber-ch04-q14", "Mutual TLS (mTLS) authenticates:", ["Both client and server with certificates","Only users via password","Only DNS","Printers"], 0, "mTLS is two-way cert auth."),
  q("cyber-ch04-q15", "DDoS scrubbing center role:", ["Absorb and filter attack traffic before origin","Encrypt laptops","Store passwords","Disable IR"], 0, "Scrubbing protects availability."),
  q("cyber-ch04-q16", "NAC (802.1X) on wired ports provides:", ["User/device authentication before network access","WEP keys","Open access","Shared password on poster"], 0, "NAC controls L2 admission."),
  q("cyber-ch04-q17", "Proxy with authentication for outbound web:", ["Identifies users and applies policy","Removes need for TLS","Disables logging","Public admin"], 0, "Proxies enable egress control."),
  q("cyber-ch04-q18", "IPv6 extension headers abused for:", ["Evasion of some security devices—ensure v6 inspection parity","Improving SPF","Eliminating MFA","Faster passwords"], 0, "v6 features can evade naive tools."),
  q("cyber-ch04-q19", "Site-to-site VPN between cloud VPC and datacenter:", ["Extends hybrid connectivity with encryption","Replaces IAM","Removes need for segmentation","Disables monitoring"], 0, "VPN links hybrid networks securely."),
  q("cyber-ch04-q20", "Network baseline anomaly: workstation scanning /24 on 445 suggests:", ["Lateral recon—investigate endpoint","Backup job always","SPF","TLS renewal"], 0, "Internal scanning is suspicious."),
  q("cyber-ch05-q01", "EDR collects:", ["Process, file, registry, network telemetry on endpoint","Only firewall logs","Coffee orders","SPF"], 0, "EDR provides host visibility."),
  q("cyber-ch05-q02", "Antivirus signature-only weakness:", ["Misses new malware without signatures","Stops all APTs","Replaces patching","Fixes BEC"], 0, "Signatures need updates."),
  q("cyber-ch05-q03", "Application allow-listing on servers:", ["Permits only approved binaries to run","Allows any exe","Disables logging","Removes MFA"], 0, "Allow-list prevents unknown execution."),
  q("cyber-ch05-q04", "Host firewall enabled on laptops:", ["Blocks unwanted inbound on untrusted networks","Useless","Replaces EDR","Disables VPN"], 0, "Host firewall helps remote workers."),
  q("cyber-ch05-q05", "Disk encryption (BitLocker/FileVault) protects:", ["Data at rest if device stolen","Data in transit only","Phishing","DNS"], 0, "Encryption protects lost/stolen media."),
  q("cyber-ch05-q06", "MDM can remote wipe corporate data on:", ["Lost mobile device","All internet traffic globally","DNS servers","Printers only"], 0, "MDM supports mobile containment."),
  q("cyber-ch05-q07", "Local admin rights on workstations increase:", ["Malware impact and persistence ease","Security always","MFA strength","SPF"], 0, "Admin rights expand blast radius."),
  q("cyber-ch05-q08", "EDR alert: suspicious PowerShell encoded command. Action:", ["Isolate host and analyze script block logs","Ignore","Disable EDR","Pay ransom"], 0, "Encoded PowerShell is common attack pattern."),
  q("cyber-ch05-q09", "Patch Tuesday cadence addresses:", ["Known vulnerability exploitation risk","Phishing only","Physical theft","SPF"], 0, "Patching closes exploit paths."),
  q("cyber-ch05-q10", "USB device control policy blocks:", ["Unauthorized storage to reduce exfil/infil","All keyboards","Monitors","TLS"], 0, "USB control limits media risk."),
  q("cyber-ch05-q11", "Credential Guard isolates:", ["LSA secrets on supported Windows versions","Email SPF","DNS TTL","Printers"], 0, "Credential Guard protects secrets."),
  q("cyber-ch05-q12", "EDR rollback feature can:", ["Remediate certain malicious changes automatically","Replace backups","Disable IR","Remove MFA"], 0, "Rollback aids quick remediation."),
  q("cyber-ch05-q13", "Hardening baseline (CIS) provides:", ["Benchmark settings reducing attack surface","Marketing text","Coffee","SPF only"], 0, "Benchmarks standardize hardening."),
  q("cyber-ch05-q14", "Kernel exploit on unpatched endpoint leads to:", ["Privilege escalation—prioritize critical patches","Better performance","SPF fix","No risk"], 0, "Kernel bugs enable full compromise."),
  q("cyber-ch05-q15", "EDR false positive tuning uses:", ["Exclusions with risk acceptance documentation","Disable EDR","Alert on everything","Delete logs"], 0, "Tune thoughtfully."),
  q("cyber-ch05-q16", "Application control via AppLocker/WDAC:", ["Restricts executable code sources","Opens all scripts","Disables TLS","Shares passwords"], 0, "Policy restricts code execution."),
  q("cyber-ch05-q17", "Browser isolation for risky sites:", ["Runs session in disposable container","Shares cookies globally","Disables HTTPS","Removes MFA"], 0, "Isolation contains web threats."),
  q("cyber-ch05-q18", "Tamper protection on EDR prevents:", ["Malware disabling agent","User productivity always","Logging","Patches"], 0, "Tamper protection keeps agent alive."),
  q("cyber-ch05-q19", "Endpoint logs forwarded to SIEM enable:", ["Correlation with network and identity events","Nothing","Slower internet","SPF only"], 0, "Central correlation improves detection."),
  q("cyber-ch05-q20", "BYOD without containerization risk:", ["Personal malware accessing corp mail data","Improves security","Required","Fixes Wi-Fi"], 0, "BYOD needs separation."),
  q("cyber-ch06-q01", "AES-256-GCM provides:", ["Confidentiality and authenticated encryption","Only hashing","Password storage without salt","DNSSEC"], 0, "GCM is AEAD mode."),
  q("cyber-ch06-q02", "RSA 2048-bit keys used for:", ["Asymmetric encryption/signing—being phased down for TLS in favor of ECC","Symmetric bulk encryption of disks only","WEP","SPF"], 0, "RSA is asymmetric; ECC often preferred now."),
  q("cyber-ch06-q03", "SHA-256 is:", ["Cryptographic hash function","Encryption algorithm","VPN protocol","MFA factor"], 0, "SHA-256 hashes data."),
  q("cyber-ch06-q04", "Salt in password hashing prevents:", ["Rainbow table attacks","Brute force entirely","Phishing","DDoS"], 0, "Salts defeat precomputed tables."),
  q("cyber-ch06-q05", "TLS forward secrecy ensured by:", ["Ephemeral Diffie-Hellman key exchange","Static RSA key exchange only","MD5","Plain HTTP"], 0, "Ephemeral keys protect past sessions if long-term key stolen."),
  q("cyber-ch06-q06", "Public key encrypts small data; bulk data uses symmetric key because:", ["Performance—hybrid cryptography","Laws forbid symmetric","AES is broken","Hashes encrypt files"], 0, "Hybrid combines strengths."),
  q("cyber-ch06-q07", "Digital signature proves:", ["Integrity and authenticity from holder of private key","Confidentiality of message body always","Anonymous sender","SPF alignment"], 0, "Signatures verify origin and tampering."),
  q("cyber-ch06-q08", "Certificate Authority role:", ["Issues and signs certificates binding keys to identities","Stores user passwords","Blocks phishing automatically","Runs SIEM"], 0, "CAs anchor PKI trust."),
  q("cyber-ch06-q09", "Expired TLS cert on website causes:", ["Browser warnings and failed connections","Stronger security","Automatic MFA","Faster DNS"], 0, "Expiry breaks trust chain."),
  q("cyber-ch06-q10", "Quantum computers threaten:", ["Current asymmetric algorithms eventually—plan PQ migration","AES-256 immediately today","All hashing now","Physical locks"], 0, "PQ threat is to asymmetric mainly long-term."),
  q("cyber-ch06-q11", "HMAC-SHA256 used for:", ["Message authentication with secret key","Disk encryption at rest only","Email marketing","WEP"], 0, "HMAC provides keyed integrity."),
  q("cyber-ch06-q12", "ECDSA on P-256 curve provides:", ["Digital signatures with smaller keys than RSA","Password hashing","VPN only","SPF"], 0, "ECC efficient signatures."),
  q("cyber-ch06-q13", "Encrypting data at rest on S3 with KMS means:", ["Keys managed by cloud HSM/policy","No encryption happens","Public bucket OK","Password in bucket name"], 0, "KMS governs encryption keys."),
  q("cyber-ch06-q14", "MD5 for file integrity today is:", ["Deprecated—use SHA-256 or stronger","Best practice","Required by TLS 1.3","Same as Argon2"], 0, "MD5 is broken for collision resistance."),
  q("cyber-ch06-q15", "PGP email encryption provides:", ["End-to-end confidentiality between correspondents","Server-side scanning only","SPF","Firewall rules"], 0, "PGP is E2E email crypto."),
  q("cyber-ch06-q16", "Key escrow for enterprise recovery:", ["Trade-off between availability and pure zero-knowledge","Always evil illegal","Replaces MFA","Stops IR"], 0, "Escrow enables recovery with policy risk."),
  q("cyber-ch06-q17", "Cryptographic agility means:", ["Ability to swap algorithms as standards evolve","Never change algorithms","Use MD5 forever","Disable TLS"], 0, "Agility supports migrations like PQ."),
  q("cyber-ch06-q18", "Entropy source for keys must be:", ["Cryptographically secure random (CSPRNG)","Date of birth","Username","Clock only"], 0, "Weak entropy breaks keys."),
  q("cyber-ch06-q19", "Bit-flipping attack on unauthenticated encryption prevented by:", ["AEAD modes like GCM","ECB mode","ROT13","Compression only"], 0, "Authentication tags detect tampering."),
  q("cyber-ch06-q20", "TLS cipher suite TLS_AES_128_GCM_SHA256 indicates:", ["TLS 1.3 AEAD cipher","SSLv3","WEP","Cleartext"], 0, "Naming reflects TLS 1.3 AEAD."),
  q("cyber-ch07-q01", "Pretexting establishes:", ["Fabricated scenario to gain trust before request","Encryption","Patching","SPF"], 0, "Pretext sets the story."),
  q("cyber-ch07-q02", "Tailgating bypasses:", ["Physical access controls","TLS","MFA on VPN","DNSSEC"], 0, "Tailgating is physical social engineering."),
  q("cyber-ch07-q03", "Spearphishing uses:", ["Personalized lure from OSINT","Random lottery only","Hardware faults","BGP only"], 0, "Spearphish targets individuals."),
  q("cyber-ch07-q04", "Authority principle in social engineering:", ["Impersonating police/IT exec to coerce compliance","Using long passwords","Patching","Logging"], 0, "Authority pressures victims."),
  q("cyber-ch07-q05", "Urgency in vishing reduces:", ["Victim critical thinking","Attacker success always zero","MFA strength","Backups"], 0, "Urgency causes rash actions."),
  q("cyber-ch07-q06", "Baiting with infected USB labeled 'Salaries' exploits:", ["Curiosity","TLS 1.3","Argon2","SPF"], 0, "Baiting lures interaction."),
  q("cyber-ch07-q07", "Quid pro quo offer of 'free IT check' for password is:", ["Exchange-based scam","Legitimate service","Patch process","DNS fix"], 0, "Quid pro quo trades fake help for access."),
  q("cyber-ch07-q08", "CEO fraud wire transfer relies on:", ["Trust in executive authority + urgency","Exploiting CVE-2024 only","Wi-Fi deauth only","SPF"], 0, "BEC uses authority and urgency."),
  q("cyber-ch07-q09", "Security awareness reduces but does not eliminate:", ["Human error—layer technical controls too","All attacks 100%","Need for EDR","Logging"], 0, "Humans remain variable; defense in depth needed."),
  q("cyber-ch07-q10", "Red flags: unsolicited attachment from vendor:", ["Verify via known contact before open","Open immediately","Forward to all","Disable AV"], 0, "Verify unexpected attachments."),
  q("cyber-ch07-q11", "Social engineer researches LinkedIn for:", ["Names, roles, projects for credible pretext","Patch levels","TLS ciphers","Disk encryption only"], 0, "OSINT fuels credible lures."),
  q("cyber-ch07-q12", "Helpdesk vishing to reset MFA is:", ["High-impact attack path—harden verification","Impossible","Low risk","SPF fix"], 0, "Helpdesk is frequent target."),
  q("cyber-ch07-q13", "In-person impersonation as fire inspector tests:", ["Physical security awareness","SQLi","BGP","AES"], 0, "Physical impersonation bypasses cyber-only controls."),
  q("cyber-ch07-q14", "Deepfake audio in wire fraud increases:", ["Believability of urgent executive requests","Patch speed","Entropy","SPF"], 0, "Deepfakes enhance deception."),
  q("cyber-ch07-q15", "Reporting suspicious calls policy:", ["Hang up and call official number","Comply with codes","Email passwords","Install profile"], 0, "OOB verification stops vishing."),
  q("cyber-ch07-q16", "Social engineering penetration test differs from phish sim by:", ["Broader physical/phone pretexts with scope","Using real malware always","No rules","Attacking customers"], 0, "SE pen tests are controlled broader assessments."),
  q("cyber-ch07-q17", "Culture of blame after phish click causes:", ["Under-reporting future incidents","More reports","Better metrics","Stronger MFA"], 0, "Blame reduces reporting."),
  q("cyber-ch07-q18", "Multi-channel attack (email + call) increases:", ["Credibility—train verify on sensitive actions","Security automatically","SPF","TLS only"], 0, "Channels reinforce story."),
  q("cyber-ch07-q19", "Gift card payment request is:", ["Strong fraud indicator","Standard AP","IRS rule","Patch Tuesday"], 0, "Gift cards signal scam."),
  q("cyber-ch07-q20", "Physical clean desk policy reduces:", ["Shoulder surfing and document theft","DDoS","SQLi","BGP"], 0, "Clean desk protects confidential papers."),
  q("cyber-ch08-q01", "OWASP Top 10 includes:", ["Broken access control and injection among leading web risks","Only physical security","Only DNS","Only printers"], 0, "Top 10 lists prevalent web app risks."),
  q("cyber-ch08-q02", "SQL injection mitigated by:", ["Parameterized queries/ORM binding","Concatenating user input in SQL","Disabling HTTPS","MD5 passwords"], 0, "Parameterization separates code from data."),
  q("cyber-ch08-q03", "XSS stored in forum posts affects:", ["Other users viewing posts—persistent XSS","Only attacker browser","DNS only","SPF"], 0, "Stored XSS hits many victims."),
  q("cyber-ch08-q04", "CSRF forces victim browser to:", ["Submit unwanted authenticated request","Download patches","Enable MFA","Fix TLS"], 0, "CSRF abuses existing session."),
  q("cyber-ch08-q05", "Broken access control IDOR lets user:", ["Access another user's object by changing ID","Only see own data always","Patch servers","Improve SPF"], 0, "IDOR is insecure direct object reference."),
  q("cyber-ch08-q06", "Security misconfiguration example:", ["Default admin creds on cloud storage","Strong MFA everywhere","Argon2 passwords","Logging enabled"], 0, "Defaults left in place are misconfigurations."),
  q("cyber-ch08-q07", "SSRF from web app to cloud metadata can:", ["Steal IAM role credentials","Only slow page load","Fix phishing","Disable EDR"], 0, "Metadata SSRF is critical in cloud."),
  q("cyber-ch08-q08", "Insecure deserialization may lead to:", ["Remote code execution","Better performance only","SPF alignment","Stronger TLS"], 0, "Unsafe deserialization is RCE risk."),
  q("cyber-ch08-q09", "Content Security Policy (CSP) helps mitigate:", ["XSS by restricting script sources","SQLi in database","Physical theft","BGP leaks"], 0, "CSP limits script execution sources."),
  q("cyber-ch08-q10", "OWASP ASVS provides:", ["Application security verification requirements","Firewall rules only","Coffee standards","SPF"], 0, "ASVS is app security standard."),
  q("cyber-ch08-q11", "DevSecOps integrates security into:", ["CI/CD pipelines with SAST/DAST/dependency scan","Only production firefighting","HR onboarding","Marketing"], 0, "Shift-left testing finds issues early."),
  q("cyber-ch08-q12", "Dependency scanner finds:", ["Known vulnerable libraries (CVE) in bill of materials","Office layout","DNS TTL","Mouse DPI"], 0, "SCA identifies vulnerable components."),
  q("cyber-ch08-q13", "WAF in front of app:", ["Mitigates some attacks but does not replace secure coding","Fixes all bugs","Removes need for patches","Stores passwords plaintext"], 0, "WAF is compensating control."),
  q("cyber-ch08-q14", "JWT alg none vulnerability:", ["Accepting unsigned tokens—validate alg and signature","Feature of OAuth","Required","SPF fix"], 0, "Must enforce proper JWT validation."),
  q("cyber-ch08-q15", "Secrets in Git history require:", ["Rotation and secret scanning—even after deletion","Ignore","Publicize","Disable git"], 0, "History retains secrets."),
  q("cyber-ch08-q16", "Rate limiting login API prevents:", ["Brute force and credential stuffing","SQLi entirely alone","Phishing","DDoS globally always"], 0, "Rate limits slow guessing."),
  q("cyber-ch08-q17", "Secure cookie flags HttpOnly and Secure:", ["Reduce theft via XSS and enforce HTTPS transmission","Stop all attacks","Replace MFA","Fix DNS"], 0, "Cookie flags harden session cookies."),
  q("cyber-ch08-q18", "Threat modeling for new API should include:", ["Abuse cases and authZ for each endpoint","Only UI colors","Coffee","SPF"], 0, "Model before build."),
  q("cyber-ch08-q19", "Pen test finding critical RCE on internet-facing app priority:", ["Emergency patch/virtual patch and hunt for exploitation","Next year","Ignore","Disable logging"], 0, "RCE exposure is urgent."),
  q("cyber-ch08-q20", "OWASP API Security Top 10 addresses:", ["Broken object level auth and excessive data exposure","Only hardware","Only Wi-Fi","Only printers"], 0, "API list covers modern API risks."),
  q("cyber-ch09-q01", "NIST IR phases include:", ["Prepare, Detect & Analyze, Contain, Eradicate & Recover, Post-Incident","Only marketing","Only patching","Only training posters"], 0, "800-61 defines IR lifecycle."),
  q("cyber-ch09-q02", "Preparation includes:", ["Playbooks, contacts, tools, and training","Paying ransom upfront","Deleting logs","Public attribution"], 0, "Preparation enables effective response."),
  q("cyber-ch09-q03", "Containment short-term may:", ["Isolate host at network without immediate wipe","Publish all IOCs to press first","Disable all backups","Ignore legal"], 0, "Short-term containment stops spread."),
  q("cyber-ch09-q04", "Eradication ensures:", ["Malware/persistence removed and vectors closed","Only AV scan once","Assume contained equals clean","Stop monitoring"], 0, "Eradication removes footholds."),
  q("cyber-ch09-q05", "Recovery validates:", ["Systems restored from trusted images/backups and monitored","Blind restore of encrypted backups","No testing","Disable MFA"], 0, "Recovery needs integrity checks."),
  q("cyber-ch09-q06", "Post-incident lessons learned feed:", ["Control improvements and playbook updates","Nothing","Blame only","Delete SIEM"], 0, "PIR drives maturity."),
  q("cyber-ch09-q07", "Severity P1 typically means:", ["Active major business impact requiring immediate all-hands","Low priority newsletter","Printer jam","Slow Wi-Fi only"], 0, "P1 is highest operational urgency."),
  q("cyber-ch09-q08", "Chain of custody applies when:", ["Evidence may be used in legal proceedings","Never","Only marketing","Only phishing sims"], 0, "Legal cases need custody."),
  q("cyber-ch09-q09", "Volatile data collection order:", ["Memory and network state before powered-off disk imaging when feasible","Only paper shredder","DNS only","SPF"], 0, "Order of volatility guides collection."),
  q("cyber-ch09-q10", "Incident commander coordinates:", ["Technical, legal, comms, and business workstreams","Only one analyst silently","Attacker negotiations alone","Marketing only"], 0, "IC orchestrates response."),
  q("cyber-ch09-q11", "Regulatory notification timing (e.g., GDPR 72h) requires:", ["Legal assessment of notifiable personal data breach","Instant tweet","Ignore counsel","All spam is breach"], 0, "Notifications are legally conditioned."),
  q("cyber-ch09-q12", "Tabletop exercise tests:", ["Decision-making without live compromise","Production malware deployment","Customer data deletion","Disable EDR"], 0, "Tabletops are simulations."),
  q("cyber-ch09-q13", "Hot wash captures:", ["Immediate tactical lessons within days","Annual budget only","Office decor","DNS TTL"], 0, "Hot washes are near-real-time."),
  q("cyber-ch09-q14", "SOC tier-1 triage determines:", ["Severity and escalation path","Final legal verdict","Ransom payment approval alone","Marketing copy"], 0, "Triage routes incidents."),
  q("cyber-ch09-q15", "Playbook for ransomware includes:", ["Isolation, evidence preservation, backup restore decision tree","Pay immediately always","Delete logs first","Disable MFA"], 0, "Ransomware playbooks are specialized."),
  q("cyber-ch09-q16", "Communication during IR avoids:", ["Sharing sensitive TTP details that aid attacker","Any stakeholder updates","Legal involvement","Status tracking"], 0, "Balance transparency with opsec."),
  q("cyber-ch09-q17", "Metrics MTTD measures:", ["Time from compromise start to detection","Coffee time","Desk moves","SPF"], 0, "MTTD reflects detection capability."),
  q("cyber-ch09-q18", "Forensic image hashing verifies:", ["Integrity of evidence copies","Password strength","MFA","TLS version"], 0, "Hashes detect tampering."),
  q("cyber-ch09-q19", "Incident closure requires:", ["Validated eradication, recovery, and documented lessons","AV green on one host","Executive impatience","No monitoring"], 0, "Formal closure criteria prevent premature end."),
  q("cyber-ch09-q20", "NIST IR function 'Detect' aligns with SOC activities such as:", ["SIEM alerting, EDR detections, and user reports triaged into incidents","Annual poster design only","Hardware procurement","SPF record creation"], 0, "Detect covers analysis of events to determine incidents."),
  q("cyber-ch10-q01", "GDPR personal data is:", ["Information relating to identified or identifiable natural person","Only credit cards","Only servers","Only passwords"], 0, "GDPR defines broad personal data."),
  q("cyber-ch10-q02", "GDPR data processor must:", ["Process only on controller instructions with appropriate security","Sell data freely","Ignore breaches","Disable encryption"], 0, "Processors act on controller direction."),
  q("cyber-ch10-q03", "HIPAA PHI includes:", ["Health information linked to individual","Only public tweets","Only firewall logs","Only DNS"], 0, "PHI is identifiable health data."),
  q("cyber-ch10-q04", "HIPAA Security Rule requires:", ["Administrative, physical, technical safeguards for ePHI","Nothing for cloud","Only posters","Disable MFA"], 0, "Security Rule mandates safeguards."),
  q("cyber-ch10-q05", "GDPR right to erasure ('right to be forgotten') may conflict with:", ["Legal retention obligations—legal review required","Always delete backups instantly without plan","Security logs always erased immediately without policy","SPF records"], 0, "Erasure must balance other duties."),
  q("cyber-ch10-q06", "Data minimization principle:", ["Collect only data necessary for stated purpose","Collect everything possible","Share with any vendor","Publish databases"], 0, "Minimization limits exposure."),
  q("cyber-ch10-q07", "Breach notification under GDPR to supervisory authority often within:", ["72 hours of awareness where feasible","5 years","Never","Only if attacker emails"], 0, "72-hour notification is well-known GDPR requirement."),
  q("cyber-ch10-q08", "HIPAA Business Associate Agreement (BAA) required when:", ["Vendor handles PHI on covered entity's behalf","Buying coffee","Marketing blog","Public website only"], 0, "BAA governs vendor PHI handling."),
  q("cyber-ch10-q09", "Privacy Impact Assessment (DPIA) for high-risk processing:", ["Identifies mitigations before launch","Optional always","Replaces security","Disables logging"], 0, "DPIA is proactive risk analysis."),
  q("cyber-ch10-q10", "Cross-border EU data transfer may need:", ["Standard contractual clauses or adequacy decision","Random email attachment","Public paste","Disable TLS"], 0, "Transfers need legal mechanisms."),
  q("cyber-ch10-q11", "HIPAA minimum necessary standard:", ["Limit PHI access to job need","All staff access all PHI","Post PHI online","Share with advertisers"], 0, "Minimum necessary reduces exposure."),
  q("cyber-ch10-q12", "GDPR lawful bases include:", ["Consent, contract, legal obligation, legitimate interests among others","Only hacker consent","No basis needed","SPF"], 0, "Processing requires lawful basis."),
  q("cyber-ch10-q13", "Encryption of PHI at rest helps meet:", ["HIPAA addressable encryption implementation specification","Nothing","Marketing only","Eliminates IR"], 0, "Encryption is expected safeguard."),
  q("cyber-ch10-q14", "Data subject access request (DSAR) under GDPR:", ["Requires timely response providing copy of personal data","Ignore forever","Charge unlimited fee always","Delete subject"], 0, "DSAR rights enable transparency."),
  q("cyber-ch10-q15", "HIPAA breach risk assessment considers:", ["Probability PHI was compromised and impact","Only coffee spill","DNS TTL","Mouse DPI"], 0, "Risk assessment determines notification."),
  q("cyber-ch10-q16", "PCI DSS applies when:", ["Storing/processing/transmitting cardholder data","Never for e-commerce","Only paper","Only DNS"], 0, "PCI scope is payment card data."),
  q("cyber-ch10-q17", "Privacy by design means:", ["Embed privacy into systems from inception","Add privacy after breach only","Collect max data","Disable auth"], 0, "Proactive privacy engineering."),
  q("cyber-ch10-q18", "Records of processing activities (ROPA) under GDPR:", ["Documents processing purposes and data categories","Optional for all","Coffee log","SPF list"], 0, "ROPA demonstrates accountability."),
  q("cyber-ch10-q19", "HIPAA workforce training must cover:", ["Policies and procedures for PHI handling","Only executives exempt","Only interns","Never"], 0, "Training is administrative safeguard."),
  q("cyber-ch10-q20", "Regulatory fine risk should be in:", ["Risk register alongside operational impact","Ignored by security","Only marketing","SPF config"], 0, "Fines are part of risk impact."),
];
