import { CYBER_BASICS_CHAPTERS } from "../cyber-hard-meta.mjs";
import { fromChapters, Q } from "./_loader.mjs";

function pack(rows) {
  return rows.map(([q, a, w, c, e]) => Q(q, a, w, c, e));
}

export function buildBasicsChapters() {
  return fromChapters(CYBER_BASICS_CHAPTERS, [
    pack([
      ["A payroll outage during month-end threatens which CIA pillar most directly?", "Availability", ["Confidentiality only", "Integrity only", "None—outages are confidentiality issues"], 0, "Service interruption is primarily an availability impact."],
      ["An attacker alters invoice bank details in the ERP. Primary harm:", "Integrity—data was modified without authorization", ["Availability", "Confidentiality only", "Physical security"], 0, "Unauthorized modification is integrity failure."],
      ["Customer PII posted on a paste site indicates loss of:", "Confidentiality", ["Availability", "Integrity only", "Accountability"], 0, "Unauthorized disclosure is confidentiality breach."],
      ["Risk = threat × vulnerability × impact in qualitative models helps:", "Prioritize controls where combinations are highest", ["Eliminate all threats", "Avoid documentation", "Replace MFA"], 0, "Risk models focus limited resources."],
      ["Residual risk after controls is:", "Risk remaining accepted or transferred", ["Zero always if compliant", "Only legal risk", "Unmeasurable"], 0, "Perfect security is unattainable; residual remains."],
      ["A BIA finds RPO 1 hour for billing DB. Meaning:", "Max acceptable data loss is one hour of transactions", ["Recovery must finish in one hour always", "One backup per year", "Password rotation hourly"], 0, "RPO defines tolerable data loss window."],
      ["Compensating control when patching legacy OT is impossible:", "Network isolation and monitoring at boundaries", ["Connect OT to guest Wi-Fi", "Disable safety interlocks", "Share admin password"], 0, "Compensating controls reduce risk when primary fix lags."],
      ["Single point of failure in auth IdP affects:", "Availability and potentially all apps relying on SSO", ["Only printers", "DNS TTL", "Coffee supply"], 0, "Central IdP failure is widespread outage."],
      ["Defense in depth means:", "Multiple independent controls so one failure does not collapse security", ["One very strong firewall only", "Security through obscurity", "Removing layers for speed"], 0, "Layers contain failures."],
      ["Least privilege limits:", "Access rights to minimum needed for role", ["Password length only", "Internet speed", "Log retention"], 0, "Least privilege reduces abuse blast radius."],
      ["Risk acceptance requires:", "Documented approval by risk owner with rationale", ["Verbal nod only", "Ignoring risk", "Automatic for all high risks"], 0, "Acceptance is a governed decision."],
      ["Threat modeling STRIDE 'Information Disclosure' maps to:", "Confidentiality loss", ["Availability", "Repudiation only", "Elevation of desk"], 0, "Information disclosure is confidentiality."],
      ["Quantitative risk annual loss expectancy (ALE) = SLE × ARO. Use:", "Budgeting control investments with dollar estimates", ["Replacing qualitative entirely always", "Eliminating IR", "Disabling logs"], 0, "ALE helps financial justification."],
      ["Shared admin account violates accountability and:", "Increases integrity/confidentiality risk via untraced actions", ["Improves availability", "Required for zero trust", "Fixes SPF"], 0, "Shared creds obscure actor identity."],
      ["Downtime cost $50k/hour makes availability controls:", "Financially justified at higher priority", ["Irrelevant", "Less important than posters", "Optional"], 0, "Impact drives prioritization."],
      ["Regulatory fine risk is part of:", "Overall risk impact alongside operational harm", ["Only legal dept unrelated to security", "SPF configuration", "Printer speed"], 0, "Compliance consequences are impact factors."],
      ["Kerckhoffs's principle implies algorithm details may be public if:", "Key secrecy is maintained", ["No keys exist", "Security through obscurity suffices", "MD5 is used"], 0, "System security should not rely on secret design alone."],
      ["An asset inventory supports risk management by:", "Knowing what to protect and value", ["Decorating office", "Slowing patches", "Removing MFA"], 0, "You cannot protect unknown assets."],
      ["Third-party processor breach affects your risk as:", "Potential confidentiality/availability impact to your customers", ["No relationship", "Automatic patch", "SPF only"], 0, "Vendor incidents become your business risk."],
      ["Heat map 5×5 risk matrix plots:", "Likelihood vs impact for prioritization", ["Coffee vs tea", "Desk color", "DNS TTL"], 0, "Heat maps visualize prioritization."],
    ]),
    pack([
      ["MITRE ATT&CK tactic 'Initial Access' includes:", "Phishing and exploitation of public-facing apps among others", ["Only impact", "Only recovery", "Only printing"], 0, "Initial Access is entry to environment."],
      ["Technique T1059.001 is:", "PowerShell execution", ["DNS tunneling only", "Physical theft", "WEP cracking"], 0, "T1059.001 subtechnique is PowerShell."],
      ["APT groups differ from opportunistic criminals by:", "Objectives, resources, and sustained campaigns", ["Never using malware", "Only attacking printers", "Always announcing themselves day one"], 0, "APTs are defined by persistence and capability."],
      ["Cyber kill chain 'actions on objectives' is:", "Achieving attacker goals like exfiltration", ["Patching systems", "User training", "SPF alignment"], 0, "Final stage realizes intent."],
      ["Diamond Model infrastructure vertex captures:", "C2 servers, domains, IPs used", ["Office seating", "Coffee brands", "HR titles"], 0, "Infrastructure is adversary tooling."],
      ["Nation-state actor stealing defense designs prioritizes:", "Confidentiality/espionage over quick ransom", ["Gift card fraud only", "Website defacement only", "Printer repair"], 0, "Espionage seeks secrets."],
      ["Ransomware operator MITRE tactic at encryption stage:", "Impact", ["Reconnaissance only", "Resource development only", "None"], 0, "Encryption affects availability/data—Impact tactic."],
      ["MITRE mitigation M1049 recommends:", "Antivirus/EDR on endpoints", ["Disable logging", "Public RDP", "Shared passwords"], 0, "M1049 is anti-malware deployment."],
      ["T1566 phishing subtechniques include:", "Spearphishing attachment and link", ["Only physical theft", "Only BGP hijack always", "Only TLS downgrade"], 0, "T1566 covers multiple phish delivery modes."],
      ["Threat intel enriches ATT&CK with:", "Campaign IOCs and actor TTP mappings", ["Coffee recipes", "Desk manuals", "SPF only"], 0, "Intel operationalizes framework."],
      ["Living off the land maps to:", "Execution using legitimate system tools", ["Only custom malware", "Only hardware implants", "Only fax"], 0, "LOTL abuses trusted binaries."],
      ["MITRE ICS ATT&CK relevant when:", "Protecting OT/SCADA environments", ["Only marketing sites", "Only HR surveys", "Never"], 0, "ICS matrix covers OT threats."],
      ["Defender uses ATT&CK for:", "Gap analysis of detection coverage", ["Replacing firewalls only", "Eliminating training", "Disabling SIEM"], 0, "Matrix shows uncovered techniques."],
      ["T1078 valid accounts technique highlights:", "Stolen or default creds bypassing malware defenses", ["Only zero-days", "Only USB drops", "Only WEP"], 0, "Valid accounts are stealthy access."],
      ["Campaign uses Cobalt Strike beacons mapped to:", "Command and Control tactic", ["Only exfiltration", "Only patching", "Only awareness"], 0, "Beacons are C2."],
      ["Threat actor motivation 'financial' aligns with:", "Fraud, ransomware, credential markets", ["Espionage of state secrets only", "Academic research only", "Improving SPF"], 0, "Financial actors monetize access."],
      ["MITRE technique metadata includes detection ideas to:", "Guide SIEM rule creation", ["Replace IR", "Disable MFA", "Remove logs"], 0, "Detection fields help defenders."],
      ["ATT&CK Navigator layers show:", "Coverage heatmaps per technique", ["Physical office maps", "Coffee strength", "DNS only"], 0, "Navigator visualizes coverage."],
      ["Supply-chain as initial access increasing means defenders should:", "Verify software integrity and vendor security", ["Trust all updates blindly", "Disable code signing", "Stop patching"], 0, "Supply-chain needs integrity controls."],
      ["Mapping incident findings to ATT&CK aids:", "Consistent reporting and control selection", ["Marketing only", "Hiding TTPs from SOC", "Deleting tickets"], 0, "Common language improves response."],
    ]),
    pack([
      ["OAuth authorization code flow exchanges code for tokens:", "After user authenticates at IdP—client never sees user password", ["Without TLS", "Using MD5", "By emailing password"], 0, "Code flow keeps user creds at IdP."],
      ["MFA TOTP 30-second window accepts small skew to handle:", "Clock drift between phone and server", ["Eliminating seed secrecy", "Disabling HTTPS", "Publishing OTP"], 0, "Time windows accommodate drift."],
      ["FIDO2/WebAuthn resists phishing because:", "Private key signs challenge bound to origin", ["Password sent in email", "Uses SMS only", "Shares seed"], 0, "Cryptographic origin binding stops replay on fake sites."],
      ["SAML assertion must be validated for signature and:", "Audience, NotOnOrAfter, and issuer", ["User favorite color", "Desk number", "Printer speed"], 0, "Assertion validation prevents token abuse."],
      ["Refresh token rotation limits:", "Replay window if refresh token stolen", ["All phishing", "Need for TLS", "Logging"], 0, "Rotation shrinks stolen token utility."],
      ["Kerberos ticket-granting ticket (TGT) proves:", "User authenticated to domain for service ticket requests", ["Internet speed", "SPF alignment", "Coffee quality"], 0, "TGT is core Kerberos auth artifact."],
      ["Conditional access policy blocks legacy auth protocols because:", "They bypass MFA", ["Improve latency", "Required by printers", "Fix DNS"], 0, "Legacy protocols often lack MFA support."],
      ["OAuth scope `Mail.ReadWrite` excessive for calendar app means:", "Violates least privilege—request minimal scopes", ["Better security", "Required always", "Fixes ransomware"], 0, "Minimize scopes."],
      ["Password spraying avoids lockout by:", "Few passwords across many accounts", ["Many passwords one account until lock", "Disabling MFA", "Using Argon2"], 0, "Spray distributes guesses."],
      ["Passkey synced via platform cloud relies on:", "Vendor secure enclave/encryption design", ["Plaintext upload", "ROT13", "Public posting of keys"], 0, "Understand provider security model."],
      ["SAML XML signature wrapping attack exploited:", "Improper signature validation implementations", ["TLS 1.3", "Strong MFA always", "SPF"], 0, "Implementation flaws enabled XML attacks historically."],
      ["OAuth implicit flow deprecated because:", "Tokens exposed in browser—use code flow with PKCE", ["Too secure", "Required for FIDO", "Fixes Wi-Fi"], 0, "Implicit flow unsafe for modern apps."],
      ["PKCE protects mobile/public OAuth clients by:", "Proof key for code exchange preventing interception", ["Sharing client secret in app", "Disabling TLS", "MD5 challenge"], 0, "PKCE secures public clients."],
      ["Smart card auth provides:", "Strong multi-factor (something you have + PIN)", ["Weaker than password only", "No audit trail", "SPF fix"], 0, "Cards are strong factors."],
      ["Session fixation prevented by:", "Regenerating session ID after login", ["Reusing same ID", "Disabling HTTPS", "Long-lived ID forever"], 0, "New session ID post-auth stops fixation."],
      ["IdP session timeout reduces:", "Window for hijacked session abuse", ["Need for MFA", "Logging", "Patches"], 0, "Timeouts limit stolen session use."],
      ["OAuth consent phishing grants:", "Malicious app access tokens to user data", ["Hardware keys", "Firewall rules", "Backups"], 0, "Consent abuse steals API access."],
      ["AD password spray detection:", "Many account failures with few passwords from one IP", ["One failure total", "SPF fail", "TLS expiry"], 0, "Pattern distinguishes spray."],
      ["Break-glass accounts require:", "Monitoring, rare use, and strong storage", ["Daily use", "Posting in chat", "No MFA"], 0, "Break-glass is emergency only."],
      ["Authentication assurance level (NIST 800-63B AAL3) approximates:", "Hardware-based phishing-resistant MFA", ["Password only", "Security questions", "Email OTP alone"], 0, "AAL3 is highest authenticator assurance."],
    ]),
    pack([
      ["TLS 1.3 removes:", "Weak ciphers like RSA key exchange in favor of forward secrecy", ["All encryption", "Certificates", "MFA"], 0, "TLS 1.3 improves crypto defaults."],
      ["Certificate pinning in mobile app mitigates:", "Fraudulent CA-issued certs for MITM", ["Phishing email", "Ransomware", "Weak passwords only"], 0, "Pinning trusts only expected cert/public key."],
      ["HSTS header protects:", "Users from SSL stripping by forcing HTTPS", ["Email SPF", "DNS cache", "Printer"], 0, "HSTS reduces downgrade attacks."],
      ["VPN IPsec ESP provides:", "Confidentiality and integrity for IP packets", ["Only routing", "Password storage", "SPF"], 0, "ESP encrypts tunnel payloads."],
      ["Split horizon DNS in VPN ensures:", "Internal names resolve correctly when tunneled", ["Public DNS for corp domains always", "Attacker DNS", "Disable DNS"], 0, "Split DNS supports hybrid access."],
      ["Firewall default deny with allowlist:", "Permits only required services", ["Allows all then block", "Disables logging", "Open RDP worldwide"], 0, "Allowlist minimizes exposure."],
      ["WAF blocks SQLi by:", "Inspecting HTTP for injection patterns", ["Encrypting database", "Rotating passwords only", "SPF"], 0, "WAF is app-layer filter."],
      ["Network segmentation limits:", "Lateral movement after initial compromise", ["Phishing email", "User training", "Coffee"], 0, "Segmentation contains spread."],
      ["DNS over HTTPS (DoH) corporate policy may:", "Force corporate resolver to maintain visibility", ["Ignore DNS entirely", "Disable all DNS", "Publish passwords"], 0, "DoH can blind corporate monitoring if unmanaged."],
      ["BGP route leak impact:", "Availability and potential traffic interception", ["Only confidentiality of disks", "MFA", "Argon2"], 0, "BGP issues affect routing/trust."],
      ["TLS inspection requires:", "Enterprise trust of re-signing CA on endpoints", ["Disabling TLS", "Sharing private keys online", "Removing MFA"], 0, "Inspection needs trusted MITM CA."],
      ["Zero trust reduces implicit trust in:", "Flat internal networks", ["Encrypted TLS", "MFA", "Backups"], 0, "Internal LAN trust is reduced."],
      ["Port 445 SMB exposed to internet is:", "Critical misconfiguration—block immediately", ["Required for cloud", "Best practice", "SPF fix"], 0, "SMB should not be internet-facing."],
      ["Mutual TLS (mTLS) authenticates:", "Both client and server with certificates", ["Only users via password", "Only DNS", "Printers"], 0, "mTLS is two-way cert auth."],
      ["DDoS scrubbing center role:", "Absorb and filter attack traffic before origin", ["Encrypt laptops", "Store passwords", "Disable IR"], 0, "Scrubbing protects availability."],
      ["NAC (802.1X) on wired ports provides:", "User/device authentication before network access", ["WEP keys", "Open access", "Shared password on poster"], 0, "NAC controls L2 admission."],
      ["Proxy with authentication for outbound web:", "Identifies users and applies policy", ["Removes need for TLS", "Disables logging", "Public admin"], 0, "Proxies enable egress control."],
      ["IPv6 extension headers abused for:", "Evasion of some security devices—ensure v6 inspection parity", ["Improving SPF", "Eliminating MFA", "Faster passwords"], 0, "v6 features can evade naive tools."],
      ["Site-to-site VPN between cloud VPC and datacenter:", "Extends hybrid connectivity with encryption", ["Replaces IAM", "Removes need for segmentation", "Disables monitoring"], 0, "VPN links hybrid networks securely."],
      ["Network baseline anomaly: workstation scanning /24 on 445 suggests:", "Lateral recon—investigate endpoint", ["Backup job always", "SPF", "TLS renewal"], 0, "Internal scanning is suspicious."],
    ]),
    pack([
      ["EDR collects:", "Process, file, registry, network telemetry on endpoint", ["Only firewall logs", "Coffee orders", "SPF"], 0, "EDR provides host visibility."],
      ["Antivirus signature-only weakness:", "Misses new malware without signatures", ["Stops all APTs", "Replaces patching", "Fixes BEC"], 0, "Signatures need updates."],
      ["Application allow-listing on servers:", "Permits only approved binaries to run", ["Allows any exe", "Disables logging", "Removes MFA"], 0, "Allow-list prevents unknown execution."],
      ["Host firewall enabled on laptops:", "Blocks unwanted inbound on untrusted networks", ["Useless", "Replaces EDR", "Disables VPN"], 0, "Host firewall helps remote workers."],
      ["Disk encryption (BitLocker/FileVault) protects:", "Data at rest if device stolen", ["Data in transit only", "Phishing", "DNS"], 0, "Encryption protects lost/stolen media."],
      ["MDM can remote wipe corporate data on:", "Lost mobile device", ["All internet traffic globally", "DNS servers", "Printers only"], 0, "MDM supports mobile containment."],
      ["Local admin rights on workstations increase:", "Malware impact and persistence ease", ["Security always", "MFA strength", "SPF"], 0, "Admin rights expand blast radius."],
      ["EDR alert: suspicious PowerShell encoded command. Action:", "Isolate host and analyze script block logs", ["Ignore", "Disable EDR", "Pay ransom"], 0, "Encoded PowerShell is common attack pattern."],
      ["Patch Tuesday cadence addresses:", "Known vulnerability exploitation risk", ["Phishing only", "Physical theft", "SPF"], 0, "Patching closes exploit paths."],
      ["USB device control policy blocks:", "Unauthorized storage to reduce exfil/infil", ["All keyboards", "Monitors", "TLS"], 0, "USB control limits media risk."],
      ["Credential Guard isolates:", "LSA secrets on supported Windows versions", ["Email SPF", "DNS TTL", "Printers"], 0, "Credential Guard protects secrets."],
      ["EDR rollback feature can:", "Remediate certain malicious changes automatically", ["Replace backups", "Disable IR", "Remove MFA"], 0, "Rollback aids quick remediation."],
      ["Hardening baseline (CIS) provides:", "Benchmark settings reducing attack surface", ["Marketing text", "Coffee", "SPF only"], 0, "Benchmarks standardize hardening."],
      ["Kernel exploit on unpatched endpoint leads to:", "Privilege escalation—prioritize critical patches", ["Better performance", "SPF fix", "No risk"], 0, "Kernel bugs enable full compromise."],
      ["EDR false positive tuning uses:", "Exclusions with risk acceptance documentation", ["Disable EDR", "Alert on everything", "Delete logs"], 0, "Tune thoughtfully."],
      ["Application control via AppLocker/WDAC:", "Restricts executable code sources", ["Opens all scripts", "Disables TLS", "Shares passwords"], 0, "Policy restricts code execution."],
      ["Browser isolation for risky sites:", "Runs session in disposable container", ["Shares cookies globally", "Disables HTTPS", "Removes MFA"], 0, "Isolation contains web threats."],
      ["Tamper protection on EDR prevents:", "Malware disabling agent", ["User productivity always", "Logging", "Patches"], 0, "Tamper protection keeps agent alive."],
      ["Endpoint logs forwarded to SIEM enable:", "Correlation with network and identity events", ["Nothing", "Slower internet", "SPF only"], 0, "Central correlation improves detection."],
      ["BYOD without containerization risk:", "Personal malware accessing corp mail data", ["Improves security", "Required", "Fixes Wi-Fi"], 0, "BYOD needs separation."],
    ]),
    pack([
      ["AES-256-GCM provides:", "Confidentiality and authenticated encryption", ["Only hashing", "Password storage without salt", "DNSSEC"], 0, "GCM is AEAD mode."],
      ["RSA 2048-bit keys used for:", "Asymmetric encryption/signing—being phased down for TLS in favor of ECC", ["Symmetric bulk encryption of disks only", "WEP", "SPF"], 0, "RSA is asymmetric; ECC often preferred now."],
      ["SHA-256 is:", "Cryptographic hash function", ["Encryption algorithm", "VPN protocol", "MFA factor"], 0, "SHA-256 hashes data."],
      ["Salt in password hashing prevents:", "Rainbow table attacks", ["Brute force entirely", "Phishing", "DDoS"], 0, "Salts defeat precomputed tables."],
      ["TLS forward secrecy ensured by:", "Ephemeral Diffie-Hellman key exchange", ["Static RSA key exchange only", "MD5", "Plain HTTP"], 0, "Ephemeral keys protect past sessions if long-term key stolen."],
      ["Public key encrypts small data; bulk data uses symmetric key because:", "Performance—hybrid cryptography", ["Laws forbid symmetric", "AES is broken", "Hashes encrypt files"], 0, "Hybrid combines strengths."],
      ["Digital signature proves:", "Integrity and authenticity from holder of private key", ["Confidentiality of message body always", "Anonymous sender", "SPF alignment"], 0, "Signatures verify origin and tampering."],
      ["Certificate Authority role:", "Issues and signs certificates binding keys to identities", ["Stores user passwords", "Blocks phishing automatically", "Runs SIEM"], 0, "CAs anchor PKI trust."],
      ["Expired TLS cert on website causes:", "Browser warnings and failed connections", ["Stronger security", "Automatic MFA", "Faster DNS"], 0, "Expiry breaks trust chain."],
      ["Quantum computers threaten:", "Current asymmetric algorithms eventually—plan PQ migration", ["AES-256 immediately today", "All hashing now", "Physical locks"], 0, "PQ threat is to asymmetric mainly long-term."],
      ["HMAC-SHA256 used for:", "Message authentication with secret key", ["Disk encryption at rest only", "Email marketing", "WEP"], 0, "HMAC provides keyed integrity."],
      ["ECDSA on P-256 curve provides:", "Digital signatures with smaller keys than RSA", ["Password hashing", "VPN only", "SPF"], 0, "ECC efficient signatures."],
      ["Encrypting data at rest on S3 with KMS means:", "Keys managed by cloud HSM/policy", ["No encryption happens", "Public bucket OK", "Password in bucket name"], 0, "KMS governs encryption keys."],
      ["MD5 for file integrity today is:", "Deprecated—use SHA-256 or stronger", ["Best practice", "Required by TLS 1.3", "Same as Argon2"], 0, "MD5 is broken for collision resistance."],
      ["PGP email encryption provides:", "End-to-end confidentiality between correspondents", ["Server-side scanning only", "SPF", "Firewall rules"], 0, "PGP is E2E email crypto."],
      ["Key escrow for enterprise recovery:", "Trade-off between availability and pure zero-knowledge", ["Always evil illegal", "Replaces MFA", "Stops IR"], 0, "Escrow enables recovery with policy risk."],
      ["Cryptographic agility means:", "Ability to swap algorithms as standards evolve", ["Never change algorithms", "Use MD5 forever", "Disable TLS"], 0, "Agility supports migrations like PQ."],
      ["Entropy source for keys must be:", "Cryptographically secure random (CSPRNG)", ["Date of birth", "Username", "Clock only"], 0, "Weak entropy breaks keys."],
      ["Bit-flipping attack on unauthenticated encryption prevented by:", "AEAD modes like GCM", ["ECB mode", "ROT13", "Compression only"], 0, "Authentication tags detect tampering."],
      ["TLS cipher suite TLS_AES_128_GCM_SHA256 indicates:", "TLS 1.3 AEAD cipher", ["SSLv3", "WEP", "Cleartext"], 0, "Naming reflects TLS 1.3 AEAD."],
    ]),
    pack([
      ["Pretexting establishes:", "Fabricated scenario to gain trust before request", ["Encryption", "Patching", "SPF"], 0, "Pretext sets the story."],
      ["Tailgating bypasses:", "Physical access controls", ["TLS", "MFA on VPN", "DNSSEC"], 0, "Tailgating is physical social engineering."],
      ["Spearphishing uses:", "Personalized lure from OSINT", ["Random lottery only", "Hardware faults", "BGP only"], 0, "Spearphish targets individuals."],
      ["Authority principle in social engineering:", "Impersonating police/IT exec to coerce compliance", ["Using long passwords", "Patching", "Logging"], 0, "Authority pressures victims."],
      ["Urgency in vishing reduces:", "Victim critical thinking", ["Attacker success always zero", "MFA strength", "Backups"], 0, "Urgency causes rash actions."],
      ["Baiting with infected USB labeled 'Salaries' exploits:", "Curiosity", ["TLS 1.3", "Argon2", "SPF"], 0, "Baiting lures interaction."],
      ["Quid pro quo offer of 'free IT check' for password is:", "Exchange-based scam", ["Legitimate service", "Patch process", "DNS fix"], 0, "Quid pro quo trades fake help for access."],
      ["CEO fraud wire transfer relies on:", "Trust in executive authority + urgency", ["Exploiting CVE-2024 only", "Wi-Fi deauth only", "SPF"], 0, "BEC uses authority and urgency."],
      ["Security awareness reduces but does not eliminate:", "Human error—layer technical controls too", ["All attacks 100%", "Need for EDR", "Logging"], 0, "Humans remain variable; defense in depth needed."],
      ["Red flags: unsolicited attachment from vendor:", "Verify via known contact before open", ["Open immediately", "Forward to all", "Disable AV"], 0, "Verify unexpected attachments."],
      ["Social engineer researches LinkedIn for:", "Names, roles, projects for credible pretext", ["Patch levels", "TLS ciphers", "Disk encryption only"], 0, "OSINT fuels credible lures."],
      ["Helpdesk vishing to reset MFA is:", "High-impact attack path—harden verification", ["Impossible", "Low risk", "SPF fix"], 0, "Helpdesk is frequent target."],
      ["In-person impersonation as fire inspector tests:", "Physical security awareness", ["SQLi", "BGP", "AES"], 0, "Physical impersonation bypasses cyber-only controls."],
      ["Deepfake audio in wire fraud increases:", "Believability of urgent executive requests", ["Patch speed", "Entropy", "SPF"], 0, "Deepfakes enhance deception."],
      ["Reporting suspicious calls policy:", "Hang up and call official number", ["Comply with codes", "Email passwords", "Install profile"], 0, "OOB verification stops vishing."],
      ["Social engineering penetration test differs from phish sim by:", "Broader physical/phone pretexts with scope", ["Using real malware always", "No rules", "Attacking customers"], 0, "SE pen tests are controlled broader assessments."],
      ["Culture of blame after phish click causes:", "Under-reporting future incidents", ["More reports", "Better metrics", "Stronger MFA"], 0, "Blame reduces reporting."],
      ["Multi-channel attack (email + call) increases:", "Credibility—train verify on sensitive actions", ["Security automatically", "SPF", "TLS only"], 0, "Channels reinforce story."],
      ["Gift card payment request is:", "Strong fraud indicator", ["Standard AP", "IRS rule", "Patch Tuesday"], 0, "Gift cards signal scam."],
      ["Physical clean desk policy reduces:", "Shoulder surfing and document theft", ["DDoS", "SQLi", "BGP"], 0, "Clean desk protects confidential papers."],
    ]),
    pack([
      ["OWASP Top 10 includes:", "Broken access control and injection among leading web risks", ["Only physical security", "Only DNS", "Only printers"], 0, "Top 10 lists prevalent web app risks."],
      ["SQL injection mitigated by:", "Parameterized queries/ORM binding", ["Concatenating user input in SQL", "Disabling HTTPS", "MD5 passwords"], 0, "Parameterization separates code from data."],
      ["XSS stored in forum posts affects:", "Other users viewing posts—persistent XSS", ["Only attacker browser", "DNS only", "SPF"], 0, "Stored XSS hits many victims."],
      ["CSRF forces victim browser to:", "Submit unwanted authenticated request", ["Download patches", "Enable MFA", "Fix TLS"], 0, "CSRF abuses existing session."],
      ["Broken access control IDOR lets user:", "Access another user's object by changing ID", ["Only see own data always", "Patch servers", "Improve SPF"], 0, "IDOR is insecure direct object reference."],
      ["Security misconfiguration example:", "Default admin creds on cloud storage", ["Strong MFA everywhere", "Argon2 passwords", "Logging enabled"], 0, "Defaults left in place are misconfigurations."],
      ["SSRF from web app to cloud metadata can:", "Steal IAM role credentials", ["Only slow page load", "Fix phishing", "Disable EDR"], 0, "Metadata SSRF is critical in cloud."],
      ["Insecure deserialization may lead to:", "Remote code execution", ["Better performance only", "SPF alignment", "Stronger TLS"], 0, "Unsafe deserialization is RCE risk."],
      ["Content Security Policy (CSP) helps mitigate:", "XSS by restricting script sources", ["SQLi in database", "Physical theft", "BGP leaks"], 0, "CSP limits script execution sources."],
      ["OWASP ASVS provides:", "Application security verification requirements", ["Firewall rules only", "Coffee standards", "SPF"], 0, "ASVS is app security standard."],
      ["DevSecOps integrates security into:", "CI/CD pipelines with SAST/DAST/dependency scan", ["Only production firefighting", "HR onboarding", "Marketing"], 0, "Shift-left testing finds issues early."],
      ["Dependency scanner finds:", "Known vulnerable libraries (CVE) in bill of materials", ["Office layout", "DNS TTL", "Mouse DPI"], 0, "SCA identifies vulnerable components."],
      ["WAF in front of app:", "Mitigates some attacks but does not replace secure coding", ["Fixes all bugs", "Removes need for patches", "Stores passwords plaintext"], 0, "WAF is compensating control."],
      ["JWT alg none vulnerability:", "Accepting unsigned tokens—validate alg and signature", ["Feature of OAuth", "Required", "SPF fix"], 0, "Must enforce proper JWT validation."],
      ["Secrets in Git history require:", "Rotation and secret scanning—even after deletion", ["Ignore", "Publicize", "Disable git"], 0, "History retains secrets."],
      ["Rate limiting login API prevents:", "Brute force and credential stuffing", ["SQLi entirely alone", "Phishing", "DDoS globally always"], 0, "Rate limits slow guessing."],
      ["Secure cookie flags HttpOnly and Secure:", "Reduce theft via XSS and enforce HTTPS transmission", ["Stop all attacks", "Replace MFA", "Fix DNS"], 0, "Cookie flags harden session cookies."],
      ["Threat modeling for new API should include:", "Abuse cases and authZ for each endpoint", ["Only UI colors", "Coffee", "SPF"], 0, "Model before build."],
      ["Pen test finding critical RCE on internet-facing app priority:", "Emergency patch/virtual patch and hunt for exploitation", ["Next year", "Ignore", "Disable logging"], 0, "RCE exposure is urgent."],
      ["OWASP API Security Top 10 addresses:", "Broken object level auth and excessive data exposure", ["Only hardware", "Only Wi-Fi", "Only printers"], 0, "API list covers modern API risks."],
    ]),
    pack([
      ["NIST IR phases include:", "Prepare, Detect & Analyze, Contain, Eradicate & Recover, Post-Incident", ["Only marketing", "Only patching", "Only training posters"], 0, "800-61 defines IR lifecycle."],
      ["Preparation includes:", "Playbooks, contacts, tools, and training", ["Paying ransom upfront", "Deleting logs", "Public attribution"], 0, "Preparation enables effective response."],
      ["Containment short-term may:", "Isolate host at network without immediate wipe", ["Publish all IOCs to press first", "Disable all backups", "Ignore legal"], 0, "Short-term containment stops spread."],
      ["Eradication ensures:", "Malware/persistence removed and vectors closed", ["Only AV scan once", "Assume contained equals clean", "Stop monitoring"], 0, "Eradication removes footholds."],
      ["Recovery validates:", "Systems restored from trusted images/backups and monitored", ["Blind restore of encrypted backups", "No testing", "Disable MFA"], 0, "Recovery needs integrity checks."],
      ["Post-incident lessons learned feed:", "Control improvements and playbook updates", ["Nothing", "Blame only", "Delete SIEM"], 0, "PIR drives maturity."],
      ["Severity P1 typically means:", "Active major business impact requiring immediate all-hands", ["Low priority newsletter", "Printer jam", "Slow Wi-Fi only"], 0, "P1 is highest operational urgency."],
      ["Chain of custody applies when:", "Evidence may be used in legal proceedings", ["Never", "Only marketing", "Only phishing sims"], 0, "Legal cases need custody."],
      ["Volatile data collection order:", "Memory and network state before powered-off disk imaging when feasible", ["Only paper shredder", "DNS only", "SPF"], 0, "Order of volatility guides collection."],
      ["Incident commander coordinates:", "Technical, legal, comms, and business workstreams", ["Only one analyst silently", "Attacker negotiations alone", "Marketing only"], 0, "IC orchestrates response."],
      ["Regulatory notification timing (e.g., GDPR 72h) requires:", "Legal assessment of notifiable personal data breach", ["Instant tweet", "Ignore counsel", "All spam is breach"], 0, "Notifications are legally conditioned."],
      ["Tabletop exercise tests:", "Decision-making without live compromise", ["Production malware deployment", "Customer data deletion", "Disable EDR"], 0, "Tabletops are simulations."],
      ["Hot wash captures:", "Immediate tactical lessons within days", ["Annual budget only", "Office decor", "DNS TTL"], 0, "Hot washes are near-real-time."],
      ["SOC tier-1 triage determines:", "Severity and escalation path", ["Final legal verdict", "Ransom payment approval alone", "Marketing copy"], 0, "Triage routes incidents."],
      ["Playbook for ransomware includes:", "Isolation, evidence preservation, backup restore decision tree", ["Pay immediately always", "Delete logs first", "Disable MFA"], 0, "Ransomware playbooks are specialized."],
      ["Communication during IR avoids:", "Sharing sensitive TTP details that aid attacker", ["Any stakeholder updates", "Legal involvement", "Status tracking"], 0, "Balance transparency with opsec."],
      ["Metrics MTTD measures:", "Time from compromise start to detection", ["Coffee time", "Desk moves", "SPF"], 0, "MTTD reflects detection capability."],
      ["Forensic image hashing verifies:", "Integrity of evidence copies", ["Password strength", "MFA", "TLS version"], 0, "Hashes detect tampering."],
      ["Incident closure requires:", "Validated eradication, recovery, and documented lessons", ["AV green on one host", "Executive impatience", "No monitoring"], 0, "Formal closure criteria prevent premature end."],
      ["NIST IR function 'Detect' aligns with SOC activities such as:", "SIEM alerting, EDR detections, and user reports triaged into incidents", ["Annual poster design only", "Hardware procurement", "SPF record creation"], 0, "Detect covers analysis of events to determine incidents."],
    ]),
    pack([
      ["GDPR personal data is:", "Information relating to identified or identifiable natural person", ["Only credit cards", "Only servers", "Only passwords"], 0, "GDPR defines broad personal data."],
      ["GDPR data processor must:", "Process only on controller instructions with appropriate security", ["Sell data freely", "Ignore breaches", "Disable encryption"], 0, "Processors act on controller direction."],
      ["HIPAA PHI includes:", "Health information linked to individual", ["Only public tweets", "Only firewall logs", "Only DNS"], 0, "PHI is identifiable health data."],
      ["HIPAA Security Rule requires:", "Administrative, physical, technical safeguards for ePHI", ["Nothing for cloud", "Only posters", "Disable MFA"], 0, "Security Rule mandates safeguards."],
      ["GDPR right to erasure ('right to be forgotten') may conflict with:", "Legal retention obligations—legal review required", ["Always delete backups instantly without plan", "Security logs always erased immediately without policy", "SPF records"], 0, "Erasure must balance other duties."],
      ["Data minimization principle:", "Collect only data necessary for stated purpose", ["Collect everything possible", "Share with any vendor", "Publish databases"], 0, "Minimization limits exposure."],
      ["Breach notification under GDPR to supervisory authority often within:", "72 hours of awareness where feasible", ["5 years", "Never", "Only if attacker emails"], 0, "72-hour notification is well-known GDPR requirement."],
      ["HIPAA Business Associate Agreement (BAA) required when:", "Vendor handles PHI on covered entity's behalf", ["Buying coffee", "Marketing blog", "Public website only"], 0, "BAA governs vendor PHI handling."],
      ["Privacy Impact Assessment (DPIA) for high-risk processing:", "Identifies mitigations before launch", ["Optional always", "Replaces security", "Disables logging"], 0, "DPIA is proactive risk analysis."],
      ["Cross-border EU data transfer may need:", "Standard contractual clauses or adequacy decision", ["Random email attachment", "Public paste", "Disable TLS"], 0, "Transfers need legal mechanisms."],
      ["HIPAA minimum necessary standard:", "Limit PHI access to job need", ["All staff access all PHI", "Post PHI online", "Share with advertisers"], 0, "Minimum necessary reduces exposure."],
      ["GDPR lawful bases include:", "Consent, contract, legal obligation, legitimate interests among others", ["Only hacker consent", "No basis needed", "SPF"], 0, "Processing requires lawful basis."],
      ["Encryption of PHI at rest helps meet:", "HIPAA addressable encryption implementation specification", ["Nothing", "Marketing only", "Eliminates IR"], 0, "Encryption is expected safeguard."],
      ["Data subject access request (DSAR) under GDPR:", "Requires timely response providing copy of personal data", ["Ignore forever", "Charge unlimited fee always", "Delete subject"], 0, "DSAR rights enable transparency."],
      ["HIPAA breach risk assessment considers:", "Probability PHI was compromised and impact", ["Only coffee spill", "DNS TTL", "Mouse DPI"], 0, "Risk assessment determines notification."],
      ["PCI DSS applies when:", "Storing/processing/transmitting cardholder data", ["Never for e-commerce", "Only paper", "Only DNS"], 0, "PCI scope is payment card data."],
      ["Privacy by design means:", "Embed privacy into systems from inception", ["Add privacy after breach only", "Collect max data", "Disable auth"], 0, "Proactive privacy engineering."],
      ["Records of processing activities (ROPA) under GDPR:", "Documents processing purposes and data categories", ["Optional for all", "Coffee log", "SPF list"], 0, "ROPA demonstrates accountability."],
      ["HIPAA workforce training must cover:", "Policies and procedures for PHI handling", ["Only executives exempt", "Only interns", "Never"], 0, "Training is administrative safeguard."],
      ["Regulatory fine risk should be in:", "Risk register alongside operational impact", ["Ignored by security", "Only marketing", "SPF config"], 0, "Fines are part of risk impact."],
    ]),
  ]);
}
