import { NETWORK_CHAPTERS } from "../cyber-hard-meta.mjs";
import { fromChapters, Q } from "./_loader.mjs";

function pack(rows) {
  return rows.map(([q, a, w, c, e]) => Q(q, a, w, c, e));
}

export function buildNetworkChapters() {
  return fromChapters(NETWORK_CHAPTERS, [
    pack([
      ["Stateful firewall tracks:", "Connection state to allow return traffic for outbound-initiated flows", ["Only MAC addresses", "Email SPF", "User passwords"], 0, "Statefulness understands sessions."],
      ["Default deny firewall policy means:", "Block all unless explicitly permitted", ["Allow all then block some", "Permit internet outbound always implicit", "Disable logging"], 0, "Default deny is security baseline."],
      ["Application-layer firewall (WAF) inspects:", "HTTP semantics for web attacks", ["Raw Ethernet frames only", "Physical badges", "Printer toner"], 0, "WAF focuses on web protocols."],
      ["Firewall rule shadowing occurs when:", "Broader earlier rule prevents later specific rule from matching", ["Rules too small", "TLS failure", "MFA missing"], 0, "Order matters in rule bases."],
      ["East-west firewall between app tiers prevents:", "Lateral movement after web tier compromise", ["North-south only attacks", "Phishing", "Backups"], 0, "Internal segmentation limits spread."],
      ["NGFW adds:", "IPS, app identification, and TLS inspection capabilities", ["Only hub repeating", "DNSSEC only", "Password rotation"], 0, "NGFW integrates multiple controls."],
      ["Firewall change management requires:", "Ticket, review, and rollback plan", ["Edit live without record", "Email admin password", "Disable MFA"], 0, "Changes need governance."],
      ["Implicit deny at end of ACL:", "Drops unmatched traffic", ["Allows all", "Speeds up internet", "Fixes SPF"], 0, "Implicit deny blocks unlisted traffic."],
      ["NAT on firewall hides:", "Internal IP addressing from external observers", ["TLS keys", "User biometrics", "MFA seeds"], 0, "NAT provides address translation privacy."],
      ["Geo-blocking on firewall:", "Filters by source country—imperfect but reduces noise", ["Stops all APTs", "Replaces MFA", "Fixes phishing"], 0, "Geo filters are coarse control."],
      ["Firewall logs should send to:", "SIEM with correlation and retention policy", ["Recycle bin", "Public blog", "Attacker"], 0, "Centralized logging enables detection."],
      ["Allow rule 'any any' on internal segment is:", "Dangerous flat network—violates least privilege", ["Best practice", "Required for zero trust", "MFA alternative"], 0, "Permit-all internal ACLs increase risk."],
      ["Fail-open firewall during power loss:", "Allows traffic—physical security and design must account", ["Blocks all traffic always", "Encrypts disks", "Enables FIDO"], 0, "Fail-open vs fail-closed is design choice."],
      ["TLS inspection on firewall needs:", "Corporate CA trusted on endpoints for re-signing", ["Disable TLS everywhere", "Share private keys publicly", "Remove MFA"], 0, "Inspection requires trusted MITM CA."],
      ["Firewall HA pair uses:", "Stateful sync or clustering for failover", ["Single cable", "Sticky notes", "SPF"], 0, "HA maintains availability."],
      ["Zone-based firewall assigns:", "Interfaces to zones with inter-zone policies", ["Random IP only", "User hair color", "DNS TTL"], 0, "Zones simplify policy."],
      ["Blocking QUIC/UDP 443 may:", "Force browsers to fallback TCP—consider policy impact", ["Improve security always", "Stop all malware", "Fix BEC"], 0, "Protocol blocks have side effects."],
      ["Firewall rule naming convention helps:", "Operations understand intent during incidents", ["Nothing", "Slow patches", "Disable logging"], 0, "Documentation aids IR."],
      ["Personal firewall on laptop complements:", "Network edge controls for off-LAN travel", ["Replace EDR", "Remove MFA", "Public RDP"], 0, "Host firewall helps remote workers."],
      ["IPv6 on firewall often overlooked:", "Attackers use v6 tunnels—ensure v6 policy parity", ["Impossible to attack v6", "v4 only needed forever", "SPF fixes v6"], 0, "v6 exposure needs explicit rules."],
      ["Rate limiting on firewall mitigates:", "Brute force and some DDoS volume", ["SQLi in app code", "Insider HR issues", "Backups"], 0, "Rate limits slow automated attacks."],
      ["Egress filtering prevents:", "C2 and data exfil to unexpected destinations", ["Inbound spam only", "User training", "MFA"], 0, "Egress controls limit outbound abuse."],
      ["Firewall vs router ACL difference:", "Firewall is security policy engine; router ACL is often simpler and faster", ["Identical always", "Router always NGFW", "ACL always inspects TLS"], 0, "Roles differ though overlap exists."],
      ["Testing firewall rules uses:", "Staged changes with packet capture and policy hit counters", ["Edit production Friday 5pm blindly", "Disable logging", "Tweet rules"], 0, "Test with visibility into hits."],
      ["Zero trust reduces reliance on:", "Perimeter-only firewall trust model", ["All authentication", "Logging", "Backups"], 0, "Zero trust assumes breach; verifies continuously."],
    ]),
    pack([
      ["VLAN segmentation isolates:", "Broadcast domains and L2 adjacency", ["TLS versions", "User passwords in AD", "Email DKIM"], 0, "VLANs separate L2 networks."],
      ["Micro-segmentation differs from VLANs by:", "Granular workload-level policies often with identity", ["Using only hubs", "Disabling routing", "Removing MFA"], 0, "Micro-seg is finer than VLAN alone."],
      ["Flat network risk:", "Single compromise enables lateral movement everywhere", ["Better performance always", "Stronger MFA", "Automatic compliance"], 0, "Flat networks ease lateral movement."],
      ["DMZ hosts web servers with:", "Restricted inbound from internet and controlled egress", ["Domain admin creds", "Open SMB from internet", "No logging"], 0, "DMZ limits exposure."],
      ["Jump host (bastion) for admin access:", "Single audited entry to sensitive segments", ["Public RDP to all servers", "Shared password", "Disable MFA"], 0, "Jump hosts consolidate admin access."],
      ["Software-defined segmentation (NSX, etc.) uses:", "Policy on virtual NICs independent of VLAN plumbing", ["Only WEP", "Sticky notes", "SPF"], 0, "SDN segmentation decouples policy from topology."],
      ["PCI DSS encourages segmenting:", "Cardholder data environment from corporate LAN", ["All printers together", "Guest Wi-Fi with CDE", "Disable encryption"], 0, "CDE segmentation is PCI practice."],
      ["VLAN hopping mitigation includes:", "Disable unused trunks, DTP off, unique native VLAN", ["Use VLAN 1 everywhere", "Open all trunks", "Share admin password"], 0, "Trunk misconfig enables hopping."],
      ["East-west traffic inspection in segmented net needs:", "Internal firewall or host-based controls", ["Only perimeter firewall historically", "No monitoring", "MD5 passwords"], 0, "Internal traffic must be inspected too."],
      ["IoT VLAN should:", "Have no route to corporate user VLAN without gateway controls", ["Share AD domain freely", "Use same password as Wi-Fi", "Disable monitoring"], 0, "IoT should be isolated."],
      ["Segmentation policy based on:", "Data classification and application dependencies", ["Random colors", "Desk location", "Coffee preference"], 0, "Policies follow data sensitivity."],
      ["Over-segmentation problem:", "Operational complexity and broken app flows", ["Always better security", "Free performance", "Removes MFA"], 0, "Balance security with operability."],
      ["Kubernetes network policies provide:", "Pod-level segmentation inside cluster", ["Physical VLAN only", "DNSSEC", "Password rotation"], 0, "NetPol controls pod traffic."],
      ["Cloud security groups are:", "Distributed stateful firewalls per ENI/instance", ["Email filters", "HR policies", "SPF records"], 0, "SGs are cloud micro-firewalls."],
      ["Segmentation testing:", "Verify denied paths with traceroute and port probes from each zone", ["Assume diagrams correct", "Disable scans", "Publish topology"], 0, "Validate controls actually block."],
      ["Guest network segmentation protects:", "Corporate assets from untrusted visitors", ["Guests from internet", "Nothing", "TLS keys"], 0, "Guests are untrusted."],
      ["Data center leaf-spine with VXLAN enables:", "Overlay segmentation at scale", ["Only hub-spoke 1990 design", "No encryption", "Remove logging"], 0, "Overlays scale multi-tenant segmentation."],
      ["Segmentation during IR:", "Dynamic quarantine VLAN or ACL drop for compromised hosts", ["Open all ports for speed", "Disable SIEM", "Pay ransom"], 0, "IR uses segmentation for containment."],
      ["Zero trust segmentation principle:", "Never trust, always verify per flow", ["Trust internal VLAN fully", "Password on whiteboard OK", "Disable auth"], 0, "Zero trust removes implicit LAN trust."],
      ["Mapping application flows before segmentation avoids:", "Breaking dependencies during rollout", ["Improving security", "Documentation", "Monitoring"], 0, "Flow mapping prevents outages."],
      ["Macro-segmentation vs micro:", "Macro by zone; micro by workload identity—often layered", ["Same term", "Macro is always weaker", "Micro replaces firewalls entirely"], 0, "Layer macro and micro controls."],
      ["OT segmentation from IT:", "Prevents IT malware pivoting to PLCs", ["Connect OT to internet for convenience", "Single flat plant network best", "Disable safety systems"], 0, "OT/IT separation protects safety systems."],
      ["Segmentation metrics:", "Percent critical apps protected by east-west controls", ["Poster count", "Mouse DPI", "DNS TTL"], 0, "Measure coverage of key assets."],
      ["Hybrid cloud segmentation uses:", "VPN/ExpressRoute with consistent policy via cloud NGFW", ["Public RDP", "Shared admin", "No encryption"], 0, "Hybrid needs consistent policy."],
      ["Least privilege routing means:", "Routes advertised only where needed", ["Full table everywhere", "Default route to internet for PLCs", "Disable BGP logging"], 0, "Routing leakage expands attack surface."],
    ]),
    pack([
      ["Zero Trust Network Access (ZTNA) replaces:", "VPN trust-all-internal model with per-app access", ["Password sticky notes", "Physical locks only", "SPF"], 0, "ZTNA grants app-level access not network carte blanche."],
      ["Zero trust mantra 'never trust, always verify' applies to:", "Every access request regardless of network location", ["Only guests", "Only outsiders never employees", "Only printers"], 0, "Verification is continuous."],
      ["Identity as perimeter means:", "User/device identity drives access—not office IP alone", ["Firewall removed entirely", "No MFA needed", "Disable logging"], 0, "Identity is primary control."],
      ["Device health attestation in ZT may check:", "Patch level, EDR status, disk encryption", ["Favorite color", "Desk height", "Coffee"], 0, "Device posture influences access."],
      ["Legacy VPN full tunnel risk:", "Compromised remote host can reach entire corporate LAN", ["Always zero trust", "Improves segmentation automatically", "Blocks phishing"], 0, "Full tunnel extends LAN trust."],
      ["Policy engine for zero trust evaluates:", "User, device, resource sensitivity, behavior", ["Only day of week", "Printer status", "DNS TTL"], 0, "Contextual policy decisions."],
      ["Continuous authorization re-checks:", "Sessions during risk changes (new device, malware)", ["Only at login once", "Never", "Annually"], 0, "Risk changes require re-evaluation."],
      ["Zero trust is journey not product because:", "Requires people/process/tech alignment over time", ["Buy one box finished", "Replace IR", "Remove training"], 0, "Transformation is organizational."],
      ["NIST SP 800-207 defines:", "Zero Trust Architecture tenets and components", ["WEP keys", "Coffee standards", "SPF only"], 0, "800-207 is ZTA reference."],
      ["Micro-perimeters around data:", "Encrypt and authenticate each access path to data", ["Open share for speed", "Email database", "Disable TLS"], 0, "Protect data paths individually."],
      ["Zero trust vs MFA:", "MFA is one control; ZTA is broader architecture", ["Same thing", "MFA replaces firewalls entirely", "ZTA removes auth"], 0, "MFA necessary but not sufficient alone."],
      ["Service-to-service zero trust uses:", "mTLS and workload identity (SPIFFE/SPIRE concepts)", ["Shared password in code", "HTTP basic over internet", "Disable certs"], 0, "Machine identity secures service mesh."],
      ["Logging in zero trust essential for:", "Policy decisions audit and incident investigation", ["Marketing only", "Removing SIEM", "Disabling IR"], 0, "Decisions must be auditable."],
      ["BYOD zero trust approach:", "Isolate corp apps via container/VDI with posture checks", ["Full LAN VPN", "Domain admin on phone", "Disable EDR"], 0, "BYOD needs isolation not full trust."],
      ["Zero trust metrics:", "Percent apps behind ZTNA, MFA coverage, policy deny rates", ["Posters", "Fan speed", "Desk color"], 0, "Measure adoption and enforcement."],
      ["PAM integration with zero trust:", "Just-in-time admin for sensitive systems", ["Standing admin always", "Password in chat", "Disable monitoring"], 0, "JIT aligns with least privilege."],
      ["Legacy app unable to modernize gets:", "Wrapper/proxy with strong auth in front", ["Public internet exposure", "Shared creds", "No logging"], 0, "Wrappers extend ZT to legacy."],
      ["Zero trust failure if:", "Flat network still reachable after stolen VPN creds", ["MFA on email", "EDR deployed", "Logs collected"], 0, "Residual flat access undermines ZT."],
      ["User experience concern with ZT:", "Friction—balance with SSO and device trust", ["Always impossible", "Remove all auth", "Disable helpdesk"], 0, "UX must be managed."],
      ["Cloud IAM policies are:", "Zero trust enforcement points for cloud APIs", ["Decorative", "Replace encryption", "SPF only"], 0, "IAM enforces cloud ZT."],
      ["Zero trust during acquisition:", "Integrate identity and segment networks deliberately", ["Merge flat networks day one", "Share domain admin", "Stop monitoring"], 0, "M&A needs ZT planning."],
      ["De-perimeterization driver:", "Cloud/SaaS moves data off traditional castle", ["Stronger castle walls only solution", "Remove all firewalls always", "Disable TLS"], 0, "Data leaves perimeter—ZT adapts."],
      ["Policy simulation before ZT rollout:", "Test denies without cutting production wrongly", ["Change Friday blind", "Disable rollback", "Tweet policies"], 0, "Simulate to prevent outages."],
      ["Zero trust culture requires:", "Security partnering with app owners—not network-only project", ["IT silo only", "Ignore developers", "Remove IR"], 0, "Cross-team collaboration is required."],
      ["Ultimate ZT goal:", "Reduce blast radius and improve detection via granular controls", ["Eliminate all attacks instantly", "Remove passwords only", "Disable logging"], 0, "ZT limits impact and improves visibility."],
    ]),
    pack([
      ["Secure remote access prefers:", "ZTNA or VPN with MFA, device posture, and split tunneling where appropriate", ["RDP exposed to internet", "Shared VPN password", "Telnet"], 0, "Modern remote access layers controls."],
      ["Split tunnel VPN sends:", "Corporate traffic via VPN; general internet direct", ["All traffic including Netflix over corp", "Nothing encrypted ever", "DNS only"], 0, "Split tunnel reduces corp bandwidth load."],
      ["Full tunnel VPN risk on compromised home PC:", "Attacker pivots into corporate network", ["Impossible", "Improves security", "Blocks phishing"], 0, "Full tunnel extends LAN to hostile device."],
      ["RDP Gateway without MFA exposed:", "Common ransomware entry—enforce MFA and lockout", ["Best practice", "Required by SPF", "Fixes TLS"], 0, "RDP must be hardened."],
      ["Remote access logging should capture:", "User, device ID, source IP, resources accessed", ["Nothing", "Password plaintext", "Biometrics raw"], 0, "Logs support audit and IR."],
      ["Certificate-based VPN auth provides:", "Strong device/user binding", ["Weaker than password only", "No logging", "SPF alignment"], 0, "Certs strengthen auth."],
      ["Remote access during travel to high-risk country:", "Use dedicated travel laptop and heightened monitoring", ["Carry full domain admin creds", "Disable EDR", "Share VPN"], 0, "Travel risk warrants extra controls."],
      ["Always-on VPN for remote workers ensures:", "Consistent policy enforcement but watch performance", ["Public RDP instead", "No MFA", "Disable patches"], 0, "Always-on improves control with tradeoffs."],
      ["Remote desktop to cloud VM should use:", "Bastion/SSO—not open RDP port 3389", ["0.0.0.0/0:3389", "Password `admin`", "Disable firewall"], 0, "Expose management through controlled paths."],
      ["Remote access offboarding:", "Disable VPN/SSO within minutes of termination", ["Wait 30 days", "Share creds", "Disable logging"], 0, "Fast deprovision prevents ex-employee access."],
      ["Clientless ZTNA via browser:", "Access apps without full network VPN", ["Gives domain admin always", "Removes MFA", "Disables TLS"], 0, "Clientless reduces network exposure."],
      ["Remote access split horizon DNS issue:", "Internal names resolve only on VPN—configure correctly", ["Ignore DNS", "Use public DNS only", "Disable TLS"], 0, "DNS must work for remote users."],
      ["Geofencing VPN logins blocks:", "Auth from unexpected countries—partial control", ["All attacks", "Insiders always", "Phishing"], 0, "Geo fence is signal not panacea."],
      ["Remote access pen test finding: self-signed VPN cert:", "Replace with trusted PKI to prevent MITM", ["Ignore", "Email private key", "Disable MFA"], 0, "Trusted certs protect tunnel integrity."],
      ["Contractor remote access:", "Time-bound, least privilege, separate identity", ["Same admin as employees forever", "No logging", "Public RDP"], 0, "Contractors need scoped access."],
      ["Remote work DLP on endpoint:", "Detects exfil on device off VPN", ["Useless", "Replaces firewall", "Stops IR"], 0, "DLP helps when split tunnel."],
      ["Emergency remote access surge (pandemic lesson):", "Scale VPN capacity and monitor for fraud", ["Disable MFA for speed", "Open RDP", "Remove logging"], 0, "Capacity and fraud monitoring matter."],
      ["Remote access via Tor should be:", "Blocked or heavily scrutinized on corp resources", ["Encouraged", "Default path", "Required for execs"], 0, "Tor obscures origin—high risk."],
      ["VDI for remote contractors isolates:", "Data from contractor-controlled endpoint", ["Nothing", "Corp network fully to laptop", "Disable MFA"], 0, "VDI keeps data in datacenter."],
      ["Remote access policy forbids:", "Sharing credentials, bypassing MFA, using personal devices without MDM", ["MFA", "Logging", "Patching"], 0, "Policy sets clear prohibitions."],
      ["Monitoring VPN concurrent sessions:", "Detects credential sharing and compromise", ["Irrelevant", "Slows internet", "Fixes SPF"], 0, "Concurrent limits signal abuse."],
      ["Remote access disaster: lost MFA device procedure:", "Backup factors and helpdesk verified reset", ["Disable MFA globally", "Email seed", "Publish OTP"], 0, "Recovery must be secure."],
      ["Secure remote file access uses:", "SFTP/HTTPS with auth—not SMB over public internet", ["SMB port 445 open worldwide", "FTP cleartext", "Telnet"], 0, "Use secure protocols."],
      ["Remote access KPI:", "Percent remote users on MFA + managed devices", ["Desk count", "DNS TTL", "Coffee"], 0, "Track control coverage."],
      ["ZTNA access log review should include:", "Denied attempts and anomalous app access patterns", ["Only successful logins ignored", "Coffee orders", "Printer jams"], 0, "Deny logs reveal probing and policy gaps."],
    ]),
    pack([
      ["WPA3 improvement over WPA2 includes:", "SAE resisting offline dictionary attacks on PSK", ["WEP compatibility", "Open networks", "Removes encryption"], 0, "SAE strengthens personal Wi-Fi."],
      ["Enterprise Wi-Fi should use:", "802.1X with certificates or EAP-TLS/TEAP—not PSK shared", ["SSID password on poster", "WEP", "Open guest for corp VLAN"], 0, "802.1X per-user auth is standard."],
      ["Evil twin AP attack:", "Rogue AP mimicking SSID to MITM clients", ["Impossible", "Fixes SPF", "Requires Argon2"], 0, "Rogue APs intercept traffic."],
      ["Wi-Fi deauth attack:", "Disrupts connectivity via forged management frames", ["Encrypts data", "Patches servers", "Enables MFA"], 0, "Deauth is DoS on wireless."],
      ["Guest Wi-Fi must:", "Isolate from internal resources via firewall", ["Bridge to domain", "Share AD creds", "Disable logging"], 0, "Guest isolation is critical."],
      ["Wi-Fi password rotation on PSK network:", "Painful—prefer 802.1X instead", ["Use `password` forever", "Post on LinkedIn", "Disable encryption"], 0, "PSK rotation is operational burden."],
      ["Wireless IDS detects:", "Rogue APs and abnormal beacon patterns", ["Printer jams", "DNS TTL", "Coffee"], 0, "WIDS monitors airspace."],
      ["Captive portal on guest Wi-Fi:", "Terms acceptance—not security alone", ["Replaces MFA", "Encrypts corp data", "Stops ransomware"], 0, "Portals are legal/tracking not encryption."],
      ["Wi-Fi 6/6E adds:", "More spectrum efficiency; security still needs WPA3/802.1X", ["Automatic zero trust", "Removes need for VPN", "Disables phishing"], 0, "New PHY does not replace auth."],
      ["Bluetooth in office for:", "Keep off or controlled—separate from Wi-Fi policy", ["Domain admin auth", "Replace TLS", "Backup strategy"], 0, "Bluetooth is separate attack surface."],
      ["SSID hiding is:", "Weak security through obscurity—use strong auth instead", ["Best practice alone", "Replaces encryption", "Stops APT"], 0, "Hidden SSID does not stop attackers."],
      ["Wireless site survey ensures:", "Coverage and detects rogue APs physically", ["Coffee quality", "SPF", "Password length"], 0, "Surveys validate deployment."],
      ["KRACK-class attacks targeted:", "WPA2 handshake weaknesses—patch clients/APs", ["TLS 1.3", "Email", "DNSSEC"], 0, "Keep firmware updated."],
      ["Corporate devices should:", "Not auto-join open networks; use VPN on untrusted Wi-Fi", ["Join any hotspot", "Disable EDR", "Share passwords"], 0, "Untrusted networks need VPN."],
      ["Wi-Fi MFA often via:", "802.1X integrated with RADIUS + IdP", ["SSID password only", "WEP key index", "MAC filter alone"], 0, "RADIUS integrates identity."],
      ["MAC filtering on AP:", "Easily spoofed—not primary security", ["Strong as MFA", "Stops nation-states", "Replaces encryption"], 0, "MAC filters are weak."],
      ["Wireless segmentation per SSID maps to:", "VLANs with firewall policies", ["Flat domain admin", "Public SMB", "Disable monitoring"], 0, "SSID maps to VLAN security."],
      ["IoT Wi-Fi devices often:", "Cannot do 802.1X—use PSK IoT VLAN isolated", ["Join domain as admin", "Store PAN data unencrypted", "Disable firewall"], 0, "IoT needs isolated PSK networks."],
      ["Pen test finds WPA2-PSK `Company123`. Fix:", "Move to WPA3-Enterprise or strong unique PSK + isolation", ["Post PSK on door", "Disable Wi-Fi", "Open network"], 0, "Weak PSK is easily cracked."],
      ["Wireless controller misconfig risk:", "Centralized mistake affects all APs—secure management", ["No impact", "Improves SPF", "Fixes backups"], 0, "Controller is high value target."],
      ["Monitoring wireless auth failures detects:", "Credential stuffing on 802.1X", ["Printer issues", "DNS only", "Coffee"], 0, "Auth failure spikes are signals."],
      ["Remote office Wi-Fi uses:", "Same corporate standards—not consumer router defaults", ["Default admin/password admin", "WEP", "Disable patches"], 0, "Branch Wi-Fi must meet corp baseline."],
      ["Wi-Fi security awareness:", "Verify SSID, avoid rogue hotspots, report anomalies", ["Join strongest signal always", "Disable reporting", "Share OTP"], 0, "Users help detect rogue APs."],
      ["WPA2-Enterprise with expired RADIUS cert causes:", "Connection failures—monitor cert lifecycle", ["Stronger security", "Free internet", "MFA bypass"], 0, "Cert expiry breaks auth."],
      ["802.11w management frame protection mitigates:", "Deauthentication/disassociation attacks", ["SQL injection", "BGP hijacks", "MD5 passwords"], 0, "Protected management frames reduce deauth DoS."],
    ]),
    pack([
      ["IDS detects:", "Suspicious activity via signatures/anomalies—alerts", ["Blocks all traffic always inline", "Encrypts disks", "Stores passwords"], 0, "IDS is detect-oriented."],
      ["IPS differs by:", "Inline prevention blocking malicious packets", ["Only offline analysis", "Email filtering", "SPF"], 0, "IPS can actively block."],
      ["Signature-based IDS weakness:", "Misses zero-day without known pattern", ["No false positives ever", "Replaces EDR", "Fixes phishing"], 0, "Signatures need prior knowledge."],
      ["Anomaly-based IDS challenge:", "High false positives without tuning baselines", ["Perfect accuracy day one", "No baselines needed", "Disables logging"], 0, "Baselines require tuning period."],
      ["IDS placement on span port:", "Passive copy of traffic—no inline latency", ["Stops all attacks always", "Replaces firewall", "Shares admin password"], 0, "SPAN/tap provides passive visibility."],
      ["IPS false positive impact:", "Blocked legitimate traffic—tune carefully", ["Always harmless", "Improves payroll", "SPF fix"], 0, "False positives cause outages."],
      ["Suricata/Snort are:", "Open-source IDS/IPS engines", ["Antivirus brands", "Password managers", "HR systems"], 0, "Snort/Suricata are common engines."],
      ["TLS encrypted traffic blind spot for IDS unless:", "Inline decryption with legal/policy approval", ["Magic decryption always free", "Ignore encrypted traffic entirely always OK", "Disable TLS"], 0, "Encryption hides payloads from passive IDS."],
      ["IDS alert tuning uses:", "Risk scoring, suppression, and context enrichment", ["Alert on every packet", "Disable SOC", "Delete logs"], 0, "Tuning maintains SOC usability."],
      ["Network IDS vs host IDS:", "NIDS watches network; HIDS on endpoint—complementary", ["Identical", "NIDS sees encrypted host memory", "HIDS sees east-west only"], 0, "Different vantage points."],
      ["IPS in fail-open mode during failure:", "Allows traffic—consider HA and monitoring", ["Blocks internet forever", "Encrypts backups", "Removes MFA"], 0, "Fail modes affect availability/security tradeoff."],
      ["Evasion technique: IP fragmentation against IDS:", "Reassembly issues may hide payload—modern IDS reassembles", ["Always works", "Stops IPS forever", "Fixes Wi-Fi"], 0, "Attackers fragment; IDS must reassemble."],
      ["IDS signature update cadence:", "Regular from vendor/community feeds", ["Never update", "Once per decade", "From random forums only"], 0, "Fresh signatures detect new threats."],
      ["Correlation of IDS with EDR:", "Links network alerts to host process", ["Unnecessary", "Slows IR", "Disables firewall"], 0, "Correlation improves context."],
      ["IPS blocking SQLi in line:", "May break app if overly broad—tune to app", ["Always safe", "Replaces secure coding", "Disables WAF"], 0, "IPS/WAF need app-aware tuning."],
      ["Honeypot IDS interaction:", "Honeypot triggers high-fidelity alerts", ["Replaces IPS", "Stores payroll", "Fixes SPF"], 0, "Honeypots generate strong signals."],
      ["IDS alert: 'ET EXPLOIT Apache Log4j' should trigger:", "Emergency hunt/patch playbook for Log4Shell era vulns", ["Ignore", "Disable internet", "Pay ransom"], 0, "Critical signatures warrant urgent action."],
      ["Machine learning IDS adds:", "Behavioral models for unknown attacks with tuning", ["Zero false positives guaranteed", "Removes need for signatures entirely always", "Disables logging"], 0, "ML aids unknown detection with oversight."],
      ["IPS throughput sizing must match:", "Network bandwidth at line rate to avoid drops", ["Ignore capacity", "Use 10Mbps IPS on 10G link", "Disable HA"], 0, "Undersized IPS misses attacks."],
      ["IDS compliance role:", "Detective control supporting PCI/monitoring requirements", ["Replaces encryption", "Eliminates MFA", "Stops IR"], 0, "IDS supports detective obligations."],
      ["Alert on internal port scan from workstation:", "Possible lateral recon—investigate host", ["Normal always", "Ignore", "Disable EDR"], 0, "Internal scans are suspicious."],
      ["IPS custom rule for C2 domain:", "Blocks egress to malicious FQDN", ["Opens RDP", "Disables TLS", "Shares passwords"], 0, "Custom rules operationalize intel."],
      ["IDS during encrypted internet era pushes:", "East-west visibility, EDR, and selective TLS inspection", ["Only perimeter IDS sufficient alone", "Remove all host agents", "Disable SIEM"], 0, "Perimeter IDS alone is insufficient."],
      ["SOC runbook for IDS alert:", "Enrich, scope, contain, eradicate per severity", ["Close without review", "Email attacker", "Disable MFA"], 0, "Runbooks standardize response."],
      ["IPS vendor virtual patch:", "Protects until code patch applied", ["Permanent fix alone", "Removes need to patch", "Disables WAF"], 0, "Virtual patch is temporary mitigation."],
    ]),
    pack([
      ["IPsec VPN modes: tunnel vs transport:", "Tunnel encrypts entire IP packet for site-to-site; transport often host-to-host", ["Same always", "Neither encrypts", "Replaces TLS"], 0, "Tunnel mode common for gateways."],
      ["SSL VPN (TLS) advantage:", "Traverses many firewalls on 443", ["Uses WEP", "No certificates needed ever", "Disables MFA"], 0, "TLS VPN uses common port."],
      ["Split tunnel VPN risk:", "Malware on host accesses internet while corp tunnel active", ["No risk ever", "Better than full tunnel always", "Stops EDR"], 0, "Split tunnel leaves local internet path."],
      ["IKEv2 with strong crypto suites provides:", "Modern VPN handshake and rekey", ["MD5 and DES best", "Cleartext passwords", "SPF"], 0, "Use modern IKE/IPsec suites."],
      ["VPN MFA should occur:", "At VPN gateway integrated with IdP", ["Never", "After domain compromise only", "Via email password"], 0, "VPN auth must be strong."],
      ["Compromised VPN creds lead to:", "Network access—pair with ZTNA segmentation", ["Nothing if MFA on email only", "Automatic patch", "SPF fix"], 0, "VPN creds grant network layer access."],
      ["Dead peer detection (DPD) in VPN:", "Detects failed peers for tunnel recovery", ["Encrypts Wi-Fi", "Stores biometrics", "Removes logging"], 0, "DPD maintains tunnel health."],
      ["VPN logs for SOC include:", "User, assigned IP, bytes, duration, disconnect reason", ["Nothing", "Plaintext passwords", "Coffee orders"], 0, "Logs support investigations."],
      ["Site-to-site VPN between cloud and on-prem:", "Encrypts hybrid traffic over internet", ["Replaces IAM", "Public RDP instead", "Disables TLS"], 0, "Site-to-site links hybrid networks."],
      ["VPN bypass attack uses:", "Stolen creds or malware on VPN endpoint to pivot", ["Quantum DNS only", "Printer driver", "SPF"], 0, "Endpoint compromise bypasses VPN crypto."],
      ["Always-on VPN on mobile:", "Protects data in transit from untrusted networks", ["Drains battery only—no security", "Replaces MDM", "Disables patches"], 0, "Mobile benefits from VPN on public Wi-Fi."],
      ["IPsec AH provides:", "Integrity/authentication without confidentiality alone", ["Full encryption always", "Password storage", "MFA"], 0, "AH authenticates but ESP encrypts typically."],
      ["VPN concentrator hardening:", "Disable weak ciphers, patch, limit mgmt access", ["Telnet admin", "Default SNMP public", "Share private keys"], 0, "Concentrators are critical assets."],
      ["Client VPN split DNS:", "Internal domains resolve via corp DNS over tunnel", ["Use attacker DNS", "Disable DNSSEC always bad", "Public DNS for corp names"], 0, "Split DNS protects name resolution."],
      ["VPN vs ZTNA migration driver:", "Reduce broad network access grant", ["Slower internet desired", "Remove MFA", "Disable logging"], 0, "ZTNA limits blast radius vs VPN."],
      ["Pen test finds IKE aggressive mode PSK crackable:", "Migrate to IKEv2 with certificates", ["Keep aggressive mode", "Use password `vpn`", "Disable MFA"], 0, "Aggressive mode PSK risks offline attack."],
      ["VPN two-factor with hardware token:", "Strong protection for remote workforce", ["Weaker than password only", "Illegal", "Replaces EDR"], 0, "Hardware OTP hardens VPN."],
      ["Monitoring excessive VPN bandwidth from user:", "Possible data exfil—investigate", ["Normal always", "Ignore", "Disable SIEM"], 0, "Volume anomalies may signal exfil."],
      ["VPN kill switch on client:", "Blocks traffic if VPN drops preventing leak", ["Shares data when down", "Disables encryption", "Removes MFA"], 0, "Kill switch prevents cleartext leak."],
      ["Regulatory requirement for remote admin:", "Encrypted management channels—VPN or bastion", ["Telnet", "HTTP admin", "RDP 0.0.0.0"], 0, "Regulations expect encryption."],
      ["VPN account shared by team violates:", "Individual accountability", ["PCI always allows", "Improves security", "Required by FIDO"], 0, "Shared accounts hinder attribution."],
      ["Post-quantum VPN planning considers:", "Hybrid PQ/TLS ciphers emerging standards", ["Ignore crypto entirely", "Use ROT13", "Disable certs"], 0, "PQ migration is on roadmap."],
      ["VPN incident response:", "Revoke certs/creds, block sessions, hunt connected hosts", ["Change logo", "Disable IR", "Publish passwords"], 0, "Treat VPN compromise as network incident."],
      ["Always-on VPN with health check should verify:", "DNS, MFA, and posture before granting full tunnel", ["Nothing—password only once", "Open RDP", "Disable logging"], 0, "Health checks reduce tunnel abuse from unhealthy endpoints."],
      ["Split tunneling policy allowing only corp CIDR over VPN reduces:", "Exposure of full internal network to compromised remote host", ["Need for MFA", "TLS usage", "DNS logging"], 0, "Restricting tunnel routes limits lateral reach from BYOD endpoints."],
    ]),
    pack([
      ["NetFlow/IPFIX provides:", "Metadata about flows (5-tuple, bytes) for traffic analysis", ["Full packet payloads always", "Email content", "Passwords"], 0, "Flow data aids baselining."],
      ["SPAN/mirror port used for:", "Copying traffic to IDS/NDR sensors", ["Encrypting Wi-Fi", "Patching servers", "Storing MFA seeds"], 0, "SPAN feeds monitoring tools."],
      ["NDR (network detection and response) uses:", "ML on flow/packet metadata to find anomalies", ["Only hub repeating", "HR surveys", "SPF"], 0, "NDR detects network anomalies."],
      ["Baseline network behavior then alert on:", "Deviations like new beaconing or data exfil volumes", ["Every packet", "Coffee orders", "Desk moves"], 0, "Baselines enable anomaly detection."],
      ["DNS query logging reveals:", "C2 domains and DGA patterns", ["Only printer status", "MFA codes", "TLS certs"], 0, "DNS logs are high value."],
      ["Full packet capture (PCAP) storage challenge:", "Volume—use targeted capture and retention policy", ["Store forever all internet", "Delete all logs", "Disable encryption"], 0, "PCAP is storage intensive."],
      ["SNMP monitoring of network gear requires:", "SNMPv3 with authPriv—not v2c public", ["Community `public` on internet", "Telnet", "Disable logging"], 0, "Secure SNMP prevents device compromise."],
      ["Syslog from firewall to SIEM enables:", "Correlation of denies/drops with incidents", ["Marketing", "Coffee", "DNS TTL only"], 0, "Firewall syslog feeds detection."],
      ["Network monitoring detects lateral SMB:", "East-west traffic spikes to many hosts on 445", ["Normal user behavior always", "SPF failure", "TLS expiry"], 0, "SMB scanning is lateral signal."],
      ["Encrypted traffic visibility gap mitigated by:", "TLS metadata (JA3/JA4), DNS logs, and EDR", ["Ignore encryption", "Disable HTTPS", "Remove MFA"], 0, "Metadata aids encrypted era monitoring."],
      ["sFlow vs NetFlow:", "Both sample/export flow stats; vendor implementations differ", ["Identical to PCAP always", "Only for Wi-Fi", "Replace IAM"], 0, "Flow export standards vary."],
      ["Network baseline during onboarding week establishes:", "Normal peers and volumes for anomaly alerts", ["Nothing", "Attacker C2", "Disable SIEM"], 0, "Onboarding period sets baseline."],
      ["Alert on new device MAC in sensitive VLAN:", "Possible rogue device—investigate", ["Always welcome", "Disable port security", "Share admin password"], 0, "New MAC may be unauthorized."],
      ["Performance monitoring (latency/packet loss) supports:", "Availability leg of CIA and troubleshooting", ["Only security incidents", "HR payroll", "SPF"], 0, "Performance affects availability."],
      ["Network monitoring in cloud uses:", "VPC flow logs and cloud-native mirrors", ["Only paper logs", "Disable IAM", "Public RDP"], 0, "Cloud has native telemetry."],
      ["Synthetic monitoring probes:", "Test reachability of critical services externally", ["Replace patching", "Store passwords", "Disable MFA"], 0, "Synthetics detect outages."],
      ["Threshold alert on 95th percentile bandwidth:", "Capacity planning and DDoS early signal", ["Meaningless", "Fixes phishing", "Removes EDR"], 0, "Bandwidth trends matter."],
      ["Network TAP vs SPAN:", "TAP is inline passive copy; SPAN is switch mirror—TAP avoids dropped packets under load", ["Identical always", "TAP blocks traffic", "SPAN always full rate guaranteed"], 0, "TAPs reliable under heavy load."],
      ["Monitoring DNS tunneling via:", "Entropy of subdomain labels and query volume per host", ["SPF only", "Printer logs", "Coffee"], 0, "Statistical DNS analysis finds tunnels."],
      ["SOC playbook for net alert 'beaconing':", "Identify host/process, contain, eradicate", ["Ignore", "Disable network", "Pay ransom"], 0, "Beaconing suggests C2."],
      ["Network monitoring data retention aligned to:", "Compliance and IR needs—often 90-365 days hot", ["Delete hourly", "Keep 1 hour only always", "Forever all PCAP internet-wide"], 0, "Retention balances cost and investigations."],
      ["Integration NDR + SIEM + EDR gives:", "Cross-layer correlated incidents", ["Redundant waste always", "Removes firewalls", "Disables IR"], 0, "Layered telemetry improves context."],
      ["Monitoring management plane access:", "Detect unauthorized changes to router configs", ["Irrelevant", "Slow Wi-Fi only", "SPF"], 0, "Control plane changes are critical."],
      ["Alert fatigue mitigation:", "Risk-based alerting and suppression tuned", ["Alert everything", "Disable SOC", "Delete SIEM"], 0, "Tuning keeps SOC effective."],
      ["Network monitoring KPI:", "MTTD for network-originated incidents", ["Poster count", "Mouse DPI", "Desk color"], 0, "Detection speed measures program."],
    ]),
  ]);
}
