import { PASSWORD_CHAPTERS } from "../cyber-hard-meta.mjs";
import { fromChapters, Q } from "./_loader.mjs";

function pack(rows) {
  return rows.map(([q, a, w, c, e]) => Q(q, a, w, c, e));
}

export function buildPasswordChapters() {
  return fromChapters(PASSWORD_CHAPTERS, [
    pack([
      ["NIST SP 800-63B recommends memorized secrets minimum length roughly:", "8 characters minimum with emphasis on length and breach checking over forced composition rules", ["Exactly 6 characters always", "Maximum 4 characters", "Length irrelevant if symbols present"], 0, "Modern guidance prioritizes length and breach checks."],
      ["Password `P@ssw0rd!` for 10,000 users is weak because:", "It appears in breach corpuses despite symbol substitution", ["Symbols guarantee 128-bit entropy", "It is longer than 64 characters", "NIST forbids symbols"], 0, "Common patterns are cracked instantly via dictionaries."],
      ["Entropy of randomly generated 20-character password from [A-Za-z0-9] is approximately:", "~119 bits if characters are uniform random", ["4 bits always", "256 bits per character always", "0 bits if uppercase used"], 0, "Entropy grows with length and alphabet size."],
      ["Passphrase `correct horse battery staple` strength comes from:", "Length and random word selection from large dictionary", ["Capital letters only", "Using company name", "Writing on monitor"], 0, "Diceware-style passphrases leverage length."],
      ["Credential stuffing succeeds when users:", "Reuse passwords breached elsewhere", ["Use unique 30-char passwords per site", "Use hardware security keys only", "Disable internet"], 0, "Reuse links unrelated breaches to your login."],
      ["Password spraying tries:", "Few common passwords against many accounts to avoid lockout", ["Every password for one user until lockout", "Only MFA bypass hardware", "DNS poisoning"], 0, "Spraying distributes guesses across accounts."],
      ["Offline hash cracking after DB theft uses:", "GPU/ASIC acceleration against stolen hash dumps", ["Live login lockouts", "Email SPF checks", "Wi-Fi deauth"], 0, "Offline attacks are not limited by online lockouts."],
      ["bcrypt/scrypt/Argon2 improve storage by:", "Slowing hash computation with salts per password", ["Encrypting passwords reversibly with AES key in code", "Storing plaintext for speed", "Using MD5 unsalted"], 0, "Adaptive hashes resist offline guessing."],
      ["Password strength meter encouraging `Summer2024!` problem:", "Meters reward complexity patterns humans predict", ["Meters are always accurate", "Summer dates are high entropy", "Symbols remove need for length"], 0, "Predictable patterns fool naive meters."],
      ["Kerberos AS-REP roasting works when:", "Account has preauthentication disabled allowing offline crack of ticket", ["MFA is FIDO2", "Password is 100 random chars", "SPF fails"], 0, "AS-REP roasting targets misconfigured accounts."],
      ["Windows stores cached domain creds. Risk if laptop stolen:", "Offline attacks against cached hashes if disk not encrypted", ["No risk if password screen shown", "Automatic cloud wipe always", "TLS prevents theft"], 0, "Full-disk encryption protects cached creds at rest."],
      ["Password in browser autofill on shared PC risk:", "Next user may access session or stored creds", ["Improves security always", "Required by PCI", "Blocks phishing"], 0, "Shared systems need separate profiles and logout."],
      ["HIBP k-anonymity API allows:", "Checking if password appeared in breaches without sending full password", ["Uploading all employee passwords publicly", "Disabling MFA", "Publishing hashes"], 0, "Range API reveals only prefix for privacy."],
      ["Policy mandating special char every 90 days often causes:", "Predictable mutations like `Winter2024!` → `Spring2024!`", ["Higher entropy always", "Lower helpdesk load", "Elimination of stuffing"], 0, "Rotation without breach driver breeds patterns."],
      ["GPU cluster cracks NTLM at high rate because:", "NTLM is fast unsalted hash suited for parallel guessing", ["NTLM uses Argon2", "GPUs cannot do math", "MFA stops offline attacks"], 0, "Legacy fast hashes fall quickly offline."],
      ["Password rules blocking paste harms security by:", "Blocking password managers that generate/stored strong secrets", ["Stopping malware", "Improving entropy", "Enabling FIDO2"], 0, "Paste blocking discourages manager use."],
      ["Shared service account password in wiki violates:", "Individual accountability and rotation on staff changes", ["Least privilege only visually", "MFA requirements physically", "Logging standards"], 0, "Shared secrets cannot attribute actions."],
      ["Rainbow tables effective against:", "Unsalted MD5/SHA1 password databases", ["Argon2id hashes", "Hardware security keys", "One-time passwords"], 0, "Salting defeats precomputed tables."],
      ["Passphrase with song lyrics is weak because:", "Low randomness—attackers include lyric dictionaries", ["Too long", "Uses illegal characters", "NIST bans passphrases"], 0, "Predictable sources reduce effective entropy."],
      ["Online login throttling should:", "Backoff and alert on abnormal auth patterns per IP/account", ["Never lock accounts", "Publish valid usernames", "Disable logging"], 0, "Throttling slows online guessing."],
      ["Password embedded in mobile app binary is:", "Extractable via reverse engineering—use OAuth/device attestation instead", ["Safe if obfuscated slightly", "Protected by TLS alone", "Equivalent to HSM"], 0, "Client secrets in apps are not secret."],
      ["Biometric phone unlock protects stored passwords by:", "Gating access to OS keystore with device biometrics/PIN", ["Replacing need for server-side auth", "Sending fingerprints to websites", "Eliminating phishing"], 0, "Biometrics protect local secret storage."],
      ["Crack time estimate 10^12 guesses/sec against 80-bit password:", "Still impractical for truly random 80-bit secret", ["Instant always", "Depends on TLS version only", "Faster if password is `password1`"], 0, "Random high-entropy secrets resist even fast attackers."],
      ["Password policy exception process should:", "Require risk acceptance and compensating controls for legacy systems", ["Grant permanent weak passwords", "Disable auditing", "Email passwords to CEO"], 0, "Exceptions need governance."],
      ["Strength of passwordless FIDO2 sign-in vs password:", "Phishing-resistant challenge bound to origin reduces credential theft", ["Weaker because no password", "Same as SMS OTP", "Requires shorter secrets"], 0, "FIDO2 resists phishing replay."],
    ]),
    pack([
      ["FIDO2/WebAuthn security key is phishing-resistant because:", "Credentials are origin-bound and challenge-response signed", ["It sends password hash in email", "It stores OTP in SMS", "It disables TLS"], 0, "WebAuthn binds auth to site origin."],
      ["TOTP (RFC 6238) seed compromise means:", "Attacker can generate valid codes until seed rotated", ["Codes remain safe forever", "Hardware breaks", "SPF fails"], 0, "TOTP security requires seed confidentiality."],
      ["SMS OTP weakness includes:", "SIM swap and SS7 interception risks", ["Perfect phishing resistance", "Quantum immunity", "Automatic GDPR compliance"], 0, "SMS is not strong MFA."],
      ["Push MFA fatigue attack tricks user into:", "Approving rogue push notifications after spamming", ["Improving entropy", "Rotating passwords automatically", "Patching servers"], 0, "Users may approve pushes to stop noise."],
      ["FIDO2 resident key (discoverable credential) allows:", "Username-less login where platform discovers credential ID", ["Sharing private key online", "Bypassing TLS", "Storing password plaintext"], 0, "Resident keys enable discoverable flows."],
      ["MFA bypass via SSO session cookie theft after phishing:", "Session hijack may satisfy auth without second factor on reuse", ["Impossible if MFA exists", "Requires Argon2", "Fixes SPF"], 0, "Stolen session tokens can bypass step-up."],
      ["Hardware token with PIN protects against:", "Physical theft of token without PIN knowledge", ["All malware always", "DDoS", "DNS cache poison"], 0, "PIN gates use of stolen hardware."],
      ["OATH HOTP differs from TOTP by:", "Counter-based OTP instead of time-based", ["Using email instead of app", "Eliminating seed", "Requiring MD5 passwords"], 0, "HOTP increments counter per use."],
      ["Adaptive MFA policies should require step-up when:", "Risk signals show new device, impossible travel, or sensitive action", ["User is in office always trusted forever", "Never—MFA once per year", "Printing documents"], 0, "Risk-based step-up balances friction and security."],
      ["Backup codes for MFA should be:", "Single-use, stored securely, and regenerated after use", ["Reused indefinitely posted on monitor", "Shared on Slack", "Embedded in password hint"], 0, "Backup codes are one-time recovery."],
      ["MFA enrollment phishing site captures:", "Password plus real-time OTP relay to attacker session", ["Hardware FIDO private key easily", "TLS certificates", "Firewall rules"], 0, "Real-time phishing proxies OTP."],
      ["Number matching in push MFA mitigates:", "Blind approval of unexpected pushes", ["SIM swap", "SQL injection", "Ransomware encryption"], 0, "Number matching adds context to approval."],
      ["Certificate-based smart card MFA uses:", "Private key on card with PIN unlocking crypto operation", ["Static password in email", "DNSSEC", "MAC address filtering only"], 0, "Smart cards store keys in hardware."],
      ["MFA on VPN but not SaaS leads to:", "Attackers pivoting to cloud apps after VPN compromise", ["Complete protection", "Lower phishing", "Automatic patch"], 0, "Coverage gaps shift attack path."],
      ["Recovery of lost FIDO key requires:", "Alternate registered factors and account recovery policy", ["Publishing private key", "Disabling all MFA", "Emailing seed"], 0, "Multiple factors needed for recovery."],
      ["TOTP clock drift causes failures; fix by:", "Allowing small time window (±1 step) on server", ["Disabling MFA", "Using MD5 passwords", "Removing NTP"], 0, "Window tolerates minor skew."],
      ["Attacker registers own MFA on compromised account. Defense:", "Protect enrollment with step-up, notify user, and monitor new factor adds", ["Allow anyone to add factors", "Disable logging", "Use SMS only"], 0, "Enrollment must be secured."],
      ["MFA exemption for legacy app should:", "Use compensating network controls and migration plan", ["Be permanent without review", "Disable all logging", "Share OTP publicly"], 0, "Legacy gaps need compensating controls."],
      ["WebAuthn attestation allows enterprise to:", "Restrict allowed authenticator models/vendors", ["Read user passwords", "Disable HTTPS", "Publish biometrics"], 0, "Attestation supports device policy."],
      ["Email MFA codes vulnerable to:", "Mailbox compromise and phishing", ["Hardware theft only", "Argon2 cracking", "SPF alignment"], 0, "Email is often already compromised in attacks."],
      ["MFA rate limiting on verification endpoint prevents:", "Brute forcing short OTP space", ["Users enrolling", "TLS 1.3", "Backups"], 0, "Rate limits protect OTP verification."],
      ["Step-up MFA for wire transfers is example of:", "Risk-based authentication for high-impact actions", ["Annual password rotation", "DNS filtering", "Poster campaign"], 0, "High-risk actions warrant extra auth."],
      ["FIDO2 passwordless does not eliminate need for:", "Device unlock (PIN/biometric) and account recovery controls", ["Patching", "Logging", "Incident response"], 0, "Local device security still matters."],
      ["Helpdesk MFA reset social engineering control:", "Out-of-band identity verification and ticket approval workflow", ["Reset via email link only", "Tell caller current OTP", "Disable MFA permanently"], 0, "Reset processes are frequent attack targets."],
      ["MFA coverage metric for workforce should track:", "Percentage of interactive logins using strong factors", ["Number of posters", "Desk count", "Coffee spend"], 0, "Coverage metrics drive program maturity."],
    ]),
    pack([
      ["Passkeys (FIDO synced) use:", "Platform authenticator with cloud sync of credential keys encrypted", ["Plaintext passwords in iCloud notes", "SMS OTP only", "Shared domain admin password"], 0, "Synced passkeys use platform cloud with encryption."],
      ["Passkey phishing resistance similar to security keys because:", "Private key never leaves authenticator; origin-bound challenges", ["Users type passkey into fake forms", "Passkeys are emailed", "TLS not needed"], 0, "Cryptographic challenge-response resists phishing."],
      ["Cross-device passkey sign-in uses:", "Bluetooth proximity or QR to bridge phone authenticator to desktop", ["Sending password via fax", "Disabling MFA", "Publishing hashes"], 0, "Hybrid transport links devices securely."],
      ["Enterprise passkey deployment needs:", "Identity provider support, recovery policy, and device standards", ["Only MD5 passwords", "Removal of all logging", "Public RDP"], 0, "IdP integration and recovery are key."],
      ["Passkey vs password manager stored password:", "Passkey private key is non-exportable phishing-resistant credential", ["Identical security", "Weaker than SMS", "Stored in plaintext always"], 0, "Passkeys are asymmetric credentials."],
      ["User loses phone with synced passkeys. Recovery:", "Use preregistered backup factor and device management to revoke", ["Publish private key", "Disable all auth", "Email passkey"], 0, "Device loss triggers recovery and revocation."],
      ["Passkey provider breach concern is:", "Encrypted key material exposure—depends on provider crypto design", ["No risk ever", "All passwords leaked automatically", "SPF breaks"], 0, "Synced keys rely on provider security."],
      ["Conditional UI for passkeys in browser:", "Shows passkey option when domain has registered credential", ["Forces password always", "Disables HTTPS", "Shares seed"], 0, "Conditional mediation improves UX."],
      ["Attacker with malware on device may:", "Abuse session after passkey auth—still need EDR", ["Clone passkey private key easily from FIDO", "Break AES-256 instantly", "Disable TLS"], 0, "Endpoint compromise post-auth remains a risk."],
      ["Passkey registration after account takeover requires:", "Secured enrollment and monitoring for new credential adds", ["Open registration to anyone", "Email password", "Disable audit"], 0, "Enrollment must be protected."],
      ["Legacy app without WebAuthn bridge via:", "IdP federation or FIDO2 gateway translating to legacy protocols", ["Posting passwords to API", "Removing TLS", "Using ROT13"], 0, "Gateways enable gradual adoption."],
      ["Passkey user verification (UV) means:", "Local PIN/biometric required to unlock authenticator", ["Email OTP", "Manager approval only", "None"], 0, "UV ensures user presence at device."],
      ["Discoverable credential enables:", "Username-less login flows", ["Publishing password hashes", "Disabling MFA", "DNS tunneling"], 0, "Discoverable credentials store user handle."],
      ["Passkey backup to another platform risk:", "Vendor lock-in and differing security models—document choices", ["Automatic compliance", "Eliminates IR", "Removes logging"], 0, "Understand provider security properties."],
      ["Corporate policy may require hardware-bound passkeys for:", "High-privilege roles where sync is unacceptable", ["All cafeteria accounts", "Public marketing blog", "None ever"], 0, "High-risk roles may mandate device-bound keys."],
      ["Passkey attestation in enterprise allows:", "Allow-listing authenticator models", ["Stealing biometrics globally", "Disabling encryption", "Sharing private keys"], 0, "Attestation enforces device standards."],
      ["User tries passkey on wrong phishing domain. Result:", "Authentication fails—origin mismatch", ["Success with warning", "Password emailed", "MFA disabled"], 0, "Origin binding blocks phishing sites."],
      ["Passkey plus device compliance (MDM) ensures:", "Only managed devices enroll corporate credentials", ["Weaker security", "No need for EDR", "Public Wi-Fi only"], 0, "MDM gates corporate passkey enrollment."],
      ["Migration plan from passwords should:", "Enroll passkeys, retain fallback during transition, monitor adoption", ["Disable passwords day one without fallback", "Remove MFA", "Stop backups"], 0, "Phased migration reduces lockout risk."],
      ["Passkey reset attack via helpdesk mitigated by:", "Strong identity proofing same as MFA reset controls", ["Email alone", "Caller ID trust only", "Posting OTP"], 0, "Recovery paths must be hardened."],
      ["FIDO Alliance standards underlying passkeys:", "WebAuthn and CTAP protocols", ["SMTP and FTP", "WEP and WPA", "MD5"], 0, "Passkeys build on WebAuthn/CTAP."],
      ["Passkey on shared kiosk inappropriate because:", "Device-bound auth should not be shared across untrusted users", ["Passkeys require keyboards", "TLS unsupported", "SPF fails"], 0, "Shared kiosks need non-persistent auth models."],
      ["Audit log for passkey sign-in should record:", "Credential ID, origin, and risk context—not private key", ["Private key material", "User password", "Seed"], 0, "Logs capture metadata, never secrets."],
      ["Developer stores WebAuthn challenge in session insecurely. Risk:", "Replay or fixation if session hijacked—use secure cookies and one-time challenges", ["No effect", "Improves entropy", "Blocks phishing"], 0, "Challenge handling must prevent replay."],
      ["Passkey adoption KPI:", "Percent accounts with registered passkeys and successful auth rate", ["Poster count", "Mouse DPI", "DNS TTL"], 0, "Measure enrollment and success."],
    ]),
    pack([
      ["Enterprise password manager vault encrypted with:", "User master password-derived key and zero-knowledge architecture", ["Plaintext on vendor server by default in good designs", "MD5 of username", "Posted on intranet"], 0, "Reputable managers use client-side encryption."],
      ["Sharing vault item via manager vs Slack:", "Manager provides audited sharing with access controls", ["Slack is more secure always", "Email is best", "Sticky note preferred"], 0, "Managers offer controlled sharing."],
      ["Browser built-in password save vs dedicated manager:", "Manager offers cross-platform vault, sharing, and breach monitoring", ["Browser save is always enterprise-grade", "Neither encrypts", "Both publish passwords"], 0, "Dedicated managers add enterprise features."],
      ["Master password recovery impossible in zero-knowledge means:", "Loss of master loses vault—plan emergency recovery kits", ["Vendor can read all passwords", "Backdoor always exists", "FBI has key"], 0, "Zero-knowledge trades recoverability for privacy."],
      ["Autofill phishing uses fake login page. Manager defense:", "Match saved login URL before fill", ["Fill any form always", "Disable HTTPS", "Share vault"], 0, "URL matching reduces autofill on wrong sites."],
      ["Service account passwords in PAM integration with manager:", "Checkout/check-in rotates and audits privileged access", ["Post in Teams channel", "Use `Password123`", "Disable logs"], 0, "PAM integration governs privileged secrets."],
      ["Breach monitoring in manager alerts when:", "Stored credentials appear in known breach corpuses", ["User is late to meeting", "CPU high", "SPF fails"], 0, "Breach alerts prompt rotation."],
      ["Offline vault access requires:", "Cached encrypted vault unlocked locally", ["Internet always", "SMS only", "Domain admin"], 0, "Offline mode uses local encrypted cache."],
      ["MDM can deploy manager with:", "Policy-enforced vault and blocked weak practices", ["Mandatory password sharing", "Disable encryption", "Public vault"], 0, "MDM enforces enterprise password policy."],
      ["Attacker malware scrapes manager memory. Mitigation:", "EDR, device integrity, and auto-lock on idle", ["Use sticky notes instead", "Disable OS updates", "Remove MFA"], 0, "Endpoint security protects unlocked vaults."],
      ["Sharing password via manager 'link' feature risk:", "Link leakage grants access—use time-bound and permissioned shares", ["Always safe publicly", "Improves phishing", "Replaces MFA"], 0, "Shared links need expiration and scope."],
      ["Personal manager on corporate device policy:", "Often prohibited or segregated to avoid data co-mingling", ["Required for PCI", "Mandated for domain admin", "Replaces EDR"], 0, "Policies may separate personal and corporate vaults."],
      ["Vault export unencrypted JSON is:", "Dangerous—treat as credential breach if exposed", ["Best practice daily", "Required by GDPR", "Same as hashing"], 0, "Exports must be protected like production secrets."],
      ["Manager emergency access feature allows:", "Designated colleague access after waiting period", ["Instant public access", "Attacker backdoor", "Disable MFA globally"], 0, "Emergency access supports bus factor with delay."],
      ["API key stored in manager custom field should:", "Use least access API scopes and rotation schedule", ["Embed in public GitHub", "Email to vendors unencrypted", "Disable logging"], 0, "Secrets still need scope and rotation discipline."],
      ["SSO plus manager coexist when:", "Some legacy apps lack SSO—manager fills gap", ["Never—mutually exclusive always", "Manager replaces IdP", "SSO removes need for secrets"], 0, "Managers handle non-SSO applications."],
      ["Clipboard clear after copy password prevents:", "Clipboard history tools harvesting secrets", ["Phishing", "DDoS", "DNS issues"], 0, "Clipboard hygiene reduces leakage."],
      ["Admin audits manager vault access logs for:", "Anomalous exports and sharing by insiders", ["Coffee orders", "Wallpaper", "Fan speed"], 0, "Audit logs detect insider misuse."],
      ["Phishing site asks for manager master password. User should:", "Never enter master on unknown sites—only official extension/app UI", ["Type master for convenience", "Share with IT via email", "Screenshot vault"], 0, "Master password entry only in trusted client."],
      ["Break-glass domain admin cred in sealed envelope vs manager:", "Manager with PAM checkout is preferred for auditability", ["Envelope in desk drawer is best", "Tweet password", "Disable monitoring"], 0, "PAM/manager improves control over paper secrets."],
      ["Mobile manager unlock with biometrics protects:", "Vault at rest on phone if device stolen", ["Server private keys", "TLS certs globally", "SPF"], 0, "Device biometrics gate local vault."],
      ["Vendor SOC 2 for manager cloud:", "Informs trust but customers still configure policies correctly", ["Eliminates phishing", "Removes MFA", "Stops IR"], 0, "Vendor attestation complements customer config."],
      ["Training: generate 20-char random per site because:", "Unique high-entropy secrets limit breach reuse impact", ["Reuse is fine with MFA elsewhere only", "Shorter is always better", "Write on whiteboard"], 0, "Unique long secrets contain blast radius."],
      ["Manager integration with SCIM provisions:", "User lifecycle syncing vault accounts with HRIS", ["Firewall rules", "DNS records", "Printer drivers"], 0, "SCIM automates onboarding/offboarding."],
      ["Local-only manager without cloud sync tradeoff:", "No cloud breach surface but weaker cross-device UX", ["Weaker security always", "Illegal for enterprise", "Requires SMS MFA"], 0, "Local-only reduces sync risk, limits mobility."],
    ]),
    pack([
      ["NIST 800-63B on periodic rotation:", "Do not require arbitrary rotation absent compromise evidence", ["Rotate daily always", "Never rotate after breach", "Rotate usernames instead"], 0, "Forced rotation often reduces security."],
      ["Microsoft and others deprecated 60-day rotation because:", "Users choose predictable sequences", ["Passwords became uncrackable", "MFA obsolete", "Hashes faster"], 0, "Predictable changes help attackers."],
      ["Rotate immediately when:", "Credential appears in breach dump or suspected compromise", ["Calendar says Tuesday", "User likes new password", "Poster updated"], 0, "Evidence-driven rotation is appropriate."],
      ["Rotation after helpdesk reset should:", "Force change at next login and invalidate old sessions", ["Email password in ticket", "Reuse old password", "Disable MFA"], 0, "Reset flows must invalidate old material."],
      ["Service account password rotation challenge:", "Applications may cache creds—coordinate change windows", ["Never rotate service accounts", "Post in chat", "Use `admin`"], 0, "Service accounts need dependency mapping."],
      ["KRBTGT rotation twice after AD compromise:", "Invalidates golden ticket forgeries", ["Cosmetic only", "Breaks DNS", "Removes MFA"], 0, "KRBTGT reset addresses golden ticket."],
      ["Rotation myth: changing `Winter1!` to `Winter2!`", "Trivial for attackers using rules based on old password", ["Adds 100 bits entropy", "Stops ransomware", "Fixes SPF"], 0, "Minor mutations are rule-based cracked."],
      ["Password history prevents:", "Reusing last N passwords but can encourage minor patterns", ["All attacks", "MFA", "Logging"], 0, "History helps but can incentivize patterns."],
      ["API key 'rotation' best practice:", "Issue new key, dual-run, deprecate old with monitoring", ["Publish both keys publicly", "Never rotate", "Email keys"], 0, "Graceful rotation avoids outages."],
      ["Rotation policy exception documentation needs:", "Risk owner, compensating controls, review date", ["Nothing", "Public blog", "Attacker approval"], 0, "Exceptions require governance."],
      ["Frequent rotation increases helpdesk:", "Lockouts and weak choices—operational cost", ["Security always up", "Zero tickets", "Free coffee"], 0, "Operational impact is real."],
      ["Compromised DB forces:", "Reset passwords and invalidate sessions tokens", ["Only rotate TLS certs", "Ignore", "Disable EDR"], 0, "DB breach requires credential invalidation."],
      ["Rotation of Wi-Fi PSK in office:", "Reasonable when staff leave or PSK exposed", ["Never for Wi-Fi", "Every hour", "Post PSK on door"], 0, "PSK rotation matters when exposure suspected."],
      ["Secrets in Kubernetes should rotate via:", "Automated secret operator with short TTL where possible", ["ConfigMap plaintext forever", "Docker hub comment", "Sticky note"], 0, "Automation reduces staleness."],
      ["Password rotation without fixing root cause:", "Useless if malware/keylogger still present", ["Always sufficient", "Stops APT", "Fixes phishing"], 0, "Must eradicate persistence alongside rotation."],
      ["Evidence-based rotation trigger from SIEM:", "Impossible travel successful login plus malware on host", ["Daylight saving time", "User birthday", "Printer jam"], 0, "Combine signals for rotation decisions."],
      ["Legacy app cannot change password programmatically. Control:", "PAM vault checkout and network isolation", ["Post password on wiki", "Disable MFA", "Ignore"], 0, "Compensate for technical limits."],
      ["Communicating rotation policy change:", "Explain breach-driven model to reduce user fatigue", ["Silent change", "Threaten users", "Remove MFA"], 0, "Change management improves compliance."],
      ["Rotation of SSH keys preferred over passwords because:", "Asymmetric keys easier to automate and revoke individually", ["SSH keys are shorter", "Passwords stronger", "Keys stored in email"], 0, "Keys support automation and per-host trust."],
      ["After merger, password policy harmonization should:", "Adopt stronger baseline without arbitrary frequent rotation", ["Weaken to lowest", "Share one domain admin", "Stop SSO"], 0, "Harmonize to stronger evidence-based policy."],
      ["Pen test finds passwords unchanged 5 years. Priority:", "Assess compromise evidence and enable MFA plus breach checks", ["Mandate daily rotation only", "Ignore", "Disable logging"], 0, "Age alone is weak signal—combine with controls."],
      ["Rotation dashboards should track:", "Compromise-driven resets completed vs scheduled busywork", ["Poster count", "Mouse clicks", "DNS TTL"], 0, "Measure meaningful rotation events."],
      ["OAuth refresh token rotation on use helps:", "Limit replay window of stolen refresh tokens", ["Eliminate phishing", "Remove TLS", "Disable IR"], 0, "Refresh rotation reduces token theft impact."],
      ["Post-rotation validation:", "Confirm apps/services reconnected and no lockout storm", ["Assume success", "Delete SIEM", "Pay ransom"], 0, "Validate to avoid operational outage."],
      ["Education on rotation myth:", "Teach unique strong passwords and MFA over calendar churn", ["More sticky notes", "Shorter passwords", "Share creds"], 0, "User education aligns with modern guidance."],
    ]),
    pack([
      ["HaveIBeenPwned notification for corporate email means:", "Assume credential may be reused—force reset and MFA review", ["Ignore—public site unreliable", "Publish password", "Disable monitoring"], 0, "Treat breach presence as rotation trigger."],
      ["Credential spill includes NTLM hashes. Immediate action:", "Assume domain compromise risk—reset impacted accounts and hunt PtH", ["Wait for quarterly review", "Email users new password in plaintext", "Disable EDR"], 0, "Hash leaks enable offline cracking and PtH."],
      ["User admits reusing work password on gaming site breached. Response:", "Mandatory unique password, MFA, and session revocation", ["No action", "Reward user", "Share with press"], 0, "Reuse links external breach to corporate account."],
      ["Breach response communications to users should:", "Direct to official reset portal—not links in attacker-style email", ["Include clickable password in email", "Ask for SSN", "Attach malware sample"], 0, "Avoid phishing-like reset messages."],
      ["Session invalidation after breach:", "Revoke refresh tokens/sessions globally for affected users", ["Leave sessions active", "Disable MFA", "Publish tokens"], 0, "Active sessions may remain valid after password change."],
      ["Attacker sells corp creds on market. Detection:", "Dark web monitoring and impossible travel auth alerts", ["Only annual survey", "Printer logs", "SPF"], 0, "Monitoring and auth anomalies detect abuse."],
      ["Password reset portal flooded by bots. Mitigation:", "CAPTCHA, rate limits, and MFA on reset", ["Disable resets", "Email passwords", "Remove TLS"], 0, "Protect reset flows from automation."],
      ["Helpdesk verifies identity for reset via:", "Approved OOB methods—not security questions with public answers", ["Birthday on Facebook", "Caller ID only", "Email from unknown address"], 0, "Weak verification enables social engineering."],
      ["Breach includes OAuth refresh tokens. Action:", "Revoke app grants and rotate client secrets", ["Only change wallpaper", "Ignore cloud", "Disable SPF"], 0, "Cloud tokens need revocation."],
      ["Legal requires documenting breach response timeline for:", "Regulatory and litigation readiness", ["Coffee budget", "Desk moves", "Font size"], 0, "Timelines support legal obligations."],
      ["Credential stuffing spike after breach. Control:", "MFA, breached-password deny list, and IP rate limits", ["Publish valid users", "Disable lockout", "Remove logging"], 0, "Layered controls reduce stuffing success."],
      ["Third-party breach exposes employee emails. Risk:", "Targeted spearphishing and credential reuse attempts", ["None", "Improves security", "Fixes TLS"], 0, "Emails enable targeted attacks."],
      ["Post-breach password policy update should:", "Mandate manager + MFA, ban reuse, remove arbitrary rotation", ["Shorten minimum length", "Remove MFA", "Share passwords"], 0, "Modernize policy after lessons learned."],
      ["Insider posts creds on paste site. Response:", "Treat as incident—reset, hunt usage, involve legal/HR", ["Ignore paste sites", "Public reply", "Pay poster"], 0, "Paste leaks are security incidents."],
      ["Kubernetes secret exposed in Git. Rotation:", "Revoke credentials, rotate secrets, scan history", ["Commit again", "Ignore if private later", "Disable git"], 0, "Exposed secrets need rotation and repo hygiene."],
      ["Breach vendor provides list of affected users. You:", "Validate list, reset, notify per legal, and monitor fraud", ["Post list publicly", "Delete users", "Disable IR"], 0, "Operationalize vendor data carefully."],
      ["Delayed breach discovery increases:", "Attacker dwell time and regulatory scrutiny", ["Backup speed", "MFA strength", "SPF alignment"], 0, "Late discovery worsens harm and compliance."],
      ["Communication: 'All passwords expired tonight' causes:", "Helpdesk surge and weak choices—phase resets by risk", ["Better security always", "Zero risk", "Automatic compliance"], 0, "Phased response reduces operational harm."],
      ["Forensics finds attacker used valid creds. After eradication:", "Reset creds, enforce MFA, and review access grants", ["Keep same passwords", "Disable logging", "Stop monitoring"], 0, "Valid cred abuse requires credential hygiene."],
      ["Breach KPI: median time to reset affected accounts measures:", "Response effectiveness containing account abuse", ["Posters printed", "Desk color", "DNS TTL"], 0, "Reset velocity limits attacker window."],
      ["Consumer breach affects CEO personal email password reused on work SSO. Lesson:", "Block breached passwords and educate on separation", ["Allow reuse", "Disable SSO", "Remove MFA"], 0, "Breached password deny lists protect SSO."],
      ["Insurance requires breach coach engagement. Security team:", "Coordinates technical containment with coach/legal", ["Ignores insurer", "Publishes all data", "Disables EDR"], 0, "Coordinate across functions."],
      ["Post-breach phishing wave expected. Action:", "Heighten email filtering and user warnings", ["Lower filtering", "Remove reporting button", "Pay invoices"], 0, "Victims face follow-on phishing."],
      ["Credential breach tabletop should test:", "Reset comms, session kill, and fraud monitoring", ["Only fire drill", "Office decor", "Printer test"], 0, "Exercises validate breach playbooks."],
      ["After breach, forced password reset should be paired with:", "MFA re-enrollment and hunt for active adversary sessions", ["Disabling SIEM", "Publishing passwords", "Removing EDR"], 0, "Resets alone fail if attacker retains session or MFA enrollment."],
    ]),
    pack([
      ["Team password policy should require:", "Unique credentials, MFA, and approved manager—no shared accounts where avoidable", ["Shared `Team2024!` in wiki", "Password on whiteboard", "Email passwords externally"], 0, "Policies discourage shared weak secrets."],
      ["Shared mailbox `sales@` password in KeePass group vault is:", "Better than emailing password if checkout/audit enabled", ["Best as plaintext in signature", "Illegal always", "Weaker than individual accounts"], 0, "Vault with controls beats insecure sharing."],
      ["Password policy for contractors:", "Time-bound accounts, MFA, and offboarding automation", ["Permanent admin", "Same password all contractors", "No logging"], 0, "Contractors need lifecycle controls."],
      ["Policy prohibits password in ticket system because:", "Tickets have broad visibility and long retention", ["Tickets are encrypted always", "IT never reads tickets", "Improves phishing"], 0, "Ticket systems leak secrets broadly."],
      ["Enforcement via IdP + MDM can:", "Block noncompliant devices from accessing apps", ["Replace training", "Eliminate IR", "Disable TLS"], 0, "Technical enforcement complements policy."],
      ["Password policy exception for OT system:", "Document risk acceptance, network isolation, monitoring", ["Use `admin/admin`", "Connect OT to internet", "Disable safety"], 0, "OT exceptions need compensating controls."],
      ["Annual attestation for privileged users:", "Confirm MFA, training, and no password sharing", ["Optional joke", "Delete accounts", "Disable SIEM"], 0, "Attestation reinforces accountability."],
      ["Policy on passphrase minimum 15 chars aligns with:", "NIST emphasis on length over arbitrary complexity", ["MD5 usage", "Daily rotation", "Sticky notes"], 0, "Length improves memorized secret strength."],
      ["Helpdesk cannot ask for user's password. Alternative:", "Reset via verified identity and user sets new secret", ["Ask for password anyway", "Email temp password unencrypted", "Disable MFA"], 0, "Helpdesk should never collect user passwords."],
      ["Policy requires breached-password deny list at login. Implementation:", "Check hash prefix against HIBP or internal corpus", ["Ignore breaches", "Store plaintext passwords", "Disable MFA"], 0, "Deny lists block known bad secrets."],
      ["Developers embedding secrets in code violates policy. Fix:", "Secret scanning in CI and vault references", ["Commit to main", "Share in Slack", "Disable git"], 0, "CI scanning prevents secret commits."],
      ["Guest Wi-Fi password posted daily rotates risk down by:", "Limiting exposure window if PSK must be used", ["Increasing entropy of corporate AD", "Stopping phishing", "Removing TLS"], 0, "Short-lived PSK reduces stale exposure."],
      ["Policy mandates privileged access via PAM not shared admin. Benefit:", "Session audit and individual attribution", ["Faster ransomware", "Weaker logging", "Public RDP"], 0, "PAM improves accountability."],
      ["Sanctions for policy violations should be:", "Consistent, proportional, and defined in HR/security policy", ["Random firing", "Public shaming only", "None ever"], 0, "Governance requires fair enforcement."],
      ["Password policy communication to executives:", "Emphasize their targeting and model compliant behavior", ["Exempt executives", "Share CISO password", "Disable MFA for board"], 0, "Leadership modeling matters."],
      ["Policy alignment with ISO 27001 A.5.17 covers:", "Authentication information management including passwords", ["Only physical security", "Coffee machines", "Desk plants"], 0, "ISO addresses credential management."],
      ["Team rotating shared local admin on servers is:", "Discouraged—use individual privileged accounts via PAM", ["Best practice", "Required by FIDO", "Same as MFA"], 0, "Individual privileged accounts improve traceability."],
      ["Policy on writing passwords on paper:", "Discourage; if break-glass, use sealed physical controls", ["Encourage for all", "Post on LinkedIn", "Email photo"], 0, "Paper storage is high risk except controlled break-glass."],
      ["Quarterly access review complements password policy by:", "Removing stale accounts reducing attack surface", ["Increasing shared creds", "Disabling MFA", "Deleting logs"], 0, "Access reviews enforce least privilege."],
      ["Policy requires MFA for all remote access. Rationale:", "Passwords alone fail against stuffing and phishing", ["MFA slows internet", "Replaces patching", "Eliminates SIEM"], 0, "Remote access is high-risk without MFA."],
      ["Security champions reinforce policy by:", "Team-specific coaching and phishing reporting culture", ["Bypassing policy", "Sharing admin creds", "Disabling training"], 0, "Champions embed policy in teams."],
      ["Metrics for policy compliance:", "MFA adoption, manager coverage, shared account count", ["Number of posters only", "Desk weight", "DNS TTL"], 0, "Measure meaningful adherence."],
      ["Policy prohibits credential sharing with vendors. Alternative:", "Federated access or time-bound PAM vendor accounts", ["Email domain admin", "VPN shared password", "Disable logging"], 0, "Vendor access should be federated or PAM-managed."],
      ["New hire onboarding checklist includes:", "Manager install, MFA enrollment, and policy acknowledgment", ["Default password never changed", "Skip training", "Admin rights day one"], 0, "Onboarding embeds secure credential practices."],
      ["Policy review trigger events:", "Major breach, audit finding, or IdP capability change", ["Never review", "Only when attacker asks", "Office move"], 0, "Policies should evolve with risk landscape."],
    ]),
    pack([
      ["SSO via SAML/OIDC reduces:", "Password entry frequency—users authenticate once to IdP", ["Need for any authentication", "Logging requirements", "Patching"], 0, "SSO centralizes primary authentication."],
      ["IdP outage with SSO-only apps causes:", "Enterprise-wide login failure—plan IdP HA and break-glass", ["Improved security", "Automatic offline mode always", "Free coffee"], 0, "SSO concentrates availability risk."],
      ["SAML assertion replay attack mitigated by:", "Short assertion lifetime, OneTimeUse, and signature validation", ["Emailing assertions", "Disabling HTTPS", "Long-lived assertions"], 0, "SAML requires tight validation and freshness."],
      ["OIDC ID token must be validated for:", "Issuer, audience, signature, and expiration", ["Color scheme", "Font size", "Desk location"], 0, "OIDC validation prevents token misuse."],
      ["SSO to SaaS without SCIM provisioning risk:", "Orphan accounts when HR offboards slowly", ["Better MFA", "Automatic patching", "SPF fix"], 0, "Provisioning sync is critical."],
      ["Golden SAML attack involves:", "Forging SAML tokens with stolen IdP signing keys", ["Phishing only", "USB drops only", "Printer issues"], 0, "Compromised IdP keys enable forged federation."],
      ["SSO + MFA at IdP means:", "Downstream apps inherit strong auth when session established at IdP", ["Apps never need authorization", "Passwords stored in each app", "TLS disabled"], 0, "Central MFA protects federated apps."],
      ["Just-in-time SSO provisioning creates:", "User on first login—reduces manual account sprawl", ["Permanent admin always", "Public RDP", "Disabled logs"], 0, "JIT creates accounts on demand."],
      ["Break-glass local admin when IdP down:", "Documented emergency accounts with monitoring and rare use", ["Daily use preferred", "Share on Twitter", "Disable MFA"], 0, "Break-glass is for emergencies only."],
      ["OAuth SSO differs from SAML by:", "Often using OAuth2/OIDC flows common in modern SaaS", ["Never using TLS", "Eliminating tokens", "Requiring MD5"], 0, "OIDC is prevalent in modern cloud SSO."],
      ["SSO session timeout policy should:", "Balance UX and risk—shorter for high-risk apps", ["Never expire", "Expire every second", "Ignore risk"], 0, "Timeouts should reflect app sensitivity."],
      ["App supports SAML but enables local login fallback. Risk:", "Attackers bypass SSO MFA via local creds—disable or harden fallback", ["No risk", "Improves security", "Required by GDPR"], 0, "Fallback accounts are alternate path."],
      ["IdP logs are valuable for:", "Investigating auth anomalies and federation issues", ["Printer maintenance", "Coffee", "DNS TTL"], 0, "IdP logs support detection and IR."],
      ["SSO attribute mapping sends:", "Groups/roles to apps for authorization", ["Passwords in clear", "Private keys", "Biometrics raw"], 0, "Attributes drive authZ in apps."],
      ["Multi-IdP strategy for mergers needs:", "Federation trust or consolidation roadmap", ["Separate forever without plan", "Shared admin password", "Disable MFA"], 0, "M&A requires identity integration planning."],
      ["SSO phishing (consent/OAuth) targets:", "Token grants—not passwords directly", ["Hardware FIDO keys in tokens", "TLS certs", "SPF"], 0, "OAuth phishing abuses consent."],
      ["Conditional access at IdP can block:", "Legacy auth protocols bypassing MFA", ["All security", "Logging", "Backups"], 0, "CA policies block weak protocols."],
      ["SSO to on-prem apps via:", "Identity proxy or federation bridge (ADFS, etc.)", ["Posting passwords in DNS", "WEP keys", "Sticky notes"], 0, "Proxies extend SSO to legacy."],
      ["Certificate-based SSO for high assurance uses:", "Mutual TLS or smart card auth at IdP", ["SMS only", "Shared password", "ROT13"], 0, "Certs provide strong authentication."],
      ["SSO logout (SLO) challenge:", "Not all apps honor global logout—session may persist", ["Always perfect", "Illegal", "Removes MFA"], 0, "SLO coverage varies; verify app behavior."],
      ["IdP compromise is catastrophic because:", "Central trust enables wide access—protect IdP keys and admins", ["Minor issue", "Only affects one laptop", "Fixes phishing"], 0, "IdP is crown jewel."],
      ["SSO adoption metric:", "Percent apps integrated vs password vault entries remaining", ["Poster count", "Mouse DPI", "Fan speed"], 0, "Track integration progress."],
      ["Testing SSO after cert rotation requires:", "Validate metadata exchange and signing cert trust", ["Ignore until users complain", "Disable MFA", "Delete IdP"], 0, "Cert rotation breaks federation if misconfigured."],
      ["SSO for customer-facing vs workforce:", "Separate IdP/tenants to isolate trust boundaries", ["One IdP for everything always", "Share admin password", "Disable TLS"], 0, "Separate trust domains reduce blast radius."],
      ["Passwordless SSO with FIDO at IdP:", "Strong phishing-resistant primary auth federated to apps", ["Weaker than passwords", "Requires SMS", "Stores passwords in SAML"], 0, "FIDO at IdP strengthens entire SSO chain."],
    ]),
  ]);
}
