import { PHISHING_CHAPTERS } from "../cyber-hard-meta.mjs";
import { fromChapters, Q } from "./_loader.mjs";

function pack(rows) {
  return rows.map(([q, a, w, c, e]) => Q(q, a, w, c, e));
}

export function buildPhishingChapters() {
  return fromChapters(PHISHING_CHAPTERS, [
    pack([
      ["Spearphishing differs from bulk phishing by:", "Targeting specific individuals with tailored lures", ["Sending to random millions only", "Using only postal mail", "Requiring zero social research"], 0, "Spearphishing is personalized."],
      ["Whaling targets:", "Senior executives with high-value fraud or access goals", ["Only interns", "Printers", "DNS servers"], 0, "Whaling focuses on leadership."],
      ["Clone phishing reuses:", "Legitimate prior message with malicious replacement links/attachments", ["Only voice calls", "Hardware tokens", "TLS certs"], 0, "Clones mimic trusted threads."],
      ["Angler phishing occurs on:", "Social media—fake support accounts replying to complaints", ["Only fax", "OT PLC", "Backup tapes"], 0, "Angler phishers hijack brand help threads."],
      ["HTTPS padlock on phishing site means:", "Connection encrypted—not that site is legitimate", ["Site is trustworthy", "MFA unnecessary", "Email SPF passed"], 0, "TLS does not prove legitimacy."],
      ["MITRE T1566.002 is:", "Spearphishing link", ["Data encrypted for impact", "Firmware corruption", "Backup restore"], 0, "T1566.002 covers malicious links."],
      ["QR phishing (quishing) evades:", "Some email URL scanners by hiding link in image", ["All MFA", "EDR", "Backups"], 0, "QR codes obscure destination from text scanners."],
      ["Search engine phishing (SEO poison) promotes:", "Malicious sites ranking for popular search terms", ["Only legit results", "Hardware drivers always safe", "SPF records"], 0, "Attackers manipulate SEO."],
      ["Phishing kit sold on forum enables:", "Low-skill actors to deploy credential harvesting pages", ["Automatic patching", "Compliance", "Zero fraud"], 0, "Kits lower barrier to phish."],
      ["Voice phishing (vishing) to IT helpdesk aims to:", "Reset MFA or credentials via social engineering", ["Patch servers", "Improve SPF", "Encrypt backups"], 0, "Vishing targets human procedures."],
      ["Calendar invite phishing uses:", "Malicious links in meeting invites users trust", ["Only SMS", "GPU drivers", "WEP keys"], 0, "Calendar lures exploit scheduling trust."],
      ["Deepfake audio CEO fraud is:", "Synthetic voice urging urgent wire transfer", ["Always detectable easily", "Legal wire protocol", "Patch Tuesday"], 0, "Deepfakes enable convincing vishing."],
      ["Phishing via compromised vendor email is:", "Supply-chain trust abuse—harder to spot", ["Always external Gmail only", "Impossible", "Only affects printers"], 0, "Trusted sender domains increase success."],
      ["Multi-stage phishing: email links to:", "Benign PDF with link to credential page—layered evasion", ["Only patch notes", "Hardware store", "DNSSEC"], 0, "Layers evade single-scan defenses."],
      ["Brand impersonation with punycode domain `exаmple.com` uses:", "Homoglyph IDN to mimic ASCII domain", ["Valid EV cert only", "Better SPF", "Stronger MFA automatically"], 0, "IDN homographs deceive users."],
      ["Phishing targeting OAuth consent requests:", "Malicious app permissions to data", ["Only password spraying", "Firmware", "Cable faults"], 0, "Consent phishing steals API access."],
      ["Holiday-themed phishing exploits:", "Urgency and curiosity around seasonal themes", ["TLS 1.3", "Argon2", "NTP"], 0, "Seasonal lures increase click rates."],
      ["Internal phishing from compromised mailbox:", "Appears from colleague—high trust", ["Always external", "Blocked by SPF always", "Requires zero access"], 0, "Internal senders bypass external filters psychologically."],
      ["Phishing landing on IP address not domain suggests:", "Ephemeral infrastructure—block and investigate campaign", ["Legitimate enterprise always", "Required for MFA", "SPF alignment"], 0, "Raw IP hosts are suspicious."],
      ["Attachment phishing with macro doc:", "Enables malware download if macros enabled", ["Always safe preview", "Improves entropy", "Fixes Wi-Fi"], 0, "Macros can execute payloads."],
      ["Smishing uses:", "SMS lures with shortened URLs", ["Only ethernet", "BIOS password", "Kerberos"], 0, "Smishing is SMS-based phishing."],
      ["Phishing-resistant architecture includes:", "FIDO2/WebAuthn plus email authentication (DMARC)", ["MD5 passwords", "Shared admin", "Disabled logging"], 0, "Layer technical controls against phish."],
      ["Reporting phishing types helps SOC:", "Tune detections and block campaigns", ["Slow response", "Publish passwords", "Disable MFA"], 0, "Classification improves defenses."],
      ["User believes 'IT' email is real due to:", "Display name spoofing while From domain differs—teach header checks", ["TLS padlock", "Long password", "SPF always fails on legit mail"], 0, "Display names are not authentication."],
      ["Phishing simulation metrics track:", "Click/report rates to target training", ["Coffee spend", "Desk color", "DNS TTL"], 0, "Simulations measure human risk."],
    ]),
    pack([
      ["Header `Received:` chain helps analysts:", "Trace mail path and identify injecting server", ["Guess password", "Patch OS", "Configure Wi-Fi"], 0, "Received headers show routing."],
      ["DMARC `p=reject` policy means:", "Failing messages should be rejected by receivers", ["Always deliver spoofed mail", "Disable SPF", "Remove TLS"], 0, "Reject is strongest DMARC enforcement."],
      ["SPF `~all` indicates:", "Soft fail—may mark suspicious not always block", ["Hard fail always", "No SPF record", "DKIM replacement"], 0, "Soft fail is weaker enforcement."],
      ["DKIM signature invalid on message suggests:", "Tampering or misconfiguration—treat with caution", ["Guaranteed phishing always", "Better security", "Automatic MFA"], 0, "Invalid DKIM warrants scrutiny."],
      ["Look-alike domain `micr0soft.com` red flag:", "Homoglyph/typosquat domain registration", ["Official vendor", "Improves SPF", "Required for TLS"], 0, "Typosquats mimic brands."],
      ["Reply-To different from From indicates:", "Possible BEC redirecting replies to attacker", ["Always normal", "SPF pass guaranteed", "Hardware failure"], 0, "Mismatched Reply-To is BEC signal."],
      ["Urgent 'pay invoice now' from new vendor bank details:", "BEC wire fraud indicator—verify OOB with known contact", ["Always pay immediately", "Forward to everyone", "Disable MFA"], 0, "Payment detail changes need verification."],
      ["Embedded link `href` differs from displayed text:", "Hidden destination—hover/inspect before click", ["Safe practice", "Improves encryption", "SPF fix"], 0, "Link mismatch is deception."],
      ["Attachment `invoice.exe` red flag because:", "Executable masquerading as document", ["Normal PDF", "Improves security", "Required macro"], 0, "Unexpected executables are malicious."],
      ["Email from free webmail claiming CEO on mobile:", "Common BEC pattern—verify via known channel", ["Always legitimate", "Requires payment", "Fixes DNS"], 0, "Free webmail + urgency is suspicious."],
      ["X-Originating-IP in headers helps:", "Identify sending infrastructure for blocking", ["Set user password", "Patch laptop", "Train phishing only"], 0, "Originating IP aids blocking."],
      ["HTML-only email with no plain text:", "Can hide payloads—prefer plain view cautiously", ["Always safer", "Required by GDPR", "Enables FIDO"], 0, "HTML can obfuscate content."],
      ["`Authentication-Results: dmarc=fail` means:", "Message failed DMARC alignment—do not trust sender", ["Message definitely safe", "TLS broken", "MFA enrolled"], 0, "DMARC fail is strong negative signal."],
      ["Too-good-to-be true prize email:", "Classic phish lure—delete/report", ["Claim prize quickly", "Send SSN", "Install root cert from mail"], 0, "Prize lures harvest data."],
      ["Email asks to disable AV for 'support.' Response:", "Refuse—legitimate IT never requires disabling protections", ["Comply immediately", "Share admin password", "Forward macro"], 0, "Disabling AV is a social engineering tactic."],
      ["Mismatch: email about payroll from `marketing@` domain:", "Department/domain inconsistency—verify", ["Always process", "Pay anyway", "Disable logging"], 0, "Context should match sender role."],
      ["Large unexpected attachment from known contact:", "Possible compromised mailbox—verify OOB before open", ["Open always", "Forward macros", "Disable SPF"], 0, "Compromised contacts send malware."],
      ["Email gateway banner 'External email' helps users:", "Contextualize spoofed internal-looking messages", ["Guarantee safety", "Remove MFA", "Patch servers"], 0, "Banners remind users to scrutinize."],
      ["URL shortener in corporate email:", "Obscures destination—expand/analyze before click", ["Always trusted", "Improves SPF", "Required for TLS"], 0, "Shorteners hide malicious URLs."],
      ["S/MIME signed internal email with valid cert:", "Higher trust—but still verify unusual requests", ["Ignore content always", "Pay any invoice", "Disable MFA"], 0, "Signing helps authenticity not intent."],
      ["Grammar errors alone:", "Weak signal—many phish are polished now", ["Prove legitimacy", "Require payment", "Fix Wi-Fi"], 0, "Do not rely only on grammar."],
      ["Email `Return-Path` bounce domain unrelated to From:", "Possible spoofing or forwarding anomaly—investigate", ["Always benign", "SPF irrelevant", "MFA token"], 0, "Return-Path aids trace analysis."],
      ["Hidden white-on-white text in HTML:", "Evasion technique for filters—suspicious", ["Accessibility feature always", "Improves DKIM", "Patches CVE"], 0, "Hidden text tricks scanners."],
      ["Red flag: request for gift cards as payment:", "Common fraud—verify policy prohibits", ["Standard AP practice always", "Required by IRS", "Enables SSO"], 0, "Gift card payments are fraud hallmark."],
      ["Safe email handling:", "Report suspicious, avoid clicking, verify OOB for money/auth changes", ["Click to see if bad", "Reply with password", "Enable macros"], 0, "Process reduces successful phish."],
    ]),
    pack([
      ["Smishing 'Your package held' SMS with link. Action:", "Track via official carrier app/site typed manually—not link", ["Click link immediately", "Reply with bank PIN", "Install profile"], 0, "Use official channels not SMS links."],
      ["Smishing uses SIM swap to intercept:", "SMS OTP codes", ["FIDO private keys easily", "TLS 1.3", "Argon2 hashes"], 0, "SMS MFA vulnerable to SIM attacks."],
      ["Vishing caller ID spoof shows 'Bank.' Reality:", "Caller ID untrusted—hang up and call bank number on card", ["Always bank", "Requires wire transfer", "Fixes SPF"], 0, "CLI spoofing is common."],
      ["Vishing asks for MFA code 'to verify identity.' Response:", "Never share OTP—legitimate orgs never ask", ["Read code aloud", "Email code", "Disable MFA"], 0, "OTP requests are scam hallmark."],
      ["SMS link to fake O365 login harvests:", "Credentials and MFA via real-time proxy", ["Hardware tokens", "Firewall rules", "Backups"], 0, "Credential harvesting pages steal sessions."],
      ["Smishing 'IRS warrant' threat aims to:", "Panic victim into payment or data disclosure", ["Provide tax advice", "Patch Windows", "Improve DKIM"], 0, "Authority threats coerce action."],
      ["Mobile delivery smishing peak seasons:", "Holidays—heighten user awareness", ["Never occur", "Fix TLS", "Remove EDR"], 0, "Seasonal shipping lures spike."],
      ["Report smishing in US often includes:", "Forwarding to 7726 (SPAM) and internal SOC", ["Posting on TikTok only", "Replying with SSN", "Disabling phone"], 0, "7726 helps carriers aggregate reports."],
      ["Vishing to elderly for 'grandchild bail' is:", "Family emergency scam—verify family directly", ["Always real", "Bank procedure", "Patch firmware"], 0, "Emergency scams exploit emotion."],
      ["SMS requests to install MDM/profile on personal phone:", "Likely surveillance—do not install", ["Required for Gmail", "Improves battery", "SPF alignment"], 0, "Profiles can compromise device."],
      ["Callback vishing uses toll number to:", "Charge victim and gather info", ["Free support always", "Enable MFA", "Fix DNS"], 0, "Premium callbacks monetize victims."],
      ["Deepfake video call vishing risk:", "Convincing face/voice for fraud instructions", ["Impossible today", "Only spam filter stops", "Replaces EDR"], 0, "Deepfakes enhance vishing."],
      ["Smishing with bit.ly link—check:", "Expand URL via safe tools before visiting", ["Click fast", "Share password", "Disable AV"], 0, "Analyze destination first."],
      ["Corporate policy on smishing:", "Report to SOC, do not engage links/calls", ["Pay fines via SMS", "Share OTP", "Install unknown apps"], 0, "Policy channels incidents to security."],
      ["Vishing targeting helpdesk to reset exec MFA:", "High priority social engineering—strict verification", ["Comply quickly", "Email password", "Disable logs"], 0, "Helpdesk vishing is critical path."],
      ["SMS 2FA codes on personal phone used for work:", "Blurs boundary—prefer app/hardware MFA on managed device", ["Best practice always", "Stops phishing 100%", "Removes need for policy"], 0, "Mixed use increases risk."],
      ["Robocall 'credit card lower rate' is:", "Scam seeking card data—hang up", ["Mandatory offer", "IRS program", "Patch tool"], 0, "Unsolicited financial robocalls are fraudulent."],
      ["Smishing in non-English targeting immigrant workers:", "Exploits language barriers—provide multilingual training", ["Irrelevant", "Fixes Wi-Fi", "Enables WEP"], 0, "Tailor awareness to workforce."],
      ["Vishing + email combo (vish-o-phish):", "Multi-channel credibility—verify via known process", ["Always trust", "Pay invoice", "Disable MFA"], 0, "Multi-channel increases believability."],
      ["Telecom STIR/SHAKEN helps reduce:", "Spoofed caller ID on supported networks", ["All smishing", "Ransomware", "SQLi"], 0, "STIR/SHAKEN attests call origin partially."],
      ["SMS from 'boss' new number asking for gift cards:", "Verify voice call to known boss number", ["Buy immediately", "Post codes online", "Disable SPF"], 0, "Gift card requests via SMS are fraud."],
      ["Mobile OS warns about unknown sender SMS links. User should:", "Heed warning and report", ["Bypass warning", "Install profile", "Share OTP"], 0, "OS warnings are protective."],
      ["Vishing pretending to be Microsoft support:", "Microsoft does not cold-call—hang up", ["Grant RDP", "Pay fee", "Disable firewall"], 0, "Cold-call tech support is scam."],
      ["Smishing metrics for awareness program:", "Report rate and repeat clickers for coaching", ["Desk count", "DNS TTL", "Coffee"], 0, "Measure reporting culture."],
      ["After smishing click, user should:", "Report immediately, change passwords from clean device, contact SOC", ["Ignore", "Post screenshot publicly", "Disable MFA"], 0, "Rapid reporting limits harm."],
    ]),
    pack([
      ["BEC wire transfer change email best defense:", "Callback verification to known number before payment", ["Email reply only", "Faster payment", "Disable MFA"], 0, "OOB voice verification stops BEC."],
      ["BEC attacker monitors inbox for:", "Timing replies to redirect payments", ["Hardware temps", "DNS TTL", "Printer toner"], 0, "Compromised mailboxes enable conversation hijacking."],
      ["Display name 'CEO' with gmail.com From is:", "Spoofed identity—check actual address", ["Always CEO", "Improves SPF", "Legal invoice"], 0, "Display names mislead."],
      ["Finance team dual approval for wires prevents:", "Single compromised user initiating fraud", ["Phishing entirely", "Patching", "Logging"], 0, "Dual control adds friction to fraud."],
      ["BEC using look-alike domain `company-co.com` vs `company.com`:", "Typosquat—block similar domains at gateway", ["Legitimate subsidiary always", "Required DKIM", "TLS fix"], 0, "Look-alikes fool busy staff."],
      ["Attorney impersonation BEC targets:", "Real estate closings with wiring instructions", ["Only interns", "DNS servers", "Backups"], 0, "Real estate transactions are high value."],
      ["BEC 'urgent confidential acquisition' story aims to:", "Bypass normal approval channels via secrecy", ["Improve compliance", "Patch CVE", "Train interns"], 0, "Secrecy prevents verification."],
      ["Email rule forwarding to external address indicates:", "Mailbox compromise persistence—hunt rules", ["Normal IT", "SPF fix", "Better MFA on printer"], 0, "Hidden rules exfiltrate mail."],
      ["BEC loss recovery via bank:", "Often difficult if transfer completed—prevention critical", ["Guaranteed refund always", "Automatic police refund", "Insurance always pays"], 0, "Wire fraud recovery is hard after transfer."],
      ["Vendor BEC changes bank account. Verification:", "Use contract phone number—not email reply", ["Pay to new account quickly", "Tweet vendor", "Disable logging"], 0, "Verify via pre-established channel."],
      ["BEC detection rule: new bank details + urgency + exec keyword:", "Flag for manual review", ["Auto-approve payment", "Delete mail", "Disable SPF"], 0, "Composite rules catch BEC patterns."],
      ["Legal hold on mailbox during BEC investigation:", "Preserve messages for law enforcement", ["Delete all mail", "Ignore legal", "Publish inbox"], 0, "Preservation supports case."],
      ["BEC using compromised partner mailbox is:", "Harder to detect—monitor partner security posture", ["Impossible", "Only affects HR", "Fixes Wi-Fi"], 0, "Partner compromise appears legitimate."],
      ["Training finance on BEC focuses on:", "Payment change verification procedures", ["Speed only", "Grammar", "Coffee"], 0, "Process training reduces fraud."],
      ["BEC after MFA deployment still possible via:", "Session cookie theft or token phishing", ["Impossible", "Hardware breaks", "SPF"], 0, "MFA does not stop session abuse."],
      ["Invoice PDF with altered banking details:", "Compare to ERP master vendor record", ["Pay immediately", "Trust PDF", "Disable AV"], 0, "Validate against authoritative records."],
      ["BEC 'payroll diversion' changes:", "Direct deposit account—HR must verify in person/OOB", ["Auto-approve", "Email only OK", "Disable MFA"], 0, "Payroll changes need strong verification."],
      ["Executive PGP signing email rare; if absent:", "Do not rely on style alone—use process controls", ["Trust writing style", "Pay any request", "Disable DMARC"], 0, "Style mimicry is common."],
      ["BEC insurance coverage:", "Varies—cyber/fraud policies may differ on social engineering", ["Always full coverage", "Illegal to claim", "Replaces MFA"], 0, "Understand policy terms."],
      ["Time-of-day BEC near month-end:", "Exploits AP rush—enforce cooling period", ["Ignore", "Remove approvals", "Disable logging"], 0, "Fraud exploits process pressure."],
      ["BEC using thread reply keeps:", "Context credibility—users lower guard", ["SPF fail always", "Hardware fault", "DNS fix"], 0, "Thread hijack increases trust."],
      ["Marking external email reduces BEC by:", "Highlighting messages not truly internal", ["Nothing", "Removing MFA", "Patching"], 0, "Banners contextualize origin."],
      ["BEC incident declared when:", "Fraudulent payment attempted or succeeded", ["Any spam received", "Printer jam", "Slow Wi-Fi"], 0, "Financial impact triggers incident."],
      ["Post-BEC controls:", "Enhanced payment verification, rule monitoring, MFA on mail", ["Stop all email", "Share passwords", "Disable IR"], 0, "Layer controls after lesson learned."],
      ["BEC reporting to FBI IC3:", "Supports law enforcement statistics and possible recovery efforts", ["Mandatory for all spam", "Replaces SOC", "Publishes credentials"], 0, "IC3 collects internet crime reports."],
    ]),
    pack([
      ["Report phish button in Outlook should:", "Send full message to SOC mailbox or API preserving headers", ["Delete without SOC visibility", "Forward to all staff", "Reply to attacker"], 0, "Preservation enables response."],
      ["SOC auto-quarantine reported phish benefits:", "Protect other users while analyzing", ["Slows mail forever", "Deletes legit mail always", "Disables MFA"], 0, "Quarantine limits spread."],
      ["User reports phish but also clicked link. Priority:", "Contain account/session and reset creds per playbook", ["Only close ticket", "Public shame", "Ignore click"], 0, "Clicks imply possible compromise."],
      ["Phishing mailbox `phish@company` purpose:", "Central ingestion for analysis and blocking", ["Marketing", "HR complaints", "Coffee orders"], 0, "Dedicated mailbox feeds workflow."],
      ["After report, auto-reply should:", "Thank user and provide ticket ID without sensitive IOC leaks", ["Include malware attachment", "Ask for password", "Disable MFA"], 0, "Acknowledgment encourages reporting."],
      ["SOC shares IoC from reported phish to:", "Email gateway block lists and threat intel platform", ["Public Twitter only", "Attacker", "Delete logs"], 0, "Operationalize reports into blocks."],
      ["False positive report training reduces:", "Noise while keeping reporting culture", ["All reports", "Security", "Logging"], 0, "Feedback improves signal quality."],
      ["Integration with Microsoft Report Message add-in:", "Feeds Defender for Office 365 analysis", ["Disables mail", "Removes TLS", "Publishes keys"], 0, "Integrated reporting improves vendor detection."],
      ["Reported phish with malware attachment handling:", "Sandbox in isolated environment—do not open on SOC desktop casually", ["Open on domain controller", "Email to users", "Disable AV"], 0, "Malware needs safe analysis."],
      ["Metrics: report rate per 100 users indicates:", "Security culture strength", ["Coffee quality", "DNS speed", "Desk size"], 0, "Reporting rates reflect culture."],
      ["Phish report SLA 15 minutes for finance users because:", "High-value targets need fast mitigation", ["Marketing preference", "DNS TTL", "Printer"], 0, "Prioritize high-risk groups."],
      ["User forwards phish as attachment vs inline:", "Attachment preserves headers better", ["Inline always better", "Deletes headers", "Improves SPF"], 0, "EML attachment retains metadata."],
      ["Automated playbook on report:", "Search mailboxes for same subject/hash and remove", ["Ignore others", "Disable mail globally", "Pay ransom"], 0, "Hunt widens protection."],
      ["Report phish from mobile client:", "Use mobile report feature or forward via managed mail app", ["Screenshot only", "SMS attacker", "Install unknown profile"], 0, "Mobile reporting should preserve message."],
      ["Legal privilege on reported phish:", "Usually not privileged—coordinate with counsel on investigations", ["Always secret from SOC", "Public release day one", "Destroy evidence"], 0, "Understand legal handling."],
      ["Reporting phishing is part of:", "Human firewall layered with technical controls", ["Optional hobby", "Replacement for EDR", "DNS only control"], 0, "Users complement technology."],
      ["After campaign, comms to staff include:", "Sample lure indicators without live malicious links", ["Live malware links for training", "Admin passwords", "Disable reporting"], 0, "Awareness uses safe examples."],
      ["Phish report tied to SOAR ticket:", "Ensures traceability and metrics", ["Deletes user", "Stops logging", "Removes MFA"], 0, "Tickets track response."],
      ["Executive assistant reports phish targeting CFO. SOC:", "Escalate priority and hunt org-wide", ["Low priority", "Ignore", "Disable mail"], 0, "VIP targeting gets fast response."],
      ["Reporting outside business hours:", "Automated triage still quarantines known IoCs", ["Wait Monday always", "Delete mail", "Disable SOC"], 0, "Automation protects off-hours."],
      ["Post-report feedback loop:", "Tell reporter outcome in generic terms", ["Never respond", "Share full IR secrets", "Publish creds"], 0, "Feedback reinforces behavior."],
      ["Phish report containing PII:", "Handle per data handling policy in SOC tools", ["Post in Slack", "Email world", "Disable encryption"], 0, "Protect PII in investigations."],
      ["Contractor reports phish to personal email. Policy:", "Use corporate reporting channel on managed account", ["Ignore contractors", "Pay invoice", "Disable MFA"], 0, "Contractors follow same reporting paths."],
      ["Quarterly phishing report to leadership shows:", "Trends, top lures, time-to-quarantine", ["Coffee spend", "Mouse DPI", "Fan speed"], 0, "Leadership needs trend metrics."],
      ["Reward program for good reports should:", "Encourage behavior without creating perverse incentives to spam SOC", ["Pay cash per email", "Punish non-reporters", "Disable training"], 0, "Positive reinforcement with balance."],
    ]),
    pack([
      ["Phishing simulation legal/ethical requirement:", "Notice in acceptable use policy and avoid deceptive cruelty", ["Secretly trick without policy", "Punish all clickers fired", "Use real malware"], 0, "Simulations need policy basis."],
      ["Simulation clicker follow-up:", "Coaching, not shame—targeted training", ["Public leaderboard of names", "Terminate automatically", "Disable account permanently"], 0, "Coach to improve behavior."],
      ["Simulation too easy yields:", "False confidence—use realistic lures", ["Perfect security", "No training need", "Remove MFA"], 0, "Realism improves value."],
      ["Simulation landing page should:", "Educate immediately after click without harvesting real creds", ["Store passwords for scoring", "Install malware", "Wire money"], 0, "Safe landing teaches lesson."],
      ["Measuring simulation click rate over time goal:", "Downward trend with stable reporting rate up", ["Zero reporting", "100% clicks", "Remove simulations"], 0, "Clicks down, reports up is healthy."],
      ["Simulation exempt roles:", "Some groups (IR, legal) may need different tests—plan carefully", ["Everyone same always", "Only interns tested", "Attack real customers"], 0, "Tailor program thoughtfully."],
      ["Simulated spearphish for finance:", "Tests payment verification discipline", ["Replaces dual control", "Transfers money", "Disables MFA"], 0, "Targeted sims test critical processes."],
      ["Simulation provider integrates with:", "Email system and LMS for training assignment", ["Only printers", "DNS only", "Physical locks"], 0, "Integration automates workflow."],
      ["Repeat clickers after training:", "Escalate manager coaching or restricted access per policy", ["Ignore forever", "Reward", "Disable logging"], 0, "Chronic risk needs escalation."],
      ["Simulation timing:", "Avoid major crises or holidays causing backlash", ["During active IR without notice", "Never communicate", "Use real ransomware"], 0, "Timing affects acceptance."],
      ["Control group without simulation:", "Helps measure program impact scientifically", ["Required by PCI always", "Illegal", "Replaces EDR"], 0, "Controls validate effectiveness."],
      ["Phish sim domain similar to production:", "Use clearly labeled test domain to avoid confusion", ["Clone exact login", "Steal creds", "Disable TLS"], 0, "Clear labeling avoids real phishing overlap."],
      ["Executive simulation failure:", "Private coaching—high risk if public", ["Tweet failure", "Fire on spot mandatory", "Share password"], 0, "Handle VIP failures discreetly."],
      ["Simulation metrics shared with board:", "Aggregate rates and program coverage", ["Individual names by default", "All passwords", "Live malware"], 0, "Board sees aggregate risk trends."],
      ["Combining sims with technical controls:", "Defense in depth—sim tests humans, DMARC blocks spoof", ["Sim replaces email security", "Remove MFA", "Stop patching"], 0, "Programs complement technology."],
      ["Simulation of smishing:", "Uses SMS test platform with consent", ["Random public spam", "Steal OTP", "Disable phone"], 0, "SMS sims need carrier/platform support."],
      ["Users report simulation as phish. Interpretation:", "Positive—shows reporting habit", ["Failure of program", "Stop sims", "Punish reporters"], 0, "Reporting sims indicates culture."],
      ["Simulation frequency:", "Regular but not so often users fatigue", ["Hourly", "Once per decade", "Never"], 0, "Balance frequency for learning."],
      ["Localized simulations:", "Language/culture appropriate lures", ["English only global", "Ignore regions", "Illegal always"], 0, "Localize for effectiveness."],
      ["Contractors included in sims:", "Yes—attackers target supply chain users", ["Never test contractors", "Give admin rights", "Disable reporting"], 0, "Contractors are in scope."],
      ["After sim, microlearning video:", "Reinforces lesson in <5 minutes", ["2 hour lecture only", "None", "Malware install"], 0, "Just-in-time training aids retention."],
      ["Simulated attachment with benign file:", "Tests attachment policy without malware", ["Use real ransomware sample", "EXE always", "Disable AV"], 0, "Benign markers test process safely."],
      ["Program KPI: time-to-report median improves meaning:", "Users detect faster—good culture signal", ["Worse security", "Remove MFA", "Stop IR"], 0, "Faster reporting reduces impact window."],
      ["Ethical line: sim should not:", "Cause emotional harm, discrimination, or undue punishment", ["Educate users", "Measure risk", "Track trends"], 0, "Programs must be professional and fair."],
      ["Red team email vs phishing sim:", "Red team tests SOC/process; sim focuses on user awareness scale", ["Identical always", "Red team mass emails all customers", "Sim replaces pen test"], 0, "Different objectives and scope."],
    ]),
    pack([
      ["Security awareness should be:", "Continuous, role-based, and measured—not annual checkbox", ["One poster only", "Optional forever", "Only for IT"], 0, "Effective programs are ongoing and targeted."],
      ["Role-based training for developers includes:", "Secure coding and secret management", ["Only phishing", "Physical fitness", "Desk ergonomics only"], 0, "Technical roles need technical modules."],
      ["Phishing-resistant culture metric:", "High report rate with declining click rates", ["Zero reports", "100% clicks", "No training"], 0, "Reports up, clicks down is ideal."],
      ["Awareness microlearning fits:", "Short modules after events or sim clicks", ["8-hour annual lecture only", "Never", "Malware deployment"], 0, "Microlearning improves retention."],
      ["Gamification in awareness risks:", "Trivializing serious topics if poorly designed", ["Always perfect", "Replaces MFA", "Stops IR"], 0, "Design must stay professional."],
      ["Executive awareness briefing covers:", "BEC, physical security, and incident reporting expectations", ["Only interns", "Coffee", "DNS TTL"], 0, "Leaders face targeted threats."],
      ["Multilingual awareness for:", "Non-native speakers and regional lures", ["English only always", "Ignore regions", "Disable reporting"], 0, "Language access improves outcomes."],
      ["Insider threat awareness teaches:", "Reporting anomalies without vigilantism", ["Hack coworkers", "Share passwords", "Disable legal"], 0, "Channel concerns properly."],
      ["Physical security awareness includes:", "Tailgating, clean desk, and device locking", ["Only email", "GPU tuning", "SPF"], 0, "Physical vectors matter."],
      ["Remote work awareness emphasizes:", "Home network hygiene and family device separation", ["Use public Wi-Fi for classified", "Share VPN password", "Disable MFA"], 0, "Remote expands risk surface."],
      ["Measuring training effectiveness:", "Behaviors (report rate) not just completion clicks", ["Posters printed", "Seats filled only", "Font size"], 0, "Outcomes beat completion metrics."],
      ["Awareness for AI tools warns:", "Do not paste confidential data into public LLMs", ["Share all secrets for speed", "Disable DLP", "Remove MFA"], 0, "AI tools may retain or leak data."],
      ["Social media oversharing aids:", "Spearphishing reconnaissance", ["Better SPF", "Stronger TLS", "Argon2"], 0, "OSINT harvests personal details."],
      ["Security champions program:", "Embedded advocates per department", ["Replace SOC", "Eliminate policy", "Share admin creds"], 0, "Champions scale awareness."],
      ["New hire day-one security:", "MFA, reporting, acceptable use acknowledgment", ["Default weak password forever", "Skip training", "Admin rights"], 0, "Day-one sets expectations."],
      ["Awareness for USB drops:", "Do not plug unknown devices—report to security", ["Plug in to see contents", "Share with IT via email attachment", "Disable EDR"], 0, "Unknown media may auto-execute."],
      ["Compliance training overlap:", "PCI/HIPAA modules plus practical scenarios", ["Only compliance without practice", "Ignore regulations", "Remove logging"], 0, "Blend compliance with practical skills."],
      ["Storytelling with anonymized incidents:", "Increases engagement and memory", ["Share live PII publicly", "Fabricate laws", "Disable reporting"], 0, "Stories make lessons relatable."],
      ["Awareness fatigue mitigation:", "Varied formats and relevance to role", ["Same slide yearly", "Punish questions", "Remove simulations"], 0, "Variety sustains attention."],
      ["Third-party staff training:", "Contractors must meet same standards before access", ["Exempt all vendors", "Shared passwords OK", "No logging"], 0, "Supply chain includes people risk."],
      ["Reporting culture leadership models:", "Executives report suspicious mail too", ["Executives exempt", "Public ridicule", "Disable button"], 0, "Leadership participation matters."],
      ["Awareness for deepfakes:", "Verify urgent requests via second channel", ["Trust video always", "Wire immediately", "Disable MFA"], 0, "Deepfakes require verification habits."],
      ["KPI linking awareness to incidents:", "Correlate training cohorts with phish success rates", ["Ignore outcomes", "Delete SIEM", "Stop IR"], 0, "Analytics show program impact."],
      ["Accessibility in training:", "Captions, screen-reader friendly content", ["Video only no captions", "Ignore ADA", "Remove training"], 0, "Inclusive design reaches all staff."],
      ["Security culture defined as:", "Shared values and habits protecting assets—not fear", ["Blame only", "Secrecy from SOC", "Password sharing encouraged"], 0, "Culture is collective secure behavior."],
    ]),
    pack([
      ["User clicked phish link on corporate laptop. FIRST step:", "Disconnect network/VPN and report to SOC immediately", ["Continue working", "Click again to verify", "Email password to SOC"], 0, "Isolation limits further compromise."],
      ["User entered creds on fake O365 page. Actions:", "Reset password, revoke sessions, enforce MFA re-register", ["Ignore if AV green", "Share creds with team", "Disable logging"], 0, "Assume credential compromise."],
      ["Opened malicious attachment. SOC should:", "Isolate host, collect EDR telemetry, scan enterprise for IoCs", ["Delete user", "Publicly shame", "Ignore"], 0, "Attachment may mean malware."],
      ["User ran macro enabling editing. Likely:", "Malware execution—treat as incident", ["Safe always", "Improves performance", "SPF fix"], 0, "Enabled macros are high risk."],
      ["Personal phone clicked smishing link on BYOD with corp mail:", "Remove corp account, wipe if MDM, assess data exposure", ["No action", "Pay SMS fee", "Disable MFA"], 0, "BYOD compromise affects corporate data."],
      ["After click, user cleared browser history. Problem:", "Removes forensic evidence—discourage before SOC images", ["Helps investigation", "Required", "Fixes malware"], 0, "Preserve evidence for investigators."],
      ["SOC gives user clean loaner machine while:", "Original imaged and investigated", ["User waits weeks without work unnecessarily without plan", "Ignore business need", "Disable MFA"], 0, "Loaners maintain productivity safely."],
      ["User fears punishment after click. Culture fix:", "No-blame reporting emphasizing rapid response", ["Terminate immediately always", "Public punishment", "Stop reporting"], 0, "Blame reduces reporting."],
      ["Clicked link but MFA blocked login. Still:", "Reset creds and hunt for token phishing artifacts", ["Do nothing", "Disable MFA", "Publish session"], 0, "MFA block does not guarantee no artifacts."],
      ["User provided OTP to vishing attacker. Action:", "Invalidate MFA factor, reset passwords, review auth logs", ["Ignore", "Share another OTP", "Disable IR"], 0, "OTP disclosure compromises factor."],
      ["After remediation, user education:", "Review specific indicators missed in that lure", ["Generic only", "No training", "Malware gift"], 0, "Targeted coaching improves future detection."],
      ["Shared drive accessed after user click. Hunt for:", "Lateral movement and ransomware precursors", ["Nothing", "Coffee", "DNS"], 0, "Assume broader compromise until scoped."],
      ["User forwarded phish to family. Risk:", "Spreads IOCs and may leak corp headers", ["Improves security", "Required", "Fixes Wi-Fi"], 0, "Keep corp incidents internal."],
      ["Mobile device click with MDM. SOC can:", "Remote wipe/contain via MDM commands", ["Nothing", "Disable MDM", "Publish keys"], 0, "MDM supports mobile containment."],
      ["Browser saved password on phishing site. Also:", "Rotate all saved passwords in manager and check autofill abuse", ["Only one password", "Disable manager", "Share vault"], 0, "Autofill may have exposed multiple creds."],
      ["User delayed reporting 3 days. Impact:", "Longer attacker dwell—reinforce immediate reporting", ["No effect", "Better security", "Automatic eradication"], 0, "Delay increases harm."],
      ["After click, legal hold may:", "Apply to user's mailbox and related systems", ["Never apply", "Delete mail", "Stop IR"], 0, "Legal may require preservation."],
      ["SOC confirms no malware but creds entered. Still:", "Credential incident response required", ["Close as false alarm", "Disable MFA", "Ignore"], 0, "Credential theft is incident without malware."],
      ["Reimage machine after click when:", "Malware or persistence confirmed or per playbook threshold", ["Always without investigation", "Never", "Only if user requests"], 0, "Reimage when compromise confirmed."],
      ["Post-click monitoring period:", "Enhanced logging on user account 30+ days", ["No monitoring", "Delete SIEM", "Disable EDR"], 0, "Watch for delayed abuse."],
      ["Helpdesk reset after click should:", "Follow compromised account playbook not standard reset only", ["Reuse old password", "Email password", "Disable MFA"], 0, "Compromised playbook is stricter."],
      ["User clicked sim link in training. Action:", "Show education page—no IR unless real attack", ["Full enterprise IR", "Terminate user", "Pay ransom"], 0, "Simulations differ from real incidents."],
      ["Executive click triggers:", "Expedited IR with comms and legal involvement", ["Ignore", "Tweet", "Disable mail"], 0, "VIP clicks have higher stakes."],
      ["After click, check email rules for:", "Forwarding/deletion rules attackers add", ["Nothing", "Printer", "DNS TTL"], 0, "Rules persist after password reset."],
      ["Closure criteria after click response:", "No IOCs, resets done, monitoring period complete, user coached", ["User apologized only", "AV green once", "Ignore hunting"], 0, "Documented criteria end incident."],
    ]),
  ]);
}
