import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const AISLS_TEXTBOOK_INTRO: TextbookIntro = {
  title: "AI-Assisted Sales",
  subtitle: "ForgEd path course — AI-Assisted Sales",
  paragraphs: [
    "AI-Assisted Sales is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Each chapter includes five sections and section quizzes. Pass chapter quizzes, the course review, and final exam to mark the course complete.",
    "Content is practical workforce education — not licensure, legal, or financial advice.",
  ],
};

export const AISLS_TEXTBOOK: TextbookChapter[] = [
  chapter("ai-prospecting", 1, "AI for Prospecting", [
      section("ai-prospecting-s1", "1.1 AI for Prospecting — applied practice (1)", ["1.1 AI for Prospecting — applied practice (1) connects AI for Prospecting to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-prospecting-s2", "1.2 AI for Prospecting — applied practice (2)", ["1.2 AI for Prospecting — applied practice (2) connects AI for Prospecting to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-prospecting-s3", "1.3 AI for Prospecting — applied practice (3)", ["1.3 AI for Prospecting — applied practice (3) connects AI for Prospecting to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-prospecting-s4", "1.4 AI for Prospecting — applied practice (4)", ["1.4 AI for Prospecting — applied practice (4) connects AI for Prospecting to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-prospecting-s5", "1.5 AI for Prospecting — applied practice (5)", ["1.5 AI for Prospecting — applied practice (5) connects AI for Prospecting to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("ai-prep-calls", 2, "AI Call Preparation", [
      section("ai-prep-calls-s1", "2.1 AI Call Preparation — applied practice (1)", ["2.1 AI Call Preparation — applied practice (1) connects AI Call Preparation to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-prep-calls-s2", "2.2 AI Call Preparation — applied practice (2)", ["2.2 AI Call Preparation — applied practice (2) connects AI Call Preparation to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-prep-calls-s3", "2.3 AI Call Preparation — applied practice (3)", ["2.3 AI Call Preparation — applied practice (3) connects AI Call Preparation to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-prep-calls-s4", "2.4 AI Call Preparation — applied practice (4)", ["2.4 AI Call Preparation — applied practice (4) connects AI Call Preparation to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-prep-calls-s5", "2.5 AI Call Preparation — applied practice (5)", ["2.5 AI Call Preparation — applied practice (5) connects AI Call Preparation to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("ai-email", 3, "AI Email Drafts", [
      section("ai-email-s1", "3.1 AI Email Drafts — applied practice (1)", ["3.1 AI Email Drafts — applied practice (1) connects AI Email Drafts to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-email-s2", "3.2 AI Email Drafts — applied practice (2)", ["3.2 AI Email Drafts — applied practice (2) connects AI Email Drafts to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-email-s3", "3.3 AI Email Drafts — applied practice (3)", ["3.3 AI Email Drafts — applied practice (3) connects AI Email Drafts to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-email-s4", "3.4 AI Email Drafts — applied practice (4)", ["3.4 AI Email Drafts — applied practice (4) connects AI Email Drafts to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-email-s5", "3.5 AI Email Drafts — applied practice (5)", ["3.5 AI Email Drafts — applied practice (5) connects AI Email Drafts to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("ai-research-account", 4, "Account Research", [
      section("ai-research-account-s1", "4.1 Account Research — applied practice (1)", ["4.1 Account Research — applied practice (1) connects Account Research to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-research-account-s2", "4.2 Account Research — applied practice (2)", ["4.2 Account Research — applied practice (2) connects Account Research to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-research-account-s3", "4.3 Account Research — applied practice (3)", ["4.3 Account Research — applied practice (3) connects Account Research to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-research-account-s4", "4.4 Account Research — applied practice (4)", ["4.4 Account Research — applied practice (4) connects Account Research to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-research-account-s5", "4.5 Account Research — applied practice (5)", ["4.5 Account Research — applied practice (5) connects Account Research to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("ai-proposals", 5, "Proposal Support", [
      section("ai-proposals-s1", "5.1 Proposal Support — applied practice (1)", ["5.1 Proposal Support — applied practice (1) connects Proposal Support to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-proposals-s2", "5.2 Proposal Support — applied practice (2)", ["5.2 Proposal Support — applied practice (2) connects Proposal Support to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-proposals-s3", "5.3 Proposal Support — applied practice (3)", ["5.3 Proposal Support — applied practice (3) connects Proposal Support to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-proposals-s4", "5.4 Proposal Support — applied practice (4)", ["5.4 Proposal Support — applied practice (4) connects Proposal Support to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-proposals-s5", "5.5 Proposal Support — applied practice (5)", ["5.5 Proposal Support — applied practice (5) connects Proposal Support to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("compliance-sales", 6, "Compliance in AI Sales", [
      section("compliance-sales-s1", "6.1 Compliance in AI Sales — applied practice (1)", ["6.1 Compliance in AI Sales — applied practice (1) connects Compliance in AI Sales to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("compliance-sales-s2", "6.2 Compliance in AI Sales — applied practice (2)", ["6.2 Compliance in AI Sales — applied practice (2) connects Compliance in AI Sales to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("compliance-sales-s3", "6.3 Compliance in AI Sales — applied practice (3)", ["6.3 Compliance in AI Sales — applied practice (3) connects Compliance in AI Sales to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("compliance-sales-s4", "6.4 Compliance in AI Sales — applied practice (4)", ["6.4 Compliance in AI Sales — applied practice (4) connects Compliance in AI Sales to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("compliance-sales-s5", "6.5 Compliance in AI Sales — applied practice (5)", ["6.5 Compliance in AI Sales — applied practice (5) connects Compliance in AI Sales to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("quality-control", 7, "Quality Control", [
      section("quality-control-s1", "7.1 Quality Control — applied practice (1)", ["7.1 Quality Control — applied practice (1) connects Quality Control to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("quality-control-s2", "7.2 Quality Control — applied practice (2)", ["7.2 Quality Control — applied practice (2) connects Quality Control to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("quality-control-s3", "7.3 Quality Control — applied practice (3)", ["7.3 Quality Control — applied practice (3) connects Quality Control to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("quality-control-s4", "7.4 Quality Control — applied practice (4)", ["7.4 Quality Control — applied practice (4) connects Quality Control to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("quality-control-s5", "7.5 Quality Control — applied practice (5)", ["7.5 Quality Control — applied practice (5) connects Quality Control to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("ai-sales-future", 8, "Future of AI in Sales", [
      section("ai-sales-future-s1", "8.1 Future of AI in Sales — applied practice (1)", ["8.1 Future of AI in Sales — applied practice (1) connects Future of AI in Sales to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-sales-future-s2", "8.2 Future of AI in Sales — applied practice (2)", ["8.2 Future of AI in Sales — applied practice (2) connects Future of AI in Sales to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-sales-future-s3", "8.3 Future of AI in Sales — applied practice (3)", ["8.3 Future of AI in Sales — applied practice (3) connects Future of AI in Sales to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-sales-future-s4", "8.4 Future of AI in Sales — applied practice (4)", ["8.4 Future of AI in Sales — applied practice (4) connects Future of AI in Sales to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-sales-future-s5", "8.5 Future of AI in Sales — applied practice (5)", ["8.5 Future of AI in Sales — applied practice (5) connects Future of AI in Sales to real workforce outcomes in AI-Assisted Sales. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ])
];
