import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const AASVC_TEXTBOOK_INTRO: TextbookIntro = {
  title: "AI in Automotive Service",
  subtitle: "Workforce training — AI in Automotive Service",
  paragraphs: [
    "AI in Automotive Service is built for professionals who want usable skill—not trivia. Each chapter moves from why the topic matters, through structured explanation, to quizzes that check judgment rather than memorization.",
    "AI in Automotive Service is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn ForgEd path completion badges on your profile.",
    "Content is practical workforce education. It does not replace licensure, legal, medical, or employer-specific policy. When your organization has a rule that conflicts with a general lesson, follow your organization's rule and treat this course as context.",
  ],
};

export const AASVC_TEXTBOOK: TextbookChapter[] = [
  chapter("ai-scheduling-svc", 1, "AI Scheduling", [
    section("ai-scheduling-svc-s1", "1.1 AI Scheduling — foundations and vocabulary", ["foundations and vocabulary is where ai scheduling stops being abstract. In AI in Automotive Service, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A repair order is a contract—what you document protects the shop and the driver. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("ai-scheduling-svc-s2", "1.2 AI Scheduling — how practitioners think", ["Most mistakes in ai scheduling happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Service lanes run on trust and timestamps; customers forgive delays they understand. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("ai-scheduling-svc-s3", "1.3 AI Scheduling — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","A repair order is a contract—what you document protects the shop and the driver. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("ai-scheduling-svc-s4", "1.4 AI Scheduling — common failures and fixes", ["common failures and fixes is where ai scheduling stops being abstract. In AI in Automotive Service, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Service lanes run on trust and timestamps; customers forgive delays they understand. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("ai-scheduling-svc-s5", "1.5 AI Scheduling — putting it together", ["Most mistakes in ai scheduling happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","A repair order is a contract—what you document protects the shop and the driver. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why ai scheduling matters in modern ai in automotive service work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around ai scheduling","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "AI Scheduling connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master ai scheduling reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("ai-status", 2, "AI Status Updates", [
    section("ai-status-s1", "2.1 AI Status Updates — foundations and vocabulary", ["foundations and vocabulary is where ai status updates stops being abstract. In AI in Automotive Service, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A repair order is a contract—what you document protects the shop and the driver. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("ai-status-s2", "2.2 AI Status Updates — how practitioners think", ["Most mistakes in ai status updates happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Service lanes run on trust and timestamps; customers forgive delays they understand. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("ai-status-s3", "2.3 AI Status Updates — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","A repair order is a contract—what you document protects the shop and the driver. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("ai-status-s4", "2.4 AI Status Updates — common failures and fixes", ["common failures and fixes is where ai status updates stops being abstract. In AI in Automotive Service, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Service lanes run on trust and timestamps; customers forgive delays they understand. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("ai-status-s5", "2.5 AI Status Updates — putting it together", ["Most mistakes in ai status updates happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","A repair order is a contract—what you document protects the shop and the driver. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why ai status updates matters in modern ai in automotive service work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around ai status updates","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "AI Status Updates connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master ai status updates reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("ai-notes", 3, "AI Service Notes", [
    section("ai-notes-s1", "3.1 AI Service Notes — foundations and vocabulary", ["foundations and vocabulary is where ai service notes stops being abstract. In AI in Automotive Service, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A repair order is a contract—what you document protects the shop and the driver. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("ai-notes-s2", "3.2 AI Service Notes — how practitioners think", ["Most mistakes in ai service notes happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Service lanes run on trust and timestamps; customers forgive delays they understand. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("ai-notes-s3", "3.3 AI Service Notes — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","A repair order is a contract—what you document protects the shop and the driver. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("ai-notes-s4", "3.4 AI Service Notes — common failures and fixes", ["common failures and fixes is where ai service notes stops being abstract. In AI in Automotive Service, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Service lanes run on trust and timestamps; customers forgive delays they understand. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("ai-notes-s5", "3.5 AI Service Notes — putting it together", ["Most mistakes in ai service notes happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","A repair order is a contract—what you document protects the shop and the driver. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why ai service notes matters in modern ai in automotive service work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around ai service notes","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "AI Service Notes connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master ai service notes reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("ai-parts", 4, "AI Parts Lookup", [
    section("ai-parts-s1", "4.1 AI Parts Lookup — foundations and vocabulary", ["foundations and vocabulary is where ai parts lookup stops being abstract. In AI in Automotive Service, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A repair order is a contract—what you document protects the shop and the driver. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("ai-parts-s2", "4.2 AI Parts Lookup — how practitioners think", ["Most mistakes in ai parts lookup happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Service lanes run on trust and timestamps; customers forgive delays they understand. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("ai-parts-s3", "4.3 AI Parts Lookup — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","A repair order is a contract—what you document protects the shop and the driver. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("ai-parts-s4", "4.4 AI Parts Lookup — common failures and fixes", ["common failures and fixes is where ai parts lookup stops being abstract. In AI in Automotive Service, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Service lanes run on trust and timestamps; customers forgive delays they understand. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("ai-parts-s5", "4.5 AI Parts Lookup — putting it together", ["Most mistakes in ai parts lookup happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","A repair order is a contract—what you document protects the shop and the driver. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why ai parts lookup matters in modern ai in automotive service work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around ai parts lookup","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "AI Parts Lookup connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master ai parts lookup reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("ai-training", 5, "Training Staff on AI", [
    section("ai-training-s1", "5.1 Training Staff on AI — foundations and vocabulary", ["foundations and vocabulary is where training staff on ai stops being abstract. In AI in Automotive Service, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A repair order is a contract—what you document protects the shop and the driver. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("ai-training-s2", "5.2 Training Staff on AI — how practitioners think", ["Most mistakes in training staff on ai happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Service lanes run on trust and timestamps; customers forgive delays they understand. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("ai-training-s3", "5.3 Training Staff on AI — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","A repair order is a contract—what you document protects the shop and the driver. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("ai-training-s4", "5.4 Training Staff on AI — common failures and fixes", ["common failures and fixes is where training staff on ai stops being abstract. In AI in Automotive Service, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Service lanes run on trust and timestamps; customers forgive delays they understand. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("ai-training-s5", "5.5 Training Staff on AI — putting it together", ["Most mistakes in training staff on ai happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","A repair order is a contract—what you document protects the shop and the driver. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why training staff on ai matters in modern ai in automotive service work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around training staff on ai","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Training Staff on AI connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master training staff on ai reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("privacy-svc", 6, "Customer Privacy", [
    section("privacy-svc-s1", "6.1 Customer Privacy — foundations and vocabulary", ["foundations and vocabulary is where customer privacy stops being abstract. In AI in Automotive Service, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A repair order is a contract—what you document protects the shop and the driver. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("privacy-svc-s2", "6.2 Customer Privacy — how practitioners think", ["Most mistakes in customer privacy happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Service lanes run on trust and timestamps; customers forgive delays they understand. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("privacy-svc-s3", "6.3 Customer Privacy — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","A repair order is a contract—what you document protects the shop and the driver. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("privacy-svc-s4", "6.4 Customer Privacy — common failures and fixes", ["common failures and fixes is where customer privacy stops being abstract. In AI in Automotive Service, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Service lanes run on trust and timestamps; customers forgive delays they understand. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("privacy-svc-s5", "6.5 Customer Privacy — putting it together", ["Most mistakes in customer privacy happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","A repair order is a contract—what you document protects the shop and the driver. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why customer privacy matters in modern ai in automotive service work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around customer privacy","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Customer Privacy connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master customer privacy reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("quality-ai-svc", 7, "Quality Control", [
    section("quality-ai-svc-s1", "7.1 Quality Control — foundations and vocabulary", ["foundations and vocabulary is where quality control stops being abstract. In AI in Automotive Service, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A repair order is a contract—what you document protects the shop and the driver. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("quality-ai-svc-s2", "7.2 Quality Control — how practitioners think", ["Most mistakes in quality control happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Service lanes run on trust and timestamps; customers forgive delays they understand. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("quality-ai-svc-s3", "7.3 Quality Control — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","A repair order is a contract—what you document protects the shop and the driver. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("quality-ai-svc-s4", "7.4 Quality Control — common failures and fixes", ["common failures and fixes is where quality control stops being abstract. In AI in Automotive Service, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Service lanes run on trust and timestamps; customers forgive delays they understand. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("quality-ai-svc-s5", "7.5 Quality Control — putting it together", ["Most mistakes in quality control happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","A repair order is a contract—what you document protects the shop and the driver. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why quality control matters in modern ai in automotive service work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around quality control","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Quality Control connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master quality control reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("future-svc-ai", 8, "Future of AI in Service", [
    section("future-svc-ai-s1", "8.1 Future of AI in Service — foundations and vocabulary", ["foundations and vocabulary is where future of ai in service stops being abstract. In AI in Automotive Service, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A repair order is a contract—what you document protects the shop and the driver. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("future-svc-ai-s2", "8.2 Future of AI in Service — how practitioners think", ["Most mistakes in future of ai in service happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Service lanes run on trust and timestamps; customers forgive delays they understand. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("future-svc-ai-s3", "8.3 Future of AI in Service — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","A repair order is a contract—what you document protects the shop and the driver. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("future-svc-ai-s4", "8.4 Future of AI in Service — common failures and fixes", ["common failures and fixes is where future of ai in service stops being abstract. In AI in Automotive Service, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Service lanes run on trust and timestamps; customers forgive delays they understand. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("future-svc-ai-s5", "8.5 Future of AI in Service — putting it together", ["Most mistakes in future of ai in service happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","A repair order is a contract—what you document protects the shop and the driver. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why future of ai in service matters in modern ai in automotive service work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around future of ai in service","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Future of AI in Service connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master future of ai in service reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  })
];
