import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const AASVC_TEXTBOOK_INTRO: TextbookIntro = {
  title: "AI in Automotive Service",
  subtitle: "ForgEd path course — AI in Automotive Service",
  paragraphs: [
    "AI in Automotive Service is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Each chapter includes five sections and section quizzes. Pass chapter quizzes, the course review, and final exam to mark the course complete.",
    "Content is practical workforce education — not licensure, legal, or financial advice.",
  ],
};

export const AASVC_TEXTBOOK: TextbookChapter[] = [
  chapter("ai-scheduling-svc", 1, "AI Scheduling", [
      section("ai-scheduling-svc-s1", "1.1 AI Scheduling — applied practice (1)", ["1.1 AI Scheduling — applied practice (1) connects AI Scheduling to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-scheduling-svc-s2", "1.2 AI Scheduling — applied practice (2)", ["1.2 AI Scheduling — applied practice (2) connects AI Scheduling to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-scheduling-svc-s3", "1.3 AI Scheduling — applied practice (3)", ["1.3 AI Scheduling — applied practice (3) connects AI Scheduling to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-scheduling-svc-s4", "1.4 AI Scheduling — applied practice (4)", ["1.4 AI Scheduling — applied practice (4) connects AI Scheduling to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-scheduling-svc-s5", "1.5 AI Scheduling — applied practice (5)", ["1.5 AI Scheduling — applied practice (5) connects AI Scheduling to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("ai-status", 2, "AI Status Updates", [
      section("ai-status-s1", "2.1 AI Status Updates — applied practice (1)", ["2.1 AI Status Updates — applied practice (1) connects AI Status Updates to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-status-s2", "2.2 AI Status Updates — applied practice (2)", ["2.2 AI Status Updates — applied practice (2) connects AI Status Updates to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-status-s3", "2.3 AI Status Updates — applied practice (3)", ["2.3 AI Status Updates — applied practice (3) connects AI Status Updates to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-status-s4", "2.4 AI Status Updates — applied practice (4)", ["2.4 AI Status Updates — applied practice (4) connects AI Status Updates to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-status-s5", "2.5 AI Status Updates — applied practice (5)", ["2.5 AI Status Updates — applied practice (5) connects AI Status Updates to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("ai-notes", 3, "AI Service Notes", [
      section("ai-notes-s1", "3.1 AI Service Notes — applied practice (1)", ["3.1 AI Service Notes — applied practice (1) connects AI Service Notes to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-notes-s2", "3.2 AI Service Notes — applied practice (2)", ["3.2 AI Service Notes — applied practice (2) connects AI Service Notes to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-notes-s3", "3.3 AI Service Notes — applied practice (3)", ["3.3 AI Service Notes — applied practice (3) connects AI Service Notes to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-notes-s4", "3.4 AI Service Notes — applied practice (4)", ["3.4 AI Service Notes — applied practice (4) connects AI Service Notes to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-notes-s5", "3.5 AI Service Notes — applied practice (5)", ["3.5 AI Service Notes — applied practice (5) connects AI Service Notes to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("ai-parts", 4, "AI Parts Lookup", [
      section("ai-parts-s1", "4.1 AI Parts Lookup — applied practice (1)", ["4.1 AI Parts Lookup — applied practice (1) connects AI Parts Lookup to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-parts-s2", "4.2 AI Parts Lookup — applied practice (2)", ["4.2 AI Parts Lookup — applied practice (2) connects AI Parts Lookup to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-parts-s3", "4.3 AI Parts Lookup — applied practice (3)", ["4.3 AI Parts Lookup — applied practice (3) connects AI Parts Lookup to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-parts-s4", "4.4 AI Parts Lookup — applied practice (4)", ["4.4 AI Parts Lookup — applied practice (4) connects AI Parts Lookup to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-parts-s5", "4.5 AI Parts Lookup — applied practice (5)", ["4.5 AI Parts Lookup — applied practice (5) connects AI Parts Lookup to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("ai-training", 5, "Training Staff on AI", [
      section("ai-training-s1", "5.1 Training Staff on AI — applied practice (1)", ["5.1 Training Staff on AI — applied practice (1) connects Training Staff on AI to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-training-s2", "5.2 Training Staff on AI — applied practice (2)", ["5.2 Training Staff on AI — applied practice (2) connects Training Staff on AI to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-training-s3", "5.3 Training Staff on AI — applied practice (3)", ["5.3 Training Staff on AI — applied practice (3) connects Training Staff on AI to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-training-s4", "5.4 Training Staff on AI — applied practice (4)", ["5.4 Training Staff on AI — applied practice (4) connects Training Staff on AI to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-training-s5", "5.5 Training Staff on AI — applied practice (5)", ["5.5 Training Staff on AI — applied practice (5) connects Training Staff on AI to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("privacy-svc", 6, "Customer Privacy", [
      section("privacy-svc-s1", "6.1 Customer Privacy — applied practice (1)", ["6.1 Customer Privacy — applied practice (1) connects Customer Privacy to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("privacy-svc-s2", "6.2 Customer Privacy — applied practice (2)", ["6.2 Customer Privacy — applied practice (2) connects Customer Privacy to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("privacy-svc-s3", "6.3 Customer Privacy — applied practice (3)", ["6.3 Customer Privacy — applied practice (3) connects Customer Privacy to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("privacy-svc-s4", "6.4 Customer Privacy — applied practice (4)", ["6.4 Customer Privacy — applied practice (4) connects Customer Privacy to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("privacy-svc-s5", "6.5 Customer Privacy — applied practice (5)", ["6.5 Customer Privacy — applied practice (5) connects Customer Privacy to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("quality-ai-svc", 7, "Quality Control", [
      section("quality-ai-svc-s1", "7.1 Quality Control — applied practice (1)", ["7.1 Quality Control — applied practice (1) connects Quality Control to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("quality-ai-svc-s2", "7.2 Quality Control — applied practice (2)", ["7.2 Quality Control — applied practice (2) connects Quality Control to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("quality-ai-svc-s3", "7.3 Quality Control — applied practice (3)", ["7.3 Quality Control — applied practice (3) connects Quality Control to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("quality-ai-svc-s4", "7.4 Quality Control — applied practice (4)", ["7.4 Quality Control — applied practice (4) connects Quality Control to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("quality-ai-svc-s5", "7.5 Quality Control — applied practice (5)", ["7.5 Quality Control — applied practice (5) connects Quality Control to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("future-svc-ai", 8, "Future of AI in Service", [
      section("future-svc-ai-s1", "8.1 Future of AI in Service — applied practice (1)", ["8.1 Future of AI in Service — applied practice (1) connects Future of AI in Service to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("future-svc-ai-s2", "8.2 Future of AI in Service — applied practice (2)", ["8.2 Future of AI in Service — applied practice (2) connects Future of AI in Service to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("future-svc-ai-s3", "8.3 Future of AI in Service — applied practice (3)", ["8.3 Future of AI in Service — applied practice (3) connects Future of AI in Service to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("future-svc-ai-s4", "8.4 Future of AI in Service — applied practice (4)", ["8.4 Future of AI in Service — applied practice (4) connects Future of AI in Service to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("future-svc-ai-s5", "8.5 Future of AI in Service — applied practice (5)", ["8.5 Future of AI in Service — applied practice (5) connects Future of AI in Service to real workforce outcomes in AI in Automotive Service. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ])
];
