import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const AIETH_TEXTBOOK_INTRO: TextbookIntro = {
  title: "AI Ethics & Risks",
  subtitle: "ForgEd path course — AI Ethics & Risks",
  paragraphs: [
    "AI Ethics & Risks is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Each chapter includes five sections and section quizzes. Pass chapter quizzes, the course review, and final exam to mark the course complete.",
    "Content is practical workforce education — not licensure, legal, or financial advice.",
  ],
};

export const AIETH_TEXTBOOK: TextbookChapter[] = [
  chapter("ethics-framework", 1, "Ethics Frameworks", [
      section("ethics-framework-s1", "1.1 Ethics Frameworks — applied practice (1)", ["1.1 Ethics Frameworks — applied practice (1) connects Ethics Frameworks to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ethics-framework-s2", "1.2 Ethics Frameworks — applied practice (2)", ["1.2 Ethics Frameworks — applied practice (2) connects Ethics Frameworks to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ethics-framework-s3", "1.3 Ethics Frameworks — applied practice (3)", ["1.3 Ethics Frameworks — applied practice (3) connects Ethics Frameworks to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ethics-framework-s4", "1.4 Ethics Frameworks — applied practice (4)", ["1.4 Ethics Frameworks — applied practice (4) connects Ethics Frameworks to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ethics-framework-s5", "1.5 Ethics Frameworks — applied practice (5)", ["1.5 Ethics Frameworks — applied practice (5) connects Ethics Frameworks to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("bias-fairness", 2, "Bias and Fairness", [
      section("bias-fairness-s1", "2.1 Bias and Fairness — applied practice (1)", ["2.1 Bias and Fairness — applied practice (1) connects Bias and Fairness to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("bias-fairness-s2", "2.2 Bias and Fairness — applied practice (2)", ["2.2 Bias and Fairness — applied practice (2) connects Bias and Fairness to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("bias-fairness-s3", "2.3 Bias and Fairness — applied practice (3)", ["2.3 Bias and Fairness — applied practice (3) connects Bias and Fairness to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("bias-fairness-s4", "2.4 Bias and Fairness — applied practice (4)", ["2.4 Bias and Fairness — applied practice (4) connects Bias and Fairness to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("bias-fairness-s5", "2.5 Bias and Fairness — applied practice (5)", ["2.5 Bias and Fairness — applied practice (5) connects Bias and Fairness to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("privacy-ai", 3, "Privacy and Data Use", [
      section("privacy-ai-s1", "3.1 Privacy and Data Use — applied practice (1)", ["3.1 Privacy and Data Use — applied practice (1) connects Privacy and Data Use to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("privacy-ai-s2", "3.2 Privacy and Data Use — applied practice (2)", ["3.2 Privacy and Data Use — applied practice (2) connects Privacy and Data Use to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("privacy-ai-s3", "3.3 Privacy and Data Use — applied practice (3)", ["3.3 Privacy and Data Use — applied practice (3) connects Privacy and Data Use to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("privacy-ai-s4", "3.4 Privacy and Data Use — applied practice (4)", ["3.4 Privacy and Data Use — applied practice (4) connects Privacy and Data Use to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("privacy-ai-s5", "3.5 Privacy and Data Use — applied practice (5)", ["3.5 Privacy and Data Use — applied practice (5) connects Privacy and Data Use to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("ip-ai", 4, "Intellectual Property", [
      section("ip-ai-s1", "4.1 Intellectual Property — applied practice (1)", ["4.1 Intellectual Property — applied practice (1) connects Intellectual Property to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ip-ai-s2", "4.2 Intellectual Property — applied practice (2)", ["4.2 Intellectual Property — applied practice (2) connects Intellectual Property to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ip-ai-s3", "4.3 Intellectual Property — applied practice (3)", ["4.3 Intellectual Property — applied practice (3) connects Intellectual Property to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ip-ai-s4", "4.4 Intellectual Property — applied practice (4)", ["4.4 Intellectual Property — applied practice (4) connects Intellectual Property to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ip-ai-s5", "4.5 Intellectual Property — applied practice (5)", ["4.5 Intellectual Property — applied practice (5) connects Intellectual Property to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("workplace-policy", 5, "Workplace AI Policy", [
      section("workplace-policy-s1", "5.1 Workplace AI Policy — applied practice (1)", ["5.1 Workplace AI Policy — applied practice (1) connects Workplace AI Policy to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("workplace-policy-s2", "5.2 Workplace AI Policy — applied practice (2)", ["5.2 Workplace AI Policy — applied practice (2) connects Workplace AI Policy to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("workplace-policy-s3", "5.3 Workplace AI Policy — applied practice (3)", ["5.3 Workplace AI Policy — applied practice (3) connects Workplace AI Policy to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("workplace-policy-s4", "5.4 Workplace AI Policy — applied practice (4)", ["5.4 Workplace AI Policy — applied practice (4) connects Workplace AI Policy to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("workplace-policy-s5", "5.5 Workplace AI Policy — applied practice (5)", ["5.5 Workplace AI Policy — applied practice (5) connects Workplace AI Policy to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("transparency", 6, "Transparency and Disclosure", [
      section("transparency-s1", "6.1 Transparency and Disclosure — applied practice (1)", ["6.1 Transparency and Disclosure — applied practice (1) connects Transparency and Disclosure to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("transparency-s2", "6.2 Transparency and Disclosure — applied practice (2)", ["6.2 Transparency and Disclosure — applied practice (2) connects Transparency and Disclosure to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("transparency-s3", "6.3 Transparency and Disclosure — applied practice (3)", ["6.3 Transparency and Disclosure — applied practice (3) connects Transparency and Disclosure to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("transparency-s4", "6.4 Transparency and Disclosure — applied practice (4)", ["6.4 Transparency and Disclosure — applied practice (4) connects Transparency and Disclosure to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("transparency-s5", "6.5 Transparency and Disclosure — applied practice (5)", ["6.5 Transparency and Disclosure — applied practice (5) connects Transparency and Disclosure to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("incident-ai", 7, "When AI Fails", [
      section("incident-ai-s1", "7.1 When AI Fails — applied practice (1)", ["7.1 When AI Fails — applied practice (1) connects When AI Fails to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("incident-ai-s2", "7.2 When AI Fails — applied practice (2)", ["7.2 When AI Fails — applied practice (2) connects When AI Fails to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("incident-ai-s3", "7.3 When AI Fails — applied practice (3)", ["7.3 When AI Fails — applied practice (3) connects When AI Fails to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("incident-ai-s4", "7.4 When AI Fails — applied practice (4)", ["7.4 When AI Fails — applied practice (4) connects When AI Fails to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("incident-ai-s5", "7.5 When AI Fails — applied practice (5)", ["7.5 When AI Fails — applied practice (5) connects When AI Fails to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("governance", 8, "Lightweight AI Governance", [
      section("governance-s1", "8.1 Lightweight AI Governance — applied practice (1)", ["8.1 Lightweight AI Governance — applied practice (1) connects Lightweight AI Governance to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("governance-s2", "8.2 Lightweight AI Governance — applied practice (2)", ["8.2 Lightweight AI Governance — applied practice (2) connects Lightweight AI Governance to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("governance-s3", "8.3 Lightweight AI Governance — applied practice (3)", ["8.3 Lightweight AI Governance — applied practice (3) connects Lightweight AI Governance to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("governance-s4", "8.4 Lightweight AI Governance — applied practice (4)", ["8.4 Lightweight AI Governance — applied practice (4) connects Lightweight AI Governance to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("governance-s5", "8.5 Lightweight AI Governance — applied practice (5)", ["8.5 Lightweight AI Governance — applied practice (5) connects Lightweight AI Governance to real workforce outcomes in AI Ethics & Risks. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ])
];
