import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const AIENT_TEXTBOOK_INTRO: TextbookIntro = {
  title: "AI For Entrepreneurs",
  subtitle: "ForgEd path course — AI For Entrepreneurs",
  paragraphs: [
    "AI For Entrepreneurs is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Each chapter includes five sections and section quizzes. Pass chapter quizzes, the course review, and final exam to mark the course complete.",
    "Content is practical workforce education — not licensure, legal, or financial advice.",
  ],
};

export const AIENT_TEXTBOOK: TextbookChapter[] = [
  chapter("ai-market-research", 1, "AI Market Research", [
      section("ai-market-research-s1", "1.1 AI Market Research — applied practice (1)", ["1.1 AI Market Research — applied practice (1) connects AI Market Research to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-market-research-s2", "1.2 AI Market Research — applied practice (2)", ["1.2 AI Market Research — applied practice (2) connects AI Market Research to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-market-research-s3", "1.3 AI Market Research — applied practice (3)", ["1.3 AI Market Research — applied practice (3) connects AI Market Research to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-market-research-s4", "1.4 AI Market Research — applied practice (4)", ["1.4 AI Market Research — applied practice (4) connects AI Market Research to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-market-research-s5", "1.5 AI Market Research — applied practice (5)", ["1.5 AI Market Research — applied practice (5) connects AI Market Research to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("ai-copy", 2, "AI Copy and Content", [
      section("ai-copy-s1", "2.1 AI Copy and Content — applied practice (1)", ["2.1 AI Copy and Content — applied practice (1) connects AI Copy and Content to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-copy-s2", "2.2 AI Copy and Content — applied practice (2)", ["2.2 AI Copy and Content — applied practice (2) connects AI Copy and Content to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-copy-s3", "2.3 AI Copy and Content — applied practice (3)", ["2.3 AI Copy and Content — applied practice (3) connects AI Copy and Content to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-copy-s4", "2.4 AI Copy and Content — applied practice (4)", ["2.4 AI Copy and Content — applied practice (4) connects AI Copy and Content to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-copy-s5", "2.5 AI Copy and Content — applied practice (5)", ["2.5 AI Copy and Content — applied practice (5) connects AI Copy and Content to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("ai-support", 3, "AI Customer Support", [
      section("ai-support-s1", "3.1 AI Customer Support — applied practice (1)", ["3.1 AI Customer Support — applied practice (1) connects AI Customer Support to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-support-s2", "3.2 AI Customer Support — applied practice (2)", ["3.2 AI Customer Support — applied practice (2) connects AI Customer Support to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-support-s3", "3.3 AI Customer Support — applied practice (3)", ["3.3 AI Customer Support — applied practice (3) connects AI Customer Support to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-support-s4", "3.4 AI Customer Support — applied practice (4)", ["3.4 AI Customer Support — applied practice (4) connects AI Customer Support to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-support-s5", "3.5 AI Customer Support — applied practice (5)", ["3.5 AI Customer Support — applied practice (5) connects AI Customer Support to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("ai-ops-startup", 4, "AI in Operations", [
      section("ai-ops-startup-s1", "4.1 AI in Operations — applied practice (1)", ["4.1 AI in Operations — applied practice (1) connects AI in Operations to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-ops-startup-s2", "4.2 AI in Operations — applied practice (2)", ["4.2 AI in Operations — applied practice (2) connects AI in Operations to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-ops-startup-s3", "4.3 AI in Operations — applied practice (3)", ["4.3 AI in Operations — applied practice (3) connects AI in Operations to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-ops-startup-s4", "4.4 AI in Operations — applied practice (4)", ["4.4 AI in Operations — applied practice (4) connects AI in Operations to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-ops-startup-s5", "4.5 AI in Operations — applied practice (5)", ["4.5 AI in Operations — applied practice (5) connects AI in Operations to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("ai-product", 5, "AI in Product", [
      section("ai-product-s1", "5.1 AI in Product — applied practice (1)", ["5.1 AI in Product — applied practice (1) connects AI in Product to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-product-s2", "5.2 AI in Product — applied practice (2)", ["5.2 AI in Product — applied practice (2) connects AI in Product to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-product-s3", "5.3 AI in Product — applied practice (3)", ["5.3 AI in Product — applied practice (3) connects AI in Product to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-product-s4", "5.4 AI in Product — applied practice (4)", ["5.4 AI in Product — applied practice (4) connects AI in Product to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ai-product-s5", "5.5 AI in Product — applied practice (5)", ["5.5 AI in Product — applied practice (5) connects AI in Product to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("cost-ai", 6, "Cost Control", [
      section("cost-ai-s1", "6.1 Cost Control — applied practice (1)", ["6.1 Cost Control — applied practice (1) connects Cost Control to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("cost-ai-s2", "6.2 Cost Control — applied practice (2)", ["6.2 Cost Control — applied practice (2) connects Cost Control to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("cost-ai-s3", "6.3 Cost Control — applied practice (3)", ["6.3 Cost Control — applied practice (3) connects Cost Control to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("cost-ai-s4", "6.4 Cost Control — applied practice (4)", ["6.4 Cost Control — applied practice (4) connects Cost Control to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("cost-ai-s5", "6.5 Cost Control — applied practice (5)", ["6.5 Cost Control — applied practice (5) connects Cost Control to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("policy-startup", 7, "Startup AI Policy", [
      section("policy-startup-s1", "7.1 Startup AI Policy — applied practice (1)", ["7.1 Startup AI Policy — applied practice (1) connects Startup AI Policy to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("policy-startup-s2", "7.2 Startup AI Policy — applied practice (2)", ["7.2 Startup AI Policy — applied practice (2) connects Startup AI Policy to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("policy-startup-s3", "7.3 Startup AI Policy — applied practice (3)", ["7.3 Startup AI Policy — applied practice (3) connects Startup AI Policy to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("policy-startup-s4", "7.4 Startup AI Policy — applied practice (4)", ["7.4 Startup AI Policy — applied practice (4) connects Startup AI Policy to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("policy-startup-s5", "7.5 Startup AI Policy — applied practice (5)", ["7.5 Startup AI Policy — applied practice (5) connects Startup AI Policy to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("scale-ai", 8, "Scaling AI Use", [
      section("scale-ai-s1", "8.1 Scaling AI Use — applied practice (1)", ["8.1 Scaling AI Use — applied practice (1) connects Scaling AI Use to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("scale-ai-s2", "8.2 Scaling AI Use — applied practice (2)", ["8.2 Scaling AI Use — applied practice (2) connects Scaling AI Use to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("scale-ai-s3", "8.3 Scaling AI Use — applied practice (3)", ["8.3 Scaling AI Use — applied practice (3) connects Scaling AI Use to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("scale-ai-s4", "8.4 Scaling AI Use — applied practice (4)", ["8.4 Scaling AI Use — applied practice (4) connects Scaling AI Use to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("scale-ai-s5", "8.5 Scaling AI Use — applied practice (5)", ["8.5 Scaling AI Use — applied practice (5) connects Scaling AI Use to real workforce outcomes in AI For Entrepreneurs. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ])
];
