import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const AIPROD_TEXTBOOK_INTRO: TextbookIntro = {
  title: "AI Productivity Systems",
  subtitle: "Workforce training — AI Productivity Systems",
  paragraphs: [
    "AI Productivity Systems is built for professionals who want usable skill—not trivia. Each chapter moves from why the topic matters, through structured explanation, to quizzes that check judgment rather than memorization.",
    "AI Productivity Systems is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn ForgEd path completion badges on your profile.",
    "Content is practical workforce education. It does not replace licensure, legal, medical, or employer-specific policy. When your organization has a rule that conflicts with a general lesson, follow your organization's rule and treat this course as context.",
  ],
};

export const AIPROD_TEXTBOOK: TextbookChapter[] = [
  chapter("inbox-triage", 1, "Inbox and Message Triage", [
    section("inbox-triage-s1", "1.1 Inbox and Message Triage — foundations and vocabulary", ["foundations and vocabulary is where inbox and message triage stops being abstract. In AI Productivity Systems, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("inbox-triage-s2", "1.2 Inbox and Message Triage — how practitioners think", ["Most mistakes in inbox and message triage happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("inbox-triage-s3", "1.3 Inbox and Message Triage — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("inbox-triage-s4", "1.4 Inbox and Message Triage — common failures and fixes", ["common failures and fixes is where inbox and message triage stops being abstract. In AI Productivity Systems, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("inbox-triage-s5", "1.5 Inbox and Message Triage — putting it together", ["Most mistakes in inbox and message triage happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why inbox and message triage matters in modern ai productivity systems work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around inbox and message triage","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Inbox and Message Triage connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master inbox and message triage reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("meeting-prep", 2, "Meeting Preparation", [
    section("meeting-prep-s1", "2.1 Meeting Preparation — foundations and vocabulary", ["foundations and vocabulary is where meeting preparation stops being abstract. In AI Productivity Systems, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("meeting-prep-s2", "2.2 Meeting Preparation — how practitioners think", ["Most mistakes in meeting preparation happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("meeting-prep-s3", "2.3 Meeting Preparation — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("meeting-prep-s4", "2.4 Meeting Preparation — common failures and fixes", ["common failures and fixes is where meeting preparation stops being abstract. In AI Productivity Systems, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("meeting-prep-s5", "2.5 Meeting Preparation — putting it together", ["Most mistakes in meeting preparation happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why meeting preparation matters in modern ai productivity systems work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around meeting preparation","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Meeting Preparation connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master meeting preparation reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("doc-drafting", 3, "Document Drafting", [
    section("doc-drafting-s1", "3.1 Document Drafting — foundations and vocabulary", ["foundations and vocabulary is where document drafting stops being abstract. In AI Productivity Systems, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("doc-drafting-s2", "3.2 Document Drafting — how practitioners think", ["Most mistakes in document drafting happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("doc-drafting-s3", "3.3 Document Drafting — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("doc-drafting-s4", "3.4 Document Drafting — common failures and fixes", ["common failures and fixes is where document drafting stops being abstract. In AI Productivity Systems, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("doc-drafting-s5", "3.5 Document Drafting — putting it together", ["Most mistakes in document drafting happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why document drafting matters in modern ai productivity systems work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around document drafting","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Document Drafting connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master document drafting reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("summarization", 4, "Summarization Patterns", [
    section("summarization-s1", "4.1 Summarization Patterns — foundations and vocabulary", ["foundations and vocabulary is where summarization patterns stops being abstract. In AI Productivity Systems, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("summarization-s2", "4.2 Summarization Patterns — how practitioners think", ["Most mistakes in summarization patterns happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("summarization-s3", "4.3 Summarization Patterns — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("summarization-s4", "4.4 Summarization Patterns — common failures and fixes", ["common failures and fixes is where summarization patterns stops being abstract. In AI Productivity Systems, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("summarization-s5", "4.5 Summarization Patterns — putting it together", ["Most mistakes in summarization patterns happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why summarization patterns matters in modern ai productivity systems work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around summarization patterns","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Summarization Patterns connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master summarization patterns reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("task-delegation", 5, "Task Delegation to AI", [
    section("task-delegation-s1", "5.1 Task Delegation to AI — foundations and vocabulary", ["foundations and vocabulary is where task delegation to ai stops being abstract. In AI Productivity Systems, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("task-delegation-s2", "5.2 Task Delegation to AI — how practitioners think", ["Most mistakes in task delegation to ai happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("task-delegation-s3", "5.3 Task Delegation to AI — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("task-delegation-s4", "5.4 Task Delegation to AI — common failures and fixes", ["common failures and fixes is where task delegation to ai stops being abstract. In AI Productivity Systems, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("task-delegation-s5", "5.5 Task Delegation to AI — putting it together", ["Most mistakes in task delegation to ai happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why task delegation to ai matters in modern ai productivity systems work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around task delegation to ai","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Task Delegation to AI connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master task delegation to ai reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("templates", 6, "Reusable Templates", [
    section("templates-s1", "6.1 Reusable Templates — foundations and vocabulary", ["foundations and vocabulary is where reusable templates stops being abstract. In AI Productivity Systems, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("templates-s2", "6.2 Reusable Templates — how practitioners think", ["Most mistakes in reusable templates happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("templates-s3", "6.3 Reusable Templates — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("templates-s4", "6.4 Reusable Templates — common failures and fixes", ["common failures and fixes is where reusable templates stops being abstract. In AI Productivity Systems, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("templates-s5", "6.5 Reusable Templates — putting it together", ["Most mistakes in reusable templates happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why reusable templates matters in modern ai productivity systems work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around reusable templates","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Reusable Templates connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master reusable templates reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("review-loops", 7, "Human Review Loops", [
    section("review-loops-s1", "7.1 Human Review Loops — foundations and vocabulary", ["foundations and vocabulary is where human review loops stops being abstract. In AI Productivity Systems, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("review-loops-s2", "7.2 Human Review Loops — how practitioners think", ["Most mistakes in human review loops happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("review-loops-s3", "7.3 Human Review Loops — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("review-loops-s4", "7.4 Human Review Loops — common failures and fixes", ["common failures and fixes is where human review loops stops being abstract. In AI Productivity Systems, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("review-loops-s5", "7.5 Human Review Loops — putting it together", ["Most mistakes in human review loops happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why human review loops matters in modern ai productivity systems work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around human review loops","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Human Review Loops connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master human review loops reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("productivity-metrics", 8, "Measuring Productivity Gains", [
    section("productivity-metrics-s1", "8.1 Measuring Productivity Gains — foundations and vocabulary", ["foundations and vocabulary is where measuring productivity gains stops being abstract. In AI Productivity Systems, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("productivity-metrics-s2", "8.2 Measuring Productivity Gains — how practitioners think", ["Most mistakes in measuring productivity gains happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("productivity-metrics-s3", "8.3 Measuring Productivity Gains — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("productivity-metrics-s4", "8.4 Measuring Productivity Gains — common failures and fixes", ["common failures and fixes is where measuring productivity gains stops being abstract. In AI Productivity Systems, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("productivity-metrics-s5", "8.5 Measuring Productivity Gains — putting it together", ["Most mistakes in measuring productivity gains happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why measuring productivity gains matters in modern ai productivity systems work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around measuring productivity gains","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Measuring Productivity Gains connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master measuring productivity gains reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  })
];
