import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const AIAUTO_TEXTBOOK_INTRO: TextbookIntro = {
  title: "AI Workflow Automation",
  subtitle: "Workforce training — AI Workflow Automation",
  paragraphs: [
    "AI Workflow Automation is built for professionals who want usable skill—not trivia. Each chapter moves from why the topic matters, through structured explanation, to quizzes that check judgment rather than memorization.",
    "AI Workflow Automation is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Content is practical workforce education. It does not replace licensure, legal, medical, or employer-specific policy. When your organization has a rule that conflicts with a general lesson, follow your organization's rule and treat this course as context.",
  ],
};

export const AIAUTO_TEXTBOOK: TextbookChapter[] = [
  chapter("automation-map", 1, "Mapping Workflows", [
    section("automation-map-s1", "1.1 Mapping Workflows — foundations and vocabulary", ["foundations and vocabulary is where mapping workflows stops being abstract. In AI Workflow Automation, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("automation-map-s2", "1.2 Mapping Workflows — how practitioners think", ["Most mistakes in mapping workflows happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("automation-map-s3", "1.3 Mapping Workflows — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("automation-map-s4", "1.4 Mapping Workflows — common failures and fixes", ["common failures and fixes is where mapping workflows stops being abstract. In AI Workflow Automation, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("automation-map-s5", "1.5 Mapping Workflows — putting it together", ["Most mistakes in mapping workflows happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why mapping workflows matters in modern ai workflow automation work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around mapping workflows","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Mapping Workflows connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master mapping workflows reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("triggers", 2, "Triggers and Inputs", [
    section("triggers-s1", "2.1 Triggers and Inputs — foundations and vocabulary", ["foundations and vocabulary is where triggers and inputs stops being abstract. In AI Workflow Automation, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("triggers-s2", "2.2 Triggers and Inputs — how practitioners think", ["Most mistakes in triggers and inputs happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("triggers-s3", "2.3 Triggers and Inputs — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("triggers-s4", "2.4 Triggers and Inputs — common failures and fixes", ["common failures and fixes is where triggers and inputs stops being abstract. In AI Workflow Automation, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("triggers-s5", "2.5 Triggers and Inputs — putting it together", ["Most mistakes in triggers and inputs happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why triggers and inputs matters in modern ai workflow automation work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around triggers and inputs","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Triggers and Inputs connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master triggers and inputs reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("steps-human", 3, "Human-in-the-Loop Steps", [
    section("steps-human-s1", "3.1 Human-in-the-Loop Steps — foundations and vocabulary", ["foundations and vocabulary is where human-in-the-loop steps stops being abstract. In AI Workflow Automation, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("steps-human-s2", "3.2 Human-in-the-Loop Steps — how practitioners think", ["Most mistakes in human-in-the-loop steps happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("steps-human-s3", "3.3 Human-in-the-Loop Steps — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("steps-human-s4", "3.4 Human-in-the-Loop Steps — common failures and fixes", ["common failures and fixes is where human-in-the-loop steps stops being abstract. In AI Workflow Automation, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("steps-human-s5", "3.5 Human-in-the-Loop Steps — putting it together", ["Most mistakes in human-in-the-loop steps happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why human-in-the-loop steps matters in modern ai workflow automation work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around human-in-the-loop steps","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Human-in-the-Loop Steps connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master human-in-the-loop steps reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("approvals", 4, "Approval Gates", [
    section("approvals-s1", "4.1 Approval Gates — foundations and vocabulary", ["foundations and vocabulary is where approval gates stops being abstract. In AI Workflow Automation, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("approvals-s2", "4.2 Approval Gates — how practitioners think", ["Most mistakes in approval gates happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("approvals-s3", "4.3 Approval Gates — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("approvals-s4", "4.4 Approval Gates — common failures and fixes", ["common failures and fixes is where approval gates stops being abstract. In AI Workflow Automation, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("approvals-s5", "4.5 Approval Gates — putting it together", ["Most mistakes in approval gates happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why approval gates matters in modern ai workflow automation work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around approval gates","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Approval Gates connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master approval gates reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("integrations", 5, "Tool Integrations", [
    section("integrations-s1", "5.1 Tool Integrations — foundations and vocabulary", ["foundations and vocabulary is where tool integrations stops being abstract. In AI Workflow Automation, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("integrations-s2", "5.2 Tool Integrations — how practitioners think", ["Most mistakes in tool integrations happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("integrations-s3", "5.3 Tool Integrations — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("integrations-s4", "5.4 Tool Integrations — common failures and fixes", ["common failures and fixes is where tool integrations stops being abstract. In AI Workflow Automation, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("integrations-s5", "5.5 Tool Integrations — putting it together", ["Most mistakes in tool integrations happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why tool integrations matters in modern ai workflow automation work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around tool integrations","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Tool Integrations connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master tool integrations reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("monitoring", 6, "Monitoring Outputs", [
    section("monitoring-s1", "6.1 Monitoring Outputs — foundations and vocabulary", ["foundations and vocabulary is where monitoring outputs stops being abstract. In AI Workflow Automation, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("monitoring-s2", "6.2 Monitoring Outputs — how practitioners think", ["Most mistakes in monitoring outputs happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("monitoring-s3", "6.3 Monitoring Outputs — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("monitoring-s4", "6.4 Monitoring Outputs — common failures and fixes", ["common failures and fixes is where monitoring outputs stops being abstract. In AI Workflow Automation, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("monitoring-s5", "6.5 Monitoring Outputs — putting it together", ["Most mistakes in monitoring outputs happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why monitoring outputs matters in modern ai workflow automation work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around monitoring outputs","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Monitoring Outputs connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master monitoring outputs reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("rollback", 7, "Rollback and Overrides", [
    section("rollback-s1", "7.1 Rollback and Overrides — foundations and vocabulary", ["foundations and vocabulary is where rollback and overrides stops being abstract. In AI Workflow Automation, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("rollback-s2", "7.2 Rollback and Overrides — how practitioners think", ["Most mistakes in rollback and overrides happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("rollback-s3", "7.3 Rollback and Overrides — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("rollback-s4", "7.4 Rollback and Overrides — common failures and fixes", ["common failures and fixes is where rollback and overrides stops being abstract. In AI Workflow Automation, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("rollback-s5", "7.5 Rollback and Overrides — putting it together", ["Most mistakes in rollback and overrides happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why rollback and overrides matters in modern ai workflow automation work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around rollback and overrides","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Rollback and Overrides connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master rollback and overrides reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("scale-automation", 8, "Scaling Automation Safely", [
    section("scale-automation-s1", "8.1 Scaling Automation Safely — foundations and vocabulary", ["foundations and vocabulary is where scaling automation safely stops being abstract. In AI Workflow Automation, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("scale-automation-s2", "8.2 Scaling Automation Safely — how practitioners think", ["Most mistakes in scaling automation safely happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("scale-automation-s3", "8.3 Scaling Automation Safely — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("scale-automation-s4", "8.4 Scaling Automation Safely — common failures and fixes", ["common failures and fixes is where scaling automation safely stops being abstract. In AI Workflow Automation, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("scale-automation-s5", "8.5 Scaling Automation Safely — putting it together", ["Most mistakes in scaling automation safely happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why scaling automation safely matters in modern ai workflow automation work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around scaling automation safely","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Scaling Automation Safely connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master scaling automation safely reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  })
];
