import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const AIAUTO_TEXTBOOK_INTRO: TextbookIntro = {
  title: "AI Workflow Automation",
  subtitle: "ForgEd path course — AI Workflow Automation",
  paragraphs: [
    "AI Workflow Automation is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Each chapter includes five sections and section quizzes. Pass chapter quizzes, the course review, and final exam to mark the course complete.",
    "Content is practical workforce education — not licensure, legal, or financial advice.",
  ],
};

export const AIAUTO_TEXTBOOK: TextbookChapter[] = [
  chapter("automation-map", 1, "Mapping Workflows", [
      section("automation-map-s1", "1.1 Mapping Workflows — applied practice (1)", ["1.1 Mapping Workflows — applied practice (1) connects Mapping Workflows to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("automation-map-s2", "1.2 Mapping Workflows — applied practice (2)", ["1.2 Mapping Workflows — applied practice (2) connects Mapping Workflows to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("automation-map-s3", "1.3 Mapping Workflows — applied practice (3)", ["1.3 Mapping Workflows — applied practice (3) connects Mapping Workflows to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("automation-map-s4", "1.4 Mapping Workflows — applied practice (4)", ["1.4 Mapping Workflows — applied practice (4) connects Mapping Workflows to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("automation-map-s5", "1.5 Mapping Workflows — applied practice (5)", ["1.5 Mapping Workflows — applied practice (5) connects Mapping Workflows to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("triggers", 2, "Triggers and Inputs", [
      section("triggers-s1", "2.1 Triggers and Inputs — applied practice (1)", ["2.1 Triggers and Inputs — applied practice (1) connects Triggers and Inputs to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("triggers-s2", "2.2 Triggers and Inputs — applied practice (2)", ["2.2 Triggers and Inputs — applied practice (2) connects Triggers and Inputs to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("triggers-s3", "2.3 Triggers and Inputs — applied practice (3)", ["2.3 Triggers and Inputs — applied practice (3) connects Triggers and Inputs to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("triggers-s4", "2.4 Triggers and Inputs — applied practice (4)", ["2.4 Triggers and Inputs — applied practice (4) connects Triggers and Inputs to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("triggers-s5", "2.5 Triggers and Inputs — applied practice (5)", ["2.5 Triggers and Inputs — applied practice (5) connects Triggers and Inputs to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("steps-human", 3, "Human-in-the-Loop Steps", [
      section("steps-human-s1", "3.1 Human-in-the-Loop Steps — applied practice (1)", ["3.1 Human-in-the-Loop Steps — applied practice (1) connects Human-in-the-Loop Steps to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("steps-human-s2", "3.2 Human-in-the-Loop Steps — applied practice (2)", ["3.2 Human-in-the-Loop Steps — applied practice (2) connects Human-in-the-Loop Steps to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("steps-human-s3", "3.3 Human-in-the-Loop Steps — applied practice (3)", ["3.3 Human-in-the-Loop Steps — applied practice (3) connects Human-in-the-Loop Steps to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("steps-human-s4", "3.4 Human-in-the-Loop Steps — applied practice (4)", ["3.4 Human-in-the-Loop Steps — applied practice (4) connects Human-in-the-Loop Steps to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("steps-human-s5", "3.5 Human-in-the-Loop Steps — applied practice (5)", ["3.5 Human-in-the-Loop Steps — applied practice (5) connects Human-in-the-Loop Steps to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("approvals", 4, "Approval Gates", [
      section("approvals-s1", "4.1 Approval Gates — applied practice (1)", ["4.1 Approval Gates — applied practice (1) connects Approval Gates to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("approvals-s2", "4.2 Approval Gates — applied practice (2)", ["4.2 Approval Gates — applied practice (2) connects Approval Gates to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("approvals-s3", "4.3 Approval Gates — applied practice (3)", ["4.3 Approval Gates — applied practice (3) connects Approval Gates to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("approvals-s4", "4.4 Approval Gates — applied practice (4)", ["4.4 Approval Gates — applied practice (4) connects Approval Gates to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("approvals-s5", "4.5 Approval Gates — applied practice (5)", ["4.5 Approval Gates — applied practice (5) connects Approval Gates to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("integrations", 5, "Tool Integrations", [
      section("integrations-s1", "5.1 Tool Integrations — applied practice (1)", ["5.1 Tool Integrations — applied practice (1) connects Tool Integrations to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("integrations-s2", "5.2 Tool Integrations — applied practice (2)", ["5.2 Tool Integrations — applied practice (2) connects Tool Integrations to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("integrations-s3", "5.3 Tool Integrations — applied practice (3)", ["5.3 Tool Integrations — applied practice (3) connects Tool Integrations to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("integrations-s4", "5.4 Tool Integrations — applied practice (4)", ["5.4 Tool Integrations — applied practice (4) connects Tool Integrations to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("integrations-s5", "5.5 Tool Integrations — applied practice (5)", ["5.5 Tool Integrations — applied practice (5) connects Tool Integrations to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("monitoring", 6, "Monitoring Outputs", [
      section("monitoring-s1", "6.1 Monitoring Outputs — applied practice (1)", ["6.1 Monitoring Outputs — applied practice (1) connects Monitoring Outputs to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("monitoring-s2", "6.2 Monitoring Outputs — applied practice (2)", ["6.2 Monitoring Outputs — applied practice (2) connects Monitoring Outputs to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("monitoring-s3", "6.3 Monitoring Outputs — applied practice (3)", ["6.3 Monitoring Outputs — applied practice (3) connects Monitoring Outputs to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("monitoring-s4", "6.4 Monitoring Outputs — applied practice (4)", ["6.4 Monitoring Outputs — applied practice (4) connects Monitoring Outputs to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("monitoring-s5", "6.5 Monitoring Outputs — applied practice (5)", ["6.5 Monitoring Outputs — applied practice (5) connects Monitoring Outputs to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("rollback", 7, "Rollback and Overrides", [
      section("rollback-s1", "7.1 Rollback and Overrides — applied practice (1)", ["7.1 Rollback and Overrides — applied practice (1) connects Rollback and Overrides to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("rollback-s2", "7.2 Rollback and Overrides — applied practice (2)", ["7.2 Rollback and Overrides — applied practice (2) connects Rollback and Overrides to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("rollback-s3", "7.3 Rollback and Overrides — applied practice (3)", ["7.3 Rollback and Overrides — applied practice (3) connects Rollback and Overrides to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("rollback-s4", "7.4 Rollback and Overrides — applied practice (4)", ["7.4 Rollback and Overrides — applied practice (4) connects Rollback and Overrides to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("rollback-s5", "7.5 Rollback and Overrides — applied practice (5)", ["7.5 Rollback and Overrides — applied practice (5) connects Rollback and Overrides to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("scale-automation", 8, "Scaling Automation Safely", [
      section("scale-automation-s1", "8.1 Scaling Automation Safely — applied practice (1)", ["8.1 Scaling Automation Safely — applied practice (1) connects Scaling Automation Safely to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("scale-automation-s2", "8.2 Scaling Automation Safely — applied practice (2)", ["8.2 Scaling Automation Safely — applied practice (2) connects Scaling Automation Safely to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("scale-automation-s3", "8.3 Scaling Automation Safely — applied practice (3)", ["8.3 Scaling Automation Safely — applied practice (3) connects Scaling Automation Safely to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("scale-automation-s4", "8.4 Scaling Automation Safely — applied practice (4)", ["8.4 Scaling Automation Safely — applied practice (4) connects Scaling Automation Safely to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("scale-automation-s5", "8.5 Scaling Automation Safely — applied practice (5)", ["8.5 Scaling Automation Safely — applied practice (5) connects Scaling Automation Safely to real workforce outcomes in AI Workflow Automation. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ])
];
