import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const BANK_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Banking Basics",
  subtitle: "ForgEd path course — Banking Basics",
  paragraphs: [
    "Banking Basics is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Each chapter includes five sections and section quizzes. Pass chapter quizzes, the course review, and final exam to mark the course complete.",
    "Content is practical workforce education — not licensure, legal, or financial advice.",
  ],
};

export const BANK_TEXTBOOK: TextbookChapter[] = [
  chapter("account-types", 1, "Account Types", [
      section("account-types-s1", "1.1 Account Types — applied practice (1)", ["1.1 Account Types — applied practice (1) connects Account Types to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("account-types-s2", "1.2 Account Types — applied practice (2)", ["1.2 Account Types — applied practice (2) connects Account Types to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("account-types-s3", "1.3 Account Types — applied practice (3)", ["1.3 Account Types — applied practice (3) connects Account Types to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("account-types-s4", "1.4 Account Types — applied practice (4)", ["1.4 Account Types — applied practice (4) connects Account Types to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("account-types-s5", "1.5 Account Types — applied practice (5)", ["1.5 Account Types — applied practice (5) connects Account Types to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("fees-banking", 2, "Fees and Features", [
      section("fees-banking-s1", "2.1 Fees and Features — applied practice (1)", ["2.1 Fees and Features — applied practice (1) connects Fees and Features to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("fees-banking-s2", "2.2 Fees and Features — applied practice (2)", ["2.2 Fees and Features — applied practice (2) connects Fees and Features to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("fees-banking-s3", "2.3 Fees and Features — applied practice (3)", ["2.3 Fees and Features — applied practice (3) connects Fees and Features to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("fees-banking-s4", "2.4 Fees and Features — applied practice (4)", ["2.4 Fees and Features — applied practice (4) connects Fees and Features to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("fees-banking-s5", "2.5 Fees and Features — applied practice (5)", ["2.5 Fees and Features — applied practice (5) connects Fees and Features to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("digital-banking", 3, "Digital Banking", [
      section("digital-banking-s1", "3.1 Digital Banking — applied practice (1)", ["3.1 Digital Banking — applied practice (1) connects Digital Banking to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("digital-banking-s2", "3.2 Digital Banking — applied practice (2)", ["3.2 Digital Banking — applied practice (2) connects Digital Banking to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("digital-banking-s3", "3.3 Digital Banking — applied practice (3)", ["3.3 Digital Banking — applied practice (3) connects Digital Banking to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("digital-banking-s4", "3.4 Digital Banking — applied practice (4)", ["3.4 Digital Banking — applied practice (4) connects Digital Banking to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("digital-banking-s5", "3.5 Digital Banking — applied practice (5)", ["3.5 Digital Banking — applied practice (5) connects Digital Banking to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("fraud-banking", 4, "Fraud Protection", [
      section("fraud-banking-s1", "4.1 Fraud Protection — applied practice (1)", ["4.1 Fraud Protection — applied practice (1) connects Fraud Protection to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("fraud-banking-s2", "4.2 Fraud Protection — applied practice (2)", ["4.2 Fraud Protection — applied practice (2) connects Fraud Protection to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("fraud-banking-s3", "4.3 Fraud Protection — applied practice (3)", ["4.3 Fraud Protection — applied practice (3) connects Fraud Protection to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("fraud-banking-s4", "4.4 Fraud Protection — applied practice (4)", ["4.4 Fraud Protection — applied practice (4) connects Fraud Protection to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("fraud-banking-s5", "4.5 Fraud Protection — applied practice (5)", ["4.5 Fraud Protection — applied practice (5) connects Fraud Protection to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("savings", 5, "Savings Strategies", [
      section("savings-s1", "5.1 Savings Strategies — applied practice (1)", ["5.1 Savings Strategies — applied practice (1) connects Savings Strategies to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("savings-s2", "5.2 Savings Strategies — applied practice (2)", ["5.2 Savings Strategies — applied practice (2) connects Savings Strategies to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("savings-s3", "5.3 Savings Strategies — applied practice (3)", ["5.3 Savings Strategies — applied practice (3) connects Savings Strategies to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("savings-s4", "5.4 Savings Strategies — applied practice (4)", ["5.4 Savings Strategies — applied practice (4) connects Savings Strategies to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("savings-s5", "5.5 Savings Strategies — applied practice (5)", ["5.5 Savings Strategies — applied practice (5) connects Savings Strategies to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("joint-accounts", 6, "Joint and Shared Accounts", [
      section("joint-accounts-s1", "6.1 Joint and Shared Accounts — applied practice (1)", ["6.1 Joint and Shared Accounts — applied practice (1) connects Joint and Shared Accounts to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("joint-accounts-s2", "6.2 Joint and Shared Accounts — applied practice (2)", ["6.2 Joint and Shared Accounts — applied practice (2) connects Joint and Shared Accounts to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("joint-accounts-s3", "6.3 Joint and Shared Accounts — applied practice (3)", ["6.3 Joint and Shared Accounts — applied practice (3) connects Joint and Shared Accounts to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("joint-accounts-s4", "6.4 Joint and Shared Accounts — applied practice (4)", ["6.4 Joint and Shared Accounts — applied practice (4) connects Joint and Shared Accounts to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("joint-accounts-s5", "6.5 Joint and Shared Accounts — applied practice (5)", ["6.5 Joint and Shared Accounts — applied practice (5) connects Joint and Shared Accounts to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("business-banking", 7, "Business Banking Intro", [
      section("business-banking-s1", "7.1 Business Banking Intro — applied practice (1)", ["7.1 Business Banking Intro — applied practice (1) connects Business Banking Intro to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("business-banking-s2", "7.2 Business Banking Intro — applied practice (2)", ["7.2 Business Banking Intro — applied practice (2) connects Business Banking Intro to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("business-banking-s3", "7.3 Business Banking Intro — applied practice (3)", ["7.3 Business Banking Intro — applied practice (3) connects Business Banking Intro to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("business-banking-s4", "7.4 Business Banking Intro — applied practice (4)", ["7.4 Business Banking Intro — applied practice (4) connects Business Banking Intro to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("business-banking-s5", "7.5 Business Banking Intro — applied practice (5)", ["7.5 Business Banking Intro — applied practice (5) connects Business Banking Intro to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("choosing-bank", 8, "Choosing a Bank", [
      section("choosing-bank-s1", "8.1 Choosing a Bank — applied practice (1)", ["8.1 Choosing a Bank — applied practice (1) connects Choosing a Bank to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("choosing-bank-s2", "8.2 Choosing a Bank — applied practice (2)", ["8.2 Choosing a Bank — applied practice (2) connects Choosing a Bank to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("choosing-bank-s3", "8.3 Choosing a Bank — applied practice (3)", ["8.3 Choosing a Bank — applied practice (3) connects Choosing a Bank to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("choosing-bank-s4", "8.4 Choosing a Bank — applied practice (4)", ["8.4 Choosing a Bank — applied practice (4) connects Choosing a Bank to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("choosing-bank-s5", "8.5 Choosing a Bank — applied practice (5)", ["8.5 Choosing a Bank — applied practice (5) connects Choosing a Bank to real workforce outcomes in Banking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ])
];
