import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const BRAND_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Branding Fundamentals",
  subtitle: "ForgEd path course — Branding Fundamentals",
  paragraphs: [
    "Branding Fundamentals is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Each chapter includes five sections and section quizzes. Pass chapter quizzes, the course review, and final exam to mark the course complete.",
    "Content is practical workforce education — not licensure, legal, or financial advice.",
  ],
};

export const BRAND_TEXTBOOK: TextbookChapter[] = [
  chapter("brand-why", 1, "Why Brand Matters", [
      section("brand-why-s1", "1.1 Why Brand Matters — applied practice (1)", ["1.1 Why Brand Matters — applied practice (1) connects Why Brand Matters to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("brand-why-s2", "1.2 Why Brand Matters — applied practice (2)", ["1.2 Why Brand Matters — applied practice (2) connects Why Brand Matters to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("brand-why-s3", "1.3 Why Brand Matters — applied practice (3)", ["1.3 Why Brand Matters — applied practice (3) connects Why Brand Matters to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("brand-why-s4", "1.4 Why Brand Matters — applied practice (4)", ["1.4 Why Brand Matters — applied practice (4) connects Why Brand Matters to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("brand-why-s5", "1.5 Why Brand Matters — applied practice (5)", ["1.5 Why Brand Matters — applied practice (5) connects Why Brand Matters to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("positioning", 2, "Positioning", [
      section("positioning-s1", "2.1 Positioning — applied practice (1)", ["2.1 Positioning — applied practice (1) connects Positioning to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("positioning-s2", "2.2 Positioning — applied practice (2)", ["2.2 Positioning — applied practice (2) connects Positioning to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("positioning-s3", "2.3 Positioning — applied practice (3)", ["2.3 Positioning — applied practice (3) connects Positioning to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("positioning-s4", "2.4 Positioning — applied practice (4)", ["2.4 Positioning — applied practice (4) connects Positioning to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("positioning-s5", "2.5 Positioning — applied practice (5)", ["2.5 Positioning — applied practice (5) connects Positioning to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("voice-tone", 3, "Voice and Tone", [
      section("voice-tone-s1", "3.1 Voice and Tone — applied practice (1)", ["3.1 Voice and Tone — applied practice (1) connects Voice and Tone to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("voice-tone-s2", "3.2 Voice and Tone — applied practice (2)", ["3.2 Voice and Tone — applied practice (2) connects Voice and Tone to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("voice-tone-s3", "3.3 Voice and Tone — applied practice (3)", ["3.3 Voice and Tone — applied practice (3) connects Voice and Tone to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("voice-tone-s4", "3.4 Voice and Tone — applied practice (4)", ["3.4 Voice and Tone — applied practice (4) connects Voice and Tone to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("voice-tone-s5", "3.5 Voice and Tone — applied practice (5)", ["3.5 Voice and Tone — applied practice (5) connects Voice and Tone to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("visual-id", 4, "Visual Identity", [
      section("visual-id-s1", "4.1 Visual Identity — applied practice (1)", ["4.1 Visual Identity — applied practice (1) connects Visual Identity to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("visual-id-s2", "4.2 Visual Identity — applied practice (2)", ["4.2 Visual Identity — applied practice (2) connects Visual Identity to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("visual-id-s3", "4.3 Visual Identity — applied practice (3)", ["4.3 Visual Identity — applied practice (3) connects Visual Identity to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("visual-id-s4", "4.4 Visual Identity — applied practice (4)", ["4.4 Visual Identity — applied practice (4) connects Visual Identity to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("visual-id-s5", "4.5 Visual Identity — applied practice (5)", ["4.5 Visual Identity — applied practice (5) connects Visual Identity to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("consistency", 5, "Brand Consistency", [
      section("consistency-s1", "5.1 Brand Consistency — applied practice (1)", ["5.1 Brand Consistency — applied practice (1) connects Brand Consistency to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("consistency-s2", "5.2 Brand Consistency — applied practice (2)", ["5.2 Brand Consistency — applied practice (2) connects Brand Consistency to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("consistency-s3", "5.3 Brand Consistency — applied practice (3)", ["5.3 Brand Consistency — applied practice (3) connects Brand Consistency to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("consistency-s4", "5.4 Brand Consistency — applied practice (4)", ["5.4 Brand Consistency — applied practice (4) connects Brand Consistency to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("consistency-s5", "5.5 Brand Consistency — applied practice (5)", ["5.5 Brand Consistency — applied practice (5) connects Brand Consistency to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("story", 6, "Brand Story", [
      section("story-s1", "6.1 Brand Story — applied practice (1)", ["6.1 Brand Story — applied practice (1) connects Brand Story to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("story-s2", "6.2 Brand Story — applied practice (2)", ["6.2 Brand Story — applied practice (2) connects Brand Story to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("story-s3", "6.3 Brand Story — applied practice (3)", ["6.3 Brand Story — applied practice (3) connects Brand Story to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("story-s4", "6.4 Brand Story — applied practice (4)", ["6.4 Brand Story — applied practice (4) connects Brand Story to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("story-s5", "6.5 Brand Story — applied practice (5)", ["6.5 Brand Story — applied practice (5) connects Brand Story to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("competitors-brand", 7, "Competitive Differentiation", [
      section("competitors-brand-s1", "7.1 Competitive Differentiation — applied practice (1)", ["7.1 Competitive Differentiation — applied practice (1) connects Competitive Differentiation to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("competitors-brand-s2", "7.2 Competitive Differentiation — applied practice (2)", ["7.2 Competitive Differentiation — applied practice (2) connects Competitive Differentiation to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("competitors-brand-s3", "7.3 Competitive Differentiation — applied practice (3)", ["7.3 Competitive Differentiation — applied practice (3) connects Competitive Differentiation to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("competitors-brand-s4", "7.4 Competitive Differentiation — applied practice (4)", ["7.4 Competitive Differentiation — applied practice (4) connects Competitive Differentiation to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("competitors-brand-s5", "7.5 Competitive Differentiation — applied practice (5)", ["7.5 Competitive Differentiation — applied practice (5) connects Competitive Differentiation to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("brand-metrics", 8, "Brand Metrics", [
      section("brand-metrics-s1", "8.1 Brand Metrics — applied practice (1)", ["8.1 Brand Metrics — applied practice (1) connects Brand Metrics to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("brand-metrics-s2", "8.2 Brand Metrics — applied practice (2)", ["8.2 Brand Metrics — applied practice (2) connects Brand Metrics to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("brand-metrics-s3", "8.3 Brand Metrics — applied practice (3)", ["8.3 Brand Metrics — applied practice (3) connects Brand Metrics to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("brand-metrics-s4", "8.4 Brand Metrics — applied practice (4)", ["8.4 Brand Metrics — applied practice (4) connects Brand Metrics to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("brand-metrics-s5", "8.5 Brand Metrics — applied practice (5)", ["8.5 Brand Metrics — applied practice (5) connects Brand Metrics to real workforce outcomes in Branding Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ])
];
