import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const BUD_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Budgeting Systems",
  subtitle: "Workforce training — Budgeting Systems",
  paragraphs: [
    "Budgeting Systems is built for professionals who want usable skill—not trivia. Each chapter moves from why the topic matters, through structured explanation, to quizzes that check judgment rather than memorization.",
    "Budgeting Systems is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn ForgEd path completion badges on your profile.",
    "Content is practical workforce education. It does not replace licensure, legal, medical, or employer-specific policy. When your organization has a rule that conflicts with a general lesson, follow your organization's rule and treat this course as context.",
  ],
};

export const BUD_TEXTBOOK: TextbookChapter[] = [
  chapter("budget-why", 1, "Why Budgets Work", [
    section("budget-why-s1", "1.1 Why Budgets Work — foundations and vocabulary", ["foundations and vocabulary is where why budgets work stops being abstract. In Budgeting Systems, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Your paycheck is a system—inputs, fixed outputs, and what you control. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("budget-why-s2", "1.2 Why Budgets Work — how practitioners think", ["Most mistakes in why budgets work happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Money decisions compound: a small fee today can cost thousands over a decade. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("budget-why-s3", "1.3 Why Budgets Work — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Your paycheck is a system—inputs, fixed outputs, and what you control. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("budget-why-s4", "1.4 Why Budgets Work — common failures and fixes", ["common failures and fixes is where why budgets work stops being abstract. In Budgeting Systems, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Money decisions compound: a small fee today can cost thousands over a decade. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("budget-why-s5", "1.5 Why Budgets Work — putting it together", ["Most mistakes in why budgets work happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","Your paycheck is a system—inputs, fixed outputs, and what you control. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why why budgets work matters in modern budgeting systems work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around why budgets work","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Why Budgets Work connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master why budgets work reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("zero-based", 2, "Zero-Based Budgeting", [
    section("zero-based-s1", "2.1 Zero-Based Budgeting — foundations and vocabulary", ["foundations and vocabulary is where zero-based budgeting stops being abstract. In Budgeting Systems, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Your paycheck is a system—inputs, fixed outputs, and what you control. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("zero-based-s2", "2.2 Zero-Based Budgeting — how practitioners think", ["Most mistakes in zero-based budgeting happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Money decisions compound: a small fee today can cost thousands over a decade. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("zero-based-s3", "2.3 Zero-Based Budgeting — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Your paycheck is a system—inputs, fixed outputs, and what you control. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("zero-based-s4", "2.4 Zero-Based Budgeting — common failures and fixes", ["common failures and fixes is where zero-based budgeting stops being abstract. In Budgeting Systems, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Money decisions compound: a small fee today can cost thousands over a decade. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("zero-based-s5", "2.5 Zero-Based Budgeting — putting it together", ["Most mistakes in zero-based budgeting happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","Your paycheck is a system—inputs, fixed outputs, and what you control. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why zero-based budgeting matters in modern budgeting systems work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around zero-based budgeting","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Zero-Based Budgeting connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master zero-based budgeting reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("envelope", 3, "Envelope Method", [
    section("envelope-s1", "3.1 Envelope Method — foundations and vocabulary", ["foundations and vocabulary is where envelope method stops being abstract. In Budgeting Systems, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Your paycheck is a system—inputs, fixed outputs, and what you control. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("envelope-s2", "3.2 Envelope Method — how practitioners think", ["Most mistakes in envelope method happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Money decisions compound: a small fee today can cost thousands over a decade. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("envelope-s3", "3.3 Envelope Method — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Your paycheck is a system—inputs, fixed outputs, and what you control. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("envelope-s4", "3.4 Envelope Method — common failures and fixes", ["common failures and fixes is where envelope method stops being abstract. In Budgeting Systems, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Money decisions compound: a small fee today can cost thousands over a decade. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("envelope-s5", "3.5 Envelope Method — putting it together", ["Most mistakes in envelope method happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","Your paycheck is a system—inputs, fixed outputs, and what you control. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why envelope method matters in modern budgeting systems work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around envelope method","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Envelope Method connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master envelope method reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("irregular-income", 4, "Irregular Income", [
    section("irregular-income-s1", "4.1 Irregular Income — foundations and vocabulary", ["foundations and vocabulary is where irregular income stops being abstract. In Budgeting Systems, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Your paycheck is a system—inputs, fixed outputs, and what you control. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("irregular-income-s2", "4.2 Irregular Income — how practitioners think", ["Most mistakes in irregular income happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Money decisions compound: a small fee today can cost thousands over a decade. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("irregular-income-s3", "4.3 Irregular Income — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Your paycheck is a system—inputs, fixed outputs, and what you control. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("irregular-income-s4", "4.4 Irregular Income — common failures and fixes", ["common failures and fixes is where irregular income stops being abstract. In Budgeting Systems, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Money decisions compound: a small fee today can cost thousands over a decade. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("irregular-income-s5", "4.5 Irregular Income — putting it together", ["Most mistakes in irregular income happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","Your paycheck is a system—inputs, fixed outputs, and what you control. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why irregular income matters in modern budgeting systems work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around irregular income","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Irregular Income connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master irregular income reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("categories", 5, "Expense Categories", [
    section("categories-s1", "5.1 Expense Categories — foundations and vocabulary", ["foundations and vocabulary is where expense categories stops being abstract. In Budgeting Systems, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Your paycheck is a system—inputs, fixed outputs, and what you control. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("categories-s2", "5.2 Expense Categories — how practitioners think", ["Most mistakes in expense categories happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Money decisions compound: a small fee today can cost thousands over a decade. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("categories-s3", "5.3 Expense Categories — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Your paycheck is a system—inputs, fixed outputs, and what you control. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("categories-s4", "5.4 Expense Categories — common failures and fixes", ["common failures and fixes is where expense categories stops being abstract. In Budgeting Systems, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Money decisions compound: a small fee today can cost thousands over a decade. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("categories-s5", "5.5 Expense Categories — putting it together", ["Most mistakes in expense categories happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","Your paycheck is a system—inputs, fixed outputs, and what you control. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why expense categories matters in modern budgeting systems work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around expense categories","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Expense Categories connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master expense categories reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("tracking-tools", 6, "Tracking Tools", [
    section("tracking-tools-s1", "6.1 Tracking Tools — foundations and vocabulary", ["foundations and vocabulary is where tracking tools stops being abstract. In Budgeting Systems, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Your paycheck is a system—inputs, fixed outputs, and what you control. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("tracking-tools-s2", "6.2 Tracking Tools — how practitioners think", ["Most mistakes in tracking tools happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Money decisions compound: a small fee today can cost thousands over a decade. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("tracking-tools-s3", "6.3 Tracking Tools — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Your paycheck is a system—inputs, fixed outputs, and what you control. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("tracking-tools-s4", "6.4 Tracking Tools — common failures and fixes", ["common failures and fixes is where tracking tools stops being abstract. In Budgeting Systems, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Money decisions compound: a small fee today can cost thousands over a decade. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("tracking-tools-s5", "6.5 Tracking Tools — putting it together", ["Most mistakes in tracking tools happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","Your paycheck is a system—inputs, fixed outputs, and what you control. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why tracking tools matters in modern budgeting systems work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around tracking tools","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Tracking Tools connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master tracking tools reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("review-monthly", 7, "Monthly Reviews", [
    section("review-monthly-s1", "7.1 Monthly Reviews — foundations and vocabulary", ["foundations and vocabulary is where monthly reviews stops being abstract. In Budgeting Systems, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Your paycheck is a system—inputs, fixed outputs, and what you control. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("review-monthly-s2", "7.2 Monthly Reviews — how practitioners think", ["Most mistakes in monthly reviews happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Money decisions compound: a small fee today can cost thousands over a decade. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("review-monthly-s3", "7.3 Monthly Reviews — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Your paycheck is a system—inputs, fixed outputs, and what you control. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("review-monthly-s4", "7.4 Monthly Reviews — common failures and fixes", ["common failures and fixes is where monthly reviews stops being abstract. In Budgeting Systems, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Money decisions compound: a small fee today can cost thousands over a decade. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("review-monthly-s5", "7.5 Monthly Reviews — putting it together", ["Most mistakes in monthly reviews happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","Your paycheck is a system—inputs, fixed outputs, and what you control. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why monthly reviews matters in modern budgeting systems work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around monthly reviews","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Monthly Reviews connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master monthly reviews reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("budget-goals", 8, "Goal-Based Budgets", [
    section("budget-goals-s1", "8.1 Goal-Based Budgets — foundations and vocabulary", ["foundations and vocabulary is where goal-based budgets stops being abstract. In Budgeting Systems, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Your paycheck is a system—inputs, fixed outputs, and what you control. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("budget-goals-s2", "8.2 Goal-Based Budgets — how practitioners think", ["Most mistakes in goal-based budgets happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Money decisions compound: a small fee today can cost thousands over a decade. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("budget-goals-s3", "8.3 Goal-Based Budgets — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Your paycheck is a system—inputs, fixed outputs, and what you control. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("budget-goals-s4", "8.4 Goal-Based Budgets — common failures and fixes", ["common failures and fixes is where goal-based budgets stops being abstract. In Budgeting Systems, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Money decisions compound: a small fee today can cost thousands over a decade. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("budget-goals-s5", "8.5 Goal-Based Budgets — putting it together", ["Most mistakes in goal-based budgets happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","Your paycheck is a system—inputs, fixed outputs, and what you control. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why goal-based budgets matters in modern budgeting systems work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around goal-based budgets","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Goal-Based Budgets connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master goal-based budgets reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  })
];
