import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const CREA_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Creative Media Fundamentals",
  subtitle: "ForgEd deep-dive — creative media fundamentals",
  paragraphs: [
    "This ForgEd digital textbook presents Creative Media Fundamentals at academic survey depth for self-paced study.",
    "Complete each section quiz before advancing. Chapter and course assessments draw from a 150-question bank.",
    "Material is general education, not professional licensure or certification prep by itself.",
  ],
};

export const CREA_TEXTBOOK: TextbookChapter[] = [
  chapter("design-principles", 1, "Design Principles", [
      section("design-principles-s1", "1.1 Design Principles — core concepts (1)", ["1.1 Design Principles — core concepts (1) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply design principles with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in design principles."]),
      section("design-principles-s2", "1.2 Design Principles — core concepts (2)", ["1.2 Design Principles — core concepts (2) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply design principles with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in design principles."]),
      section("design-principles-s3", "1.3 Design Principles — core concepts (3)", ["1.3 Design Principles — core concepts (3) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply design principles with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in design principles."]),
      section("design-principles-s4", "1.4 Design Principles — core concepts (4)", ["1.4 Design Principles — core concepts (4) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply design principles with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in design principles."]),
      section("design-principles-s5", "1.5 Design Principles — core concepts (5)", ["1.5 Design Principles — core concepts (5) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply design principles with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in design principles."]),
  ]),
  chapter("visual-tools", 2, "Visual Tools and Workflow", [
      section("visual-tools-s1", "2.1 Visual Tools and Workflow — core concepts (1)", ["2.1 Visual Tools and Workflow — core concepts (1) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply visual tools and workflow with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in visual tools and workflow."]),
      section("visual-tools-s2", "2.2 Visual Tools and Workflow — core concepts (2)", ["2.2 Visual Tools and Workflow — core concepts (2) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply visual tools and workflow with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in visual tools and workflow."]),
      section("visual-tools-s3", "2.3 Visual Tools and Workflow — core concepts (3)", ["2.3 Visual Tools and Workflow — core concepts (3) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply visual tools and workflow with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in visual tools and workflow."]),
      section("visual-tools-s4", "2.4 Visual Tools and Workflow — core concepts (4)", ["2.4 Visual Tools and Workflow — core concepts (4) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply visual tools and workflow with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in visual tools and workflow."]),
      section("visual-tools-s5", "2.5 Visual Tools and Workflow — core concepts (5)", ["2.5 Visual Tools and Workflow — core concepts (5) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply visual tools and workflow with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in visual tools and workflow."]),
  ]),
  chapter("photography", 3, "Photography Basics", [
      section("photography-s1", "3.1 Photography Basics — core concepts (1)", ["3.1 Photography Basics — core concepts (1) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply photography basics with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in photography basics."]),
      section("photography-s2", "3.2 Photography Basics — core concepts (2)", ["3.2 Photography Basics — core concepts (2) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply photography basics with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in photography basics."]),
      section("photography-s3", "3.3 Photography Basics — core concepts (3)", ["3.3 Photography Basics — core concepts (3) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply photography basics with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in photography basics."]),
      section("photography-s4", "3.4 Photography Basics — core concepts (4)", ["3.4 Photography Basics — core concepts (4) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply photography basics with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in photography basics."]),
      section("photography-s5", "3.5 Photography Basics — core concepts (5)", ["3.5 Photography Basics — core concepts (5) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply photography basics with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in photography basics."]),
  ]),
  chapter("video-editing", 4, "Video Editing Intro", [
      section("video-editing-s1", "4.1 Video Editing Intro — core concepts (1)", ["4.1 Video Editing Intro — core concepts (1) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply video editing intro with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in video editing intro."]),
      section("video-editing-s2", "4.2 Video Editing Intro — core concepts (2)", ["4.2 Video Editing Intro — core concepts (2) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply video editing intro with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in video editing intro."]),
      section("video-editing-s3", "4.3 Video Editing Intro — core concepts (3)", ["4.3 Video Editing Intro — core concepts (3) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply video editing intro with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in video editing intro."]),
      section("video-editing-s4", "4.4 Video Editing Intro — core concepts (4)", ["4.4 Video Editing Intro — core concepts (4) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply video editing intro with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in video editing intro."]),
      section("video-editing-s5", "4.5 Video Editing Intro — core concepts (5)", ["4.5 Video Editing Intro — core concepts (5) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply video editing intro with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in video editing intro."]),
  ]),
  chapter("audio-basics", 5, "Audio and Music Basics", [
      section("audio-basics-s1", "5.1 Audio and Music Basics — core concepts (1)", ["5.1 Audio and Music Basics — core concepts (1) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply audio and music basics with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in audio and music basics."]),
      section("audio-basics-s2", "5.2 Audio and Music Basics — core concepts (2)", ["5.2 Audio and Music Basics — core concepts (2) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply audio and music basics with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in audio and music basics."]),
      section("audio-basics-s3", "5.3 Audio and Music Basics — core concepts (3)", ["5.3 Audio and Music Basics — core concepts (3) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply audio and music basics with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in audio and music basics."]),
      section("audio-basics-s4", "5.4 Audio and Music Basics — core concepts (4)", ["5.4 Audio and Music Basics — core concepts (4) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply audio and music basics with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in audio and music basics."]),
      section("audio-basics-s5", "5.5 Audio and Music Basics — core concepts (5)", ["5.5 Audio and Music Basics — core concepts (5) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply audio and music basics with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in audio and music basics."]),
  ]),
  chapter("writing-creative", 6, "Creative Writing", [
      section("writing-creative-s1", "6.1 Creative Writing — core concepts (1)", ["6.1 Creative Writing — core concepts (1) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply creative writing with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in creative writing."]),
      section("writing-creative-s2", "6.2 Creative Writing — core concepts (2)", ["6.2 Creative Writing — core concepts (2) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply creative writing with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in creative writing."]),
      section("writing-creative-s3", "6.3 Creative Writing — core concepts (3)", ["6.3 Creative Writing — core concepts (3) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply creative writing with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in creative writing."]),
      section("writing-creative-s4", "6.4 Creative Writing — core concepts (4)", ["6.4 Creative Writing — core concepts (4) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply creative writing with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in creative writing."]),
      section("writing-creative-s5", "6.5 Creative Writing — core concepts (5)", ["6.5 Creative Writing — core concepts (5) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply creative writing with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in creative writing."]),
  ]),
  chapter("branding", 7, "Branding and Portfolios", [
      section("branding-s1", "7.1 Branding and Portfolios — core concepts (1)", ["7.1 Branding and Portfolios — core concepts (1) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply branding and portfolios with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in branding and portfolios."]),
      section("branding-s2", "7.2 Branding and Portfolios — core concepts (2)", ["7.2 Branding and Portfolios — core concepts (2) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply branding and portfolios with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in branding and portfolios."]),
      section("branding-s3", "7.3 Branding and Portfolios — core concepts (3)", ["7.3 Branding and Portfolios — core concepts (3) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply branding and portfolios with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in branding and portfolios."]),
      section("branding-s4", "7.4 Branding and Portfolios — core concepts (4)", ["7.4 Branding and Portfolios — core concepts (4) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply branding and portfolios with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in branding and portfolios."]),
      section("branding-s5", "7.5 Branding and Portfolios — core concepts (5)", ["7.5 Branding and Portfolios — core concepts (5) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply branding and portfolios with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in branding and portfolios."]),
  ]),
  chapter("collaboration", 8, "Creative Collaboration", [
      section("collaboration-s1", "8.1 Creative Collaboration — core concepts (1)", ["8.1 Creative Collaboration — core concepts (1) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply creative collaboration with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in creative collaboration."]),
      section("collaboration-s2", "8.2 Creative Collaboration — core concepts (2)", ["8.2 Creative Collaboration — core concepts (2) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply creative collaboration with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in creative collaboration."]),
      section("collaboration-s3", "8.3 Creative Collaboration — core concepts (3)", ["8.3 Creative Collaboration — core concepts (3) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply creative collaboration with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in creative collaboration."]),
      section("collaboration-s4", "8.4 Creative Collaboration — core concepts (4)", ["8.4 Creative Collaboration — core concepts (4) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply creative collaboration with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in creative collaboration."]),
      section("collaboration-s5", "8.5 Creative Collaboration — core concepts (5)", ["8.5 Creative Collaboration — core concepts (5) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply creative collaboration with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in creative collaboration."]),
  ]),
  chapter("freelance", 9, "Freelance and Client Work", [
      section("freelance-s1", "9.1 Freelance and Client Work — core concepts (1)", ["9.1 Freelance and Client Work — core concepts (1) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply freelance and client work with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in freelance and client work."]),
      section("freelance-s2", "9.2 Freelance and Client Work — core concepts (2)", ["9.2 Freelance and Client Work — core concepts (2) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply freelance and client work with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in freelance and client work."]),
      section("freelance-s3", "9.3 Freelance and Client Work — core concepts (3)", ["9.3 Freelance and Client Work — core concepts (3) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply freelance and client work with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in freelance and client work."]),
      section("freelance-s4", "9.4 Freelance and Client Work — core concepts (4)", ["9.4 Freelance and Client Work — core concepts (4) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply freelance and client work with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in freelance and client work."]),
      section("freelance-s5", "9.5 Freelance and Client Work — core concepts (5)", ["9.5 Freelance and Client Work — core concepts (5) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply freelance and client work with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in freelance and client work."]),
  ]),
  chapter("creative-careers", 10, "Creative Careers", [
      section("creative-careers-s1", "10.1 Creative Careers — core concepts (1)", ["10.1 Creative Careers — core concepts (1) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply creative careers with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in creative careers."]),
      section("creative-careers-s2", "10.2 Creative Careers — core concepts (2)", ["10.2 Creative Careers — core concepts (2) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply creative careers with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in creative careers."]),
      section("creative-careers-s3", "10.3 Creative Careers — core concepts (3)", ["10.3 Creative Careers — core concepts (3) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply creative careers with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in creative careers."]),
      section("creative-careers-s4", "10.4 Creative Careers — core concepts (4)", ["10.4 Creative Careers — core concepts (4) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply creative careers with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in creative careers."]),
      section("creative-careers-s5", "10.5 Creative Careers — core concepts (5)", ["10.5 Creative Careers — core concepts (5) is a core topic in Creative Media Fundamentals. Learners should connect definitions to how professionals apply creative careers with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in creative careers."]),
  ])
];
