import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const CRED_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Credit & Debt",
  subtitle: "Workforce training — Credit & Debt",
  paragraphs: [
    "Credit & Debt is built for professionals who want usable skill—not trivia. Each chapter moves from why the topic matters, through structured explanation, to quizzes that check judgment rather than memorization.",
    "Credit & Debt is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn ForgEd path completion badges on your profile.",
    "Content is practical workforce education. It does not replace licensure, legal, medical, or employer-specific policy. When your organization has a rule that conflicts with a general lesson, follow your organization's rule and treat this course as context.",
  ],
};

export const CRED_TEXTBOOK: TextbookChapter[] = [
  chapter("credit-scores", 1, "Credit Scores Explained", [
    section("credit-scores-s1", "1.1 Credit Scores Explained — foundations and vocabulary", ["foundations and vocabulary is where credit scores explained stops being abstract. In Credit & Debt, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Your paycheck is a system—inputs, fixed outputs, and what you control. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("credit-scores-s2", "1.2 Credit Scores Explained — how practitioners think", ["Most mistakes in credit scores explained happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Money decisions compound: a small fee today can cost thousands over a decade. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("credit-scores-s3", "1.3 Credit Scores Explained — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Your paycheck is a system—inputs, fixed outputs, and what you control. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("credit-scores-s4", "1.4 Credit Scores Explained — common failures and fixes", ["common failures and fixes is where credit scores explained stops being abstract. In Credit & Debt, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Money decisions compound: a small fee today can cost thousands over a decade. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("credit-scores-s5", "1.5 Credit Scores Explained — putting it together", ["Most mistakes in credit scores explained happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","Your paycheck is a system—inputs, fixed outputs, and what you control. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why credit scores explained matters in modern credit & debt work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around credit scores explained","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Credit Scores Explained connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master credit scores explained reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("reports", 2, "Credit Reports", [
    section("reports-s1", "2.1 Credit Reports — foundations and vocabulary", ["foundations and vocabulary is where credit reports stops being abstract. In Credit & Debt, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Your paycheck is a system—inputs, fixed outputs, and what you control. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("reports-s2", "2.2 Credit Reports — how practitioners think", ["Most mistakes in credit reports happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Money decisions compound: a small fee today can cost thousands over a decade. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("reports-s3", "2.3 Credit Reports — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Your paycheck is a system—inputs, fixed outputs, and what you control. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("reports-s4", "2.4 Credit Reports — common failures and fixes", ["common failures and fixes is where credit reports stops being abstract. In Credit & Debt, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Money decisions compound: a small fee today can cost thousands over a decade. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("reports-s5", "2.5 Credit Reports — putting it together", ["Most mistakes in credit reports happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","Your paycheck is a system—inputs, fixed outputs, and what you control. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why credit reports matters in modern credit & debt work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around credit reports","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Credit Reports connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master credit reports reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("utilization", 3, "Utilization", [
    section("utilization-s1", "3.1 Utilization — foundations and vocabulary", ["foundations and vocabulary is where utilization stops being abstract. In Credit & Debt, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Your paycheck is a system—inputs, fixed outputs, and what you control. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("utilization-s2", "3.2 Utilization — how practitioners think", ["Most mistakes in utilization happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Money decisions compound: a small fee today can cost thousands over a decade. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("utilization-s3", "3.3 Utilization — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Your paycheck is a system—inputs, fixed outputs, and what you control. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("utilization-s4", "3.4 Utilization — common failures and fixes", ["common failures and fixes is where utilization stops being abstract. In Credit & Debt, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Money decisions compound: a small fee today can cost thousands over a decade. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("utilization-s5", "3.5 Utilization — putting it together", ["Most mistakes in utilization happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","Your paycheck is a system—inputs, fixed outputs, and what you control. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why utilization matters in modern credit & debt work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around utilization","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Utilization connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master utilization reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("debt-types", 4, "Types of Debt", [
    section("debt-types-s1", "4.1 Types of Debt — foundations and vocabulary", ["foundations and vocabulary is where types of debt stops being abstract. In Credit & Debt, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Your paycheck is a system—inputs, fixed outputs, and what you control. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("debt-types-s2", "4.2 Types of Debt — how practitioners think", ["Most mistakes in types of debt happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Money decisions compound: a small fee today can cost thousands over a decade. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("debt-types-s3", "4.3 Types of Debt — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Your paycheck is a system—inputs, fixed outputs, and what you control. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("debt-types-s4", "4.4 Types of Debt — common failures and fixes", ["common failures and fixes is where types of debt stops being abstract. In Credit & Debt, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Money decisions compound: a small fee today can cost thousands over a decade. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("debt-types-s5", "4.5 Types of Debt — putting it together", ["Most mistakes in types of debt happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","Your paycheck is a system—inputs, fixed outputs, and what you control. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why types of debt matters in modern credit & debt work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around types of debt","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Types of Debt connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master types of debt reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("payoff-strategies", 5, "Payoff Strategies", [
    section("payoff-strategies-s1", "5.1 Payoff Strategies — foundations and vocabulary", ["foundations and vocabulary is where payoff strategies stops being abstract. In Credit & Debt, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Your paycheck is a system—inputs, fixed outputs, and what you control. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("payoff-strategies-s2", "5.2 Payoff Strategies — how practitioners think", ["Most mistakes in payoff strategies happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Money decisions compound: a small fee today can cost thousands over a decade. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("payoff-strategies-s3", "5.3 Payoff Strategies — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Your paycheck is a system—inputs, fixed outputs, and what you control. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("payoff-strategies-s4", "5.4 Payoff Strategies — common failures and fixes", ["common failures and fixes is where payoff strategies stops being abstract. In Credit & Debt, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Money decisions compound: a small fee today can cost thousands over a decade. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("payoff-strategies-s5", "5.5 Payoff Strategies — putting it together", ["Most mistakes in payoff strategies happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","Your paycheck is a system—inputs, fixed outputs, and what you control. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why payoff strategies matters in modern credit & debt work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around payoff strategies","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Payoff Strategies connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master payoff strategies reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("consolidation", 6, "Consolidation Options", [
    section("consolidation-s1", "6.1 Consolidation Options — foundations and vocabulary", ["foundations and vocabulary is where consolidation options stops being abstract. In Credit & Debt, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Your paycheck is a system—inputs, fixed outputs, and what you control. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("consolidation-s2", "6.2 Consolidation Options — how practitioners think", ["Most mistakes in consolidation options happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Money decisions compound: a small fee today can cost thousands over a decade. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("consolidation-s3", "6.3 Consolidation Options — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Your paycheck is a system—inputs, fixed outputs, and what you control. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("consolidation-s4", "6.4 Consolidation Options — common failures and fixes", ["common failures and fixes is where consolidation options stops being abstract. In Credit & Debt, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Money decisions compound: a small fee today can cost thousands over a decade. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("consolidation-s5", "6.5 Consolidation Options — putting it together", ["Most mistakes in consolidation options happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","Your paycheck is a system—inputs, fixed outputs, and what you control. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why consolidation options matters in modern credit & debt work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around consolidation options","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Consolidation Options connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master consolidation options reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("collections", 7, "Collections and Recovery", [
    section("collections-s1", "7.1 Collections and Recovery — foundations and vocabulary", ["foundations and vocabulary is where collections and recovery stops being abstract. In Credit & Debt, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Your paycheck is a system—inputs, fixed outputs, and what you control. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("collections-s2", "7.2 Collections and Recovery — how practitioners think", ["Most mistakes in collections and recovery happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Money decisions compound: a small fee today can cost thousands over a decade. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("collections-s3", "7.3 Collections and Recovery — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Your paycheck is a system—inputs, fixed outputs, and what you control. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("collections-s4", "7.4 Collections and Recovery — common failures and fixes", ["common failures and fixes is where collections and recovery stops being abstract. In Credit & Debt, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Money decisions compound: a small fee today can cost thousands over a decade. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("collections-s5", "7.5 Collections and Recovery — putting it together", ["Most mistakes in collections and recovery happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","Your paycheck is a system—inputs, fixed outputs, and what you control. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why collections and recovery matters in modern credit & debt work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around collections and recovery","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Collections and Recovery connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master collections and recovery reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("credit-rebuild", 8, "Rebuilding Credit", [
    section("credit-rebuild-s1", "8.1 Rebuilding Credit — foundations and vocabulary", ["foundations and vocabulary is where rebuilding credit stops being abstract. In Credit & Debt, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Your paycheck is a system—inputs, fixed outputs, and what you control. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("credit-rebuild-s2", "8.2 Rebuilding Credit — how practitioners think", ["Most mistakes in rebuilding credit happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Money decisions compound: a small fee today can cost thousands over a decade. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("credit-rebuild-s3", "8.3 Rebuilding Credit — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Your paycheck is a system—inputs, fixed outputs, and what you control. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("credit-rebuild-s4", "8.4 Rebuilding Credit — common failures and fixes", ["common failures and fixes is where rebuilding credit stops being abstract. In Credit & Debt, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Money decisions compound: a small fee today can cost thousands over a decade. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("credit-rebuild-s5", "8.5 Rebuilding Credit — putting it together", ["Most mistakes in rebuilding credit happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","Your paycheck is a system—inputs, fixed outputs, and what you control. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why rebuilding credit matters in modern credit & debt work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around rebuilding credit","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Rebuilding Credit connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master rebuilding credit reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  })
];
