import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const CRED_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Credit & Debt",
  subtitle: "ForgEd path course — Credit & Debt",
  paragraphs: [
    "Credit & Debt is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Each chapter includes five sections and section quizzes. Pass chapter quizzes, the course review, and final exam to mark the course complete.",
    "Content is practical workforce education — not licensure, legal, or financial advice.",
  ],
};

export const CRED_TEXTBOOK: TextbookChapter[] = [
  chapter("credit-scores", 1, "Credit Scores Explained", [
      section("credit-scores-s1", "1.1 Credit Scores Explained — applied practice (1)", ["1.1 Credit Scores Explained — applied practice (1) connects Credit Scores Explained to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("credit-scores-s2", "1.2 Credit Scores Explained — applied practice (2)", ["1.2 Credit Scores Explained — applied practice (2) connects Credit Scores Explained to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("credit-scores-s3", "1.3 Credit Scores Explained — applied practice (3)", ["1.3 Credit Scores Explained — applied practice (3) connects Credit Scores Explained to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("credit-scores-s4", "1.4 Credit Scores Explained — applied practice (4)", ["1.4 Credit Scores Explained — applied practice (4) connects Credit Scores Explained to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("credit-scores-s5", "1.5 Credit Scores Explained — applied practice (5)", ["1.5 Credit Scores Explained — applied practice (5) connects Credit Scores Explained to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("reports", 2, "Credit Reports", [
      section("reports-s1", "2.1 Credit Reports — applied practice (1)", ["2.1 Credit Reports — applied practice (1) connects Credit Reports to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("reports-s2", "2.2 Credit Reports — applied practice (2)", ["2.2 Credit Reports — applied practice (2) connects Credit Reports to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("reports-s3", "2.3 Credit Reports — applied practice (3)", ["2.3 Credit Reports — applied practice (3) connects Credit Reports to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("reports-s4", "2.4 Credit Reports — applied practice (4)", ["2.4 Credit Reports — applied practice (4) connects Credit Reports to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("reports-s5", "2.5 Credit Reports — applied practice (5)", ["2.5 Credit Reports — applied practice (5) connects Credit Reports to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("utilization", 3, "Utilization", [
      section("utilization-s1", "3.1 Utilization — applied practice (1)", ["3.1 Utilization — applied practice (1) connects Utilization to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("utilization-s2", "3.2 Utilization — applied practice (2)", ["3.2 Utilization — applied practice (2) connects Utilization to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("utilization-s3", "3.3 Utilization — applied practice (3)", ["3.3 Utilization — applied practice (3) connects Utilization to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("utilization-s4", "3.4 Utilization — applied practice (4)", ["3.4 Utilization — applied practice (4) connects Utilization to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("utilization-s5", "3.5 Utilization — applied practice (5)", ["3.5 Utilization — applied practice (5) connects Utilization to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("debt-types", 4, "Types of Debt", [
      section("debt-types-s1", "4.1 Types of Debt — applied practice (1)", ["4.1 Types of Debt — applied practice (1) connects Types of Debt to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("debt-types-s2", "4.2 Types of Debt — applied practice (2)", ["4.2 Types of Debt — applied practice (2) connects Types of Debt to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("debt-types-s3", "4.3 Types of Debt — applied practice (3)", ["4.3 Types of Debt — applied practice (3) connects Types of Debt to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("debt-types-s4", "4.4 Types of Debt — applied practice (4)", ["4.4 Types of Debt — applied practice (4) connects Types of Debt to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("debt-types-s5", "4.5 Types of Debt — applied practice (5)", ["4.5 Types of Debt — applied practice (5) connects Types of Debt to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("payoff-strategies", 5, "Payoff Strategies", [
      section("payoff-strategies-s1", "5.1 Payoff Strategies — applied practice (1)", ["5.1 Payoff Strategies — applied practice (1) connects Payoff Strategies to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("payoff-strategies-s2", "5.2 Payoff Strategies — applied practice (2)", ["5.2 Payoff Strategies — applied practice (2) connects Payoff Strategies to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("payoff-strategies-s3", "5.3 Payoff Strategies — applied practice (3)", ["5.3 Payoff Strategies — applied practice (3) connects Payoff Strategies to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("payoff-strategies-s4", "5.4 Payoff Strategies — applied practice (4)", ["5.4 Payoff Strategies — applied practice (4) connects Payoff Strategies to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("payoff-strategies-s5", "5.5 Payoff Strategies — applied practice (5)", ["5.5 Payoff Strategies — applied practice (5) connects Payoff Strategies to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("consolidation", 6, "Consolidation Options", [
      section("consolidation-s1", "6.1 Consolidation Options — applied practice (1)", ["6.1 Consolidation Options — applied practice (1) connects Consolidation Options to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("consolidation-s2", "6.2 Consolidation Options — applied practice (2)", ["6.2 Consolidation Options — applied practice (2) connects Consolidation Options to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("consolidation-s3", "6.3 Consolidation Options — applied practice (3)", ["6.3 Consolidation Options — applied practice (3) connects Consolidation Options to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("consolidation-s4", "6.4 Consolidation Options — applied practice (4)", ["6.4 Consolidation Options — applied practice (4) connects Consolidation Options to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("consolidation-s5", "6.5 Consolidation Options — applied practice (5)", ["6.5 Consolidation Options — applied practice (5) connects Consolidation Options to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("collections", 7, "Collections and Recovery", [
      section("collections-s1", "7.1 Collections and Recovery — applied practice (1)", ["7.1 Collections and Recovery — applied practice (1) connects Collections and Recovery to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("collections-s2", "7.2 Collections and Recovery — applied practice (2)", ["7.2 Collections and Recovery — applied practice (2) connects Collections and Recovery to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("collections-s3", "7.3 Collections and Recovery — applied practice (3)", ["7.3 Collections and Recovery — applied practice (3) connects Collections and Recovery to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("collections-s4", "7.4 Collections and Recovery — applied practice (4)", ["7.4 Collections and Recovery — applied practice (4) connects Collections and Recovery to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("collections-s5", "7.5 Collections and Recovery — applied practice (5)", ["7.5 Collections and Recovery — applied practice (5) connects Collections and Recovery to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("credit-rebuild", 8, "Rebuilding Credit", [
      section("credit-rebuild-s1", "8.1 Rebuilding Credit — applied practice (1)", ["8.1 Rebuilding Credit — applied practice (1) connects Rebuilding Credit to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("credit-rebuild-s2", "8.2 Rebuilding Credit — applied practice (2)", ["8.2 Rebuilding Credit — applied practice (2) connects Rebuilding Credit to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("credit-rebuild-s3", "8.3 Rebuilding Credit — applied practice (3)", ["8.3 Rebuilding Credit — applied practice (3) connects Rebuilding Credit to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("credit-rebuild-s4", "8.4 Rebuilding Credit — applied practice (4)", ["8.4 Rebuilding Credit — applied practice (4) connects Rebuilding Credit to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("credit-rebuild-s5", "8.5 Rebuilding Credit — applied practice (5)", ["8.5 Rebuilding Credit — applied practice (5) connects Rebuilding Credit to real workforce outcomes in Credit & Debt. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ])
];
