import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const CRM_TEXTBOOK_INTRO: TextbookIntro = {
  title: "CRM Fundamentals",
  subtitle: "ForgEd path course — CRM Fundamentals",
  paragraphs: [
    "CRM Fundamentals is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Each chapter includes five sections and section quizzes. Pass chapter quizzes, the course review, and final exam to mark the course complete.",
    "Content is practical workforce education — not licensure, legal, or financial advice.",
  ],
};

export const CRM_TEXTBOOK: TextbookChapter[] = [
  chapter("crm-purpose", 1, "Why CRMs Matter", [
      section("crm-purpose-s1", "1.1 Why CRMs Matter — applied practice (1)", ["1.1 Why CRMs Matter — applied practice (1) connects Why CRMs Matter to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("crm-purpose-s2", "1.2 Why CRMs Matter — applied practice (2)", ["1.2 Why CRMs Matter — applied practice (2) connects Why CRMs Matter to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("crm-purpose-s3", "1.3 Why CRMs Matter — applied practice (3)", ["1.3 Why CRMs Matter — applied practice (3) connects Why CRMs Matter to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("crm-purpose-s4", "1.4 Why CRMs Matter — applied practice (4)", ["1.4 Why CRMs Matter — applied practice (4) connects Why CRMs Matter to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("crm-purpose-s5", "1.5 Why CRMs Matter — applied practice (5)", ["1.5 Why CRMs Matter — applied practice (5) connects Why CRMs Matter to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("data-model", 2, "CRM Data Model", [
      section("data-model-s1", "2.1 CRM Data Model — applied practice (1)", ["2.1 CRM Data Model — applied practice (1) connects CRM Data Model to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("data-model-s2", "2.2 CRM Data Model — applied practice (2)", ["2.2 CRM Data Model — applied practice (2) connects CRM Data Model to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("data-model-s3", "2.3 CRM Data Model — applied practice (3)", ["2.3 CRM Data Model — applied practice (3) connects CRM Data Model to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("data-model-s4", "2.4 CRM Data Model — applied practice (4)", ["2.4 CRM Data Model — applied practice (4) connects CRM Data Model to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("data-model-s5", "2.5 CRM Data Model — applied practice (5)", ["2.5 CRM Data Model — applied practice (5) connects CRM Data Model to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("stages", 3, "Pipeline Stages", [
      section("stages-s1", "3.1 Pipeline Stages — applied practice (1)", ["3.1 Pipeline Stages — applied practice (1) connects Pipeline Stages to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("stages-s2", "3.2 Pipeline Stages — applied practice (2)", ["3.2 Pipeline Stages — applied practice (2) connects Pipeline Stages to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("stages-s3", "3.3 Pipeline Stages — applied practice (3)", ["3.3 Pipeline Stages — applied practice (3) connects Pipeline Stages to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("stages-s4", "3.4 Pipeline Stages — applied practice (4)", ["3.4 Pipeline Stages — applied practice (4) connects Pipeline Stages to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("stages-s5", "3.5 Pipeline Stages — applied practice (5)", ["3.5 Pipeline Stages — applied practice (5) connects Pipeline Stages to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("activities", 4, "Logging Activities", [
      section("activities-s1", "4.1 Logging Activities — applied practice (1)", ["4.1 Logging Activities — applied practice (1) connects Logging Activities to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("activities-s2", "4.2 Logging Activities — applied practice (2)", ["4.2 Logging Activities — applied practice (2) connects Logging Activities to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("activities-s3", "4.3 Logging Activities — applied practice (3)", ["4.3 Logging Activities — applied practice (3) connects Logging Activities to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("activities-s4", "4.4 Logging Activities — applied practice (4)", ["4.4 Logging Activities — applied practice (4) connects Logging Activities to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("activities-s5", "4.5 Logging Activities — applied practice (5)", ["4.5 Logging Activities — applied practice (5) connects Logging Activities to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("reports-crm", 5, "CRM Reporting", [
      section("reports-crm-s1", "5.1 CRM Reporting — applied practice (1)", ["5.1 CRM Reporting — applied practice (1) connects CRM Reporting to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("reports-crm-s2", "5.2 CRM Reporting — applied practice (2)", ["5.2 CRM Reporting — applied practice (2) connects CRM Reporting to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("reports-crm-s3", "5.3 CRM Reporting — applied practice (3)", ["5.3 CRM Reporting — applied practice (3) connects CRM Reporting to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("reports-crm-s4", "5.4 CRM Reporting — applied practice (4)", ["5.4 CRM Reporting — applied practice (4) connects CRM Reporting to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("reports-crm-s5", "5.5 CRM Reporting — applied practice (5)", ["5.5 CRM Reporting — applied practice (5) connects CRM Reporting to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("hygiene", 6, "Data Hygiene", [
      section("hygiene-s1", "6.1 Data Hygiene — applied practice (1)", ["6.1 Data Hygiene — applied practice (1) connects Data Hygiene to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("hygiene-s2", "6.2 Data Hygiene — applied practice (2)", ["6.2 Data Hygiene — applied practice (2) connects Data Hygiene to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("hygiene-s3", "6.3 Data Hygiene — applied practice (3)", ["6.3 Data Hygiene — applied practice (3) connects Data Hygiene to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("hygiene-s4", "6.4 Data Hygiene — applied practice (4)", ["6.4 Data Hygiene — applied practice (4) connects Data Hygiene to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("hygiene-s5", "6.5 Data Hygiene — applied practice (5)", ["6.5 Data Hygiene — applied practice (5) connects Data Hygiene to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("automation-crm", 7, "CRM Automation", [
      section("automation-crm-s1", "7.1 CRM Automation — applied practice (1)", ["7.1 CRM Automation — applied practice (1) connects CRM Automation to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("automation-crm-s2", "7.2 CRM Automation — applied practice (2)", ["7.2 CRM Automation — applied practice (2) connects CRM Automation to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("automation-crm-s3", "7.3 CRM Automation — applied practice (3)", ["7.3 CRM Automation — applied practice (3) connects CRM Automation to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("automation-crm-s4", "7.4 CRM Automation — applied practice (4)", ["7.4 CRM Automation — applied practice (4) connects CRM Automation to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("automation-crm-s5", "7.5 CRM Automation — applied practice (5)", ["7.5 CRM Automation — applied practice (5) connects CRM Automation to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("crm-adoption", 8, "Team Adoption", [
      section("crm-adoption-s1", "8.1 Team Adoption — applied practice (1)", ["8.1 Team Adoption — applied practice (1) connects Team Adoption to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("crm-adoption-s2", "8.2 Team Adoption — applied practice (2)", ["8.2 Team Adoption — applied practice (2) connects Team Adoption to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("crm-adoption-s3", "8.3 Team Adoption — applied practice (3)", ["8.3 Team Adoption — applied practice (3) connects Team Adoption to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("crm-adoption-s4", "8.4 Team Adoption — applied practice (4)", ["8.4 Team Adoption — applied practice (4) connects Team Adoption to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("crm-adoption-s5", "8.5 Team Adoption — applied practice (5)", ["8.5 Team Adoption — applied practice (5) connects Team Adoption to real workforce outcomes in CRM Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ])
];
