import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const CUSTPSY_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Customer Psychology",
  subtitle: "ForgEd path course — Customer Psychology",
  paragraphs: [
    "Customer Psychology is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Each chapter includes five sections and section quizzes. Pass chapter quizzes, the course review, and final exam to mark the course complete.",
    "Content is practical workforce education — not licensure, legal, or financial advice.",
  ],
};

export const CUSTPSY_TEXTBOOK: TextbookChapter[] = [
  chapter("buyer-journey", 1, "Buyer Journey Stages", [
      section("buyer-journey-s1", "1.1 Buyer Journey Stages — applied practice (1)", ["1.1 Buyer Journey Stages — applied practice (1) connects Buyer Journey Stages to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("buyer-journey-s2", "1.2 Buyer Journey Stages — applied practice (2)", ["1.2 Buyer Journey Stages — applied practice (2) connects Buyer Journey Stages to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("buyer-journey-s3", "1.3 Buyer Journey Stages — applied practice (3)", ["1.3 Buyer Journey Stages — applied practice (3) connects Buyer Journey Stages to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("buyer-journey-s4", "1.4 Buyer Journey Stages — applied practice (4)", ["1.4 Buyer Journey Stages — applied practice (4) connects Buyer Journey Stages to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("buyer-journey-s5", "1.5 Buyer Journey Stages — applied practice (5)", ["1.5 Buyer Journey Stages — applied practice (5) connects Buyer Journey Stages to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("motivation", 2, "Motivation and Trust", [
      section("motivation-s1", "2.1 Motivation and Trust — applied practice (1)", ["2.1 Motivation and Trust — applied practice (1) connects Motivation and Trust to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("motivation-s2", "2.2 Motivation and Trust — applied practice (2)", ["2.2 Motivation and Trust — applied practice (2) connects Motivation and Trust to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("motivation-s3", "2.3 Motivation and Trust — applied practice (3)", ["2.3 Motivation and Trust — applied practice (3) connects Motivation and Trust to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("motivation-s4", "2.4 Motivation and Trust — applied practice (4)", ["2.4 Motivation and Trust — applied practice (4) connects Motivation and Trust to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("motivation-s5", "2.5 Motivation and Trust — applied practice (5)", ["2.5 Motivation and Trust — applied practice (5) connects Motivation and Trust to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("friction", 3, "Decision Friction", [
      section("friction-s1", "3.1 Decision Friction — applied practice (1)", ["3.1 Decision Friction — applied practice (1) connects Decision Friction to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("friction-s2", "3.2 Decision Friction — applied practice (2)", ["3.2 Decision Friction — applied practice (2) connects Decision Friction to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("friction-s3", "3.3 Decision Friction — applied practice (3)", ["3.3 Decision Friction — applied practice (3) connects Decision Friction to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("friction-s4", "3.4 Decision Friction — applied practice (4)", ["3.4 Decision Friction — applied practice (4) connects Decision Friction to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("friction-s5", "3.5 Decision Friction — applied practice (5)", ["3.5 Decision Friction — applied practice (5) connects Decision Friction to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("social-proof", 4, "Social Proof", [
      section("social-proof-s1", "4.1 Social Proof — applied practice (1)", ["4.1 Social Proof — applied practice (1) connects Social Proof to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("social-proof-s2", "4.2 Social Proof — applied practice (2)", ["4.2 Social Proof — applied practice (2) connects Social Proof to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("social-proof-s3", "4.3 Social Proof — applied practice (3)", ["4.3 Social Proof — applied practice (3) connects Social Proof to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("social-proof-s4", "4.4 Social Proof — applied practice (4)", ["4.4 Social Proof — applied practice (4) connects Social Proof to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("social-proof-s5", "4.5 Social Proof — applied practice (5)", ["4.5 Social Proof — applied practice (5) connects Social Proof to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("pricing-psych", 5, "Pricing Psychology", [
      section("pricing-psych-s1", "5.1 Pricing Psychology — applied practice (1)", ["5.1 Pricing Psychology — applied practice (1) connects Pricing Psychology to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("pricing-psych-s2", "5.2 Pricing Psychology — applied practice (2)", ["5.2 Pricing Psychology — applied practice (2) connects Pricing Psychology to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("pricing-psych-s3", "5.3 Pricing Psychology — applied practice (3)", ["5.3 Pricing Psychology — applied practice (3) connects Pricing Psychology to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("pricing-psych-s4", "5.4 Pricing Psychology — applied practice (4)", ["5.4 Pricing Psychology — applied practice (4) connects Pricing Psychology to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("pricing-psych-s5", "5.5 Pricing Psychology — applied practice (5)", ["5.5 Pricing Psychology — applied practice (5) connects Pricing Psychology to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("objections-psych", 6, "Psychology of Objections", [
      section("objections-psych-s1", "6.1 Psychology of Objections — applied practice (1)", ["6.1 Psychology of Objections — applied practice (1) connects Psychology of Objections to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("objections-psych-s2", "6.2 Psychology of Objections — applied practice (2)", ["6.2 Psychology of Objections — applied practice (2) connects Psychology of Objections to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("objections-psych-s3", "6.3 Psychology of Objections — applied practice (3)", ["6.3 Psychology of Objections — applied practice (3) connects Psychology of Objections to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("objections-psych-s4", "6.4 Psychology of Objections — applied practice (4)", ["6.4 Psychology of Objections — applied practice (4) connects Psychology of Objections to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("objections-psych-s5", "6.5 Psychology of Objections — applied practice (5)", ["6.5 Psychology of Objections — applied practice (5) connects Psychology of Objections to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("loyalty", 7, "Loyalty and Retention", [
      section("loyalty-s1", "7.1 Loyalty and Retention — applied practice (1)", ["7.1 Loyalty and Retention — applied practice (1) connects Loyalty and Retention to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("loyalty-s2", "7.2 Loyalty and Retention — applied practice (2)", ["7.2 Loyalty and Retention — applied practice (2) connects Loyalty and Retention to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("loyalty-s3", "7.3 Loyalty and Retention — applied practice (3)", ["7.3 Loyalty and Retention — applied practice (3) connects Loyalty and Retention to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("loyalty-s4", "7.4 Loyalty and Retention — applied practice (4)", ["7.4 Loyalty and Retention — applied practice (4) connects Loyalty and Retention to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("loyalty-s5", "7.5 Loyalty and Retention — applied practice (5)", ["7.5 Loyalty and Retention — applied practice (5) connects Loyalty and Retention to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("personas", 8, "Buyer Personas", [
      section("personas-s1", "8.1 Buyer Personas — applied practice (1)", ["8.1 Buyer Personas — applied practice (1) connects Buyer Personas to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("personas-s2", "8.2 Buyer Personas — applied practice (2)", ["8.2 Buyer Personas — applied practice (2) connects Buyer Personas to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("personas-s3", "8.3 Buyer Personas — applied practice (3)", ["8.3 Buyer Personas — applied practice (3) connects Buyer Personas to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("personas-s4", "8.4 Buyer Personas — applied practice (4)", ["8.4 Buyer Personas — applied practice (4) connects Buyer Personas to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("personas-s5", "8.5 Buyer Personas — applied practice (5)", ["8.5 Buyer Personas — applied practice (5) connects Buyer Personas to real workforce outcomes in Customer Psychology. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ])
];
