import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const CAC_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Customer Acquisition",
  subtitle: "ForgEd path course — Customer Acquisition",
  paragraphs: [
    "Customer Acquisition is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Each chapter includes five sections and section quizzes. Pass chapter quizzes, the course review, and final exam to mark the course complete.",
    "Content is practical workforce education — not licensure, legal, or financial advice.",
  ],
};

export const CAC_TEXTBOOK: TextbookChapter[] = [
  chapter("channels-acq", 1, "Acquisition Channels", [
      section("channels-acq-s1", "1.1 Acquisition Channels — applied practice (1)", ["1.1 Acquisition Channels — applied practice (1) connects Acquisition Channels to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("channels-acq-s2", "1.2 Acquisition Channels — applied practice (2)", ["1.2 Acquisition Channels — applied practice (2) connects Acquisition Channels to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("channels-acq-s3", "1.3 Acquisition Channels — applied practice (3)", ["1.3 Acquisition Channels — applied practice (3) connects Acquisition Channels to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("channels-acq-s4", "1.4 Acquisition Channels — applied practice (4)", ["1.4 Acquisition Channels — applied practice (4) connects Acquisition Channels to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("channels-acq-s5", "1.5 Acquisition Channels — applied practice (5)", ["1.5 Acquisition Channels — applied practice (5) connects Acquisition Channels to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("cac-ltv", 2, "CAC and LTV", [
      section("cac-ltv-s1", "2.1 CAC and LTV — applied practice (1)", ["2.1 CAC and LTV — applied practice (1) connects CAC and LTV to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("cac-ltv-s2", "2.2 CAC and LTV — applied practice (2)", ["2.2 CAC and LTV — applied practice (2) connects CAC and LTV to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("cac-ltv-s3", "2.3 CAC and LTV — applied practice (3)", ["2.3 CAC and LTV — applied practice (3) connects CAC and LTV to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("cac-ltv-s4", "2.4 CAC and LTV — applied practice (4)", ["2.4 CAC and LTV — applied practice (4) connects CAC and LTV to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("cac-ltv-s5", "2.5 CAC and LTV — applied practice (5)", ["2.5 CAC and LTV — applied practice (5) connects CAC and LTV to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("experiments-growth", 3, "Growth Experiments", [
      section("experiments-growth-s1", "3.1 Growth Experiments — applied practice (1)", ["3.1 Growth Experiments — applied practice (1) connects Growth Experiments to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("experiments-growth-s2", "3.2 Growth Experiments — applied practice (2)", ["3.2 Growth Experiments — applied practice (2) connects Growth Experiments to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("experiments-growth-s3", "3.3 Growth Experiments — applied practice (3)", ["3.3 Growth Experiments — applied practice (3) connects Growth Experiments to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("experiments-growth-s4", "3.4 Growth Experiments — applied practice (4)", ["3.4 Growth Experiments — applied practice (4) connects Growth Experiments to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("experiments-growth-s5", "3.5 Growth Experiments — applied practice (5)", ["3.5 Growth Experiments — applied practice (5) connects Growth Experiments to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("content-acq", 4, "Content Marketing", [
      section("content-acq-s1", "4.1 Content Marketing — applied practice (1)", ["4.1 Content Marketing — applied practice (1) connects Content Marketing to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("content-acq-s2", "4.2 Content Marketing — applied practice (2)", ["4.2 Content Marketing — applied practice (2) connects Content Marketing to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("content-acq-s3", "4.3 Content Marketing — applied practice (3)", ["4.3 Content Marketing — applied practice (3) connects Content Marketing to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("content-acq-s4", "4.4 Content Marketing — applied practice (4)", ["4.4 Content Marketing — applied practice (4) connects Content Marketing to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("content-acq-s5", "4.5 Content Marketing — applied practice (5)", ["4.5 Content Marketing — applied practice (5) connects Content Marketing to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("paid-acq", 5, "Paid Acquisition Intro", [
      section("paid-acq-s1", "5.1 Paid Acquisition Intro — applied practice (1)", ["5.1 Paid Acquisition Intro — applied practice (1) connects Paid Acquisition Intro to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("paid-acq-s2", "5.2 Paid Acquisition Intro — applied practice (2)", ["5.2 Paid Acquisition Intro — applied practice (2) connects Paid Acquisition Intro to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("paid-acq-s3", "5.3 Paid Acquisition Intro — applied practice (3)", ["5.3 Paid Acquisition Intro — applied practice (3) connects Paid Acquisition Intro to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("paid-acq-s4", "5.4 Paid Acquisition Intro — applied practice (4)", ["5.4 Paid Acquisition Intro — applied practice (4) connects Paid Acquisition Intro to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("paid-acq-s5", "5.5 Paid Acquisition Intro — applied practice (5)", ["5.5 Paid Acquisition Intro — applied practice (5) connects Paid Acquisition Intro to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("referrals", 6, "Referral Programs", [
      section("referrals-s1", "6.1 Referral Programs — applied practice (1)", ["6.1 Referral Programs — applied practice (1) connects Referral Programs to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("referrals-s2", "6.2 Referral Programs — applied practice (2)", ["6.2 Referral Programs — applied practice (2) connects Referral Programs to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("referrals-s3", "6.3 Referral Programs — applied practice (3)", ["6.3 Referral Programs — applied practice (3) connects Referral Programs to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("referrals-s4", "6.4 Referral Programs — applied practice (4)", ["6.4 Referral Programs — applied practice (4) connects Referral Programs to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("referrals-s5", "6.5 Referral Programs — applied practice (5)", ["6.5 Referral Programs — applied practice (5) connects Referral Programs to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("partnerships", 7, "Partnerships", [
      section("partnerships-s1", "7.1 Partnerships — applied practice (1)", ["7.1 Partnerships — applied practice (1) connects Partnerships to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("partnerships-s2", "7.2 Partnerships — applied practice (2)", ["7.2 Partnerships — applied practice (2) connects Partnerships to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("partnerships-s3", "7.3 Partnerships — applied practice (3)", ["7.3 Partnerships — applied practice (3) connects Partnerships to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("partnerships-s4", "7.4 Partnerships — applied practice (4)", ["7.4 Partnerships — applied practice (4) connects Partnerships to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("partnerships-s5", "7.5 Partnerships — applied practice (5)", ["7.5 Partnerships — applied practice (5) connects Partnerships to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("measure-acq", 8, "Measuring Acquisition", [
      section("measure-acq-s1", "8.1 Measuring Acquisition — applied practice (1)", ["8.1 Measuring Acquisition — applied practice (1) connects Measuring Acquisition to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("measure-acq-s2", "8.2 Measuring Acquisition — applied practice (2)", ["8.2 Measuring Acquisition — applied practice (2) connects Measuring Acquisition to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("measure-acq-s3", "8.3 Measuring Acquisition — applied practice (3)", ["8.3 Measuring Acquisition — applied practice (3) connects Measuring Acquisition to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("measure-acq-s4", "8.4 Measuring Acquisition — applied practice (4)", ["8.4 Measuring Acquisition — applied practice (4) connects Measuring Acquisition to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("measure-acq-s5", "8.5 Measuring Acquisition — applied practice (5)", ["8.5 Measuring Acquisition — applied practice (5) connects Measuring Acquisition to real workforce outcomes in Customer Acquisition. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ])
];
