import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const DIFF_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Difficult Customer Scenarios",
  subtitle: "Workforce training — Difficult Customer Scenarios",
  paragraphs: [
    "Difficult Customer Scenarios is built for professionals who want usable skill—not trivia. Each chapter moves from why the topic matters, through structured explanation, to quizzes that check judgment rather than memorization.",
    "Difficult Customer Scenarios is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Content is practical workforce education. It does not replace licensure, legal, medical, or employer-specific policy. When your organization has a rule that conflicts with a general lesson, follow your organization's rule and treat this course as context.",
  ],
};

export const DIFF_TEXTBOOK: TextbookChapter[] = [
  chapter("de-escalation", 1, "De-escalation", [
    section("de-escalation-s1", "1.1 De-escalation — foundations and vocabulary", ["foundations and vocabulary is where de-escalation stops being abstract. In Difficult Customer Scenarios, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("de-escalation-s2", "1.2 De-escalation — how practitioners think", ["Most mistakes in de-escalation happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("de-escalation-s3", "1.3 De-escalation — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("de-escalation-s4", "1.4 De-escalation — common failures and fixes", ["common failures and fixes is where de-escalation stops being abstract. In Difficult Customer Scenarios, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("de-escalation-s5", "1.5 De-escalation — putting it together", ["Most mistakes in de-escalation happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why de-escalation matters in modern difficult customer scenarios work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around de-escalation","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "De-escalation connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master de-escalation reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("delays", 2, "Handling Delays", [
    section("delays-s1", "2.1 Handling Delays — foundations and vocabulary", ["foundations and vocabulary is where handling delays stops being abstract. In Difficult Customer Scenarios, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("delays-s2", "2.2 Handling Delays — how practitioners think", ["Most mistakes in handling delays happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("delays-s3", "2.3 Handling Delays — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("delays-s4", "2.4 Handling Delays — common failures and fixes", ["common failures and fixes is where handling delays stops being abstract. In Difficult Customer Scenarios, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("delays-s5", "2.5 Handling Delays — putting it together", ["Most mistakes in handling delays happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why handling delays matters in modern difficult customer scenarios work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around handling delays","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Handling Delays connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master handling delays reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("price-disputes", 3, "Price Disputes", [
    section("price-disputes-s1", "3.1 Price Disputes — foundations and vocabulary", ["foundations and vocabulary is where price disputes stops being abstract. In Difficult Customer Scenarios, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("price-disputes-s2", "3.2 Price Disputes — how practitioners think", ["Most mistakes in price disputes happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("price-disputes-s3", "3.3 Price Disputes — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("price-disputes-s4", "3.4 Price Disputes — common failures and fixes", ["common failures and fixes is where price disputes stops being abstract. In Difficult Customer Scenarios, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("price-disputes-s5", "3.5 Price Disputes — putting it together", ["Most mistakes in price disputes happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why price disputes matters in modern difficult customer scenarios work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around price disputes","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Price Disputes connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master price disputes reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("comebacks-diff", 4, "Comeback Conversations", [
    section("comebacks-diff-s1", "4.1 Comeback Conversations — foundations and vocabulary", ["foundations and vocabulary is where comeback conversations stops being abstract. In Difficult Customer Scenarios, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("comebacks-diff-s2", "4.2 Comeback Conversations — how practitioners think", ["Most mistakes in comeback conversations happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("comebacks-diff-s3", "4.3 Comeback Conversations — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("comebacks-diff-s4", "4.4 Comeback Conversations — common failures and fixes", ["common failures and fixes is where comeback conversations stops being abstract. In Difficult Customer Scenarios, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("comebacks-diff-s5", "4.5 Comeback Conversations — putting it together", ["Most mistakes in comeback conversations happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why comeback conversations matters in modern difficult customer scenarios work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around comeback conversations","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Comeback Conversations connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master comeback conversations reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("angry-customers", 5, "Angry Customers", [
    section("angry-customers-s1", "5.1 Angry Customers — foundations and vocabulary", ["foundations and vocabulary is where angry customers stops being abstract. In Difficult Customer Scenarios, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("angry-customers-s2", "5.2 Angry Customers — how practitioners think", ["Most mistakes in angry customers happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("angry-customers-s3", "5.3 Angry Customers — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("angry-customers-s4", "5.4 Angry Customers — common failures and fixes", ["common failures and fixes is where angry customers stops being abstract. In Difficult Customer Scenarios, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("angry-customers-s5", "5.5 Angry Customers — putting it together", ["Most mistakes in angry customers happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why angry customers matters in modern difficult customer scenarios work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around angry customers","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Angry Customers connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master angry customers reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("apologies", 6, "Effective Apologies", [
    section("apologies-s1", "6.1 Effective Apologies — foundations and vocabulary", ["foundations and vocabulary is where effective apologies stops being abstract. In Difficult Customer Scenarios, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("apologies-s2", "6.2 Effective Apologies — how practitioners think", ["Most mistakes in effective apologies happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("apologies-s3", "6.3 Effective Apologies — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("apologies-s4", "6.4 Effective Apologies — common failures and fixes", ["common failures and fixes is where effective apologies stops being abstract. In Difficult Customer Scenarios, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("apologies-s5", "6.5 Effective Apologies — putting it together", ["Most mistakes in effective apologies happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why effective apologies matters in modern difficult customer scenarios work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around effective apologies","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Effective Apologies connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master effective apologies reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("manager-escalation", 7, "Manager Escalation", [
    section("manager-escalation-s1", "7.1 Manager Escalation — foundations and vocabulary", ["foundations and vocabulary is where manager escalation stops being abstract. In Difficult Customer Scenarios, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("manager-escalation-s2", "7.2 Manager Escalation — how practitioners think", ["Most mistakes in manager escalation happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("manager-escalation-s3", "7.3 Manager Escalation — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("manager-escalation-s4", "7.4 Manager Escalation — common failures and fixes", ["common failures and fixes is where manager escalation stops being abstract. In Difficult Customer Scenarios, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("manager-escalation-s5", "7.5 Manager Escalation — putting it together", ["Most mistakes in manager escalation happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why manager escalation matters in modern difficult customer scenarios work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around manager escalation","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Manager Escalation connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master manager escalation reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("learning-scenarios", 8, "Learning from Scenarios", [
    section("learning-scenarios-s1", "8.1 Learning from Scenarios — foundations and vocabulary", ["foundations and vocabulary is where learning from scenarios stops being abstract. In Difficult Customer Scenarios, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("learning-scenarios-s2", "8.2 Learning from Scenarios — how practitioners think", ["Most mistakes in learning from scenarios happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("learning-scenarios-s3", "8.3 Learning from Scenarios — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("learning-scenarios-s4", "8.4 Learning from Scenarios — common failures and fixes", ["common failures and fixes is where learning from scenarios stops being abstract. In Difficult Customer Scenarios, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("learning-scenarios-s5", "8.5 Learning from Scenarios — putting it together", ["Most mistakes in learning from scenarios happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why learning from scenarios matters in modern difficult customer scenarios work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around learning from scenarios","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Learning from Scenarios connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master learning from scenarios reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  })
];
