import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const DIG_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Digital Presence",
  subtitle: "ForgEd path course — Digital Presence",
  paragraphs: [
    "Digital Presence is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Each chapter includes five sections and section quizzes. Pass chapter quizzes, the course review, and final exam to mark the course complete.",
    "Content is practical workforce education — not licensure, legal, or financial advice.",
  ],
};

export const DIG_TEXTBOOK: TextbookChapter[] = [
  chapter("website-basics", 1, "Website Essentials", [
      section("website-basics-s1", "1.1 Website Essentials — applied practice (1)", ["1.1 Website Essentials — applied practice (1) connects Website Essentials to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("website-basics-s2", "1.2 Website Essentials — applied practice (2)", ["1.2 Website Essentials — applied practice (2) connects Website Essentials to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("website-basics-s3", "1.3 Website Essentials — applied practice (3)", ["1.3 Website Essentials — applied practice (3) connects Website Essentials to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("website-basics-s4", "1.4 Website Essentials — applied practice (4)", ["1.4 Website Essentials — applied practice (4) connects Website Essentials to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("website-basics-s5", "1.5 Website Essentials — applied practice (5)", ["1.5 Website Essentials — applied practice (5) connects Website Essentials to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("seo-intro", 2, "SEO Introduction", [
      section("seo-intro-s1", "2.1 SEO Introduction — applied practice (1)", ["2.1 SEO Introduction — applied practice (1) connects SEO Introduction to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("seo-intro-s2", "2.2 SEO Introduction — applied practice (2)", ["2.2 SEO Introduction — applied practice (2) connects SEO Introduction to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("seo-intro-s3", "2.3 SEO Introduction — applied practice (3)", ["2.3 SEO Introduction — applied practice (3) connects SEO Introduction to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("seo-intro-s4", "2.4 SEO Introduction — applied practice (4)", ["2.4 SEO Introduction — applied practice (4) connects SEO Introduction to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("seo-intro-s5", "2.5 SEO Introduction — applied practice (5)", ["2.5 SEO Introduction — applied practice (5) connects SEO Introduction to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("social-proof", 3, "Social Proof Online", [
      section("social-proof-s1", "3.1 Social Proof Online — applied practice (1)", ["3.1 Social Proof Online — applied practice (1) connects Social Proof Online to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("social-proof-s2", "3.2 Social Proof Online — applied practice (2)", ["3.2 Social Proof Online — applied practice (2) connects Social Proof Online to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("social-proof-s3", "3.3 Social Proof Online — applied practice (3)", ["3.3 Social Proof Online — applied practice (3) connects Social Proof Online to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("social-proof-s4", "3.4 Social Proof Online — applied practice (4)", ["3.4 Social Proof Online — applied practice (4) connects Social Proof Online to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("social-proof-s5", "3.5 Social Proof Online — applied practice (5)", ["3.5 Social Proof Online — applied practice (5) connects Social Proof Online to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("content-calendar", 4, "Content Calendar", [
      section("content-calendar-s1", "4.1 Content Calendar — applied practice (1)", ["4.1 Content Calendar — applied practice (1) connects Content Calendar to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("content-calendar-s2", "4.2 Content Calendar — applied practice (2)", ["4.2 Content Calendar — applied practice (2) connects Content Calendar to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("content-calendar-s3", "4.3 Content Calendar — applied practice (3)", ["4.3 Content Calendar — applied practice (3) connects Content Calendar to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("content-calendar-s4", "4.4 Content Calendar — applied practice (4)", ["4.4 Content Calendar — applied practice (4) connects Content Calendar to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("content-calendar-s5", "4.5 Content Calendar — applied practice (5)", ["4.5 Content Calendar — applied practice (5) connects Content Calendar to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("reviews", 5, "Reviews and Reputation", [
      section("reviews-s1", "5.1 Reviews and Reputation — applied practice (1)", ["5.1 Reviews and Reputation — applied practice (1) connects Reviews and Reputation to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("reviews-s2", "5.2 Reviews and Reputation — applied practice (2)", ["5.2 Reviews and Reputation — applied practice (2) connects Reviews and Reputation to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("reviews-s3", "5.3 Reviews and Reputation — applied practice (3)", ["5.3 Reviews and Reputation — applied practice (3) connects Reviews and Reputation to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("reviews-s4", "5.4 Reviews and Reputation — applied practice (4)", ["5.4 Reviews and Reputation — applied practice (4) connects Reviews and Reputation to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("reviews-s5", "5.5 Reviews and Reputation — applied practice (5)", ["5.5 Reviews and Reputation — applied practice (5) connects Reviews and Reputation to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("analytics-web", 6, "Web Analytics Intro", [
      section("analytics-web-s1", "6.1 Web Analytics Intro — applied practice (1)", ["6.1 Web Analytics Intro — applied practice (1) connects Web Analytics Intro to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("analytics-web-s2", "6.2 Web Analytics Intro — applied practice (2)", ["6.2 Web Analytics Intro — applied practice (2) connects Web Analytics Intro to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("analytics-web-s3", "6.3 Web Analytics Intro — applied practice (3)", ["6.3 Web Analytics Intro — applied practice (3) connects Web Analytics Intro to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("analytics-web-s4", "6.4 Web Analytics Intro — applied practice (4)", ["6.4 Web Analytics Intro — applied practice (4) connects Web Analytics Intro to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("analytics-web-s5", "6.5 Web Analytics Intro — applied practice (5)", ["6.5 Web Analytics Intro — applied practice (5) connects Web Analytics Intro to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("local-presence", 7, "Local Presence", [
      section("local-presence-s1", "7.1 Local Presence — applied practice (1)", ["7.1 Local Presence — applied practice (1) connects Local Presence to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("local-presence-s2", "7.2 Local Presence — applied practice (2)", ["7.2 Local Presence — applied practice (2) connects Local Presence to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("local-presence-s3", "7.3 Local Presence — applied practice (3)", ["7.3 Local Presence — applied practice (3) connects Local Presence to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("local-presence-s4", "7.4 Local Presence — applied practice (4)", ["7.4 Local Presence — applied practice (4) connects Local Presence to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("local-presence-s5", "7.5 Local Presence — applied practice (5)", ["7.5 Local Presence — applied practice (5) connects Local Presence to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("brand-digital", 8, "Digital Brand Safety", [
      section("brand-digital-s1", "8.1 Digital Brand Safety — applied practice (1)", ["8.1 Digital Brand Safety — applied practice (1) connects Digital Brand Safety to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("brand-digital-s2", "8.2 Digital Brand Safety — applied practice (2)", ["8.2 Digital Brand Safety — applied practice (2) connects Digital Brand Safety to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("brand-digital-s3", "8.3 Digital Brand Safety — applied practice (3)", ["8.3 Digital Brand Safety — applied practice (3) connects Digital Brand Safety to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("brand-digital-s4", "8.4 Digital Brand Safety — applied practice (4)", ["8.4 Digital Brand Safety — applied practice (4) connects Digital Brand Safety to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("brand-digital-s5", "8.5 Digital Brand Safety — applied practice (5)", ["8.5 Digital Brand Safety — applied practice (5) connects Digital Brand Safety to real workforce outcomes in Digital Presence. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ])
];
