import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const ENTR_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Entrepreneurship Fundamentals",
  subtitle: "ForgEd deep-dive — entrepreneurship fundamentals",
  paragraphs: [
    "This ForgEd digital textbook presents Entrepreneurship Fundamentals at academic survey depth for self-paced study.",
    "Complete each section quiz before advancing. Chapter and course assessments draw from a 150-question bank.",
    "Material is general education, not professional licensure or certification prep by itself.",
  ],
};

export const ENTR_TEXTBOOK: TextbookChapter[] = [
  chapter("entrepreneur-mindset", 1, "Entrepreneurial Mindset", [
      section("entrepreneur-mindset-s1", "1.1 Entrepreneurial Mindset — core concepts (1)", ["1.1 Entrepreneurial Mindset — core concepts (1) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply entrepreneurial mindset with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in entrepreneurial mindset."]),
      section("entrepreneur-mindset-s2", "1.2 Entrepreneurial Mindset — core concepts (2)", ["1.2 Entrepreneurial Mindset — core concepts (2) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply entrepreneurial mindset with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in entrepreneurial mindset."]),
      section("entrepreneur-mindset-s3", "1.3 Entrepreneurial Mindset — core concepts (3)", ["1.3 Entrepreneurial Mindset — core concepts (3) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply entrepreneurial mindset with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in entrepreneurial mindset."]),
      section("entrepreneur-mindset-s4", "1.4 Entrepreneurial Mindset — core concepts (4)", ["1.4 Entrepreneurial Mindset — core concepts (4) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply entrepreneurial mindset with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in entrepreneurial mindset."]),
      section("entrepreneur-mindset-s5", "1.5 Entrepreneurial Mindset — core concepts (5)", ["1.5 Entrepreneurial Mindset — core concepts (5) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply entrepreneurial mindset with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in entrepreneurial mindset."]),
  ]),
  chapter("ideation", 2, "Ideation and Validation", [
      section("ideation-s1", "2.1 Ideation and Validation — core concepts (1)", ["2.1 Ideation and Validation — core concepts (1) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply ideation and validation with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in ideation and validation."]),
      section("ideation-s2", "2.2 Ideation and Validation — core concepts (2)", ["2.2 Ideation and Validation — core concepts (2) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply ideation and validation with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in ideation and validation."]),
      section("ideation-s3", "2.3 Ideation and Validation — core concepts (3)", ["2.3 Ideation and Validation — core concepts (3) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply ideation and validation with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in ideation and validation."]),
      section("ideation-s4", "2.4 Ideation and Validation — core concepts (4)", ["2.4 Ideation and Validation — core concepts (4) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply ideation and validation with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in ideation and validation."]),
      section("ideation-s5", "2.5 Ideation and Validation — core concepts (5)", ["2.5 Ideation and Validation — core concepts (5) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply ideation and validation with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in ideation and validation."]),
  ]),
  chapter("business-models", 3, "Business Models", [
      section("business-models-s1", "3.1 Business Models — core concepts (1)", ["3.1 Business Models — core concepts (1) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply business models with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in business models."]),
      section("business-models-s2", "3.2 Business Models — core concepts (2)", ["3.2 Business Models — core concepts (2) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply business models with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in business models."]),
      section("business-models-s3", "3.3 Business Models — core concepts (3)", ["3.3 Business Models — core concepts (3) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply business models with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in business models."]),
      section("business-models-s4", "3.4 Business Models — core concepts (4)", ["3.4 Business Models — core concepts (4) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply business models with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in business models."]),
      section("business-models-s5", "3.5 Business Models — core concepts (5)", ["3.5 Business Models — core concepts (5) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply business models with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in business models."]),
  ]),
  chapter("marketing-sales", 4, "Marketing and Sales", [
      section("marketing-sales-s1", "4.1 Marketing and Sales — core concepts (1)", ["4.1 Marketing and Sales — core concepts (1) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply marketing and sales with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in marketing and sales."]),
      section("marketing-sales-s2", "4.2 Marketing and Sales — core concepts (2)", ["4.2 Marketing and Sales — core concepts (2) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply marketing and sales with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in marketing and sales."]),
      section("marketing-sales-s3", "4.3 Marketing and Sales — core concepts (3)", ["4.3 Marketing and Sales — core concepts (3) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply marketing and sales with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in marketing and sales."]),
      section("marketing-sales-s4", "4.4 Marketing and Sales — core concepts (4)", ["4.4 Marketing and Sales — core concepts (4) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply marketing and sales with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in marketing and sales."]),
      section("marketing-sales-s5", "4.5 Marketing and Sales — core concepts (5)", ["4.5 Marketing and Sales — core concepts (5) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply marketing and sales with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in marketing and sales."]),
  ]),
  chapter("operations", 5, "Operations and Delivery", [
      section("operations-s1", "5.1 Operations and Delivery — core concepts (1)", ["5.1 Operations and Delivery — core concepts (1) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply operations and delivery with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in operations and delivery."]),
      section("operations-s2", "5.2 Operations and Delivery — core concepts (2)", ["5.2 Operations and Delivery — core concepts (2) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply operations and delivery with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in operations and delivery."]),
      section("operations-s3", "5.3 Operations and Delivery — core concepts (3)", ["5.3 Operations and Delivery — core concepts (3) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply operations and delivery with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in operations and delivery."]),
      section("operations-s4", "5.4 Operations and Delivery — core concepts (4)", ["5.4 Operations and Delivery — core concepts (4) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply operations and delivery with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in operations and delivery."]),
      section("operations-s5", "5.5 Operations and Delivery — core concepts (5)", ["5.5 Operations and Delivery — core concepts (5) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply operations and delivery with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in operations and delivery."]),
  ]),
  chapter("finance-startup", 6, "Startup Finance", [
      section("finance-startup-s1", "6.1 Startup Finance — core concepts (1)", ["6.1 Startup Finance — core concepts (1) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply startup finance with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in startup finance."]),
      section("finance-startup-s2", "6.2 Startup Finance — core concepts (2)", ["6.2 Startup Finance — core concepts (2) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply startup finance with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in startup finance."]),
      section("finance-startup-s3", "6.3 Startup Finance — core concepts (3)", ["6.3 Startup Finance — core concepts (3) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply startup finance with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in startup finance."]),
      section("finance-startup-s4", "6.4 Startup Finance — core concepts (4)", ["6.4 Startup Finance — core concepts (4) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply startup finance with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in startup finance."]),
      section("finance-startup-s5", "6.5 Startup Finance — core concepts (5)", ["6.5 Startup Finance — core concepts (5) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply startup finance with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in startup finance."]),
  ]),
  chapter("legal-basics", 7, "Legal Basics for Founders", [
      section("legal-basics-s1", "7.1 Legal Basics for Founders — core concepts (1)", ["7.1 Legal Basics for Founders — core concepts (1) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply legal basics for founders with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in legal basics for founders."]),
      section("legal-basics-s2", "7.2 Legal Basics for Founders — core concepts (2)", ["7.2 Legal Basics for Founders — core concepts (2) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply legal basics for founders with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in legal basics for founders."]),
      section("legal-basics-s3", "7.3 Legal Basics for Founders — core concepts (3)", ["7.3 Legal Basics for Founders — core concepts (3) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply legal basics for founders with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in legal basics for founders."]),
      section("legal-basics-s4", "7.4 Legal Basics for Founders — core concepts (4)", ["7.4 Legal Basics for Founders — core concepts (4) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply legal basics for founders with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in legal basics for founders."]),
      section("legal-basics-s5", "7.5 Legal Basics for Founders — core concepts (5)", ["7.5 Legal Basics for Founders — core concepts (5) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply legal basics for founders with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in legal basics for founders."]),
  ]),
  chapter("fundraising", 8, "Fundraising Intro", [
      section("fundraising-s1", "8.1 Fundraising Intro — core concepts (1)", ["8.1 Fundraising Intro — core concepts (1) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply fundraising intro with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in fundraising intro."]),
      section("fundraising-s2", "8.2 Fundraising Intro — core concepts (2)", ["8.2 Fundraising Intro — core concepts (2) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply fundraising intro with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in fundraising intro."]),
      section("fundraising-s3", "8.3 Fundraising Intro — core concepts (3)", ["8.3 Fundraising Intro — core concepts (3) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply fundraising intro with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in fundraising intro."]),
      section("fundraising-s4", "8.4 Fundraising Intro — core concepts (4)", ["8.4 Fundraising Intro — core concepts (4) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply fundraising intro with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in fundraising intro."]),
      section("fundraising-s5", "8.5 Fundraising Intro — core concepts (5)", ["8.5 Fundraising Intro — core concepts (5) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply fundraising intro with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in fundraising intro."]),
  ]),
  chapter("scaling", 9, "Scaling and Teams", [
      section("scaling-s1", "9.1 Scaling and Teams — core concepts (1)", ["9.1 Scaling and Teams — core concepts (1) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply scaling and teams with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in scaling and teams."]),
      section("scaling-s2", "9.2 Scaling and Teams — core concepts (2)", ["9.2 Scaling and Teams — core concepts (2) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply scaling and teams with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in scaling and teams."]),
      section("scaling-s3", "9.3 Scaling and Teams — core concepts (3)", ["9.3 Scaling and Teams — core concepts (3) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply scaling and teams with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in scaling and teams."]),
      section("scaling-s4", "9.4 Scaling and Teams — core concepts (4)", ["9.4 Scaling and Teams — core concepts (4) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply scaling and teams with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in scaling and teams."]),
      section("scaling-s5", "9.5 Scaling and Teams — core concepts (5)", ["9.5 Scaling and Teams — core concepts (5) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply scaling and teams with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in scaling and teams."]),
  ]),
  chapter("entrepreneur-careers", 10, "Entrepreneurship Paths", [
      section("entrepreneur-careers-s1", "10.1 Entrepreneurship Paths — core concepts (1)", ["10.1 Entrepreneurship Paths — core concepts (1) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply entrepreneurship paths with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in entrepreneurship paths."]),
      section("entrepreneur-careers-s2", "10.2 Entrepreneurship Paths — core concepts (2)", ["10.2 Entrepreneurship Paths — core concepts (2) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply entrepreneurship paths with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in entrepreneurship paths."]),
      section("entrepreneur-careers-s3", "10.3 Entrepreneurship Paths — core concepts (3)", ["10.3 Entrepreneurship Paths — core concepts (3) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply entrepreneurship paths with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in entrepreneurship paths."]),
      section("entrepreneur-careers-s4", "10.4 Entrepreneurship Paths — core concepts (4)", ["10.4 Entrepreneurship Paths — core concepts (4) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply entrepreneurship paths with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in entrepreneurship paths."]),
      section("entrepreneur-careers-s5", "10.5 Entrepreneurship Paths — core concepts (5)", ["10.5 Entrepreneurship Paths — core concepts (5) is a core topic in Entrepreneurship Fundamentals. Learners should connect definitions to how professionals apply entrepreneurship paths with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in entrepreneurship paths."]),
  ])
];
