import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const FUP_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Follow-Up Systems",
  subtitle: "ForgEd path course — Follow-Up Systems",
  paragraphs: [
    "Follow-Up Systems is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Each chapter includes five sections and section quizzes. Pass chapter quizzes, the course review, and final exam to mark the course complete.",
    "Content is practical workforce education — not licensure, legal, or financial advice.",
  ],
};

export const FUP_TEXTBOOK: TextbookChapter[] = [
  chapter("cadence-design", 1, "Designing Cadences", [
      section("cadence-design-s1", "1.1 Designing Cadences — applied practice (1)", ["1.1 Designing Cadences — applied practice (1) connects Designing Cadences to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("cadence-design-s2", "1.2 Designing Cadences — applied practice (2)", ["1.2 Designing Cadences — applied practice (2) connects Designing Cadences to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("cadence-design-s3", "1.3 Designing Cadences — applied practice (3)", ["1.3 Designing Cadences — applied practice (3) connects Designing Cadences to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("cadence-design-s4", "1.4 Designing Cadences — applied practice (4)", ["1.4 Designing Cadences — applied practice (4) connects Designing Cadences to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("cadence-design-s5", "1.5 Designing Cadences — applied practice (5)", ["1.5 Designing Cadences — applied practice (5) connects Designing Cadences to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("email-followup", 2, "Email Follow-Up", [
      section("email-followup-s1", "2.1 Email Follow-Up — applied practice (1)", ["2.1 Email Follow-Up — applied practice (1) connects Email Follow-Up to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("email-followup-s2", "2.2 Email Follow-Up — applied practice (2)", ["2.2 Email Follow-Up — applied practice (2) connects Email Follow-Up to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("email-followup-s3", "2.3 Email Follow-Up — applied practice (3)", ["2.3 Email Follow-Up — applied practice (3) connects Email Follow-Up to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("email-followup-s4", "2.4 Email Follow-Up — applied practice (4)", ["2.4 Email Follow-Up — applied practice (4) connects Email Follow-Up to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("email-followup-s5", "2.5 Email Follow-Up — applied practice (5)", ["2.5 Email Follow-Up — applied practice (5) connects Email Follow-Up to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("call-followup", 3, "Call Follow-Up", [
      section("call-followup-s1", "3.1 Call Follow-Up — applied practice (1)", ["3.1 Call Follow-Up — applied practice (1) connects Call Follow-Up to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("call-followup-s2", "3.2 Call Follow-Up — applied practice (2)", ["3.2 Call Follow-Up — applied practice (2) connects Call Follow-Up to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("call-followup-s3", "3.3 Call Follow-Up — applied practice (3)", ["3.3 Call Follow-Up — applied practice (3) connects Call Follow-Up to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("call-followup-s4", "3.4 Call Follow-Up — applied practice (4)", ["3.4 Call Follow-Up — applied practice (4) connects Call Follow-Up to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("call-followup-s5", "3.5 Call Follow-Up — applied practice (5)", ["3.5 Call Follow-Up — applied practice (5) connects Call Follow-Up to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("nurture", 4, "Nurture Sequences", [
      section("nurture-s1", "4.1 Nurture Sequences — applied practice (1)", ["4.1 Nurture Sequences — applied practice (1) connects Nurture Sequences to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("nurture-s2", "4.2 Nurture Sequences — applied practice (2)", ["4.2 Nurture Sequences — applied practice (2) connects Nurture Sequences to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("nurture-s3", "4.3 Nurture Sequences — applied practice (3)", ["4.3 Nurture Sequences — applied practice (3) connects Nurture Sequences to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("nurture-s4", "4.4 Nurture Sequences — applied practice (4)", ["4.4 Nurture Sequences — applied practice (4) connects Nurture Sequences to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("nurture-s5", "4.5 Nurture Sequences — applied practice (5)", ["4.5 Nurture Sequences — applied practice (5) connects Nurture Sequences to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("re-engagement", 5, "Re-Engagement", [
      section("re-engagement-s1", "5.1 Re-Engagement — applied practice (1)", ["5.1 Re-Engagement — applied practice (1) connects Re-Engagement to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("re-engagement-s2", "5.2 Re-Engagement — applied practice (2)", ["5.2 Re-Engagement — applied practice (2) connects Re-Engagement to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("re-engagement-s3", "5.3 Re-Engagement — applied practice (3)", ["5.3 Re-Engagement — applied practice (3) connects Re-Engagement to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("re-engagement-s4", "5.4 Re-Engagement — applied practice (4)", ["5.4 Re-Engagement — applied practice (4) connects Re-Engagement to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("re-engagement-s5", "5.5 Re-Engagement — applied practice (5)", ["5.5 Re-Engagement — applied practice (5) connects Re-Engagement to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("metrics-followup", 6, "Follow-Up Metrics", [
      section("metrics-followup-s1", "6.1 Follow-Up Metrics — applied practice (1)", ["6.1 Follow-Up Metrics — applied practice (1) connects Follow-Up Metrics to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("metrics-followup-s2", "6.2 Follow-Up Metrics — applied practice (2)", ["6.2 Follow-Up Metrics — applied practice (2) connects Follow-Up Metrics to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("metrics-followup-s3", "6.3 Follow-Up Metrics — applied practice (3)", ["6.3 Follow-Up Metrics — applied practice (3) connects Follow-Up Metrics to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("metrics-followup-s4", "6.4 Follow-Up Metrics — applied practice (4)", ["6.4 Follow-Up Metrics — applied practice (4) connects Follow-Up Metrics to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("metrics-followup-s5", "6.5 Follow-Up Metrics — applied practice (5)", ["6.5 Follow-Up Metrics — applied practice (5) connects Follow-Up Metrics to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("tools-followup", 7, "Tools and Templates", [
      section("tools-followup-s1", "7.1 Tools and Templates — applied practice (1)", ["7.1 Tools and Templates — applied practice (1) connects Tools and Templates to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("tools-followup-s2", "7.2 Tools and Templates — applied practice (2)", ["7.2 Tools and Templates — applied practice (2) connects Tools and Templates to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("tools-followup-s3", "7.3 Tools and Templates — applied practice (3)", ["7.3 Tools and Templates — applied practice (3) connects Tools and Templates to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("tools-followup-s4", "7.4 Tools and Templates — applied practice (4)", ["7.4 Tools and Templates — applied practice (4) connects Tools and Templates to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("tools-followup-s5", "7.5 Tools and Templates — applied practice (5)", ["7.5 Tools and Templates — applied practice (5) connects Tools and Templates to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("accountability", 8, "Personal Accountability", [
      section("accountability-s1", "8.1 Personal Accountability — applied practice (1)", ["8.1 Personal Accountability — applied practice (1) connects Personal Accountability to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("accountability-s2", "8.2 Personal Accountability — applied practice (2)", ["8.2 Personal Accountability — applied practice (2) connects Personal Accountability to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("accountability-s3", "8.3 Personal Accountability — applied practice (3)", ["8.3 Personal Accountability — applied practice (3) connects Personal Accountability to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("accountability-s4", "8.4 Personal Accountability — applied practice (4)", ["8.4 Personal Accountability — applied practice (4) connects Personal Accountability to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("accountability-s5", "8.5 Personal Accountability — applied practice (5)", ["8.5 Personal Accountability — applied practice (5) connects Personal Accountability to real workforce outcomes in Follow-Up Systems. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ])
];
