import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const HLTH_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Healthcare Fundamentals",
  subtitle: "ForgEd deep-dive — healthcare fundamentals",
  paragraphs: [
    "This ForgEd digital textbook presents Healthcare Fundamentals at academic survey depth for self-paced study.",
    "Complete each section quiz before advancing. Chapter and course assessments draw from a 150-question bank.",
    "Material is general education, not professional licensure or certification prep by itself.",
  ],
};

export const HLTH_TEXTBOOK: TextbookChapter[] = [
  chapter("health-systems", 1, "Healthcare Systems", [
      section("health-systems-s1", "1.1 Healthcare Systems — core concepts (1)", ["1.1 Healthcare Systems — core concepts (1) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply healthcare systems with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in healthcare systems."]),
      section("health-systems-s2", "1.2 Healthcare Systems — core concepts (2)", ["1.2 Healthcare Systems — core concepts (2) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply healthcare systems with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in healthcare systems."]),
      section("health-systems-s3", "1.3 Healthcare Systems — core concepts (3)", ["1.3 Healthcare Systems — core concepts (3) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply healthcare systems with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in healthcare systems."]),
      section("health-systems-s4", "1.4 Healthcare Systems — core concepts (4)", ["1.4 Healthcare Systems — core concepts (4) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply healthcare systems with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in healthcare systems."]),
      section("health-systems-s5", "1.5 Healthcare Systems — core concepts (5)", ["1.5 Healthcare Systems — core concepts (5) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply healthcare systems with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in healthcare systems."]),
  ]),
  chapter("patient-care", 2, "Patient Care Basics", [
      section("patient-care-s1", "2.1 Patient Care Basics — core concepts (1)", ["2.1 Patient Care Basics — core concepts (1) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply patient care basics with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in patient care basics."]),
      section("patient-care-s2", "2.2 Patient Care Basics — core concepts (2)", ["2.2 Patient Care Basics — core concepts (2) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply patient care basics with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in patient care basics."]),
      section("patient-care-s3", "2.3 Patient Care Basics — core concepts (3)", ["2.3 Patient Care Basics — core concepts (3) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply patient care basics with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in patient care basics."]),
      section("patient-care-s4", "2.4 Patient Care Basics — core concepts (4)", ["2.4 Patient Care Basics — core concepts (4) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply patient care basics with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in patient care basics."]),
      section("patient-care-s5", "2.5 Patient Care Basics — core concepts (5)", ["2.5 Patient Care Basics — core concepts (5) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply patient care basics with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in patient care basics."]),
  ]),
  chapter("medical-terminology", 3, "Medical Terminology", [
      section("medical-terminology-s1", "3.1 Medical Terminology — core concepts (1)", ["3.1 Medical Terminology — core concepts (1) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply medical terminology with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in medical terminology."]),
      section("medical-terminology-s2", "3.2 Medical Terminology — core concepts (2)", ["3.2 Medical Terminology — core concepts (2) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply medical terminology with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in medical terminology."]),
      section("medical-terminology-s3", "3.3 Medical Terminology — core concepts (3)", ["3.3 Medical Terminology — core concepts (3) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply medical terminology with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in medical terminology."]),
      section("medical-terminology-s4", "3.4 Medical Terminology — core concepts (4)", ["3.4 Medical Terminology — core concepts (4) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply medical terminology with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in medical terminology."]),
      section("medical-terminology-s5", "3.5 Medical Terminology — core concepts (5)", ["3.5 Medical Terminology — core concepts (5) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply medical terminology with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in medical terminology."]),
  ]),
  chapter("billing-coding", 4, "Billing and Coding Intro", [
      section("billing-coding-s1", "4.1 Billing and Coding Intro — core concepts (1)", ["4.1 Billing and Coding Intro — core concepts (1) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply billing and coding intro with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in billing and coding intro."]),
      section("billing-coding-s2", "4.2 Billing and Coding Intro — core concepts (2)", ["4.2 Billing and Coding Intro — core concepts (2) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply billing and coding intro with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in billing and coding intro."]),
      section("billing-coding-s3", "4.3 Billing and Coding Intro — core concepts (3)", ["4.3 Billing and Coding Intro — core concepts (3) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply billing and coding intro with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in billing and coding intro."]),
      section("billing-coding-s4", "4.4 Billing and Coding Intro — core concepts (4)", ["4.4 Billing and Coding Intro — core concepts (4) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply billing and coding intro with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in billing and coding intro."]),
      section("billing-coding-s5", "4.5 Billing and Coding Intro — core concepts (5)", ["4.5 Billing and Coding Intro — core concepts (5) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply billing and coding intro with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in billing and coding intro."]),
  ]),
  chapter("pharmacy-basics", 5, "Pharmacy Basics", [
      section("pharmacy-basics-s1", "5.1 Pharmacy Basics — core concepts (1)", ["5.1 Pharmacy Basics — core concepts (1) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply pharmacy basics with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in pharmacy basics."]),
      section("pharmacy-basics-s2", "5.2 Pharmacy Basics — core concepts (2)", ["5.2 Pharmacy Basics — core concepts (2) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply pharmacy basics with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in pharmacy basics."]),
      section("pharmacy-basics-s3", "5.3 Pharmacy Basics — core concepts (3)", ["5.3 Pharmacy Basics — core concepts (3) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply pharmacy basics with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in pharmacy basics."]),
      section("pharmacy-basics-s4", "5.4 Pharmacy Basics — core concepts (4)", ["5.4 Pharmacy Basics — core concepts (4) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply pharmacy basics with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in pharmacy basics."]),
      section("pharmacy-basics-s5", "5.5 Pharmacy Basics — core concepts (5)", ["5.5 Pharmacy Basics — core concepts (5) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply pharmacy basics with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in pharmacy basics."]),
  ]),
  chapter("public-health", 6, "Public Health", [
      section("public-health-s1", "6.1 Public Health — core concepts (1)", ["6.1 Public Health — core concepts (1) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply public health with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in public health."]),
      section("public-health-s2", "6.2 Public Health — core concepts (2)", ["6.2 Public Health — core concepts (2) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply public health with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in public health."]),
      section("public-health-s3", "6.3 Public Health — core concepts (3)", ["6.3 Public Health — core concepts (3) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply public health with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in public health."]),
      section("public-health-s4", "6.4 Public Health — core concepts (4)", ["6.4 Public Health — core concepts (4) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply public health with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in public health."]),
      section("public-health-s5", "6.5 Public Health — core concepts (5)", ["6.5 Public Health — core concepts (5) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply public health with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in public health."]),
  ]),
  chapter("ethics-hipaa", 7, "Ethics and HIPAA", [
      section("ethics-hipaa-s1", "7.1 Ethics and HIPAA — core concepts (1)", ["7.1 Ethics and HIPAA — core concepts (1) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply ethics and hipaa with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in ethics and hipaa."]),
      section("ethics-hipaa-s2", "7.2 Ethics and HIPAA — core concepts (2)", ["7.2 Ethics and HIPAA — core concepts (2) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply ethics and hipaa with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in ethics and hipaa."]),
      section("ethics-hipaa-s3", "7.3 Ethics and HIPAA — core concepts (3)", ["7.3 Ethics and HIPAA — core concepts (3) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply ethics and hipaa with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in ethics and hipaa."]),
      section("ethics-hipaa-s4", "7.4 Ethics and HIPAA — core concepts (4)", ["7.4 Ethics and HIPAA — core concepts (4) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply ethics and hipaa with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in ethics and hipaa."]),
      section("ethics-hipaa-s5", "7.5 Ethics and HIPAA — core concepts (5)", ["7.5 Ethics and HIPAA — core concepts (5) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply ethics and hipaa with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in ethics and hipaa."]),
  ]),
  chapter("emergency-basics", 8, "Emergency Response Basics", [
      section("emergency-basics-s1", "8.1 Emergency Response Basics — core concepts (1)", ["8.1 Emergency Response Basics — core concepts (1) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply emergency response basics with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in emergency response basics."]),
      section("emergency-basics-s2", "8.2 Emergency Response Basics — core concepts (2)", ["8.2 Emergency Response Basics — core concepts (2) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply emergency response basics with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in emergency response basics."]),
      section("emergency-basics-s3", "8.3 Emergency Response Basics — core concepts (3)", ["8.3 Emergency Response Basics — core concepts (3) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply emergency response basics with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in emergency response basics."]),
      section("emergency-basics-s4", "8.4 Emergency Response Basics — core concepts (4)", ["8.4 Emergency Response Basics — core concepts (4) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply emergency response basics with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in emergency response basics."]),
      section("emergency-basics-s5", "8.5 Emergency Response Basics — core concepts (5)", ["8.5 Emergency Response Basics — core concepts (5) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply emergency response basics with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in emergency response basics."]),
  ]),
  chapter("careers-health", 9, "Healthcare Careers", [
      section("careers-health-s1", "9.1 Healthcare Careers — core concepts (1)", ["9.1 Healthcare Careers — core concepts (1) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply healthcare careers with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in healthcare careers."]),
      section("careers-health-s2", "9.2 Healthcare Careers — core concepts (2)", ["9.2 Healthcare Careers — core concepts (2) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply healthcare careers with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in healthcare careers."]),
      section("careers-health-s3", "9.3 Healthcare Careers — core concepts (3)", ["9.3 Healthcare Careers — core concepts (3) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply healthcare careers with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in healthcare careers."]),
      section("careers-health-s4", "9.4 Healthcare Careers — core concepts (4)", ["9.4 Healthcare Careers — core concepts (4) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply healthcare careers with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in healthcare careers."]),
      section("careers-health-s5", "9.5 Healthcare Careers — core concepts (5)", ["9.5 Healthcare Careers — core concepts (5) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply healthcare careers with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in healthcare careers."]),
  ]),
  chapter("future-health", 10, "Future of Healthcare", [
      section("future-health-s1", "10.1 Future of Healthcare — core concepts (1)", ["10.1 Future of Healthcare — core concepts (1) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply future of healthcare with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in future of healthcare."]),
      section("future-health-s2", "10.2 Future of Healthcare — core concepts (2)", ["10.2 Future of Healthcare — core concepts (2) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply future of healthcare with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in future of healthcare."]),
      section("future-health-s3", "10.3 Future of Healthcare — core concepts (3)", ["10.3 Future of Healthcare — core concepts (3) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply future of healthcare with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in future of healthcare."]),
      section("future-health-s4", "10.4 Future of Healthcare — core concepts (4)", ["10.4 Future of Healthcare — core concepts (4) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply future of healthcare with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in future of healthcare."]),
      section("future-health-s5", "10.5 Future of Healthcare — core concepts (5)", ["10.5 Future of Healthcare — core concepts (5) is a core topic in Healthcare Fundamentals. Learners should connect definitions to how professionals apply future of healthcare with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in future of healthcare."]),
  ])
];
