import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const IR_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Incident Response Basics",
  subtitle: "ForgEd path course — Incident Response Basics",
  paragraphs: [
    "Incident Response Basics is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Each chapter includes five sections and section quizzes. Pass chapter quizzes, the course review, and final exam to mark the course complete.",
    "Content is practical workforce education — not licensure, legal, or financial advice.",
  ],
};

export const IR_TEXTBOOK: TextbookChapter[] = [
  chapter("ir-lifecycle", 1, "IR Lifecycle", [
      section("ir-lifecycle-s1", "1.1 IR Lifecycle — applied practice (1)", ["1.1 IR Lifecycle — applied practice (1) connects IR Lifecycle to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ir-lifecycle-s2", "1.2 IR Lifecycle — applied practice (2)", ["1.2 IR Lifecycle — applied practice (2) connects IR Lifecycle to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ir-lifecycle-s3", "1.3 IR Lifecycle — applied practice (3)", ["1.3 IR Lifecycle — applied practice (3) connects IR Lifecycle to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ir-lifecycle-s4", "1.4 IR Lifecycle — applied practice (4)", ["1.4 IR Lifecycle — applied practice (4) connects IR Lifecycle to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ir-lifecycle-s5", "1.5 IR Lifecycle — applied practice (5)", ["1.5 IR Lifecycle — applied practice (5) connects IR Lifecycle to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("detection", 2, "Detection", [
      section("detection-s1", "2.1 Detection — applied practice (1)", ["2.1 Detection — applied practice (1) connects Detection to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("detection-s2", "2.2 Detection — applied practice (2)", ["2.2 Detection — applied practice (2) connects Detection to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("detection-s3", "2.3 Detection — applied practice (3)", ["2.3 Detection — applied practice (3) connects Detection to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("detection-s4", "2.4 Detection — applied practice (4)", ["2.4 Detection — applied practice (4) connects Detection to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("detection-s5", "2.5 Detection — applied practice (5)", ["2.5 Detection — applied practice (5) connects Detection to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("containment", 3, "Containment", [
      section("containment-s1", "3.1 Containment — applied practice (1)", ["3.1 Containment — applied practice (1) connects Containment to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("containment-s2", "3.2 Containment — applied practice (2)", ["3.2 Containment — applied practice (2) connects Containment to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("containment-s3", "3.3 Containment — applied practice (3)", ["3.3 Containment — applied practice (3) connects Containment to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("containment-s4", "3.4 Containment — applied practice (4)", ["3.4 Containment — applied practice (4) connects Containment to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("containment-s5", "3.5 Containment — applied practice (5)", ["3.5 Containment — applied practice (5) connects Containment to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("eradication", 4, "Eradication", [
      section("eradication-s1", "4.1 Eradication — applied practice (1)", ["4.1 Eradication — applied practice (1) connects Eradication to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("eradication-s2", "4.2 Eradication — applied practice (2)", ["4.2 Eradication — applied practice (2) connects Eradication to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("eradication-s3", "4.3 Eradication — applied practice (3)", ["4.3 Eradication — applied practice (3) connects Eradication to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("eradication-s4", "4.4 Eradication — applied practice (4)", ["4.4 Eradication — applied practice (4) connects Eradication to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("eradication-s5", "4.5 Eradication — applied practice (5)", ["4.5 Eradication — applied practice (5) connects Eradication to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("recovery", 5, "Recovery", [
      section("recovery-s1", "5.1 Recovery — applied practice (1)", ["5.1 Recovery — applied practice (1) connects Recovery to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("recovery-s2", "5.2 Recovery — applied practice (2)", ["5.2 Recovery — applied practice (2) connects Recovery to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("recovery-s3", "5.3 Recovery — applied practice (3)", ["5.3 Recovery — applied practice (3) connects Recovery to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("recovery-s4", "5.4 Recovery — applied practice (4)", ["5.4 Recovery — applied practice (4) connects Recovery to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("recovery-s5", "5.5 Recovery — applied practice (5)", ["5.5 Recovery — applied practice (5) connects Recovery to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("evidence", 6, "Evidence Handling", [
      section("evidence-s1", "6.1 Evidence Handling — applied practice (1)", ["6.1 Evidence Handling — applied practice (1) connects Evidence Handling to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("evidence-s2", "6.2 Evidence Handling — applied practice (2)", ["6.2 Evidence Handling — applied practice (2) connects Evidence Handling to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("evidence-s3", "6.3 Evidence Handling — applied practice (3)", ["6.3 Evidence Handling — applied practice (3) connects Evidence Handling to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("evidence-s4", "6.4 Evidence Handling — applied practice (4)", ["6.4 Evidence Handling — applied practice (4) connects Evidence Handling to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("evidence-s5", "6.5 Evidence Handling — applied practice (5)", ["6.5 Evidence Handling — applied practice (5) connects Evidence Handling to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("comms-ir", 7, "Incident Communications", [
      section("comms-ir-s1", "7.1 Incident Communications — applied practice (1)", ["7.1 Incident Communications — applied practice (1) connects Incident Communications to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("comms-ir-s2", "7.2 Incident Communications — applied practice (2)", ["7.2 Incident Communications — applied practice (2) connects Incident Communications to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("comms-ir-s3", "7.3 Incident Communications — applied practice (3)", ["7.3 Incident Communications — applied practice (3) connects Incident Communications to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("comms-ir-s4", "7.4 Incident Communications — applied practice (4)", ["7.4 Incident Communications — applied practice (4) connects Incident Communications to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("comms-ir-s5", "7.5 Incident Communications — applied practice (5)", ["7.5 Incident Communications — applied practice (5) connects Incident Communications to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("post-incident", 8, "Post-Incident Review", [
      section("post-incident-s1", "8.1 Post-Incident Review — applied practice (1)", ["8.1 Post-Incident Review — applied practice (1) connects Post-Incident Review to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("post-incident-s2", "8.2 Post-Incident Review — applied practice (2)", ["8.2 Post-Incident Review — applied practice (2) connects Post-Incident Review to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("post-incident-s3", "8.3 Post-Incident Review — applied practice (3)", ["8.3 Post-Incident Review — applied practice (3) connects Post-Incident Review to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("post-incident-s4", "8.4 Post-Incident Review — applied practice (4)", ["8.4 Post-Incident Review — applied practice (4) connects Post-Incident Review to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("post-incident-s5", "8.5 Post-Incident Review — applied practice (5)", ["8.5 Post-Incident Review — applied practice (5) connects Post-Incident Review to real workforce outcomes in Incident Response Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ])
];
