import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const INET_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Internet Infrastructure",
  subtitle: "ForgEd path course — Internet Infrastructure",
  paragraphs: [
    "Internet Infrastructure is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Each chapter includes five sections and section quizzes. Pass chapter quizzes, the course review, and final exam to mark the course complete.",
    "Content is practical workforce education — not licensure, legal, or financial advice.",
  ],
};

export const INET_TEXTBOOK: TextbookChapter[] = [
  chapter("how-internet", 1, "How the Internet Works", [
      section("how-internet-s1", "1.1 How the Internet Works — applied practice (1)", ["1.1 How the Internet Works — applied practice (1) connects How the Internet Works to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("how-internet-s2", "1.2 How the Internet Works — applied practice (2)", ["1.2 How the Internet Works — applied practice (2) connects How the Internet Works to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("how-internet-s3", "1.3 How the Internet Works — applied practice (3)", ["1.3 How the Internet Works — applied practice (3) connects How the Internet Works to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("how-internet-s4", "1.4 How the Internet Works — applied practice (4)", ["1.4 How the Internet Works — applied practice (4) connects How the Internet Works to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("how-internet-s5", "1.5 How the Internet Works — applied practice (5)", ["1.5 How the Internet Works — applied practice (5) connects How the Internet Works to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("isps", 2, "ISPs and Peering", [
      section("isps-s1", "2.1 ISPs and Peering — applied practice (1)", ["2.1 ISPs and Peering — applied practice (1) connects ISPs and Peering to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("isps-s2", "2.2 ISPs and Peering — applied practice (2)", ["2.2 ISPs and Peering — applied practice (2) connects ISPs and Peering to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("isps-s3", "2.3 ISPs and Peering — applied practice (3)", ["2.3 ISPs and Peering — applied practice (3) connects ISPs and Peering to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("isps-s4", "2.4 ISPs and Peering — applied practice (4)", ["2.4 ISPs and Peering — applied practice (4) connects ISPs and Peering to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("isps-s5", "2.5 ISPs and Peering — applied practice (5)", ["2.5 ISPs and Peering — applied practice (5) connects ISPs and Peering to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("cdn", 3, "CDNs", [
      section("cdn-s1", "3.1 CDNs — applied practice (1)", ["3.1 CDNs — applied practice (1) connects CDNs to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("cdn-s2", "3.2 CDNs — applied practice (2)", ["3.2 CDNs — applied practice (2) connects CDNs to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("cdn-s3", "3.3 CDNs — applied practice (3)", ["3.3 CDNs — applied practice (3) connects CDNs to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("cdn-s4", "3.4 CDNs — applied practice (4)", ["3.4 CDNs — applied practice (4) connects CDNs to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("cdn-s5", "3.5 CDNs — applied practice (5)", ["3.5 CDNs — applied practice (5) connects CDNs to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("cloud-edge", 4, "Cloud and Edge", [
      section("cloud-edge-s1", "4.1 Cloud and Edge — applied practice (1)", ["4.1 Cloud and Edge — applied practice (1) connects Cloud and Edge to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("cloud-edge-s2", "4.2 Cloud and Edge — applied practice (2)", ["4.2 Cloud and Edge — applied practice (2) connects Cloud and Edge to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("cloud-edge-s3", "4.3 Cloud and Edge — applied practice (3)", ["4.3 Cloud and Edge — applied practice (3) connects Cloud and Edge to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("cloud-edge-s4", "4.4 Cloud and Edge — applied practice (4)", ["4.4 Cloud and Edge — applied practice (4) connects Cloud and Edge to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("cloud-edge-s5", "4.5 Cloud and Edge — applied practice (5)", ["4.5 Cloud and Edge — applied practice (5) connects Cloud and Edge to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("latency", 5, "Latency and Throughput", [
      section("latency-s1", "5.1 Latency and Throughput — applied practice (1)", ["5.1 Latency and Throughput — applied practice (1) connects Latency and Throughput to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("latency-s2", "5.2 Latency and Throughput — applied practice (2)", ["5.2 Latency and Throughput — applied practice (2) connects Latency and Throughput to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("latency-s3", "5.3 Latency and Throughput — applied practice (3)", ["5.3 Latency and Throughput — applied practice (3) connects Latency and Throughput to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("latency-s4", "5.4 Latency and Throughput — applied practice (4)", ["5.4 Latency and Throughput — applied practice (4) connects Latency and Throughput to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("latency-s5", "5.5 Latency and Throughput — applied practice (5)", ["5.5 Latency and Throughput — applied practice (5) connects Latency and Throughput to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("routing", 6, "Routing Basics", [
      section("routing-s1", "6.1 Routing Basics — applied practice (1)", ["6.1 Routing Basics — applied practice (1) connects Routing Basics to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("routing-s2", "6.2 Routing Basics — applied practice (2)", ["6.2 Routing Basics — applied practice (2) connects Routing Basics to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("routing-s3", "6.3 Routing Basics — applied practice (3)", ["6.3 Routing Basics — applied practice (3) connects Routing Basics to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("routing-s4", "6.4 Routing Basics — applied practice (4)", ["6.4 Routing Basics — applied practice (4) connects Routing Basics to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("routing-s5", "6.5 Routing Basics — applied practice (5)", ["6.5 Routing Basics — applied practice (5) connects Routing Basics to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("ipv6", 7, "IPv6 Intro", [
      section("ipv6-s1", "7.1 IPv6 Intro — applied practice (1)", ["7.1 IPv6 Intro — applied practice (1) connects IPv6 Intro to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ipv6-s2", "7.2 IPv6 Intro — applied practice (2)", ["7.2 IPv6 Intro — applied practice (2) connects IPv6 Intro to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ipv6-s3", "7.3 IPv6 Intro — applied practice (3)", ["7.3 IPv6 Intro — applied practice (3) connects IPv6 Intro to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ipv6-s4", "7.4 IPv6 Intro — applied practice (4)", ["7.4 IPv6 Intro — applied practice (4) connects IPv6 Intro to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ipv6-s5", "7.5 IPv6 Intro — applied practice (5)", ["7.5 IPv6 Intro — applied practice (5) connects IPv6 Intro to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("outages", 8, "Understanding Outages", [
      section("outages-s1", "8.1 Understanding Outages — applied practice (1)", ["8.1 Understanding Outages — applied practice (1) connects Understanding Outages to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("outages-s2", "8.2 Understanding Outages — applied practice (2)", ["8.2 Understanding Outages — applied practice (2) connects Understanding Outages to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("outages-s3", "8.3 Understanding Outages — applied practice (3)", ["8.3 Understanding Outages — applied practice (3) connects Understanding Outages to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("outages-s4", "8.4 Understanding Outages — applied practice (4)", ["8.4 Understanding Outages — applied practice (4) connects Understanding Outages to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("outages-s5", "8.5 Understanding Outages — applied practice (5)", ["8.5 Understanding Outages — applied practice (5) connects Understanding Outages to real workforce outcomes in Internet Infrastructure. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ])
];
