import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const INV_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Investing Fundamentals",
  subtitle: "ForgEd path course — Investing Fundamentals",
  paragraphs: [
    "Investing Fundamentals is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Each chapter includes five sections and section quizzes. Pass chapter quizzes, the course review, and final exam to mark the course complete.",
    "Content is practical workforce education — not licensure, legal, or financial advice.",
  ],
};

export const INV_TEXTBOOK: TextbookChapter[] = [
  chapter("risk-return", 1, "Risk and Return", [
      section("risk-return-s1", "1.1 Risk and Return — applied practice (1)", ["1.1 Risk and Return — applied practice (1) connects Risk and Return to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("risk-return-s2", "1.2 Risk and Return — applied practice (2)", ["1.2 Risk and Return — applied practice (2) connects Risk and Return to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("risk-return-s3", "1.3 Risk and Return — applied practice (3)", ["1.3 Risk and Return — applied practice (3) connects Risk and Return to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("risk-return-s4", "1.4 Risk and Return — applied practice (4)", ["1.4 Risk and Return — applied practice (4) connects Risk and Return to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("risk-return-s5", "1.5 Risk and Return — applied practice (5)", ["1.5 Risk and Return — applied practice (5) connects Risk and Return to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("stocks-bonds", 2, "Stocks and Bonds", [
      section("stocks-bonds-s1", "2.1 Stocks and Bonds — applied practice (1)", ["2.1 Stocks and Bonds — applied practice (1) connects Stocks and Bonds to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("stocks-bonds-s2", "2.2 Stocks and Bonds — applied practice (2)", ["2.2 Stocks and Bonds — applied practice (2) connects Stocks and Bonds to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("stocks-bonds-s3", "2.3 Stocks and Bonds — applied practice (3)", ["2.3 Stocks and Bonds — applied practice (3) connects Stocks and Bonds to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("stocks-bonds-s4", "2.4 Stocks and Bonds — applied practice (4)", ["2.4 Stocks and Bonds — applied practice (4) connects Stocks and Bonds to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("stocks-bonds-s5", "2.5 Stocks and Bonds — applied practice (5)", ["2.5 Stocks and Bonds — applied practice (5) connects Stocks and Bonds to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("index-funds", 3, "Index Funds", [
      section("index-funds-s1", "3.1 Index Funds — applied practice (1)", ["3.1 Index Funds — applied practice (1) connects Index Funds to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("index-funds-s2", "3.2 Index Funds — applied practice (2)", ["3.2 Index Funds — applied practice (2) connects Index Funds to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("index-funds-s3", "3.3 Index Funds — applied practice (3)", ["3.3 Index Funds — applied practice (3) connects Index Funds to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("index-funds-s4", "3.4 Index Funds — applied practice (4)", ["3.4 Index Funds — applied practice (4) connects Index Funds to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("index-funds-s5", "3.5 Index Funds — applied practice (5)", ["3.5 Index Funds — applied practice (5) connects Index Funds to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("diversification", 4, "Diversification", [
      section("diversification-s1", "4.1 Diversification — applied practice (1)", ["4.1 Diversification — applied practice (1) connects Diversification to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("diversification-s2", "4.2 Diversification — applied practice (2)", ["4.2 Diversification — applied practice (2) connects Diversification to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("diversification-s3", "4.3 Diversification — applied practice (3)", ["4.3 Diversification — applied practice (3) connects Diversification to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("diversification-s4", "4.4 Diversification — applied practice (4)", ["4.4 Diversification — applied practice (4) connects Diversification to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("diversification-s5", "4.5 Diversification — applied practice (5)", ["4.5 Diversification — applied practice (5) connects Diversification to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("time-horizon", 5, "Time Horizon", [
      section("time-horizon-s1", "5.1 Time Horizon — applied practice (1)", ["5.1 Time Horizon — applied practice (1) connects Time Horizon to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("time-horizon-s2", "5.2 Time Horizon — applied practice (2)", ["5.2 Time Horizon — applied practice (2) connects Time Horizon to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("time-horizon-s3", "5.3 Time Horizon — applied practice (3)", ["5.3 Time Horizon — applied practice (3) connects Time Horizon to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("time-horizon-s4", "5.4 Time Horizon — applied practice (4)", ["5.4 Time Horizon — applied practice (4) connects Time Horizon to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("time-horizon-s5", "5.5 Time Horizon — applied practice (5)", ["5.5 Time Horizon — applied practice (5) connects Time Horizon to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("brokerages", 6, "Brokerage Accounts", [
      section("brokerages-s1", "6.1 Brokerage Accounts — applied practice (1)", ["6.1 Brokerage Accounts — applied practice (1) connects Brokerage Accounts to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("brokerages-s2", "6.2 Brokerage Accounts — applied practice (2)", ["6.2 Brokerage Accounts — applied practice (2) connects Brokerage Accounts to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("brokerages-s3", "6.3 Brokerage Accounts — applied practice (3)", ["6.3 Brokerage Accounts — applied practice (3) connects Brokerage Accounts to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("brokerages-s4", "6.4 Brokerage Accounts — applied practice (4)", ["6.4 Brokerage Accounts — applied practice (4) connects Brokerage Accounts to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("brokerages-s5", "6.5 Brokerage Accounts — applied practice (5)", ["6.5 Brokerage Accounts — applied practice (5) connects Brokerage Accounts to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("dca", 7, "Dollar-Cost Averaging", [
      section("dca-s1", "7.1 Dollar-Cost Averaging — applied practice (1)", ["7.1 Dollar-Cost Averaging — applied practice (1) connects Dollar-Cost Averaging to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("dca-s2", "7.2 Dollar-Cost Averaging — applied practice (2)", ["7.2 Dollar-Cost Averaging — applied practice (2) connects Dollar-Cost Averaging to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("dca-s3", "7.3 Dollar-Cost Averaging — applied practice (3)", ["7.3 Dollar-Cost Averaging — applied practice (3) connects Dollar-Cost Averaging to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("dca-s4", "7.4 Dollar-Cost Averaging — applied practice (4)", ["7.4 Dollar-Cost Averaging — applied practice (4) connects Dollar-Cost Averaging to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("dca-s5", "7.5 Dollar-Cost Averaging — applied practice (5)", ["7.5 Dollar-Cost Averaging — applied practice (5) connects Dollar-Cost Averaging to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("investing-mistakes", 8, "Common Mistakes", [
      section("investing-mistakes-s1", "8.1 Common Mistakes — applied practice (1)", ["8.1 Common Mistakes — applied practice (1) connects Common Mistakes to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("investing-mistakes-s2", "8.2 Common Mistakes — applied practice (2)", ["8.2 Common Mistakes — applied practice (2) connects Common Mistakes to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("investing-mistakes-s3", "8.3 Common Mistakes — applied practice (3)", ["8.3 Common Mistakes — applied practice (3) connects Common Mistakes to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("investing-mistakes-s4", "8.4 Common Mistakes — applied practice (4)", ["8.4 Common Mistakes — applied practice (4) connects Common Mistakes to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("investing-mistakes-s5", "8.5 Common Mistakes — applied practice (5)", ["8.5 Common Mistakes — applied practice (5) connects Common Mistakes to real workforce outcomes in Investing Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ])
];
