import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const MAINT_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Maintenance Selling",
  subtitle: "ForgEd path course — Maintenance Selling",
  paragraphs: [
    "Maintenance Selling is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Each chapter includes five sections and section quizzes. Pass chapter quizzes, the course review, and final exam to mark the course complete.",
    "Content is practical workforce education — not licensure, legal, or financial advice.",
  ],
};

export const MAINT_TEXTBOOK: TextbookChapter[] = [
  chapter("factory-schedule", 1, "Factory Maintenance", [
      section("factory-schedule-s1", "1.1 Factory Maintenance — applied practice (1)", ["1.1 Factory Maintenance — applied practice (1) connects Factory Maintenance to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("factory-schedule-s2", "1.2 Factory Maintenance — applied practice (2)", ["1.2 Factory Maintenance — applied practice (2) connects Factory Maintenance to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("factory-schedule-s3", "1.3 Factory Maintenance — applied practice (3)", ["1.3 Factory Maintenance — applied practice (3) connects Factory Maintenance to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("factory-schedule-s4", "1.4 Factory Maintenance — applied practice (4)", ["1.4 Factory Maintenance — applied practice (4) connects Factory Maintenance to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("factory-schedule-s5", "1.5 Factory Maintenance — applied practice (5)", ["1.5 Factory Maintenance — applied practice (5) connects Factory Maintenance to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("menus", 2, "Maintenance Menus", [
      section("menus-s1", "2.1 Maintenance Menus — applied practice (1)", ["2.1 Maintenance Menus — applied practice (1) connects Maintenance Menus to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("menus-s2", "2.2 Maintenance Menus — applied practice (2)", ["2.2 Maintenance Menus — applied practice (2) connects Maintenance Menus to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("menus-s3", "2.3 Maintenance Menus — applied practice (3)", ["2.3 Maintenance Menus — applied practice (3) connects Maintenance Menus to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("menus-s4", "2.4 Maintenance Menus — applied practice (4)", ["2.4 Maintenance Menus — applied practice (4) connects Maintenance Menus to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("menus-s5", "2.5 Maintenance Menus — applied practice (5)", ["2.5 Maintenance Menus — applied practice (5) connects Maintenance Menus to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("ethical-upsell", 3, "Ethical Recommendations", [
      section("ethical-upsell-s1", "3.1 Ethical Recommendations — applied practice (1)", ["3.1 Ethical Recommendations — applied practice (1) connects Ethical Recommendations to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ethical-upsell-s2", "3.2 Ethical Recommendations — applied practice (2)", ["3.2 Ethical Recommendations — applied practice (2) connects Ethical Recommendations to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ethical-upsell-s3", "3.3 Ethical Recommendations — applied practice (3)", ["3.3 Ethical Recommendations — applied practice (3) connects Ethical Recommendations to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ethical-upsell-s4", "3.4 Ethical Recommendations — applied practice (4)", ["3.4 Ethical Recommendations — applied practice (4) connects Ethical Recommendations to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ethical-upsell-s5", "3.5 Ethical Recommendations — applied practice (5)", ["3.5 Ethical Recommendations — applied practice (5) connects Ethical Recommendations to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("declined-work", 4, "Declined Work", [
      section("declined-work-s1", "4.1 Declined Work — applied practice (1)", ["4.1 Declined Work — applied practice (1) connects Declined Work to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("declined-work-s2", "4.2 Declined Work — applied practice (2)", ["4.2 Declined Work — applied practice (2) connects Declined Work to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("declined-work-s3", "4.3 Declined Work — applied practice (3)", ["4.3 Declined Work — applied practice (3) connects Declined Work to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("declined-work-s4", "4.4 Declined Work — applied practice (4)", ["4.4 Declined Work — applied practice (4) connects Declined Work to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("declined-work-s5", "4.5 Declined Work — applied practice (5)", ["4.5 Declined Work — applied practice (5) connects Declined Work to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("seasonal", 5, "Seasonal Services", [
      section("seasonal-s1", "5.1 Seasonal Services — applied practice (1)", ["5.1 Seasonal Services — applied practice (1) connects Seasonal Services to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("seasonal-s2", "5.2 Seasonal Services — applied practice (2)", ["5.2 Seasonal Services — applied practice (2) connects Seasonal Services to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("seasonal-s3", "5.3 Seasonal Services — applied practice (3)", ["5.3 Seasonal Services — applied practice (3) connects Seasonal Services to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("seasonal-s4", "5.4 Seasonal Services — applied practice (4)", ["5.4 Seasonal Services — applied practice (4) connects Seasonal Services to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("seasonal-s5", "5.5 Seasonal Services — applied practice (5)", ["5.5 Seasonal Services — applied practice (5) connects Seasonal Services to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("fluids-filters", 6, "Fluids and Filters", [
      section("fluids-filters-s1", "6.1 Fluids and Filters — applied practice (1)", ["6.1 Fluids and Filters — applied practice (1) connects Fluids and Filters to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("fluids-filters-s2", "6.2 Fluids and Filters — applied practice (2)", ["6.2 Fluids and Filters — applied practice (2) connects Fluids and Filters to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("fluids-filters-s3", "6.3 Fluids and Filters — applied practice (3)", ["6.3 Fluids and Filters — applied practice (3) connects Fluids and Filters to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("fluids-filters-s4", "6.4 Fluids and Filters — applied practice (4)", ["6.4 Fluids and Filters — applied practice (4) connects Fluids and Filters to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("fluids-filters-s5", "6.5 Fluids and Filters — applied practice (5)", ["6.5 Fluids and Filters — applied practice (5) connects Fluids and Filters to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("ev-maintenance", 7, "EV Maintenance", [
      section("ev-maintenance-s1", "7.1 EV Maintenance — applied practice (1)", ["7.1 EV Maintenance — applied practice (1) connects EV Maintenance to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ev-maintenance-s2", "7.2 EV Maintenance — applied practice (2)", ["7.2 EV Maintenance — applied practice (2) connects EV Maintenance to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ev-maintenance-s3", "7.3 EV Maintenance — applied practice (3)", ["7.3 EV Maintenance — applied practice (3) connects EV Maintenance to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ev-maintenance-s4", "7.4 EV Maintenance — applied practice (4)", ["7.4 EV Maintenance — applied practice (4) connects EV Maintenance to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ev-maintenance-s5", "7.5 EV Maintenance — applied practice (5)", ["7.5 EV Maintenance — applied practice (5) connects EV Maintenance to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("tracking-maintenance", 8, "Tracking History", [
      section("tracking-maintenance-s1", "8.1 Tracking History — applied practice (1)", ["8.1 Tracking History — applied practice (1) connects Tracking History to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("tracking-maintenance-s2", "8.2 Tracking History — applied practice (2)", ["8.2 Tracking History — applied practice (2) connects Tracking History to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("tracking-maintenance-s3", "8.3 Tracking History — applied practice (3)", ["8.3 Tracking History — applied practice (3) connects Tracking History to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("tracking-maintenance-s4", "8.4 Tracking History — applied practice (4)", ["8.4 Tracking History — applied practice (4) connects Tracking History to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("tracking-maintenance-s5", "8.5 Tracking History — applied practice (5)", ["8.5 Tracking History — applied practice (5) connects Tracking History to real workforce outcomes in Maintenance Selling. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ])
];
