import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const MAINT_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Maintenance Selling",
  subtitle: "Workforce training — Maintenance Selling",
  paragraphs: [
    "Maintenance Selling is built for professionals who want usable skill—not trivia. Each chapter moves from why the topic matters, through structured explanation, to quizzes that check judgment rather than memorization.",
    "Maintenance Selling is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Content is practical workforce education. It does not replace licensure, legal, medical, or employer-specific policy. When your organization has a rule that conflicts with a general lesson, follow your organization's rule and treat this course as context.",
  ],
};

export const MAINT_TEXTBOOK: TextbookChapter[] = [
  chapter("factory-schedule", 1, "Factory Maintenance", [
    section("factory-schedule-s1", "1.1 Factory Maintenance — foundations and vocabulary", ["foundations and vocabulary is where factory maintenance stops being abstract. In Maintenance Selling, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("factory-schedule-s2", "1.2 Factory Maintenance — how practitioners think", ["Most mistakes in factory maintenance happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("factory-schedule-s3", "1.3 Factory Maintenance — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("factory-schedule-s4", "1.4 Factory Maintenance — common failures and fixes", ["common failures and fixes is where factory maintenance stops being abstract. In Maintenance Selling, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("factory-schedule-s5", "1.5 Factory Maintenance — putting it together", ["Most mistakes in factory maintenance happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why factory maintenance matters in modern maintenance selling work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around factory maintenance","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Factory Maintenance connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master factory maintenance reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("menus", 2, "Maintenance Menus", [
    section("menus-s1", "2.1 Maintenance Menus — foundations and vocabulary", ["foundations and vocabulary is where maintenance menus stops being abstract. In Maintenance Selling, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("menus-s2", "2.2 Maintenance Menus — how practitioners think", ["Most mistakes in maintenance menus happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("menus-s3", "2.3 Maintenance Menus — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("menus-s4", "2.4 Maintenance Menus — common failures and fixes", ["common failures and fixes is where maintenance menus stops being abstract. In Maintenance Selling, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("menus-s5", "2.5 Maintenance Menus — putting it together", ["Most mistakes in maintenance menus happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why maintenance menus matters in modern maintenance selling work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around maintenance menus","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Maintenance Menus connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master maintenance menus reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("ethical-upsell", 3, "Ethical Recommendations", [
    section("ethical-upsell-s1", "3.1 Ethical Recommendations — foundations and vocabulary", ["foundations and vocabulary is where ethical recommendations stops being abstract. In Maintenance Selling, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("ethical-upsell-s2", "3.2 Ethical Recommendations — how practitioners think", ["Most mistakes in ethical recommendations happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("ethical-upsell-s3", "3.3 Ethical Recommendations — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("ethical-upsell-s4", "3.4 Ethical Recommendations — common failures and fixes", ["common failures and fixes is where ethical recommendations stops being abstract. In Maintenance Selling, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("ethical-upsell-s5", "3.5 Ethical Recommendations — putting it together", ["Most mistakes in ethical recommendations happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why ethical recommendations matters in modern maintenance selling work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around ethical recommendations","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Ethical Recommendations connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master ethical recommendations reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("declined-work", 4, "Declined Work", [
    section("declined-work-s1", "4.1 Declined Work — foundations and vocabulary", ["foundations and vocabulary is where declined work stops being abstract. In Maintenance Selling, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("declined-work-s2", "4.2 Declined Work — how practitioners think", ["Most mistakes in declined work happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("declined-work-s3", "4.3 Declined Work — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("declined-work-s4", "4.4 Declined Work — common failures and fixes", ["common failures and fixes is where declined work stops being abstract. In Maintenance Selling, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("declined-work-s5", "4.5 Declined Work — putting it together", ["Most mistakes in declined work happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why declined work matters in modern maintenance selling work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around declined work","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Declined Work connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master declined work reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("seasonal", 5, "Seasonal Services", [
    section("seasonal-s1", "5.1 Seasonal Services — foundations and vocabulary", ["foundations and vocabulary is where seasonal services stops being abstract. In Maintenance Selling, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("seasonal-s2", "5.2 Seasonal Services — how practitioners think", ["Most mistakes in seasonal services happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("seasonal-s3", "5.3 Seasonal Services — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("seasonal-s4", "5.4 Seasonal Services — common failures and fixes", ["common failures and fixes is where seasonal services stops being abstract. In Maintenance Selling, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("seasonal-s5", "5.5 Seasonal Services — putting it together", ["Most mistakes in seasonal services happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why seasonal services matters in modern maintenance selling work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around seasonal services","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Seasonal Services connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master seasonal services reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("fluids-filters", 6, "Fluids and Filters", [
    section("fluids-filters-s1", "6.1 Fluids and Filters — foundations and vocabulary", ["foundations and vocabulary is where fluids and filters stops being abstract. In Maintenance Selling, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("fluids-filters-s2", "6.2 Fluids and Filters — how practitioners think", ["Most mistakes in fluids and filters happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("fluids-filters-s3", "6.3 Fluids and Filters — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("fluids-filters-s4", "6.4 Fluids and Filters — common failures and fixes", ["common failures and fixes is where fluids and filters stops being abstract. In Maintenance Selling, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("fluids-filters-s5", "6.5 Fluids and Filters — putting it together", ["Most mistakes in fluids and filters happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why fluids and filters matters in modern maintenance selling work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around fluids and filters","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Fluids and Filters connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master fluids and filters reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("ev-maintenance", 7, "EV Maintenance", [
    section("ev-maintenance-s1", "7.1 EV Maintenance — foundations and vocabulary", ["foundations and vocabulary is where ev maintenance stops being abstract. In Maintenance Selling, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("ev-maintenance-s2", "7.2 EV Maintenance — how practitioners think", ["Most mistakes in ev maintenance happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("ev-maintenance-s3", "7.3 EV Maintenance — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("ev-maintenance-s4", "7.4 EV Maintenance — common failures and fixes", ["common failures and fixes is where ev maintenance stops being abstract. In Maintenance Selling, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("ev-maintenance-s5", "7.5 EV Maintenance — putting it together", ["Most mistakes in ev maintenance happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why ev maintenance matters in modern maintenance selling work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around ev maintenance","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "EV Maintenance connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master ev maintenance reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("tracking-maintenance", 8, "Tracking History", [
    section("tracking-maintenance-s1", "8.1 Tracking History — foundations and vocabulary", ["foundations and vocabulary is where tracking history stops being abstract. In Maintenance Selling, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("tracking-maintenance-s2", "8.2 Tracking History — how practitioners think", ["Most mistakes in tracking history happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("tracking-maintenance-s3", "8.3 Tracking History — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("tracking-maintenance-s4", "8.4 Tracking History — common failures and fixes", ["common failures and fixes is where tracking history stops being abstract. In Maintenance Selling, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("tracking-maintenance-s5", "8.5 Tracking History — putting it together", ["Most mistakes in tracking history happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why tracking history matters in modern maintenance selling work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around tracking history","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Tracking History connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master tracking history reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  })
];
