import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const NEG_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Negotiation Basics",
  subtitle: "Workforce training — Negotiation Basics",
  paragraphs: [
    "Negotiation Basics is built for professionals who want usable skill—not trivia. Each chapter moves from why the topic matters, through structured explanation, to quizzes that check judgment rather than memorization.",
    "Negotiation Basics is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Content is practical workforce education. It does not replace licensure, legal, medical, or employer-specific policy. When your organization has a rule that conflicts with a general lesson, follow your organization's rule and treat this course as context.",
  ],
};

export const NEG_TEXTBOOK: TextbookChapter[] = [
  chapter("negotiation-prep", 1, "Negotiation Preparation", [
    section("negotiation-prep-s1", "1.1 Negotiation Preparation — foundations and vocabulary", ["foundations and vocabulary is where negotiation preparation stops being abstract. In Negotiation Basics, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("negotiation-prep-s2", "1.2 Negotiation Preparation — how practitioners think", ["Most mistakes in negotiation preparation happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("negotiation-prep-s3", "1.3 Negotiation Preparation — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("negotiation-prep-s4", "1.4 Negotiation Preparation — common failures and fixes", ["common failures and fixes is where negotiation preparation stops being abstract. In Negotiation Basics, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("negotiation-prep-s5", "1.5 Negotiation Preparation — putting it together", ["Most mistakes in negotiation preparation happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why negotiation preparation matters in modern negotiation basics work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around negotiation preparation","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Negotiation Preparation connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master negotiation preparation reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("batna", 2, "BATNA and Limits", [
    section("batna-s1", "2.1 BATNA and Limits — foundations and vocabulary", ["foundations and vocabulary is where batna and limits stops being abstract. In Negotiation Basics, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("batna-s2", "2.2 BATNA and Limits — how practitioners think", ["Most mistakes in batna and limits happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("batna-s3", "2.3 BATNA and Limits — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("batna-s4", "2.4 BATNA and Limits — common failures and fixes", ["common failures and fixes is where batna and limits stops being abstract. In Negotiation Basics, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("batna-s5", "2.5 BATNA and Limits — putting it together", ["Most mistakes in batna and limits happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why batna and limits matters in modern negotiation basics work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around batna and limits","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "BATNA and Limits connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master batna and limits reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("anchoring", 3, "Anchoring and Framing", [
    section("anchoring-s1", "3.1 Anchoring and Framing — foundations and vocabulary", ["foundations and vocabulary is where anchoring and framing stops being abstract. In Negotiation Basics, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("anchoring-s2", "3.2 Anchoring and Framing — how practitioners think", ["Most mistakes in anchoring and framing happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("anchoring-s3", "3.3 Anchoring and Framing — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("anchoring-s4", "3.4 Anchoring and Framing — common failures and fixes", ["common failures and fixes is where anchoring and framing stops being abstract. In Negotiation Basics, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("anchoring-s5", "3.5 Anchoring and Framing — putting it together", ["Most mistakes in anchoring and framing happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why anchoring and framing matters in modern negotiation basics work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around anchoring and framing","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Anchoring and Framing connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master anchoring and framing reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("concessions", 4, "Trading Concessions", [
    section("concessions-s1", "4.1 Trading Concessions — foundations and vocabulary", ["foundations and vocabulary is where trading concessions stops being abstract. In Negotiation Basics, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("concessions-s2", "4.2 Trading Concessions — how practitioners think", ["Most mistakes in trading concessions happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("concessions-s3", "4.3 Trading Concessions — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("concessions-s4", "4.4 Trading Concessions — common failures and fixes", ["common failures and fixes is where trading concessions stops being abstract. In Negotiation Basics, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("concessions-s5", "4.5 Trading Concessions — putting it together", ["Most mistakes in trading concessions happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why trading concessions matters in modern negotiation basics work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around trading concessions","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Trading Concessions connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master trading concessions reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("win-win", 5, "Win-Win Outcomes", [
    section("win-win-s1", "5.1 Win-Win Outcomes — foundations and vocabulary", ["foundations and vocabulary is where win-win outcomes stops being abstract. In Negotiation Basics, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("win-win-s2", "5.2 Win-Win Outcomes — how practitioners think", ["Most mistakes in win-win outcomes happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("win-win-s3", "5.3 Win-Win Outcomes — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("win-win-s4", "5.4 Win-Win Outcomes — common failures and fixes", ["common failures and fixes is where win-win outcomes stops being abstract. In Negotiation Basics, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("win-win-s5", "5.5 Win-Win Outcomes — putting it together", ["Most mistakes in win-win outcomes happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why win-win outcomes matters in modern negotiation basics work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around win-win outcomes","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Win-Win Outcomes connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master win-win outcomes reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("difficult-negotiation", 6, "Difficult Negotiations", [
    section("difficult-negotiation-s1", "6.1 Difficult Negotiations — foundations and vocabulary", ["foundations and vocabulary is where difficult negotiations stops being abstract. In Negotiation Basics, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("difficult-negotiation-s2", "6.2 Difficult Negotiations — how practitioners think", ["Most mistakes in difficult negotiations happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("difficult-negotiation-s3", "6.3 Difficult Negotiations — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("difficult-negotiation-s4", "6.4 Difficult Negotiations — common failures and fixes", ["common failures and fixes is where difficult negotiations stops being abstract. In Negotiation Basics, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("difficult-negotiation-s5", "6.5 Difficult Negotiations — putting it together", ["Most mistakes in difficult negotiations happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why difficult negotiations matters in modern negotiation basics work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around difficult negotiations","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Difficult Negotiations connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master difficult negotiations reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("contracts-negotiation", 7, "Contract Basics in Deals", [
    section("contracts-negotiation-s1", "7.1 Contract Basics in Deals — foundations and vocabulary", ["foundations and vocabulary is where contract basics in deals stops being abstract. In Negotiation Basics, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("contracts-negotiation-s2", "7.2 Contract Basics in Deals — how practitioners think", ["Most mistakes in contract basics in deals happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("contracts-negotiation-s3", "7.3 Contract Basics in Deals — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("contracts-negotiation-s4", "7.4 Contract Basics in Deals — common failures and fixes", ["common failures and fixes is where contract basics in deals stops being abstract. In Negotiation Basics, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("contracts-negotiation-s5", "7.5 Contract Basics in Deals — putting it together", ["Most mistakes in contract basics in deals happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why contract basics in deals matters in modern negotiation basics work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around contract basics in deals","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Contract Basics in Deals connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master contract basics in deals reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("negotiation-ethics", 8, "Negotiation Ethics", [
    section("negotiation-ethics-s1", "8.1 Negotiation Ethics — foundations and vocabulary", ["foundations and vocabulary is where negotiation ethics stops being abstract. In Negotiation Basics, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("negotiation-ethics-s2", "8.2 Negotiation Ethics — how practitioners think", ["Most mistakes in negotiation ethics happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("negotiation-ethics-s3", "8.3 Negotiation Ethics — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("negotiation-ethics-s4", "8.4 Negotiation Ethics — common failures and fixes", ["common failures and fixes is where negotiation ethics stops being abstract. In Negotiation Basics, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("negotiation-ethics-s5", "8.5 Negotiation Ethics — putting it together", ["Most mistakes in negotiation ethics happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why negotiation ethics matters in modern negotiation basics work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around negotiation ethics","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Negotiation Ethics connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master negotiation ethics reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  })
];
