import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const NET_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Networking Basics",
  subtitle: "ForgEd path course — Networking Basics",
  paragraphs: [
    "Networking Basics is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Each chapter includes five sections and section quizzes. Pass chapter quizzes, the course review, and final exam to mark the course complete.",
    "Content is practical workforce education — not licensure, legal, or financial advice.",
  ],
};

export const NET_TEXTBOOK: TextbookChapter[] = [
  chapter("network-models", 1, "Network Models", [
      section("network-models-s1", "1.1 Network Models — applied practice (1)", ["1.1 Network Models — applied practice (1) connects Network Models to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("network-models-s2", "1.2 Network Models — applied practice (2)", ["1.2 Network Models — applied practice (2) connects Network Models to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("network-models-s3", "1.3 Network Models — applied practice (3)", ["1.3 Network Models — applied practice (3) connects Network Models to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("network-models-s4", "1.4 Network Models — applied practice (4)", ["1.4 Network Models — applied practice (4) connects Network Models to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("network-models-s5", "1.5 Network Models — applied practice (5)", ["1.5 Network Models — applied practice (5) connects Network Models to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("ip-addressing", 2, "IP Addressing", [
      section("ip-addressing-s1", "2.1 IP Addressing — applied practice (1)", ["2.1 IP Addressing — applied practice (1) connects IP Addressing to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ip-addressing-s2", "2.2 IP Addressing — applied practice (2)", ["2.2 IP Addressing — applied practice (2) connects IP Addressing to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ip-addressing-s3", "2.3 IP Addressing — applied practice (3)", ["2.3 IP Addressing — applied practice (3) connects IP Addressing to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ip-addressing-s4", "2.4 IP Addressing — applied practice (4)", ["2.4 IP Addressing — applied practice (4) connects IP Addressing to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ip-addressing-s5", "2.5 IP Addressing — applied practice (5)", ["2.5 IP Addressing — applied practice (5) connects IP Addressing to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("dns-basics", 3, "DNS", [
      section("dns-basics-s1", "3.1 DNS — applied practice (1)", ["3.1 DNS — applied practice (1) connects DNS to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("dns-basics-s2", "3.2 DNS — applied practice (2)", ["3.2 DNS — applied practice (2) connects DNS to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("dns-basics-s3", "3.3 DNS — applied practice (3)", ["3.3 DNS — applied practice (3) connects DNS to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("dns-basics-s4", "3.4 DNS — applied practice (4)", ["3.4 DNS — applied practice (4) connects DNS to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("dns-basics-s5", "3.5 DNS — applied practice (5)", ["3.5 DNS — applied practice (5) connects DNS to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("wifi-basics", 4, "Wi-Fi", [
      section("wifi-basics-s1", "4.1 Wi-Fi — applied practice (1)", ["4.1 Wi-Fi — applied practice (1) connects Wi-Fi to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("wifi-basics-s2", "4.2 Wi-Fi — applied practice (2)", ["4.2 Wi-Fi — applied practice (2) connects Wi-Fi to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("wifi-basics-s3", "4.3 Wi-Fi — applied practice (3)", ["4.3 Wi-Fi — applied practice (3) connects Wi-Fi to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("wifi-basics-s4", "4.4 Wi-Fi — applied practice (4)", ["4.4 Wi-Fi — applied practice (4) connects Wi-Fi to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("wifi-basics-s5", "4.5 Wi-Fi — applied practice (5)", ["4.5 Wi-Fi — applied practice (5) connects Wi-Fi to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("ethernet", 5, "Ethernet and Switches", [
      section("ethernet-s1", "5.1 Ethernet and Switches — applied practice (1)", ["5.1 Ethernet and Switches — applied practice (1) connects Ethernet and Switches to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ethernet-s2", "5.2 Ethernet and Switches — applied practice (2)", ["5.2 Ethernet and Switches — applied practice (2) connects Ethernet and Switches to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ethernet-s3", "5.3 Ethernet and Switches — applied practice (3)", ["5.3 Ethernet and Switches — applied practice (3) connects Ethernet and Switches to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ethernet-s4", "5.4 Ethernet and Switches — applied practice (4)", ["5.4 Ethernet and Switches — applied practice (4) connects Ethernet and Switches to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ethernet-s5", "5.5 Ethernet and Switches — applied practice (5)", ["5.5 Ethernet and Switches — applied practice (5) connects Ethernet and Switches to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("vpn-basics", 6, "VPN Basics", [
      section("vpn-basics-s1", "6.1 VPN Basics — applied practice (1)", ["6.1 VPN Basics — applied practice (1) connects VPN Basics to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("vpn-basics-s2", "6.2 VPN Basics — applied practice (2)", ["6.2 VPN Basics — applied practice (2) connects VPN Basics to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("vpn-basics-s3", "6.3 VPN Basics — applied practice (3)", ["6.3 VPN Basics — applied practice (3) connects VPN Basics to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("vpn-basics-s4", "6.4 VPN Basics — applied practice (4)", ["6.4 VPN Basics — applied practice (4) connects VPN Basics to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("vpn-basics-s5", "6.5 VPN Basics — applied practice (5)", ["6.5 VPN Basics — applied practice (5) connects VPN Basics to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("troubleshoot-net", 7, "Network Troubleshooting", [
      section("troubleshoot-net-s1", "7.1 Network Troubleshooting — applied practice (1)", ["7.1 Network Troubleshooting — applied practice (1) connects Network Troubleshooting to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("troubleshoot-net-s2", "7.2 Network Troubleshooting — applied practice (2)", ["7.2 Network Troubleshooting — applied practice (2) connects Network Troubleshooting to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("troubleshoot-net-s3", "7.3 Network Troubleshooting — applied practice (3)", ["7.3 Network Troubleshooting — applied practice (3) connects Network Troubleshooting to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("troubleshoot-net-s4", "7.4 Network Troubleshooting — applied practice (4)", ["7.4 Network Troubleshooting — applied practice (4) connects Network Troubleshooting to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("troubleshoot-net-s5", "7.5 Network Troubleshooting — applied practice (5)", ["7.5 Network Troubleshooting — applied practice (5) connects Network Troubleshooting to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("home-office-net", 8, "Home and Office Networks", [
      section("home-office-net-s1", "8.1 Home and Office Networks — applied practice (1)", ["8.1 Home and Office Networks — applied practice (1) connects Home and Office Networks to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("home-office-net-s2", "8.2 Home and Office Networks — applied practice (2)", ["8.2 Home and Office Networks — applied practice (2) connects Home and Office Networks to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("home-office-net-s3", "8.3 Home and Office Networks — applied practice (3)", ["8.3 Home and Office Networks — applied practice (3) connects Home and Office Networks to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("home-office-net-s4", "8.4 Home and Office Networks — applied practice (4)", ["8.4 Home and Office Networks — applied practice (4) connects Home and Office Networks to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("home-office-net-s5", "8.5 Home and Office Networks — applied practice (5)", ["8.5 Home and Office Networks — applied practice (5) connects Home and Office Networks to real workforce outcomes in Networking Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ])
];
