import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const PASS_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Password Security",
  subtitle: "ForgEd path course — Password Security",
  paragraphs: [
    "Password Security is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Each chapter includes five sections and section quizzes. Pass chapter quizzes, the course review, and final exam to mark the course complete.",
    "Content is practical workforce education — not licensure, legal, or financial advice.",
  ],
};

export const PASS_TEXTBOOK: TextbookChapter[] = [
  chapter("password-strength", 1, "Password Strength", [
      section("password-strength-s1", "1.1 Password Strength — applied practice (1)", ["1.1 Password Strength — applied practice (1) connects Password Strength to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("password-strength-s2", "1.2 Password Strength — applied practice (2)", ["1.2 Password Strength — applied practice (2) connects Password Strength to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("password-strength-s3", "1.3 Password Strength — applied practice (3)", ["1.3 Password Strength — applied practice (3) connects Password Strength to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("password-strength-s4", "1.4 Password Strength — applied practice (4)", ["1.4 Password Strength — applied practice (4) connects Password Strength to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("password-strength-s5", "1.5 Password Strength — applied practice (5)", ["1.5 Password Strength — applied practice (5) connects Password Strength to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("mfa-types", 2, "MFA Types", [
      section("mfa-types-s1", "2.1 MFA Types — applied practice (1)", ["2.1 MFA Types — applied practice (1) connects MFA Types to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("mfa-types-s2", "2.2 MFA Types — applied practice (2)", ["2.2 MFA Types — applied practice (2) connects MFA Types to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("mfa-types-s3", "2.3 MFA Types — applied practice (3)", ["2.3 MFA Types — applied practice (3) connects MFA Types to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("mfa-types-s4", "2.4 MFA Types — applied practice (4)", ["2.4 MFA Types — applied practice (4) connects MFA Types to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("mfa-types-s5", "2.5 MFA Types — applied practice (5)", ["2.5 MFA Types — applied practice (5) connects MFA Types to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("passkeys", 3, "Passkeys", [
      section("passkeys-s1", "3.1 Passkeys — applied practice (1)", ["3.1 Passkeys — applied practice (1) connects Passkeys to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("passkeys-s2", "3.2 Passkeys — applied practice (2)", ["3.2 Passkeys — applied practice (2) connects Passkeys to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("passkeys-s3", "3.3 Passkeys — applied practice (3)", ["3.3 Passkeys — applied practice (3) connects Passkeys to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("passkeys-s4", "3.4 Passkeys — applied practice (4)", ["3.4 Passkeys — applied practice (4) connects Passkeys to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("passkeys-s5", "3.5 Passkeys — applied practice (5)", ["3.5 Passkeys — applied practice (5) connects Passkeys to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("managers", 4, "Password Managers", [
      section("managers-s1", "4.1 Password Managers — applied practice (1)", ["4.1 Password Managers — applied practice (1) connects Password Managers to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("managers-s2", "4.2 Password Managers — applied practice (2)", ["4.2 Password Managers — applied practice (2) connects Password Managers to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("managers-s3", "4.3 Password Managers — applied practice (3)", ["4.3 Password Managers — applied practice (3) connects Password Managers to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("managers-s4", "4.4 Password Managers — applied practice (4)", ["4.4 Password Managers — applied practice (4) connects Password Managers to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("managers-s5", "4.5 Password Managers — applied practice (5)", ["4.5 Password Managers — applied practice (5) connects Password Managers to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("rotation-myths", 5, "Rotation Myths", [
      section("rotation-myths-s1", "5.1 Rotation Myths — applied practice (1)", ["5.1 Rotation Myths — applied practice (1) connects Rotation Myths to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("rotation-myths-s2", "5.2 Rotation Myths — applied practice (2)", ["5.2 Rotation Myths — applied practice (2) connects Rotation Myths to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("rotation-myths-s3", "5.3 Rotation Myths — applied practice (3)", ["5.3 Rotation Myths — applied practice (3) connects Rotation Myths to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("rotation-myths-s4", "5.4 Rotation Myths — applied practice (4)", ["5.4 Rotation Myths — applied practice (4) connects Rotation Myths to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("rotation-myths-s5", "5.5 Rotation Myths — applied practice (5)", ["5.5 Rotation Myths — applied practice (5) connects Rotation Myths to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("breach-response", 6, "Credential Breach Response", [
      section("breach-response-s1", "6.1 Credential Breach Response — applied practice (1)", ["6.1 Credential Breach Response — applied practice (1) connects Credential Breach Response to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("breach-response-s2", "6.2 Credential Breach Response — applied practice (2)", ["6.2 Credential Breach Response — applied practice (2) connects Credential Breach Response to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("breach-response-s3", "6.3 Credential Breach Response — applied practice (3)", ["6.3 Credential Breach Response — applied practice (3) connects Credential Breach Response to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("breach-response-s4", "6.4 Credential Breach Response — applied practice (4)", ["6.4 Credential Breach Response — applied practice (4) connects Credential Breach Response to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("breach-response-s5", "6.5 Credential Breach Response — applied practice (5)", ["6.5 Credential Breach Response — applied practice (5) connects Credential Breach Response to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("team-passwords", 7, "Team Password Policy", [
      section("team-passwords-s1", "7.1 Team Password Policy — applied practice (1)", ["7.1 Team Password Policy — applied practice (1) connects Team Password Policy to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("team-passwords-s2", "7.2 Team Password Policy — applied practice (2)", ["7.2 Team Password Policy — applied practice (2) connects Team Password Policy to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("team-passwords-s3", "7.3 Team Password Policy — applied practice (3)", ["7.3 Team Password Policy — applied practice (3) connects Team Password Policy to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("team-passwords-s4", "7.4 Team Password Policy — applied practice (4)", ["7.4 Team Password Policy — applied practice (4) connects Team Password Policy to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("team-passwords-s5", "7.5 Team Password Policy — applied practice (5)", ["7.5 Team Password Policy — applied practice (5) connects Team Password Policy to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("sso", 8, "SSO Basics", [
      section("sso-s1", "8.1 SSO Basics — applied practice (1)", ["8.1 SSO Basics — applied practice (1) connects SSO Basics to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("sso-s2", "8.2 SSO Basics — applied practice (2)", ["8.2 SSO Basics — applied practice (2) connects SSO Basics to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("sso-s3", "8.3 SSO Basics — applied practice (3)", ["8.3 SSO Basics — applied practice (3) connects SSO Basics to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("sso-s4", "8.4 SSO Basics — applied practice (4)", ["8.4 SSO Basics — applied practice (4) connects SSO Basics to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("sso-s5", "8.5 SSO Basics — applied practice (5)", ["8.5 SSO Basics — applied practice (5) connects SSO Basics to real workforce outcomes in Password Security. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ])
];
