import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const PASS_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Password Security",
  subtitle: "Workforce training — Password Security",
  paragraphs: [
    "Password Security is built for professionals who want usable skill—not trivia. Each chapter moves from why the topic matters, through structured explanation, to quizzes that check judgment rather than memorization.",
    "Password Security is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Content is practical workforce education. It does not replace licensure, legal, medical, or employer-specific policy. When your organization has a rule that conflicts with a general lesson, follow your organization's rule and treat this course as context.",
  ],
};

export const PASS_TEXTBOOK: TextbookChapter[] = [
  chapter("password-strength", 1, "Password Strength", [
    section("password-strength-s1", "1.1 Password Strength — foundations and vocabulary", ["foundations and vocabulary is where password strength stops being abstract. In Password Security, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Security habits are boring until the day they prevent an expensive incident. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("password-strength-s2", "1.2 Password Strength — how practitioners think", ["Most mistakes in password strength happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Attackers optimize for speed; defenders win by making cheap mistakes expensive. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("password-strength-s3", "1.3 Password Strength — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Security habits are boring until the day they prevent an expensive incident. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("password-strength-s4", "1.4 Password Strength — common failures and fixes", ["common failures and fixes is where password strength stops being abstract. In Password Security, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Attackers optimize for speed; defenders win by making cheap mistakes expensive. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("password-strength-s5", "1.5 Password Strength — putting it together", ["Most mistakes in password strength happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","Security habits are boring until the day they prevent an expensive incident. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why password strength matters in modern password security work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around password strength","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Password Strength connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master password strength reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("mfa-types", 2, "MFA Types", [
    section("mfa-types-s1", "2.1 MFA Types — foundations and vocabulary", ["foundations and vocabulary is where mfa types stops being abstract. In Password Security, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Security habits are boring until the day they prevent an expensive incident. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("mfa-types-s2", "2.2 MFA Types — how practitioners think", ["Most mistakes in mfa types happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Attackers optimize for speed; defenders win by making cheap mistakes expensive. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("mfa-types-s3", "2.3 MFA Types — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Security habits are boring until the day they prevent an expensive incident. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("mfa-types-s4", "2.4 MFA Types — common failures and fixes", ["common failures and fixes is where mfa types stops being abstract. In Password Security, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Attackers optimize for speed; defenders win by making cheap mistakes expensive. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("mfa-types-s5", "2.5 MFA Types — putting it together", ["Most mistakes in mfa types happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","Security habits are boring until the day they prevent an expensive incident. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why mfa types matters in modern password security work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around mfa types","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "MFA Types connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master mfa types reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("passkeys", 3, "Passkeys", [
    section("passkeys-s1", "3.1 Passkeys — foundations and vocabulary", ["foundations and vocabulary is where passkeys stops being abstract. In Password Security, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Security habits are boring until the day they prevent an expensive incident. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("passkeys-s2", "3.2 Passkeys — how practitioners think", ["Most mistakes in passkeys happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Attackers optimize for speed; defenders win by making cheap mistakes expensive. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("passkeys-s3", "3.3 Passkeys — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Security habits are boring until the day they prevent an expensive incident. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("passkeys-s4", "3.4 Passkeys — common failures and fixes", ["common failures and fixes is where passkeys stops being abstract. In Password Security, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Attackers optimize for speed; defenders win by making cheap mistakes expensive. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("passkeys-s5", "3.5 Passkeys — putting it together", ["Most mistakes in passkeys happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","Security habits are boring until the day they prevent an expensive incident. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why passkeys matters in modern password security work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around passkeys","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Passkeys connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master passkeys reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("managers", 4, "Password Managers", [
    section("managers-s1", "4.1 Password Managers — foundations and vocabulary", ["foundations and vocabulary is where password managers stops being abstract. In Password Security, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Security habits are boring until the day they prevent an expensive incident. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("managers-s2", "4.2 Password Managers — how practitioners think", ["Most mistakes in password managers happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Attackers optimize for speed; defenders win by making cheap mistakes expensive. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("managers-s3", "4.3 Password Managers — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Security habits are boring until the day they prevent an expensive incident. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("managers-s4", "4.4 Password Managers — common failures and fixes", ["common failures and fixes is where password managers stops being abstract. In Password Security, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Attackers optimize for speed; defenders win by making cheap mistakes expensive. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("managers-s5", "4.5 Password Managers — putting it together", ["Most mistakes in password managers happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","Security habits are boring until the day they prevent an expensive incident. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why password managers matters in modern password security work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around password managers","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Password Managers connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master password managers reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("rotation-myths", 5, "Rotation Myths", [
    section("rotation-myths-s1", "5.1 Rotation Myths — foundations and vocabulary", ["foundations and vocabulary is where rotation myths stops being abstract. In Password Security, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Security habits are boring until the day they prevent an expensive incident. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("rotation-myths-s2", "5.2 Rotation Myths — how practitioners think", ["Most mistakes in rotation myths happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Attackers optimize for speed; defenders win by making cheap mistakes expensive. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("rotation-myths-s3", "5.3 Rotation Myths — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Security habits are boring until the day they prevent an expensive incident. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("rotation-myths-s4", "5.4 Rotation Myths — common failures and fixes", ["common failures and fixes is where rotation myths stops being abstract. In Password Security, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Attackers optimize for speed; defenders win by making cheap mistakes expensive. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("rotation-myths-s5", "5.5 Rotation Myths — putting it together", ["Most mistakes in rotation myths happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","Security habits are boring until the day they prevent an expensive incident. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why rotation myths matters in modern password security work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around rotation myths","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Rotation Myths connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master rotation myths reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("breach-response", 6, "Credential Breach Response", [
    section("breach-response-s1", "6.1 Credential Breach Response — foundations and vocabulary", ["foundations and vocabulary is where credential breach response stops being abstract. In Password Security, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Security habits are boring until the day they prevent an expensive incident. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("breach-response-s2", "6.2 Credential Breach Response — how practitioners think", ["Most mistakes in credential breach response happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Attackers optimize for speed; defenders win by making cheap mistakes expensive. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("breach-response-s3", "6.3 Credential Breach Response — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Security habits are boring until the day they prevent an expensive incident. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("breach-response-s4", "6.4 Credential Breach Response — common failures and fixes", ["common failures and fixes is where credential breach response stops being abstract. In Password Security, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Attackers optimize for speed; defenders win by making cheap mistakes expensive. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("breach-response-s5", "6.5 Credential Breach Response — putting it together", ["Most mistakes in credential breach response happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","Security habits are boring until the day they prevent an expensive incident. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why credential breach response matters in modern password security work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around credential breach response","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Credential Breach Response connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master credential breach response reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("team-passwords", 7, "Team Password Policy", [
    section("team-passwords-s1", "7.1 Team Password Policy — foundations and vocabulary", ["foundations and vocabulary is where team password policy stops being abstract. In Password Security, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Security habits are boring until the day they prevent an expensive incident. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("team-passwords-s2", "7.2 Team Password Policy — how practitioners think", ["Most mistakes in team password policy happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Attackers optimize for speed; defenders win by making cheap mistakes expensive. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("team-passwords-s3", "7.3 Team Password Policy — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Security habits are boring until the day they prevent an expensive incident. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("team-passwords-s4", "7.4 Team Password Policy — common failures and fixes", ["common failures and fixes is where team password policy stops being abstract. In Password Security, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Attackers optimize for speed; defenders win by making cheap mistakes expensive. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("team-passwords-s5", "7.5 Team Password Policy — putting it together", ["Most mistakes in team password policy happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","Security habits are boring until the day they prevent an expensive incident. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why team password policy matters in modern password security work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around team password policy","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Team Password Policy connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master team password policy reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("sso", 8, "SSO Basics", [
    section("sso-s1", "8.1 SSO Basics — foundations and vocabulary", ["foundations and vocabulary is where sso basics stops being abstract. In Password Security, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Security habits are boring until the day they prevent an expensive incident. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("sso-s2", "8.2 SSO Basics — how practitioners think", ["Most mistakes in sso basics happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Attackers optimize for speed; defenders win by making cheap mistakes expensive. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("sso-s3", "8.3 SSO Basics — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Security habits are boring until the day they prevent an expensive incident. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("sso-s4", "8.4 SSO Basics — common failures and fixes", ["common failures and fixes is where sso basics stops being abstract. In Password Security, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Attackers optimize for speed; defenders win by making cheap mistakes expensive. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("sso-s5", "8.5 SSO Basics — putting it together", ["Most mistakes in sso basics happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","Security habits are boring until the day they prevent an expensive incident. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why sso basics matters in modern password security work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around sso basics","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "SSO Basics connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master sso basics reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  })
];
