import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const PDEV_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Personal Development Fundamentals",
  subtitle: "ForgEd deep-dive — personal development fundamentals",
  paragraphs: [
    "This ForgEd digital textbook presents Personal Development Fundamentals at academic survey depth for self-paced study.",
    "Complete each section quiz before advancing. Chapter and course assessments draw from a 150-question bank.",
    "Material is general education, not professional licensure or certification prep by itself.",
  ],
};

export const PDEV_TEXTBOOK: TextbookChapter[] = [
  chapter("growth-mindset", 1, "Growth Mindset", [
      section("growth-mindset-s1", "1.1 Growth Mindset — core concepts (1)", ["1.1 Growth Mindset — core concepts (1) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply growth mindset with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in growth mindset."]),
      section("growth-mindset-s2", "1.2 Growth Mindset — core concepts (2)", ["1.2 Growth Mindset — core concepts (2) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply growth mindset with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in growth mindset."]),
      section("growth-mindset-s3", "1.3 Growth Mindset — core concepts (3)", ["1.3 Growth Mindset — core concepts (3) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply growth mindset with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in growth mindset."]),
      section("growth-mindset-s4", "1.4 Growth Mindset — core concepts (4)", ["1.4 Growth Mindset — core concepts (4) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply growth mindset with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in growth mindset."]),
      section("growth-mindset-s5", "1.5 Growth Mindset — core concepts (5)", ["1.5 Growth Mindset — core concepts (5) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply growth mindset with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in growth mindset."]),
  ]),
  chapter("goal-setting", 2, "Goal Setting", [
      section("goal-setting-s1", "2.1 Goal Setting — core concepts (1)", ["2.1 Goal Setting — core concepts (1) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply goal setting with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in goal setting."]),
      section("goal-setting-s2", "2.2 Goal Setting — core concepts (2)", ["2.2 Goal Setting — core concepts (2) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply goal setting with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in goal setting."]),
      section("goal-setting-s3", "2.3 Goal Setting — core concepts (3)", ["2.3 Goal Setting — core concepts (3) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply goal setting with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in goal setting."]),
      section("goal-setting-s4", "2.4 Goal Setting — core concepts (4)", ["2.4 Goal Setting — core concepts (4) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply goal setting with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in goal setting."]),
      section("goal-setting-s5", "2.5 Goal Setting — core concepts (5)", ["2.5 Goal Setting — core concepts (5) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply goal setting with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in goal setting."]),
  ]),
  chapter("habits", 3, "Habits and Routines", [
      section("habits-s1", "3.1 Habits and Routines — core concepts (1)", ["3.1 Habits and Routines — core concepts (1) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply habits and routines with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in habits and routines."]),
      section("habits-s2", "3.2 Habits and Routines — core concepts (2)", ["3.2 Habits and Routines — core concepts (2) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply habits and routines with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in habits and routines."]),
      section("habits-s3", "3.3 Habits and Routines — core concepts (3)", ["3.3 Habits and Routines — core concepts (3) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply habits and routines with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in habits and routines."]),
      section("habits-s4", "3.4 Habits and Routines — core concepts (4)", ["3.4 Habits and Routines — core concepts (4) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply habits and routines with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in habits and routines."]),
      section("habits-s5", "3.5 Habits and Routines — core concepts (5)", ["3.5 Habits and Routines — core concepts (5) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply habits and routines with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in habits and routines."]),
  ]),
  chapter("time-management", 4, "Time Management", [
      section("time-management-s1", "4.1 Time Management — core concepts (1)", ["4.1 Time Management — core concepts (1) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply time management with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in time management."]),
      section("time-management-s2", "4.2 Time Management — core concepts (2)", ["4.2 Time Management — core concepts (2) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply time management with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in time management."]),
      section("time-management-s3", "4.3 Time Management — core concepts (3)", ["4.3 Time Management — core concepts (3) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply time management with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in time management."]),
      section("time-management-s4", "4.4 Time Management — core concepts (4)", ["4.4 Time Management — core concepts (4) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply time management with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in time management."]),
      section("time-management-s5", "4.5 Time Management — core concepts (5)", ["4.5 Time Management — core concepts (5) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply time management with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in time management."]),
  ]),
  chapter("communication-self", 5, "Self and Social Skills", [
      section("communication-self-s1", "5.1 Self and Social Skills — core concepts (1)", ["5.1 Self and Social Skills — core concepts (1) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply self and social skills with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in self and social skills."]),
      section("communication-self-s2", "5.2 Self and Social Skills — core concepts (2)", ["5.2 Self and Social Skills — core concepts (2) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply self and social skills with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in self and social skills."]),
      section("communication-self-s3", "5.3 Self and Social Skills — core concepts (3)", ["5.3 Self and Social Skills — core concepts (3) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply self and social skills with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in self and social skills."]),
      section("communication-self-s4", "5.4 Self and Social Skills — core concepts (4)", ["5.4 Self and Social Skills — core concepts (4) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply self and social skills with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in self and social skills."]),
      section("communication-self-s5", "5.5 Self and Social Skills — core concepts (5)", ["5.5 Self and Social Skills — core concepts (5) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply self and social skills with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in self and social skills."]),
  ]),
  chapter("stress-resilience", 6, "Stress and Resilience", [
      section("stress-resilience-s1", "6.1 Stress and Resilience — core concepts (1)", ["6.1 Stress and Resilience — core concepts (1) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply stress and resilience with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in stress and resilience."]),
      section("stress-resilience-s2", "6.2 Stress and Resilience — core concepts (2)", ["6.2 Stress and Resilience — core concepts (2) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply stress and resilience with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in stress and resilience."]),
      section("stress-resilience-s3", "6.3 Stress and Resilience — core concepts (3)", ["6.3 Stress and Resilience — core concepts (3) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply stress and resilience with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in stress and resilience."]),
      section("stress-resilience-s4", "6.4 Stress and Resilience — core concepts (4)", ["6.4 Stress and Resilience — core concepts (4) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply stress and resilience with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in stress and resilience."]),
      section("stress-resilience-s5", "6.5 Stress and Resilience — core concepts (5)", ["6.5 Stress and Resilience — core concepts (5) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply stress and resilience with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in stress and resilience."]),
  ]),
  chapter("financial-wellness", 7, "Financial Wellness", [
      section("financial-wellness-s1", "7.1 Financial Wellness — core concepts (1)", ["7.1 Financial Wellness — core concepts (1) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply financial wellness with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in financial wellness."]),
      section("financial-wellness-s2", "7.2 Financial Wellness — core concepts (2)", ["7.2 Financial Wellness — core concepts (2) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply financial wellness with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in financial wellness."]),
      section("financial-wellness-s3", "7.3 Financial Wellness — core concepts (3)", ["7.3 Financial Wellness — core concepts (3) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply financial wellness with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in financial wellness."]),
      section("financial-wellness-s4", "7.4 Financial Wellness — core concepts (4)", ["7.4 Financial Wellness — core concepts (4) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply financial wellness with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in financial wellness."]),
      section("financial-wellness-s5", "7.5 Financial Wellness — core concepts (5)", ["7.5 Financial Wellness — core concepts (5) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply financial wellness with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in financial wellness."]),
  ]),
  chapter("career-growth", 8, "Career Growth", [
      section("career-growth-s1", "8.1 Career Growth — core concepts (1)", ["8.1 Career Growth — core concepts (1) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply career growth with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in career growth."]),
      section("career-growth-s2", "8.2 Career Growth — core concepts (2)", ["8.2 Career Growth — core concepts (2) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply career growth with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in career growth."]),
      section("career-growth-s3", "8.3 Career Growth — core concepts (3)", ["8.3 Career Growth — core concepts (3) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply career growth with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in career growth."]),
      section("career-growth-s4", "8.4 Career Growth — core concepts (4)", ["8.4 Career Growth — core concepts (4) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply career growth with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in career growth."]),
      section("career-growth-s5", "8.5 Career Growth — core concepts (5)", ["8.5 Career Growth — core concepts (5) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply career growth with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in career growth."]),
  ]),
  chapter("learning-how", 9, "Learning How to Learn", [
      section("learning-how-s1", "9.1 Learning How to Learn — core concepts (1)", ["9.1 Learning How to Learn — core concepts (1) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply learning how to learn with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in learning how to learn."]),
      section("learning-how-s2", "9.2 Learning How to Learn — core concepts (2)", ["9.2 Learning How to Learn — core concepts (2) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply learning how to learn with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in learning how to learn."]),
      section("learning-how-s3", "9.3 Learning How to Learn — core concepts (3)", ["9.3 Learning How to Learn — core concepts (3) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply learning how to learn with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in learning how to learn."]),
      section("learning-how-s4", "9.4 Learning How to Learn — core concepts (4)", ["9.4 Learning How to Learn — core concepts (4) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply learning how to learn with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in learning how to learn."]),
      section("learning-how-s5", "9.5 Learning How to Learn — core concepts (5)", ["9.5 Learning How to Learn — core concepts (5) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply learning how to learn with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in learning how to learn."]),
  ]),
  chapter("life-design", 10, "Life Design", [
      section("life-design-s1", "10.1 Life Design — core concepts (1)", ["10.1 Life Design — core concepts (1) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply life design with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in life design."]),
      section("life-design-s2", "10.2 Life Design — core concepts (2)", ["10.2 Life Design — core concepts (2) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply life design with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in life design."]),
      section("life-design-s3", "10.3 Life Design — core concepts (3)", ["10.3 Life Design — core concepts (3) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply life design with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in life design."]),
      section("life-design-s4", "10.4 Life Design — core concepts (4)", ["10.4 Life Design — core concepts (4) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply life design with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in life design."]),
      section("life-design-s5", "10.5 Life Design — core concepts (5)", ["10.5 Life Design — core concepts (5) is a core topic in Personal Development Fundamentals. Learners should connect definitions to how professionals apply life design with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in life design."]),
  ])
];
