import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const PHISH_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Phishing Defense",
  subtitle: "Workforce training — Phishing Defense",
  paragraphs: [
    "Phishing Defense is built for professionals who want usable skill—not trivia. Each chapter moves from why the topic matters, through structured explanation, to quizzes that check judgment rather than memorization.",
    "Phishing Defense is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Content is practical workforce education. It does not replace licensure, legal, medical, or employer-specific policy. When your organization has a rule that conflicts with a general lesson, follow your organization's rule and treat this course as context.",
  ],
};

export const PHISH_TEXTBOOK: TextbookChapter[] = [
  chapter("phishing-types", 1, "Phishing Types", [
    section("phishing-types-s1", "1.1 Phishing Types — foundations and vocabulary", ["foundations and vocabulary is where phishing types stops being abstract. In Phishing Defense, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Security habits are boring until the day they prevent an expensive incident. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("phishing-types-s2", "1.2 Phishing Types — how practitioners think", ["Most mistakes in phishing types happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Attackers optimize for speed; defenders win by making cheap mistakes expensive. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("phishing-types-s3", "1.3 Phishing Types — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Security habits are boring until the day they prevent an expensive incident. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("phishing-types-s4", "1.4 Phishing Types — common failures and fixes", ["common failures and fixes is where phishing types stops being abstract. In Phishing Defense, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Attackers optimize for speed; defenders win by making cheap mistakes expensive. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("phishing-types-s5", "1.5 Phishing Types — putting it together", ["Most mistakes in phishing types happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","Security habits are boring until the day they prevent an expensive incident. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why phishing types matters in modern phishing defense work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around phishing types","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Phishing Types connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master phishing types reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("email-signals", 2, "Email Red Flags", [
    section("email-signals-s1", "2.1 Email Red Flags — foundations and vocabulary", ["foundations and vocabulary is where email red flags stops being abstract. In Phishing Defense, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Security habits are boring until the day they prevent an expensive incident. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("email-signals-s2", "2.2 Email Red Flags — how practitioners think", ["Most mistakes in email red flags happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Attackers optimize for speed; defenders win by making cheap mistakes expensive. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("email-signals-s3", "2.3 Email Red Flags — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Security habits are boring until the day they prevent an expensive incident. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("email-signals-s4", "2.4 Email Red Flags — common failures and fixes", ["common failures and fixes is where email red flags stops being abstract. In Phishing Defense, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Attackers optimize for speed; defenders win by making cheap mistakes expensive. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("email-signals-s5", "2.5 Email Red Flags — putting it together", ["Most mistakes in email red flags happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","Security habits are boring until the day they prevent an expensive incident. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why email red flags matters in modern phishing defense work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around email red flags","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Email Red Flags connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master email red flags reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("smishing", 3, "Smishing and Vishing", [
    section("smishing-s1", "3.1 Smishing and Vishing — foundations and vocabulary", ["foundations and vocabulary is where smishing and vishing stops being abstract. In Phishing Defense, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Security habits are boring until the day they prevent an expensive incident. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("smishing-s2", "3.2 Smishing and Vishing — how practitioners think", ["Most mistakes in smishing and vishing happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Attackers optimize for speed; defenders win by making cheap mistakes expensive. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("smishing-s3", "3.3 Smishing and Vishing — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Security habits are boring until the day they prevent an expensive incident. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("smishing-s4", "3.4 Smishing and Vishing — common failures and fixes", ["common failures and fixes is where smishing and vishing stops being abstract. In Phishing Defense, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Attackers optimize for speed; defenders win by making cheap mistakes expensive. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("smishing-s5", "3.5 Smishing and Vishing — putting it together", ["Most mistakes in smishing and vishing happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","Security habits are boring until the day they prevent an expensive incident. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why smishing and vishing matters in modern phishing defense work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around smishing and vishing","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Smishing and Vishing connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master smishing and vishing reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("bec", 4, "Business Email Compromise", [
    section("bec-s1", "4.1 Business Email Compromise — foundations and vocabulary", ["foundations and vocabulary is where business email compromise stops being abstract. In Phishing Defense, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Security habits are boring until the day they prevent an expensive incident. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("bec-s2", "4.2 Business Email Compromise — how practitioners think", ["Most mistakes in business email compromise happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Attackers optimize for speed; defenders win by making cheap mistakes expensive. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("bec-s3", "4.3 Business Email Compromise — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Security habits are boring until the day they prevent an expensive incident. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("bec-s4", "4.4 Business Email Compromise — common failures and fixes", ["common failures and fixes is where business email compromise stops being abstract. In Phishing Defense, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Attackers optimize for speed; defenders win by making cheap mistakes expensive. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("bec-s5", "4.5 Business Email Compromise — putting it together", ["Most mistakes in business email compromise happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","Security habits are boring until the day they prevent an expensive incident. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why business email compromise matters in modern phishing defense work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around business email compromise","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Business Email Compromise connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master business email compromise reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("report-phish", 5, "Reporting Phishing", [
    section("report-phish-s1", "5.1 Reporting Phishing — foundations and vocabulary", ["foundations and vocabulary is where reporting phishing stops being abstract. In Phishing Defense, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Security habits are boring until the day they prevent an expensive incident. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("report-phish-s2", "5.2 Reporting Phishing — how practitioners think", ["Most mistakes in reporting phishing happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Attackers optimize for speed; defenders win by making cheap mistakes expensive. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("report-phish-s3", "5.3 Reporting Phishing — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Security habits are boring until the day they prevent an expensive incident. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("report-phish-s4", "5.4 Reporting Phishing — common failures and fixes", ["common failures and fixes is where reporting phishing stops being abstract. In Phishing Defense, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Attackers optimize for speed; defenders win by making cheap mistakes expensive. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("report-phish-s5", "5.5 Reporting Phishing — putting it together", ["Most mistakes in reporting phishing happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","Security habits are boring until the day they prevent an expensive incident. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why reporting phishing matters in modern phishing defense work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around reporting phishing","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Reporting Phishing connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master reporting phishing reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("simulations", 6, "Phishing Simulations", [
    section("simulations-s1", "6.1 Phishing Simulations — foundations and vocabulary", ["foundations and vocabulary is where phishing simulations stops being abstract. In Phishing Defense, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Security habits are boring until the day they prevent an expensive incident. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("simulations-s2", "6.2 Phishing Simulations — how practitioners think", ["Most mistakes in phishing simulations happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Attackers optimize for speed; defenders win by making cheap mistakes expensive. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("simulations-s3", "6.3 Phishing Simulations — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Security habits are boring until the day they prevent an expensive incident. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("simulations-s4", "6.4 Phishing Simulations — common failures and fixes", ["common failures and fixes is where phishing simulations stops being abstract. In Phishing Defense, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Attackers optimize for speed; defenders win by making cheap mistakes expensive. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("simulations-s5", "6.5 Phishing Simulations — putting it together", ["Most mistakes in phishing simulations happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","Security habits are boring until the day they prevent an expensive incident. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why phishing simulations matters in modern phishing defense work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around phishing simulations","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Phishing Simulations connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master phishing simulations reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("user-training", 7, "Security Awareness", [
    section("user-training-s1", "7.1 Security Awareness — foundations and vocabulary", ["foundations and vocabulary is where security awareness stops being abstract. In Phishing Defense, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Security habits are boring until the day they prevent an expensive incident. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("user-training-s2", "7.2 Security Awareness — how practitioners think", ["Most mistakes in security awareness happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Attackers optimize for speed; defenders win by making cheap mistakes expensive. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("user-training-s3", "7.3 Security Awareness — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Security habits are boring until the day they prevent an expensive incident. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("user-training-s4", "7.4 Security Awareness — common failures and fixes", ["common failures and fixes is where security awareness stops being abstract. In Phishing Defense, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Attackers optimize for speed; defenders win by making cheap mistakes expensive. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("user-training-s5", "7.5 Security Awareness — putting it together", ["Most mistakes in security awareness happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","Security habits are boring until the day they prevent an expensive incident. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why security awareness matters in modern phishing defense work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around security awareness","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Security Awareness connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master security awareness reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("recovery-phish", 8, "After a Click", [
    section("recovery-phish-s1", "8.1 After a Click — foundations and vocabulary", ["foundations and vocabulary is where after a click stops being abstract. In Phishing Defense, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Security habits are boring until the day they prevent an expensive incident. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("recovery-phish-s2", "8.2 After a Click — how practitioners think", ["Most mistakes in after a click happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Attackers optimize for speed; defenders win by making cheap mistakes expensive. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("recovery-phish-s3", "8.3 After a Click — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Security habits are boring until the day they prevent an expensive incident. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("recovery-phish-s4", "8.4 After a Click — common failures and fixes", ["common failures and fixes is where after a click stops being abstract. In Phishing Defense, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Attackers optimize for speed; defenders win by making cheap mistakes expensive. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("recovery-phish-s5", "8.5 After a Click — putting it together", ["Most mistakes in after a click happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","Security habits are boring until the day they prevent an expensive incident. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why after a click matters in modern phishing defense work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around after a click","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "After a Click connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master after a click reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  })
];
