import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const PHISH_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Phishing Defense",
  subtitle: "ForgEd path course — Phishing Defense",
  paragraphs: [
    "Phishing Defense is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Each chapter includes five sections and section quizzes. Pass chapter quizzes, the course review, and final exam to mark the course complete.",
    "Content is practical workforce education — not licensure, legal, or financial advice.",
  ],
};

export const PHISH_TEXTBOOK: TextbookChapter[] = [
  chapter("phishing-types", 1, "Phishing Types", [
      section("phishing-types-s1", "1.1 Phishing Types — applied practice (1)", ["1.1 Phishing Types — applied practice (1) connects Phishing Types to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("phishing-types-s2", "1.2 Phishing Types — applied practice (2)", ["1.2 Phishing Types — applied practice (2) connects Phishing Types to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("phishing-types-s3", "1.3 Phishing Types — applied practice (3)", ["1.3 Phishing Types — applied practice (3) connects Phishing Types to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("phishing-types-s4", "1.4 Phishing Types — applied practice (4)", ["1.4 Phishing Types — applied practice (4) connects Phishing Types to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("phishing-types-s5", "1.5 Phishing Types — applied practice (5)", ["1.5 Phishing Types — applied practice (5) connects Phishing Types to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("email-signals", 2, "Email Red Flags", [
      section("email-signals-s1", "2.1 Email Red Flags — applied practice (1)", ["2.1 Email Red Flags — applied practice (1) connects Email Red Flags to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("email-signals-s2", "2.2 Email Red Flags — applied practice (2)", ["2.2 Email Red Flags — applied practice (2) connects Email Red Flags to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("email-signals-s3", "2.3 Email Red Flags — applied practice (3)", ["2.3 Email Red Flags — applied practice (3) connects Email Red Flags to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("email-signals-s4", "2.4 Email Red Flags — applied practice (4)", ["2.4 Email Red Flags — applied practice (4) connects Email Red Flags to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("email-signals-s5", "2.5 Email Red Flags — applied practice (5)", ["2.5 Email Red Flags — applied practice (5) connects Email Red Flags to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("smishing", 3, "Smishing and Vishing", [
      section("smishing-s1", "3.1 Smishing and Vishing — applied practice (1)", ["3.1 Smishing and Vishing — applied practice (1) connects Smishing and Vishing to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("smishing-s2", "3.2 Smishing and Vishing — applied practice (2)", ["3.2 Smishing and Vishing — applied practice (2) connects Smishing and Vishing to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("smishing-s3", "3.3 Smishing and Vishing — applied practice (3)", ["3.3 Smishing and Vishing — applied practice (3) connects Smishing and Vishing to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("smishing-s4", "3.4 Smishing and Vishing — applied practice (4)", ["3.4 Smishing and Vishing — applied practice (4) connects Smishing and Vishing to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("smishing-s5", "3.5 Smishing and Vishing — applied practice (5)", ["3.5 Smishing and Vishing — applied practice (5) connects Smishing and Vishing to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("bec", 4, "Business Email Compromise", [
      section("bec-s1", "4.1 Business Email Compromise — applied practice (1)", ["4.1 Business Email Compromise — applied practice (1) connects Business Email Compromise to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("bec-s2", "4.2 Business Email Compromise — applied practice (2)", ["4.2 Business Email Compromise — applied practice (2) connects Business Email Compromise to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("bec-s3", "4.3 Business Email Compromise — applied practice (3)", ["4.3 Business Email Compromise — applied practice (3) connects Business Email Compromise to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("bec-s4", "4.4 Business Email Compromise — applied practice (4)", ["4.4 Business Email Compromise — applied practice (4) connects Business Email Compromise to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("bec-s5", "4.5 Business Email Compromise — applied practice (5)", ["4.5 Business Email Compromise — applied practice (5) connects Business Email Compromise to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("report-phish", 5, "Reporting Phishing", [
      section("report-phish-s1", "5.1 Reporting Phishing — applied practice (1)", ["5.1 Reporting Phishing — applied practice (1) connects Reporting Phishing to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("report-phish-s2", "5.2 Reporting Phishing — applied practice (2)", ["5.2 Reporting Phishing — applied practice (2) connects Reporting Phishing to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("report-phish-s3", "5.3 Reporting Phishing — applied practice (3)", ["5.3 Reporting Phishing — applied practice (3) connects Reporting Phishing to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("report-phish-s4", "5.4 Reporting Phishing — applied practice (4)", ["5.4 Reporting Phishing — applied practice (4) connects Reporting Phishing to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("report-phish-s5", "5.5 Reporting Phishing — applied practice (5)", ["5.5 Reporting Phishing — applied practice (5) connects Reporting Phishing to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("simulations", 6, "Phishing Simulations", [
      section("simulations-s1", "6.1 Phishing Simulations — applied practice (1)", ["6.1 Phishing Simulations — applied practice (1) connects Phishing Simulations to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("simulations-s2", "6.2 Phishing Simulations — applied practice (2)", ["6.2 Phishing Simulations — applied practice (2) connects Phishing Simulations to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("simulations-s3", "6.3 Phishing Simulations — applied practice (3)", ["6.3 Phishing Simulations — applied practice (3) connects Phishing Simulations to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("simulations-s4", "6.4 Phishing Simulations — applied practice (4)", ["6.4 Phishing Simulations — applied practice (4) connects Phishing Simulations to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("simulations-s5", "6.5 Phishing Simulations — applied practice (5)", ["6.5 Phishing Simulations — applied practice (5) connects Phishing Simulations to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("user-training", 7, "Security Awareness", [
      section("user-training-s1", "7.1 Security Awareness — applied practice (1)", ["7.1 Security Awareness — applied practice (1) connects Security Awareness to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("user-training-s2", "7.2 Security Awareness — applied practice (2)", ["7.2 Security Awareness — applied practice (2) connects Security Awareness to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("user-training-s3", "7.3 Security Awareness — applied practice (3)", ["7.3 Security Awareness — applied practice (3) connects Security Awareness to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("user-training-s4", "7.4 Security Awareness — applied practice (4)", ["7.4 Security Awareness — applied practice (4) connects Security Awareness to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("user-training-s5", "7.5 Security Awareness — applied practice (5)", ["7.5 Security Awareness — applied practice (5) connects Security Awareness to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("recovery-phish", 8, "After a Click", [
      section("recovery-phish-s1", "8.1 After a Click — applied practice (1)", ["8.1 After a Click — applied practice (1) connects After a Click to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("recovery-phish-s2", "8.2 After a Click — applied practice (2)", ["8.2 After a Click — applied practice (2) connects After a Click to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("recovery-phish-s3", "8.3 After a Click — applied practice (3)", ["8.3 After a Click — applied practice (3) connects After a Click to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("recovery-phish-s4", "8.4 After a Click — applied practice (4)", ["8.4 After a Click — applied practice (4) connects After a Click to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("recovery-phish-s5", "8.5 After a Click — applied practice (5)", ["8.5 After a Click — applied practice (5) connects After a Click to real workforce outcomes in Phishing Defense. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ])
];
