import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const PROMPT_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Prompting Fundamentals",
  subtitle: "Workforce training — Prompting Fundamentals",
  paragraphs: [
    "Prompting Fundamentals is built for professionals who want usable skill—not trivia. Each chapter moves from why the topic matters, through structured explanation, to quizzes that check judgment rather than memorization.",
    "Prompting Fundamentals is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn ForgEd path completion badges on your profile.",
    "Content is practical workforce education. It does not replace licensure, legal, medical, or employer-specific policy. When your organization has a rule that conflicts with a general lesson, follow your organization's rule and treat this course as context.",
  ],
};

export const PROMPT_TEXTBOOK: TextbookChapter[] = [
  chapter("prompt-basics", 1, "Prompt Structure and Clarity", [
    section("prompt-basics-s1", "1.1 Prompt Structure and Clarity — foundations and vocabulary", ["foundations and vocabulary is where prompt structure and clarity stops being abstract. In Prompting Fundamentals, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("prompt-basics-s2", "1.2 Prompt Structure and Clarity — how practitioners think", ["Most mistakes in prompt structure and clarity happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("prompt-basics-s3", "1.3 Prompt Structure and Clarity — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("prompt-basics-s4", "1.4 Prompt Structure and Clarity — common failures and fixes", ["common failures and fixes is where prompt structure and clarity stops being abstract. In Prompting Fundamentals, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("prompt-basics-s5", "1.5 Prompt Structure and Clarity — putting it together", ["Most mistakes in prompt structure and clarity happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why prompt structure and clarity matters in modern prompting fundamentals work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around prompt structure and clarity","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Prompt Structure and Clarity connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master prompt structure and clarity reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("context-control", 2, "Context Windows and Control", [
    section("context-control-s1", "2.1 Context Windows and Control — foundations and vocabulary", ["foundations and vocabulary is where context windows and control stops being abstract. In Prompting Fundamentals, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("context-control-s2", "2.2 Context Windows and Control — how practitioners think", ["Most mistakes in context windows and control happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("context-control-s3", "2.3 Context Windows and Control — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("context-control-s4", "2.4 Context Windows and Control — common failures and fixes", ["common failures and fixes is where context windows and control stops being abstract. In Prompting Fundamentals, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("context-control-s5", "2.5 Context Windows and Control — putting it together", ["Most mistakes in context windows and control happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why context windows and control matters in modern prompting fundamentals work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around context windows and control","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Context Windows and Control connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master context windows and control reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("role-prompts", 3, "Role and Persona Prompts", [
    section("role-prompts-s1", "3.1 Role and Persona Prompts — foundations and vocabulary", ["foundations and vocabulary is where role and persona prompts stops being abstract. In Prompting Fundamentals, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("role-prompts-s2", "3.2 Role and Persona Prompts — how practitioners think", ["Most mistakes in role and persona prompts happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("role-prompts-s3", "3.3 Role and Persona Prompts — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("role-prompts-s4", "3.4 Role and Persona Prompts — common failures and fixes", ["common failures and fixes is where role and persona prompts stops being abstract. In Prompting Fundamentals, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("role-prompts-s5", "3.5 Role and Persona Prompts — putting it together", ["Most mistakes in role and persona prompts happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why role and persona prompts matters in modern prompting fundamentals work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around role and persona prompts","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Role and Persona Prompts connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master role and persona prompts reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("few-shot", 4, "Few-Shot Examples", [
    section("few-shot-s1", "4.1 Few-Shot Examples — foundations and vocabulary", ["foundations and vocabulary is where few-shot examples stops being abstract. In Prompting Fundamentals, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("few-shot-s2", "4.2 Few-Shot Examples — how practitioners think", ["Most mistakes in few-shot examples happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("few-shot-s3", "4.3 Few-Shot Examples — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("few-shot-s4", "4.4 Few-Shot Examples — common failures and fixes", ["common failures and fixes is where few-shot examples stops being abstract. In Prompting Fundamentals, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("few-shot-s5", "4.5 Few-Shot Examples — putting it together", ["Most mistakes in few-shot examples happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why few-shot examples matters in modern prompting fundamentals work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around few-shot examples","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Few-Shot Examples connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master few-shot examples reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("chain-prompts", 5, "Chained Instructions", [
    section("chain-prompts-s1", "5.1 Chained Instructions — foundations and vocabulary", ["foundations and vocabulary is where chained instructions stops being abstract. In Prompting Fundamentals, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("chain-prompts-s2", "5.2 Chained Instructions — how practitioners think", ["Most mistakes in chained instructions happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("chain-prompts-s3", "5.3 Chained Instructions — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("chain-prompts-s4", "5.4 Chained Instructions — common failures and fixes", ["common failures and fixes is where chained instructions stops being abstract. In Prompting Fundamentals, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("chain-prompts-s5", "5.5 Chained Instructions — putting it together", ["Most mistakes in chained instructions happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why chained instructions matters in modern prompting fundamentals work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around chained instructions","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Chained Instructions connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master chained instructions reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("evaluation", 6, "Evaluating Model Outputs", [
    section("evaluation-s1", "6.1 Evaluating Model Outputs — foundations and vocabulary", ["foundations and vocabulary is where evaluating model outputs stops being abstract. In Prompting Fundamentals, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("evaluation-s2", "6.2 Evaluating Model Outputs — how practitioners think", ["Most mistakes in evaluating model outputs happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("evaluation-s3", "6.3 Evaluating Model Outputs — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("evaluation-s4", "6.4 Evaluating Model Outputs — common failures and fixes", ["common failures and fixes is where evaluating model outputs stops being abstract. In Prompting Fundamentals, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("evaluation-s5", "6.5 Evaluating Model Outputs — putting it together", ["Most mistakes in evaluating model outputs happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why evaluating model outputs matters in modern prompting fundamentals work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around evaluating model outputs","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Evaluating Model Outputs connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master evaluating model outputs reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("safety-prompts", 7, "Safety and Refusal Handling", [
    section("safety-prompts-s1", "7.1 Safety and Refusal Handling — foundations and vocabulary", ["foundations and vocabulary is where safety and refusal handling stops being abstract. In Prompting Fundamentals, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("safety-prompts-s2", "7.2 Safety and Refusal Handling — how practitioners think", ["Most mistakes in safety and refusal handling happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("safety-prompts-s3", "7.3 Safety and Refusal Handling — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("safety-prompts-s4", "7.4 Safety and Refusal Handling — common failures and fixes", ["common failures and fixes is where safety and refusal handling stops being abstract. In Prompting Fundamentals, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("safety-prompts-s5", "7.5 Safety and Refusal Handling — putting it together", ["Most mistakes in safety and refusal handling happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why safety and refusal handling matters in modern prompting fundamentals work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around safety and refusal handling","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Safety and Refusal Handling connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master safety and refusal handling reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("prompt-workflows", 8, "Prompts in Daily Work", [
    section("prompt-workflows-s1", "8.1 Prompts in Daily Work — foundations and vocabulary", ["foundations and vocabulary is where prompts in daily work stops being abstract. In Prompting Fundamentals, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("prompt-workflows-s2", "8.2 Prompts in Daily Work — how practitioners think", ["Most mistakes in prompts in daily work happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("prompt-workflows-s3", "8.3 Prompts in Daily Work — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("prompt-workflows-s4", "8.4 Prompts in Daily Work — common failures and fixes", ["common failures and fixes is where prompts in daily work stops being abstract. In Prompting Fundamentals, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("prompt-workflows-s5", "8.5 Prompts in Daily Work — putting it together", ["Most mistakes in prompts in daily work happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why prompts in daily work matters in modern prompting fundamentals work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around prompts in daily work","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Prompts in Daily Work connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master prompts in daily work reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  })
];
