import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const PROMPT_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Prompting Fundamentals",
  subtitle: "ForgEd path course — Prompting Fundamentals",
  paragraphs: [
    "Prompting Fundamentals is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Each chapter includes five sections and section quizzes. Pass chapter quizzes, the course review, and final exam to mark the course complete.",
    "Content is practical workforce education — not licensure, legal, or financial advice.",
  ],
};

export const PROMPT_TEXTBOOK: TextbookChapter[] = [
  chapter("prompt-basics", 1, "Prompt Structure and Clarity", [
      section("prompt-basics-s1", "1.1 Prompt Structure and Clarity — applied practice (1)", ["1.1 Prompt Structure and Clarity — applied practice (1) connects Prompt Structure and Clarity to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("prompt-basics-s2", "1.2 Prompt Structure and Clarity — applied practice (2)", ["1.2 Prompt Structure and Clarity — applied practice (2) connects Prompt Structure and Clarity to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("prompt-basics-s3", "1.3 Prompt Structure and Clarity — applied practice (3)", ["1.3 Prompt Structure and Clarity — applied practice (3) connects Prompt Structure and Clarity to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("prompt-basics-s4", "1.4 Prompt Structure and Clarity — applied practice (4)", ["1.4 Prompt Structure and Clarity — applied practice (4) connects Prompt Structure and Clarity to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("prompt-basics-s5", "1.5 Prompt Structure and Clarity — applied practice (5)", ["1.5 Prompt Structure and Clarity — applied practice (5) connects Prompt Structure and Clarity to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("context-control", 2, "Context Windows and Control", [
      section("context-control-s1", "2.1 Context Windows and Control — applied practice (1)", ["2.1 Context Windows and Control — applied practice (1) connects Context Windows and Control to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("context-control-s2", "2.2 Context Windows and Control — applied practice (2)", ["2.2 Context Windows and Control — applied practice (2) connects Context Windows and Control to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("context-control-s3", "2.3 Context Windows and Control — applied practice (3)", ["2.3 Context Windows and Control — applied practice (3) connects Context Windows and Control to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("context-control-s4", "2.4 Context Windows and Control — applied practice (4)", ["2.4 Context Windows and Control — applied practice (4) connects Context Windows and Control to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("context-control-s5", "2.5 Context Windows and Control — applied practice (5)", ["2.5 Context Windows and Control — applied practice (5) connects Context Windows and Control to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("role-prompts", 3, "Role and Persona Prompts", [
      section("role-prompts-s1", "3.1 Role and Persona Prompts — applied practice (1)", ["3.1 Role and Persona Prompts — applied practice (1) connects Role and Persona Prompts to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("role-prompts-s2", "3.2 Role and Persona Prompts — applied practice (2)", ["3.2 Role and Persona Prompts — applied practice (2) connects Role and Persona Prompts to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("role-prompts-s3", "3.3 Role and Persona Prompts — applied practice (3)", ["3.3 Role and Persona Prompts — applied practice (3) connects Role and Persona Prompts to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("role-prompts-s4", "3.4 Role and Persona Prompts — applied practice (4)", ["3.4 Role and Persona Prompts — applied practice (4) connects Role and Persona Prompts to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("role-prompts-s5", "3.5 Role and Persona Prompts — applied practice (5)", ["3.5 Role and Persona Prompts — applied practice (5) connects Role and Persona Prompts to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("few-shot", 4, "Few-Shot Examples", [
      section("few-shot-s1", "4.1 Few-Shot Examples — applied practice (1)", ["4.1 Few-Shot Examples — applied practice (1) connects Few-Shot Examples to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("few-shot-s2", "4.2 Few-Shot Examples — applied practice (2)", ["4.2 Few-Shot Examples — applied practice (2) connects Few-Shot Examples to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("few-shot-s3", "4.3 Few-Shot Examples — applied practice (3)", ["4.3 Few-Shot Examples — applied practice (3) connects Few-Shot Examples to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("few-shot-s4", "4.4 Few-Shot Examples — applied practice (4)", ["4.4 Few-Shot Examples — applied practice (4) connects Few-Shot Examples to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("few-shot-s5", "4.5 Few-Shot Examples — applied practice (5)", ["4.5 Few-Shot Examples — applied practice (5) connects Few-Shot Examples to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("chain-prompts", 5, "Chained Instructions", [
      section("chain-prompts-s1", "5.1 Chained Instructions — applied practice (1)", ["5.1 Chained Instructions — applied practice (1) connects Chained Instructions to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("chain-prompts-s2", "5.2 Chained Instructions — applied practice (2)", ["5.2 Chained Instructions — applied practice (2) connects Chained Instructions to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("chain-prompts-s3", "5.3 Chained Instructions — applied practice (3)", ["5.3 Chained Instructions — applied practice (3) connects Chained Instructions to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("chain-prompts-s4", "5.4 Chained Instructions — applied practice (4)", ["5.4 Chained Instructions — applied practice (4) connects Chained Instructions to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("chain-prompts-s5", "5.5 Chained Instructions — applied practice (5)", ["5.5 Chained Instructions — applied practice (5) connects Chained Instructions to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("evaluation", 6, "Evaluating Model Outputs", [
      section("evaluation-s1", "6.1 Evaluating Model Outputs — applied practice (1)", ["6.1 Evaluating Model Outputs — applied practice (1) connects Evaluating Model Outputs to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("evaluation-s2", "6.2 Evaluating Model Outputs — applied practice (2)", ["6.2 Evaluating Model Outputs — applied practice (2) connects Evaluating Model Outputs to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("evaluation-s3", "6.3 Evaluating Model Outputs — applied practice (3)", ["6.3 Evaluating Model Outputs — applied practice (3) connects Evaluating Model Outputs to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("evaluation-s4", "6.4 Evaluating Model Outputs — applied practice (4)", ["6.4 Evaluating Model Outputs — applied practice (4) connects Evaluating Model Outputs to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("evaluation-s5", "6.5 Evaluating Model Outputs — applied practice (5)", ["6.5 Evaluating Model Outputs — applied practice (5) connects Evaluating Model Outputs to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("safety-prompts", 7, "Safety and Refusal Handling", [
      section("safety-prompts-s1", "7.1 Safety and Refusal Handling — applied practice (1)", ["7.1 Safety and Refusal Handling — applied practice (1) connects Safety and Refusal Handling to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("safety-prompts-s2", "7.2 Safety and Refusal Handling — applied practice (2)", ["7.2 Safety and Refusal Handling — applied practice (2) connects Safety and Refusal Handling to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("safety-prompts-s3", "7.3 Safety and Refusal Handling — applied practice (3)", ["7.3 Safety and Refusal Handling — applied practice (3) connects Safety and Refusal Handling to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("safety-prompts-s4", "7.4 Safety and Refusal Handling — applied practice (4)", ["7.4 Safety and Refusal Handling — applied practice (4) connects Safety and Refusal Handling to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("safety-prompts-s5", "7.5 Safety and Refusal Handling — applied practice (5)", ["7.5 Safety and Refusal Handling — applied practice (5) connects Safety and Refusal Handling to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("prompt-workflows", 8, "Prompts in Daily Work", [
      section("prompt-workflows-s1", "8.1 Prompts in Daily Work — applied practice (1)", ["8.1 Prompts in Daily Work — applied practice (1) connects Prompts in Daily Work to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("prompt-workflows-s2", "8.2 Prompts in Daily Work — applied practice (2)", ["8.2 Prompts in Daily Work — applied practice (2) connects Prompts in Daily Work to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("prompt-workflows-s3", "8.3 Prompts in Daily Work — applied practice (3)", ["8.3 Prompts in Daily Work — applied practice (3) connects Prompts in Daily Work to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("prompt-workflows-s4", "8.4 Prompts in Daily Work — applied practice (4)", ["8.4 Prompts in Daily Work — applied practice (4) connects Prompts in Daily Work to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("prompt-workflows-s5", "8.5 Prompts in Daily Work — applied practice (5)", ["8.5 Prompts in Daily Work — applied practice (5) connects Prompts in Daily Work to real workforce outcomes in Prompting Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ])
];
