import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const RET_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Retirement Planning",
  subtitle: "ForgEd path course — Retirement Planning",
  paragraphs: [
    "Retirement Planning is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Each chapter includes five sections and section quizzes. Pass chapter quizzes, the course review, and final exam to mark the course complete.",
    "Content is practical workforce education — not licensure, legal, or financial advice.",
  ],
};

export const RET_TEXTBOOK: TextbookChapter[] = [
  chapter("retirement-why", 1, "Why Start Early", [
      section("retirement-why-s1", "1.1 Why Start Early — applied practice (1)", ["1.1 Why Start Early — applied practice (1) connects Why Start Early to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("retirement-why-s2", "1.2 Why Start Early — applied practice (2)", ["1.2 Why Start Early — applied practice (2) connects Why Start Early to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("retirement-why-s3", "1.3 Why Start Early — applied practice (3)", ["1.3 Why Start Early — applied practice (3) connects Why Start Early to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("retirement-why-s4", "1.4 Why Start Early — applied practice (4)", ["1.4 Why Start Early — applied practice (4) connects Why Start Early to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("retirement-why-s5", "1.5 Why Start Early — applied practice (5)", ["1.5 Why Start Early — applied practice (5) connects Why Start Early to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("401k", 2, "401(k) Basics", [
      section("401k-s1", "2.1 401(k) Basics — applied practice (1)", ["2.1 401(k) Basics — applied practice (1) connects 401(k) Basics to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("401k-s2", "2.2 401(k) Basics — applied practice (2)", ["2.2 401(k) Basics — applied practice (2) connects 401(k) Basics to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("401k-s3", "2.3 401(k) Basics — applied practice (3)", ["2.3 401(k) Basics — applied practice (3) connects 401(k) Basics to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("401k-s4", "2.4 401(k) Basics — applied practice (4)", ["2.4 401(k) Basics — applied practice (4) connects 401(k) Basics to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("401k-s5", "2.5 401(k) Basics — applied practice (5)", ["2.5 401(k) Basics — applied practice (5) connects 401(k) Basics to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("ira", 3, "IRA Options", [
      section("ira-s1", "3.1 IRA Options — applied practice (1)", ["3.1 IRA Options — applied practice (1) connects IRA Options to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ira-s2", "3.2 IRA Options — applied practice (2)", ["3.2 IRA Options — applied practice (2) connects IRA Options to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ira-s3", "3.3 IRA Options — applied practice (3)", ["3.3 IRA Options — applied practice (3) connects IRA Options to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ira-s4", "3.4 IRA Options — applied practice (4)", ["3.4 IRA Options — applied practice (4) connects IRA Options to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ira-s5", "3.5 IRA Options — applied practice (5)", ["3.5 IRA Options — applied practice (5) connects IRA Options to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("employer-match", 4, "Employer Match", [
      section("employer-match-s1", "4.1 Employer Match — applied practice (1)", ["4.1 Employer Match — applied practice (1) connects Employer Match to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("employer-match-s2", "4.2 Employer Match — applied practice (2)", ["4.2 Employer Match — applied practice (2) connects Employer Match to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("employer-match-s3", "4.3 Employer Match — applied practice (3)", ["4.3 Employer Match — applied practice (3) connects Employer Match to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("employer-match-s4", "4.4 Employer Match — applied practice (4)", ["4.4 Employer Match — applied practice (4) connects Employer Match to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("employer-match-s5", "4.5 Employer Match — applied practice (5)", ["4.5 Employer Match — applied practice (5) connects Employer Match to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("social-security", 5, "Social Security Overview", [
      section("social-security-s1", "5.1 Social Security Overview — applied practice (1)", ["5.1 Social Security Overview — applied practice (1) connects Social Security Overview to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("social-security-s2", "5.2 Social Security Overview — applied practice (2)", ["5.2 Social Security Overview — applied practice (2) connects Social Security Overview to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("social-security-s3", "5.3 Social Security Overview — applied practice (3)", ["5.3 Social Security Overview — applied practice (3) connects Social Security Overview to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("social-security-s4", "5.4 Social Security Overview — applied practice (4)", ["5.4 Social Security Overview — applied practice (4) connects Social Security Overview to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("social-security-s5", "5.5 Social Security Overview — applied practice (5)", ["5.5 Social Security Overview — applied practice (5) connects Social Security Overview to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("withdrawal", 6, "Withdrawal Strategies", [
      section("withdrawal-s1", "6.1 Withdrawal Strategies — applied practice (1)", ["6.1 Withdrawal Strategies — applied practice (1) connects Withdrawal Strategies to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("withdrawal-s2", "6.2 Withdrawal Strategies — applied practice (2)", ["6.2 Withdrawal Strategies — applied practice (2) connects Withdrawal Strategies to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("withdrawal-s3", "6.3 Withdrawal Strategies — applied practice (3)", ["6.3 Withdrawal Strategies — applied practice (3) connects Withdrawal Strategies to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("withdrawal-s4", "6.4 Withdrawal Strategies — applied practice (4)", ["6.4 Withdrawal Strategies — applied practice (4) connects Withdrawal Strategies to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("withdrawal-s5", "6.5 Withdrawal Strategies — applied practice (5)", ["6.5 Withdrawal Strategies — applied practice (5) connects Withdrawal Strategies to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("healthcare-retire", 7, "Healthcare in Retirement", [
      section("healthcare-retire-s1", "7.1 Healthcare in Retirement — applied practice (1)", ["7.1 Healthcare in Retirement — applied practice (1) connects Healthcare in Retirement to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("healthcare-retire-s2", "7.2 Healthcare in Retirement — applied practice (2)", ["7.2 Healthcare in Retirement — applied practice (2) connects Healthcare in Retirement to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("healthcare-retire-s3", "7.3 Healthcare in Retirement — applied practice (3)", ["7.3 Healthcare in Retirement — applied practice (3) connects Healthcare in Retirement to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("healthcare-retire-s4", "7.4 Healthcare in Retirement — applied practice (4)", ["7.4 Healthcare in Retirement — applied practice (4) connects Healthcare in Retirement to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("healthcare-retire-s5", "7.5 Healthcare in Retirement — applied practice (5)", ["7.5 Healthcare in Retirement — applied practice (5) connects Healthcare in Retirement to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("retirement-goals", 8, "Setting Retirement Goals", [
      section("retirement-goals-s1", "8.1 Setting Retirement Goals — applied practice (1)", ["8.1 Setting Retirement Goals — applied practice (1) connects Setting Retirement Goals to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("retirement-goals-s2", "8.2 Setting Retirement Goals — applied practice (2)", ["8.2 Setting Retirement Goals — applied practice (2) connects Setting Retirement Goals to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("retirement-goals-s3", "8.3 Setting Retirement Goals — applied practice (3)", ["8.3 Setting Retirement Goals — applied practice (3) connects Setting Retirement Goals to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("retirement-goals-s4", "8.4 Setting Retirement Goals — applied practice (4)", ["8.4 Setting Retirement Goals — applied practice (4) connects Setting Retirement Goals to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("retirement-goals-s5", "8.5 Setting Retirement Goals — applied practice (5)", ["8.5 Setting Retirement Goals — applied practice (5) connects Setting Retirement Goals to real workforce outcomes in Retirement Planning. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ])
];
