import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const SALES_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Sales School 101",
  subtitle: "ForgEd path course — Sales School 101",
  paragraphs: [
    "Sales School 101 is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Each chapter includes five sections and section quizzes. Pass chapter quizzes, the course review, and final exam to mark the course complete.",
    "Content is practical workforce education — not licensure, legal, or financial advice.",
  ],
};

export const SALES_TEXTBOOK: TextbookChapter[] = [
  chapter("sales-cycle", 1, "The Modern Sales Cycle", [
      section("sales-cycle-s1", "1.1 The Modern Sales Cycle — applied practice (1)", ["1.1 The Modern Sales Cycle — applied practice (1) connects The Modern Sales Cycle to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("sales-cycle-s2", "1.2 The Modern Sales Cycle — applied practice (2)", ["1.2 The Modern Sales Cycle — applied practice (2) connects The Modern Sales Cycle to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("sales-cycle-s3", "1.3 The Modern Sales Cycle — applied practice (3)", ["1.3 The Modern Sales Cycle — applied practice (3) connects The Modern Sales Cycle to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("sales-cycle-s4", "1.4 The Modern Sales Cycle — applied practice (4)", ["1.4 The Modern Sales Cycle — applied practice (4) connects The Modern Sales Cycle to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("sales-cycle-s5", "1.5 The Modern Sales Cycle — applied practice (5)", ["1.5 The Modern Sales Cycle — applied practice (5) connects The Modern Sales Cycle to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("icp", 2, "Ideal Customer Profile", [
      section("icp-s1", "2.1 Ideal Customer Profile — applied practice (1)", ["2.1 Ideal Customer Profile — applied practice (1) connects Ideal Customer Profile to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("icp-s2", "2.2 Ideal Customer Profile — applied practice (2)", ["2.2 Ideal Customer Profile — applied practice (2) connects Ideal Customer Profile to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("icp-s3", "2.3 Ideal Customer Profile — applied practice (3)", ["2.3 Ideal Customer Profile — applied practice (3) connects Ideal Customer Profile to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("icp-s4", "2.4 Ideal Customer Profile — applied practice (4)", ["2.4 Ideal Customer Profile — applied practice (4) connects Ideal Customer Profile to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("icp-s5", "2.5 Ideal Customer Profile — applied practice (5)", ["2.5 Ideal Customer Profile — applied practice (5) connects Ideal Customer Profile to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("discovery", 3, "Discovery Conversations", [
      section("discovery-s1", "3.1 Discovery Conversations — applied practice (1)", ["3.1 Discovery Conversations — applied practice (1) connects Discovery Conversations to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("discovery-s2", "3.2 Discovery Conversations — applied practice (2)", ["3.2 Discovery Conversations — applied practice (2) connects Discovery Conversations to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("discovery-s3", "3.3 Discovery Conversations — applied practice (3)", ["3.3 Discovery Conversations — applied practice (3) connects Discovery Conversations to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("discovery-s4", "3.4 Discovery Conversations — applied practice (4)", ["3.4 Discovery Conversations — applied practice (4) connects Discovery Conversations to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("discovery-s5", "3.5 Discovery Conversations — applied practice (5)", ["3.5 Discovery Conversations — applied practice (5) connects Discovery Conversations to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("value-prop", 4, "Value Propositions", [
      section("value-prop-s1", "4.1 Value Propositions — applied practice (1)", ["4.1 Value Propositions — applied practice (1) connects Value Propositions to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("value-prop-s2", "4.2 Value Propositions — applied practice (2)", ["4.2 Value Propositions — applied practice (2) connects Value Propositions to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("value-prop-s3", "4.3 Value Propositions — applied practice (3)", ["4.3 Value Propositions — applied practice (3) connects Value Propositions to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("value-prop-s4", "4.4 Value Propositions — applied practice (4)", ["4.4 Value Propositions — applied practice (4) connects Value Propositions to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("value-prop-s5", "4.5 Value Propositions — applied practice (5)", ["4.5 Value Propositions — applied practice (5) connects Value Propositions to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("demo-basics", 5, "Demonstrations That Convert", [
      section("demo-basics-s1", "5.1 Demonstrations That Convert — applied practice (1)", ["5.1 Demonstrations That Convert — applied practice (1) connects Demonstrations That Convert to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("demo-basics-s2", "5.2 Demonstrations That Convert — applied practice (2)", ["5.2 Demonstrations That Convert — applied practice (2) connects Demonstrations That Convert to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("demo-basics-s3", "5.3 Demonstrations That Convert — applied practice (3)", ["5.3 Demonstrations That Convert — applied practice (3) connects Demonstrations That Convert to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("demo-basics-s4", "5.4 Demonstrations That Convert — applied practice (4)", ["5.4 Demonstrations That Convert — applied practice (4) connects Demonstrations That Convert to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("demo-basics-s5", "5.5 Demonstrations That Convert — applied practice (5)", ["5.5 Demonstrations That Convert — applied practice (5) connects Demonstrations That Convert to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("pipeline", 6, "Pipeline Management", [
      section("pipeline-s1", "6.1 Pipeline Management — applied practice (1)", ["6.1 Pipeline Management — applied practice (1) connects Pipeline Management to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("pipeline-s2", "6.2 Pipeline Management — applied practice (2)", ["6.2 Pipeline Management — applied practice (2) connects Pipeline Management to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("pipeline-s3", "6.3 Pipeline Management — applied practice (3)", ["6.3 Pipeline Management — applied practice (3) connects Pipeline Management to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("pipeline-s4", "6.4 Pipeline Management — applied practice (4)", ["6.4 Pipeline Management — applied practice (4) connects Pipeline Management to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("pipeline-s5", "6.5 Pipeline Management — applied practice (5)", ["6.5 Pipeline Management — applied practice (5) connects Pipeline Management to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("ethics-sales", 7, "Ethical Selling", [
      section("ethics-sales-s1", "7.1 Ethical Selling — applied practice (1)", ["7.1 Ethical Selling — applied practice (1) connects Ethical Selling to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ethics-sales-s2", "7.2 Ethical Selling — applied practice (2)", ["7.2 Ethical Selling — applied practice (2) connects Ethical Selling to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ethics-sales-s3", "7.3 Ethical Selling — applied practice (3)", ["7.3 Ethical Selling — applied practice (3) connects Ethical Selling to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ethics-sales-s4", "7.4 Ethical Selling — applied practice (4)", ["7.4 Ethical Selling — applied practice (4) connects Ethical Selling to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ethics-sales-s5", "7.5 Ethical Selling — applied practice (5)", ["7.5 Ethical Selling — applied practice (5) connects Ethical Selling to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("sales-careers", 8, "Sales Career Paths", [
      section("sales-careers-s1", "8.1 Sales Career Paths — applied practice (1)", ["8.1 Sales Career Paths — applied practice (1) connects Sales Career Paths to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("sales-careers-s2", "8.2 Sales Career Paths — applied practice (2)", ["8.2 Sales Career Paths — applied practice (2) connects Sales Career Paths to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("sales-careers-s3", "8.3 Sales Career Paths — applied practice (3)", ["8.3 Sales Career Paths — applied practice (3) connects Sales Career Paths to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("sales-careers-s4", "8.4 Sales Career Paths — applied practice (4)", ["8.4 Sales Career Paths — applied practice (4) connects Sales Career Paths to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("sales-careers-s5", "8.5 Sales Career Paths — applied practice (5)", ["8.5 Sales Career Paths — applied practice (5) connects Sales Career Paths to real workforce outcomes in Sales School 101. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ])
];
