import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const SCI_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Science Fundamentals",
  subtitle: "ForgEd deep-dive — science fundamentals",
  paragraphs: [
    "This ForgEd digital textbook presents Science Fundamentals at academic survey depth for self-paced study.",
    "Complete each section quiz before advancing. Chapter and course assessments draw from a 150-question bank.",
    "Material is general education, not professional licensure or certification prep by itself.",
  ],
};

export const SCI_TEXTBOOK: TextbookChapter[] = [
  chapter("scientific-method", 1, "The Scientific Method", [
      section("scientific-method-s1", "1.1 The Scientific Method — core concepts (1)", ["1.1 The Scientific Method — core concepts (1) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply the scientific method with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in the scientific method."]),
      section("scientific-method-s2", "1.2 The Scientific Method — core concepts (2)", ["1.2 The Scientific Method — core concepts (2) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply the scientific method with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in the scientific method."]),
      section("scientific-method-s3", "1.3 The Scientific Method — core concepts (3)", ["1.3 The Scientific Method — core concepts (3) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply the scientific method with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in the scientific method."]),
      section("scientific-method-s4", "1.4 The Scientific Method — core concepts (4)", ["1.4 The Scientific Method — core concepts (4) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply the scientific method with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in the scientific method."]),
      section("scientific-method-s5", "1.5 The Scientific Method — core concepts (5)", ["1.5 The Scientific Method — core concepts (5) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply the scientific method with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in the scientific method."]),
  ]),
  chapter("biology-basics", 2, "Biology Essentials", [
      section("biology-basics-s1", "2.1 Biology Essentials — core concepts (1)", ["2.1 Biology Essentials — core concepts (1) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply biology essentials with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in biology essentials."]),
      section("biology-basics-s2", "2.2 Biology Essentials — core concepts (2)", ["2.2 Biology Essentials — core concepts (2) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply biology essentials with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in biology essentials."]),
      section("biology-basics-s3", "2.3 Biology Essentials — core concepts (3)", ["2.3 Biology Essentials — core concepts (3) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply biology essentials with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in biology essentials."]),
      section("biology-basics-s4", "2.4 Biology Essentials — core concepts (4)", ["2.4 Biology Essentials — core concepts (4) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply biology essentials with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in biology essentials."]),
      section("biology-basics-s5", "2.5 Biology Essentials — core concepts (5)", ["2.5 Biology Essentials — core concepts (5) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply biology essentials with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in biology essentials."]),
  ]),
  chapter("chemistry-basics", 3, "Chemistry Essentials", [
      section("chemistry-basics-s1", "3.1 Chemistry Essentials — core concepts (1)", ["3.1 Chemistry Essentials — core concepts (1) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply chemistry essentials with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in chemistry essentials."]),
      section("chemistry-basics-s2", "3.2 Chemistry Essentials — core concepts (2)", ["3.2 Chemistry Essentials — core concepts (2) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply chemistry essentials with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in chemistry essentials."]),
      section("chemistry-basics-s3", "3.3 Chemistry Essentials — core concepts (3)", ["3.3 Chemistry Essentials — core concepts (3) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply chemistry essentials with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in chemistry essentials."]),
      section("chemistry-basics-s4", "3.4 Chemistry Essentials — core concepts (4)", ["3.4 Chemistry Essentials — core concepts (4) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply chemistry essentials with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in chemistry essentials."]),
      section("chemistry-basics-s5", "3.5 Chemistry Essentials — core concepts (5)", ["3.5 Chemistry Essentials — core concepts (5) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply chemistry essentials with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in chemistry essentials."]),
  ]),
  chapter("physics-basics", 4, "Physics Essentials", [
      section("physics-basics-s1", "4.1 Physics Essentials — core concepts (1)", ["4.1 Physics Essentials — core concepts (1) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply physics essentials with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in physics essentials."]),
      section("physics-basics-s2", "4.2 Physics Essentials — core concepts (2)", ["4.2 Physics Essentials — core concepts (2) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply physics essentials with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in physics essentials."]),
      section("physics-basics-s3", "4.3 Physics Essentials — core concepts (3)", ["4.3 Physics Essentials — core concepts (3) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply physics essentials with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in physics essentials."]),
      section("physics-basics-s4", "4.4 Physics Essentials — core concepts (4)", ["4.4 Physics Essentials — core concepts (4) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply physics essentials with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in physics essentials."]),
      section("physics-basics-s5", "4.5 Physics Essentials — core concepts (5)", ["4.5 Physics Essentials — core concepts (5) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply physics essentials with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in physics essentials."]),
  ]),
  chapter("earth-science", 5, "Earth and Space Science", [
      section("earth-science-s1", "5.1 Earth and Space Science — core concepts (1)", ["5.1 Earth and Space Science — core concepts (1) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply earth and space science with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in earth and space science."]),
      section("earth-science-s2", "5.2 Earth and Space Science — core concepts (2)", ["5.2 Earth and Space Science — core concepts (2) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply earth and space science with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in earth and space science."]),
      section("earth-science-s3", "5.3 Earth and Space Science — core concepts (3)", ["5.3 Earth and Space Science — core concepts (3) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply earth and space science with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in earth and space science."]),
      section("earth-science-s4", "5.4 Earth and Space Science — core concepts (4)", ["5.4 Earth and Space Science — core concepts (4) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply earth and space science with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in earth and space science."]),
      section("earth-science-s5", "5.5 Earth and Space Science — core concepts (5)", ["5.5 Earth and Space Science — core concepts (5) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply earth and space science with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in earth and space science."]),
  ]),
  chapter("lab-skills", 6, "Laboratory Skills", [
      section("lab-skills-s1", "6.1 Laboratory Skills — core concepts (1)", ["6.1 Laboratory Skills — core concepts (1) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply laboratory skills with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in laboratory skills."]),
      section("lab-skills-s2", "6.2 Laboratory Skills — core concepts (2)", ["6.2 Laboratory Skills — core concepts (2) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply laboratory skills with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in laboratory skills."]),
      section("lab-skills-s3", "6.3 Laboratory Skills — core concepts (3)", ["6.3 Laboratory Skills — core concepts (3) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply laboratory skills with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in laboratory skills."]),
      section("lab-skills-s4", "6.4 Laboratory Skills — core concepts (4)", ["6.4 Laboratory Skills — core concepts (4) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply laboratory skills with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in laboratory skills."]),
      section("lab-skills-s5", "6.5 Laboratory Skills — core concepts (5)", ["6.5 Laboratory Skills — core concepts (5) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply laboratory skills with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in laboratory skills."]),
  ]),
  chapter("data-analysis", 7, "Data and Graphs", [
      section("data-analysis-s1", "7.1 Data and Graphs — core concepts (1)", ["7.1 Data and Graphs — core concepts (1) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply data and graphs with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in data and graphs."]),
      section("data-analysis-s2", "7.2 Data and Graphs — core concepts (2)", ["7.2 Data and Graphs — core concepts (2) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply data and graphs with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in data and graphs."]),
      section("data-analysis-s3", "7.3 Data and Graphs — core concepts (3)", ["7.3 Data and Graphs — core concepts (3) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply data and graphs with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in data and graphs."]),
      section("data-analysis-s4", "7.4 Data and Graphs — core concepts (4)", ["7.4 Data and Graphs — core concepts (4) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply data and graphs with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in data and graphs."]),
      section("data-analysis-s5", "7.5 Data and Graphs — core concepts (5)", ["7.5 Data and Graphs — core concepts (5) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply data and graphs with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in data and graphs."]),
  ]),
  chapter("research-ethics", 8, "Research and Ethics", [
      section("research-ethics-s1", "8.1 Research and Ethics — core concepts (1)", ["8.1 Research and Ethics — core concepts (1) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply research and ethics with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in research and ethics."]),
      section("research-ethics-s2", "8.2 Research and Ethics — core concepts (2)", ["8.2 Research and Ethics — core concepts (2) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply research and ethics with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in research and ethics."]),
      section("research-ethics-s3", "8.3 Research and Ethics — core concepts (3)", ["8.3 Research and Ethics — core concepts (3) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply research and ethics with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in research and ethics."]),
      section("research-ethics-s4", "8.4 Research and Ethics — core concepts (4)", ["8.4 Research and Ethics — core concepts (4) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply research and ethics with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in research and ethics."]),
      section("research-ethics-s5", "8.5 Research and Ethics — core concepts (5)", ["8.5 Research and Ethics — core concepts (5) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply research and ethics with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in research and ethics."]),
  ]),
  chapter("applied-science", 9, "Applied Science", [
      section("applied-science-s1", "9.1 Applied Science — core concepts (1)", ["9.1 Applied Science — core concepts (1) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply applied science with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in applied science."]),
      section("applied-science-s2", "9.2 Applied Science — core concepts (2)", ["9.2 Applied Science — core concepts (2) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply applied science with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in applied science."]),
      section("applied-science-s3", "9.3 Applied Science — core concepts (3)", ["9.3 Applied Science — core concepts (3) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply applied science with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in applied science."]),
      section("applied-science-s4", "9.4 Applied Science — core concepts (4)", ["9.4 Applied Science — core concepts (4) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply applied science with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in applied science."]),
      section("applied-science-s5", "9.5 Applied Science — core concepts (5)", ["9.5 Applied Science — core concepts (5) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply applied science with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in applied science."]),
  ]),
  chapter("science-careers", 10, "Science Careers", [
      section("science-careers-s1", "10.1 Science Careers — core concepts (1)", ["10.1 Science Careers — core concepts (1) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply science careers with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in science careers."]),
      section("science-careers-s2", "10.2 Science Careers — core concepts (2)", ["10.2 Science Careers — core concepts (2) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply science careers with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in science careers."]),
      section("science-careers-s3", "10.3 Science Careers — core concepts (3)", ["10.3 Science Careers — core concepts (3) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply science careers with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in science careers."]),
      section("science-careers-s4", "10.4 Science Careers — core concepts (4)", ["10.4 Science Careers — core concepts (4) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply science careers with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in science careers."]),
      section("science-careers-s5", "10.5 Science Careers — core concepts (5)", ["10.5 Science Careers — core concepts (5) is a core topic in Science Fundamentals. Learners should connect definitions to how professionals apply science careers with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in science careers."]),
  ])
];
