import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const SVC_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Service Advising Fundamentals",
  subtitle: "Workforce training — Service Advising Fundamentals",
  paragraphs: [
    "Service Advising Fundamentals is built for professionals who want usable skill—not trivia. Each chapter moves from why the topic matters, through structured explanation, to quizzes that check judgment rather than memorization.",
    "Service Advising Fundamentals is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Content is practical workforce education. It does not replace licensure, legal, medical, or employer-specific policy. When your organization has a rule that conflicts with a general lesson, follow your organization's rule and treat this course as context.",
  ],
};

export const SVC_TEXTBOOK: TextbookChapter[] = [
  chapter("advisor-role", 1, "The Service Advisor Role", [
    section("advisor-role-s1", "1.1 The Service Advisor Role — foundations and vocabulary", ["foundations and vocabulary is where the service advisor role stops being abstract. In Service Advising Fundamentals, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A repair order is a contract—what you document protects the shop and the driver. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("advisor-role-s2", "1.2 The Service Advisor Role — how practitioners think", ["Most mistakes in the service advisor role happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Service lanes run on trust and timestamps; customers forgive delays they understand. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("advisor-role-s3", "1.3 The Service Advisor Role — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","A repair order is a contract—what you document protects the shop and the driver. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("advisor-role-s4", "1.4 The Service Advisor Role — common failures and fixes", ["common failures and fixes is where the service advisor role stops being abstract. In Service Advising Fundamentals, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Service lanes run on trust and timestamps; customers forgive delays they understand. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("advisor-role-s5", "1.5 The Service Advisor Role — putting it together", ["Most mistakes in the service advisor role happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","A repair order is a contract—what you document protects the shop and the driver. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why the service advisor role matters in modern service advising fundamentals work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around the service advisor role","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "The Service Advisor Role connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master the service advisor role reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("shop-flow", 2, "Shop Flow", [
    section("shop-flow-s1", "2.1 Shop Flow — foundations and vocabulary", ["foundations and vocabulary is where shop flow stops being abstract. In Service Advising Fundamentals, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A repair order is a contract—what you document protects the shop and the driver. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("shop-flow-s2", "2.2 Shop Flow — how practitioners think", ["Most mistakes in shop flow happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Service lanes run on trust and timestamps; customers forgive delays they understand. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("shop-flow-s3", "2.3 Shop Flow — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","A repair order is a contract—what you document protects the shop and the driver. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("shop-flow-s4", "2.4 Shop Flow — common failures and fixes", ["common failures and fixes is where shop flow stops being abstract. In Service Advising Fundamentals, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Service lanes run on trust and timestamps; customers forgive delays they understand. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("shop-flow-s5", "2.5 Shop Flow — putting it together", ["Most mistakes in shop flow happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","A repair order is a contract—what you document protects the shop and the driver. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why shop flow matters in modern service advising fundamentals work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around shop flow","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Shop Flow connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master shop flow reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("customer-expectations", 3, "Customer Expectations", [
    section("customer-expectations-s1", "3.1 Customer Expectations — foundations and vocabulary", ["foundations and vocabulary is where customer expectations stops being abstract. In Service Advising Fundamentals, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A repair order is a contract—what you document protects the shop and the driver. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("customer-expectations-s2", "3.2 Customer Expectations — how practitioners think", ["Most mistakes in customer expectations happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Service lanes run on trust and timestamps; customers forgive delays they understand. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("customer-expectations-s3", "3.3 Customer Expectations — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","A repair order is a contract—what you document protects the shop and the driver. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("customer-expectations-s4", "3.4 Customer Expectations — common failures and fixes", ["common failures and fixes is where customer expectations stops being abstract. In Service Advising Fundamentals, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Service lanes run on trust and timestamps; customers forgive delays they understand. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("customer-expectations-s5", "3.5 Customer Expectations — putting it together", ["Most mistakes in customer expectations happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","A repair order is a contract—what you document protects the shop and the driver. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why customer expectations matters in modern service advising fundamentals work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around customer expectations","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Customer Expectations connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master customer expectations reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("multipoint", 4, "Multi-Point Inspections", [
    section("multipoint-s1", "4.1 Multi-Point Inspections — foundations and vocabulary", ["foundations and vocabulary is where multi-point inspections stops being abstract. In Service Advising Fundamentals, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A repair order is a contract—what you document protects the shop and the driver. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("multipoint-s2", "4.2 Multi-Point Inspections — how practitioners think", ["Most mistakes in multi-point inspections happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Service lanes run on trust and timestamps; customers forgive delays they understand. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("multipoint-s3", "4.3 Multi-Point Inspections — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","A repair order is a contract—what you document protects the shop and the driver. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("multipoint-s4", "4.4 Multi-Point Inspections — common failures and fixes", ["common failures and fixes is where multi-point inspections stops being abstract. In Service Advising Fundamentals, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Service lanes run on trust and timestamps; customers forgive delays they understand. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("multipoint-s5", "4.5 Multi-Point Inspections — putting it together", ["Most mistakes in multi-point inspections happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","A repair order is a contract—what you document protects the shop and the driver. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why multi-point inspections matters in modern service advising fundamentals work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around multi-point inspections","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Multi-Point Inspections connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master multi-point inspections reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("scheduling", 5, "Scheduling", [
    section("scheduling-s1", "5.1 Scheduling — foundations and vocabulary", ["foundations and vocabulary is where scheduling stops being abstract. In Service Advising Fundamentals, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A repair order is a contract—what you document protects the shop and the driver. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("scheduling-s2", "5.2 Scheduling — how practitioners think", ["Most mistakes in scheduling happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Service lanes run on trust and timestamps; customers forgive delays they understand. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("scheduling-s3", "5.3 Scheduling — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","A repair order is a contract—what you document protects the shop and the driver. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("scheduling-s4", "5.4 Scheduling — common failures and fixes", ["common failures and fixes is where scheduling stops being abstract. In Service Advising Fundamentals, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Service lanes run on trust and timestamps; customers forgive delays they understand. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("scheduling-s5", "5.5 Scheduling — putting it together", ["Most mistakes in scheduling happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","A repair order is a contract—what you document protects the shop and the driver. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why scheduling matters in modern service advising fundamentals work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around scheduling","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Scheduling connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master scheduling reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("parts-basics", 6, "Parts Coordination", [
    section("parts-basics-s1", "6.1 Parts Coordination — foundations and vocabulary", ["foundations and vocabulary is where parts coordination stops being abstract. In Service Advising Fundamentals, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A repair order is a contract—what you document protects the shop and the driver. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("parts-basics-s2", "6.2 Parts Coordination — how practitioners think", ["Most mistakes in parts coordination happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Service lanes run on trust and timestamps; customers forgive delays they understand. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("parts-basics-s3", "6.3 Parts Coordination — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","A repair order is a contract—what you document protects the shop and the driver. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("parts-basics-s4", "6.4 Parts Coordination — common failures and fixes", ["common failures and fixes is where parts coordination stops being abstract. In Service Advising Fundamentals, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Service lanes run on trust and timestamps; customers forgive delays they understand. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("parts-basics-s5", "6.5 Parts Coordination — putting it together", ["Most mistakes in parts coordination happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","A repair order is a contract—what you document protects the shop and the driver. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why parts coordination matters in modern service advising fundamentals work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around parts coordination","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Parts Coordination connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master parts coordination reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("technician-handoff", 7, "Technician Handoff", [
    section("technician-handoff-s1", "7.1 Technician Handoff — foundations and vocabulary", ["foundations and vocabulary is where technician handoff stops being abstract. In Service Advising Fundamentals, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A repair order is a contract—what you document protects the shop and the driver. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("technician-handoff-s2", "7.2 Technician Handoff — how practitioners think", ["Most mistakes in technician handoff happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Service lanes run on trust and timestamps; customers forgive delays they understand. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("technician-handoff-s3", "7.3 Technician Handoff — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","A repair order is a contract—what you document protects the shop and the driver. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("technician-handoff-s4", "7.4 Technician Handoff — common failures and fixes", ["common failures and fixes is where technician handoff stops being abstract. In Service Advising Fundamentals, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Service lanes run on trust and timestamps; customers forgive delays they understand. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("technician-handoff-s5", "7.5 Technician Handoff — putting it together", ["Most mistakes in technician handoff happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","A repair order is a contract—what you document protects the shop and the driver. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why technician handoff matters in modern service advising fundamentals work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around technician handoff","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Technician Handoff connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master technician handoff reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("advisor-metrics", 8, "Advisor Metrics", [
    section("advisor-metrics-s1", "8.1 Advisor Metrics — foundations and vocabulary", ["foundations and vocabulary is where advisor metrics stops being abstract. In Service Advising Fundamentals, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A repair order is a contract—what you document protects the shop and the driver. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("advisor-metrics-s2", "8.2 Advisor Metrics — how practitioners think", ["Most mistakes in advisor metrics happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","Service lanes run on trust and timestamps; customers forgive delays they understand. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("advisor-metrics-s3", "8.3 Advisor Metrics — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","A repair order is a contract—what you document protects the shop and the driver. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("advisor-metrics-s4", "8.4 Advisor Metrics — common failures and fixes", ["common failures and fixes is where advisor metrics stops being abstract. In Service Advising Fundamentals, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","Service lanes run on trust and timestamps; customers forgive delays they understand. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("advisor-metrics-s5", "8.5 Advisor Metrics — putting it together", ["Most mistakes in advisor metrics happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","A repair order is a contract—what you document protects the shop and the driver. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why advisor metrics matters in modern service advising fundamentals work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around advisor metrics","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Advisor Metrics connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master advisor metrics reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  })
];
