import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const SVC_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Service Advising Fundamentals",
  subtitle: "ForgEd path course — Service Advising Fundamentals",
  paragraphs: [
    "Service Advising Fundamentals is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Each chapter includes five sections and section quizzes. Pass chapter quizzes, the course review, and final exam to mark the course complete.",
    "Content is practical workforce education — not licensure, legal, or financial advice.",
  ],
};

export const SVC_TEXTBOOK: TextbookChapter[] = [
  chapter("advisor-role", 1, "The Service Advisor Role", [
      section("advisor-role-s1", "1.1 The Service Advisor Role — applied practice (1)", ["1.1 The Service Advisor Role — applied practice (1) connects The Service Advisor Role to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("advisor-role-s2", "1.2 The Service Advisor Role — applied practice (2)", ["1.2 The Service Advisor Role — applied practice (2) connects The Service Advisor Role to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("advisor-role-s3", "1.3 The Service Advisor Role — applied practice (3)", ["1.3 The Service Advisor Role — applied practice (3) connects The Service Advisor Role to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("advisor-role-s4", "1.4 The Service Advisor Role — applied practice (4)", ["1.4 The Service Advisor Role — applied practice (4) connects The Service Advisor Role to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("advisor-role-s5", "1.5 The Service Advisor Role — applied practice (5)", ["1.5 The Service Advisor Role — applied practice (5) connects The Service Advisor Role to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("shop-flow", 2, "Shop Flow", [
      section("shop-flow-s1", "2.1 Shop Flow — applied practice (1)", ["2.1 Shop Flow — applied practice (1) connects Shop Flow to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("shop-flow-s2", "2.2 Shop Flow — applied practice (2)", ["2.2 Shop Flow — applied practice (2) connects Shop Flow to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("shop-flow-s3", "2.3 Shop Flow — applied practice (3)", ["2.3 Shop Flow — applied practice (3) connects Shop Flow to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("shop-flow-s4", "2.4 Shop Flow — applied practice (4)", ["2.4 Shop Flow — applied practice (4) connects Shop Flow to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("shop-flow-s5", "2.5 Shop Flow — applied practice (5)", ["2.5 Shop Flow — applied practice (5) connects Shop Flow to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("customer-expectations", 3, "Customer Expectations", [
      section("customer-expectations-s1", "3.1 Customer Expectations — applied practice (1)", ["3.1 Customer Expectations — applied practice (1) connects Customer Expectations to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("customer-expectations-s2", "3.2 Customer Expectations — applied practice (2)", ["3.2 Customer Expectations — applied practice (2) connects Customer Expectations to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("customer-expectations-s3", "3.3 Customer Expectations — applied practice (3)", ["3.3 Customer Expectations — applied practice (3) connects Customer Expectations to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("customer-expectations-s4", "3.4 Customer Expectations — applied practice (4)", ["3.4 Customer Expectations — applied practice (4) connects Customer Expectations to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("customer-expectations-s5", "3.5 Customer Expectations — applied practice (5)", ["3.5 Customer Expectations — applied practice (5) connects Customer Expectations to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("multipoint", 4, "Multi-Point Inspections", [
      section("multipoint-s1", "4.1 Multi-Point Inspections — applied practice (1)", ["4.1 Multi-Point Inspections — applied practice (1) connects Multi-Point Inspections to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("multipoint-s2", "4.2 Multi-Point Inspections — applied practice (2)", ["4.2 Multi-Point Inspections — applied practice (2) connects Multi-Point Inspections to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("multipoint-s3", "4.3 Multi-Point Inspections — applied practice (3)", ["4.3 Multi-Point Inspections — applied practice (3) connects Multi-Point Inspections to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("multipoint-s4", "4.4 Multi-Point Inspections — applied practice (4)", ["4.4 Multi-Point Inspections — applied practice (4) connects Multi-Point Inspections to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("multipoint-s5", "4.5 Multi-Point Inspections — applied practice (5)", ["4.5 Multi-Point Inspections — applied practice (5) connects Multi-Point Inspections to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("scheduling", 5, "Scheduling", [
      section("scheduling-s1", "5.1 Scheduling — applied practice (1)", ["5.1 Scheduling — applied practice (1) connects Scheduling to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("scheduling-s2", "5.2 Scheduling — applied practice (2)", ["5.2 Scheduling — applied practice (2) connects Scheduling to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("scheduling-s3", "5.3 Scheduling — applied practice (3)", ["5.3 Scheduling — applied practice (3) connects Scheduling to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("scheduling-s4", "5.4 Scheduling — applied practice (4)", ["5.4 Scheduling — applied practice (4) connects Scheduling to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("scheduling-s5", "5.5 Scheduling — applied practice (5)", ["5.5 Scheduling — applied practice (5) connects Scheduling to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("parts-basics", 6, "Parts Coordination", [
      section("parts-basics-s1", "6.1 Parts Coordination — applied practice (1)", ["6.1 Parts Coordination — applied practice (1) connects Parts Coordination to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("parts-basics-s2", "6.2 Parts Coordination — applied practice (2)", ["6.2 Parts Coordination — applied practice (2) connects Parts Coordination to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("parts-basics-s3", "6.3 Parts Coordination — applied practice (3)", ["6.3 Parts Coordination — applied practice (3) connects Parts Coordination to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("parts-basics-s4", "6.4 Parts Coordination — applied practice (4)", ["6.4 Parts Coordination — applied practice (4) connects Parts Coordination to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("parts-basics-s5", "6.5 Parts Coordination — applied practice (5)", ["6.5 Parts Coordination — applied practice (5) connects Parts Coordination to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("technician-handoff", 7, "Technician Handoff", [
      section("technician-handoff-s1", "7.1 Technician Handoff — applied practice (1)", ["7.1 Technician Handoff — applied practice (1) connects Technician Handoff to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("technician-handoff-s2", "7.2 Technician Handoff — applied practice (2)", ["7.2 Technician Handoff — applied practice (2) connects Technician Handoff to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("technician-handoff-s3", "7.3 Technician Handoff — applied practice (3)", ["7.3 Technician Handoff — applied practice (3) connects Technician Handoff to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("technician-handoff-s4", "7.4 Technician Handoff — applied practice (4)", ["7.4 Technician Handoff — applied practice (4) connects Technician Handoff to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("technician-handoff-s5", "7.5 Technician Handoff — applied practice (5)", ["7.5 Technician Handoff — applied practice (5) connects Technician Handoff to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("advisor-metrics", 8, "Advisor Metrics", [
      section("advisor-metrics-s1", "8.1 Advisor Metrics — applied practice (1)", ["8.1 Advisor Metrics — applied practice (1) connects Advisor Metrics to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("advisor-metrics-s2", "8.2 Advisor Metrics — applied practice (2)", ["8.2 Advisor Metrics — applied practice (2) connects Advisor Metrics to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("advisor-metrics-s3", "8.3 Advisor Metrics — applied practice (3)", ["8.3 Advisor Metrics — applied practice (3) connects Advisor Metrics to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("advisor-metrics-s4", "8.4 Advisor Metrics — applied practice (4)", ["8.4 Advisor Metrics — applied practice (4) connects Advisor Metrics to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("advisor-metrics-s5", "8.5 Advisor Metrics — applied practice (5)", ["8.5 Advisor Metrics — applied practice (5) connects Advisor Metrics to real workforce outcomes in Service Advising Fundamentals. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ])
];
