import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const STFIN_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Startup Finance",
  subtitle: "Workforce training — Startup Finance",
  paragraphs: [
    "Startup Finance is built for professionals who want usable skill—not trivia. Each chapter moves from why the topic matters, through structured explanation, to quizzes that check judgment rather than memorization.",
    "Startup Finance is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn ForgEd path completion badges on your profile.",
    "Content is practical workforce education. It does not replace licensure, legal, medical, or employer-specific policy. When your organization has a rule that conflicts with a general lesson, follow your organization's rule and treat this course as context.",
  ],
};

export const STFIN_TEXTBOOK: TextbookChapter[] = [
  chapter("runway", 1, "Runway", [
    section("runway-s1", "1.1 Runway — foundations and vocabulary", ["foundations and vocabulary is where runway stops being abstract. In Startup Finance, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("runway-s2", "1.2 Runway — how practitioners think", ["Most mistakes in runway happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("runway-s3", "1.3 Runway — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("runway-s4", "1.4 Runway — common failures and fixes", ["common failures and fixes is where runway stops being abstract. In Startup Finance, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("runway-s5", "1.5 Runway — putting it together", ["Most mistakes in runway happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why runway matters in modern startup finance work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around runway","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Runway connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master runway reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("burn-rate", 2, "Burn Rate", [
    section("burn-rate-s1", "2.1 Burn Rate — foundations and vocabulary", ["foundations and vocabulary is where burn rate stops being abstract. In Startup Finance, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("burn-rate-s2", "2.2 Burn Rate — how practitioners think", ["Most mistakes in burn rate happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("burn-rate-s3", "2.3 Burn Rate — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("burn-rate-s4", "2.4 Burn Rate — common failures and fixes", ["common failures and fixes is where burn rate stops being abstract. In Startup Finance, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("burn-rate-s5", "2.5 Burn Rate — putting it together", ["Most mistakes in burn rate happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why burn rate matters in modern startup finance work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around burn rate","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Burn Rate connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master burn rate reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("unit-economics", 3, "Unit Economics", [
    section("unit-economics-s1", "3.1 Unit Economics — foundations and vocabulary", ["foundations and vocabulary is where unit economics stops being abstract. In Startup Finance, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("unit-economics-s2", "3.2 Unit Economics — how practitioners think", ["Most mistakes in unit economics happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("unit-economics-s3", "3.3 Unit Economics — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("unit-economics-s4", "3.4 Unit Economics — common failures and fixes", ["common failures and fixes is where unit economics stops being abstract. In Startup Finance, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("unit-economics-s5", "3.5 Unit Economics — putting it together", ["Most mistakes in unit economics happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why unit economics matters in modern startup finance work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around unit economics","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Unit Economics connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master unit economics reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("forecasting", 4, "Simple Forecasting", [
    section("forecasting-s1", "4.1 Simple Forecasting — foundations and vocabulary", ["foundations and vocabulary is where simple forecasting stops being abstract. In Startup Finance, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("forecasting-s2", "4.2 Simple Forecasting — how practitioners think", ["Most mistakes in simple forecasting happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("forecasting-s3", "4.3 Simple Forecasting — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("forecasting-s4", "4.4 Simple Forecasting — common failures and fixes", ["common failures and fixes is where simple forecasting stops being abstract. In Startup Finance, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("forecasting-s5", "4.5 Simple Forecasting — putting it together", ["Most mistakes in simple forecasting happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why simple forecasting matters in modern startup finance work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around simple forecasting","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Simple Forecasting connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master simple forecasting reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("fundraising-intro", 5, "Fundraising Intro", [
    section("fundraising-intro-s1", "5.1 Fundraising Intro — foundations and vocabulary", ["foundations and vocabulary is where fundraising intro stops being abstract. In Startup Finance, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("fundraising-intro-s2", "5.2 Fundraising Intro — how practitioners think", ["Most mistakes in fundraising intro happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("fundraising-intro-s3", "5.3 Fundraising Intro — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("fundraising-intro-s4", "5.4 Fundraising Intro — common failures and fixes", ["common failures and fixes is where fundraising intro stops being abstract. In Startup Finance, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("fundraising-intro-s5", "5.5 Fundraising Intro — putting it together", ["Most mistakes in fundraising intro happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why fundraising intro matters in modern startup finance work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around fundraising intro","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Fundraising Intro connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master fundraising intro reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("cap-table", 6, "Cap Table Basics", [
    section("cap-table-s1", "6.1 Cap Table Basics — foundations and vocabulary", ["foundations and vocabulary is where cap table basics stops being abstract. In Startup Finance, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("cap-table-s2", "6.2 Cap Table Basics — how practitioners think", ["Most mistakes in cap table basics happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("cap-table-s3", "6.3 Cap Table Basics — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("cap-table-s4", "6.4 Cap Table Basics — common failures and fixes", ["common failures and fixes is where cap table basics stops being abstract. In Startup Finance, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("cap-table-s5", "6.5 Cap Table Basics — putting it together", ["Most mistakes in cap table basics happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why cap table basics matters in modern startup finance work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around cap table basics","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Cap Table Basics connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master cap table basics reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("financial-model", 7, "Lightweight Models", [
    section("financial-model-s1", "7.1 Lightweight Models — foundations and vocabulary", ["foundations and vocabulary is where lightweight models stops being abstract. In Startup Finance, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("financial-model-s2", "7.2 Lightweight Models — how practitioners think", ["Most mistakes in lightweight models happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("financial-model-s3", "7.3 Lightweight Models — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("financial-model-s4", "7.4 Lightweight Models — common failures and fixes", ["common failures and fixes is where lightweight models stops being abstract. In Startup Finance, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("financial-model-s5", "7.5 Lightweight Models — putting it together", ["Most mistakes in lightweight models happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why lightweight models matters in modern startup finance work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around lightweight models","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Lightweight Models connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master lightweight models reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("finance-ops", 8, "Finance Operations", [
    section("finance-ops-s1", "8.1 Finance Operations — foundations and vocabulary", ["foundations and vocabulary is where finance operations stops being abstract. In Startup Finance, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("finance-ops-s2", "8.2 Finance Operations — how practitioners think", ["Most mistakes in finance operations happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("finance-ops-s3", "8.3 Finance Operations — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("finance-ops-s4", "8.4 Finance Operations — common failures and fixes", ["common failures and fixes is where finance operations stops being abstract. In Startup Finance, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("finance-ops-s5", "8.5 Finance Operations — putting it together", ["Most mistakes in finance operations happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why finance operations matters in modern startup finance work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around finance operations","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Finance Operations connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master finance operations reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  })
];
