import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const TAX_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Taxes Explained",
  subtitle: "Workforce training — Taxes Explained",
  paragraphs: [
    "Taxes Explained is built for professionals who want usable skill—not trivia. Each chapter moves from why the topic matters, through structured explanation, to quizzes that check judgment rather than memorization.",
    "Taxes Explained is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Content is practical workforce education. It does not replace licensure, legal, medical, or employer-specific policy. When your organization has a rule that conflicts with a general lesson, follow your organization's rule and treat this course as context.",
  ],
};

export const TAX_TEXTBOOK: TextbookChapter[] = [
  chapter("tax-system", 1, "How Taxes Work", [
    section("tax-system-s1", "1.1 How Taxes Work — foundations and vocabulary", ["foundations and vocabulary is where how taxes work stops being abstract. In Taxes Explained, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("tax-system-s2", "1.2 How Taxes Work — how practitioners think", ["Most mistakes in how taxes work happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("tax-system-s3", "1.3 How Taxes Work — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("tax-system-s4", "1.4 How Taxes Work — common failures and fixes", ["common failures and fixes is where how taxes work stops being abstract. In Taxes Explained, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("tax-system-s5", "1.5 How Taxes Work — putting it together", ["Most mistakes in how taxes work happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why how taxes work matters in modern taxes explained work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around how taxes work","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "How Taxes Work connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master how taxes work reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("w2-1099", 2, "W-2 vs 1099", [
    section("w2-1099-s1", "2.1 W-2 vs 1099 — foundations and vocabulary", ["foundations and vocabulary is where w-2 vs 1099 stops being abstract. In Taxes Explained, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("w2-1099-s2", "2.2 W-2 vs 1099 — how practitioners think", ["Most mistakes in w-2 vs 1099 happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("w2-1099-s3", "2.3 W-2 vs 1099 — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("w2-1099-s4", "2.4 W-2 vs 1099 — common failures and fixes", ["common failures and fixes is where w-2 vs 1099 stops being abstract. In Taxes Explained, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("w2-1099-s5", "2.5 W-2 vs 1099 — putting it together", ["Most mistakes in w-2 vs 1099 happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why w-2 vs 1099 matters in modern taxes explained work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around w-2 vs 1099","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "W-2 vs 1099 connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master w-2 vs 1099 reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("withholding", 3, "Withholding", [
    section("withholding-s1", "3.1 Withholding — foundations and vocabulary", ["foundations and vocabulary is where withholding stops being abstract. In Taxes Explained, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("withholding-s2", "3.2 Withholding — how practitioners think", ["Most mistakes in withholding happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("withholding-s3", "3.3 Withholding — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("withholding-s4", "3.4 Withholding — common failures and fixes", ["common failures and fixes is where withholding stops being abstract. In Taxes Explained, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("withholding-s5", "3.5 Withholding — putting it together", ["Most mistakes in withholding happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why withholding matters in modern taxes explained work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around withholding","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Withholding connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master withholding reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("deductions", 4, "Deductions Overview", [
    section("deductions-s1", "4.1 Deductions Overview — foundations and vocabulary", ["foundations and vocabulary is where deductions overview stops being abstract. In Taxes Explained, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("deductions-s2", "4.2 Deductions Overview — how practitioners think", ["Most mistakes in deductions overview happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("deductions-s3", "4.3 Deductions Overview — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("deductions-s4", "4.4 Deductions Overview — common failures and fixes", ["common failures and fixes is where deductions overview stops being abstract. In Taxes Explained, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("deductions-s5", "4.5 Deductions Overview — putting it together", ["Most mistakes in deductions overview happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why deductions overview matters in modern taxes explained work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around deductions overview","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Deductions Overview connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master deductions overview reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("credits", 5, "Tax Credits", [
    section("credits-s1", "5.1 Tax Credits — foundations and vocabulary", ["foundations and vocabulary is where tax credits stops being abstract. In Taxes Explained, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("credits-s2", "5.2 Tax Credits — how practitioners think", ["Most mistakes in tax credits happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("credits-s3", "5.3 Tax Credits — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("credits-s4", "5.4 Tax Credits — common failures and fixes", ["common failures and fixes is where tax credits stops being abstract. In Taxes Explained, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("credits-s5", "5.5 Tax Credits — putting it together", ["Most mistakes in tax credits happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why tax credits matters in modern taxes explained work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around tax credits","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Tax Credits connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master tax credits reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("filing", 6, "Filing Basics", [
    section("filing-s1", "6.1 Filing Basics — foundations and vocabulary", ["foundations and vocabulary is where filing basics stops being abstract. In Taxes Explained, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("filing-s2", "6.2 Filing Basics — how practitioners think", ["Most mistakes in filing basics happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("filing-s3", "6.3 Filing Basics — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("filing-s4", "6.4 Filing Basics — common failures and fixes", ["common failures and fixes is where filing basics stops being abstract. In Taxes Explained, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("filing-s5", "6.5 Filing Basics — putting it together", ["Most mistakes in filing basics happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why filing basics matters in modern taxes explained work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around filing basics","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Filing Basics connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master filing basics reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("self-employed-tax", 7, "Self-Employed Taxes", [
    section("self-employed-tax-s1", "7.1 Self-Employed Taxes — foundations and vocabulary", ["foundations and vocabulary is where self-employed taxes stops being abstract. In Taxes Explained, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("self-employed-tax-s2", "7.2 Self-Employed Taxes — how practitioners think", ["Most mistakes in self-employed taxes happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("self-employed-tax-s3", "7.3 Self-Employed Taxes — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("self-employed-tax-s4", "7.4 Self-Employed Taxes — common failures and fixes", ["common failures and fixes is where self-employed taxes stops being abstract. In Taxes Explained, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("self-employed-tax-s5", "7.5 Self-Employed Taxes — putting it together", ["Most mistakes in self-employed taxes happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why self-employed taxes matters in modern taxes explained work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around self-employed taxes","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Self-Employed Taxes connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master self-employed taxes reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("records", 8, "Record Keeping", [
    section("records-s1", "8.1 Record Keeping — foundations and vocabulary", ["foundations and vocabulary is where record keeping stops being abstract. In Taxes Explained, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","The best prompt is the one your teammate could run without you in the room. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("records-s2", "8.2 Record Keeping — how practitioners think", ["Most mistakes in record keeping happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","AI outputs are drafts until a human checks facts, policy, and tone. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("records-s3", "8.3 Record Keeping — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","The best prompt is the one your teammate could run without you in the room. Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("records-s4", "8.4 Record Keeping — common failures and fixes", ["common failures and fixes is where record keeping stops being abstract. In Taxes Explained, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","AI outputs are drafts until a human checks facts, policy, and tone. A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("records-s5", "8.5 Record Keeping — putting it together", ["Most mistakes in record keeping happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","The best prompt is the one your teammate could run without you in the room. When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why record keeping matters in modern taxes explained work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around record keeping","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Record Keeping connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master record keeping reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  })
];
