import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const TEACH_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Teaching Fundamentals",
  subtitle: "ForgEd deep-dive — teaching fundamentals",
  paragraphs: [
    "This ForgEd digital textbook presents Teaching Fundamentals at academic survey depth for self-paced study.",
    "Complete each section quiz before advancing. Chapter and course assessments draw from a 150-question bank.",
    "Material is general education, not professional licensure or certification prep by itself.",
  ],
};

export const TEACH_TEXTBOOK: TextbookChapter[] = [
  chapter("learning-theory", 1, "Learning Theory", [
      section("learning-theory-s1", "1.1 Learning Theory — core concepts (1)", ["1.1 Learning Theory — core concepts (1) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply learning theory with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in learning theory."]),
      section("learning-theory-s2", "1.2 Learning Theory — core concepts (2)", ["1.2 Learning Theory — core concepts (2) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply learning theory with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in learning theory."]),
      section("learning-theory-s3", "1.3 Learning Theory — core concepts (3)", ["1.3 Learning Theory — core concepts (3) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply learning theory with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in learning theory."]),
      section("learning-theory-s4", "1.4 Learning Theory — core concepts (4)", ["1.4 Learning Theory — core concepts (4) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply learning theory with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in learning theory."]),
      section("learning-theory-s5", "1.5 Learning Theory — core concepts (5)", ["1.5 Learning Theory — core concepts (5) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply learning theory with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in learning theory."]),
  ]),
  chapter("lesson-planning", 2, "Lesson Planning", [
      section("lesson-planning-s1", "2.1 Lesson Planning — core concepts (1)", ["2.1 Lesson Planning — core concepts (1) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply lesson planning with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in lesson planning."]),
      section("lesson-planning-s2", "2.2 Lesson Planning — core concepts (2)", ["2.2 Lesson Planning — core concepts (2) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply lesson planning with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in lesson planning."]),
      section("lesson-planning-s3", "2.3 Lesson Planning — core concepts (3)", ["2.3 Lesson Planning — core concepts (3) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply lesson planning with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in lesson planning."]),
      section("lesson-planning-s4", "2.4 Lesson Planning — core concepts (4)", ["2.4 Lesson Planning — core concepts (4) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply lesson planning with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in lesson planning."]),
      section("lesson-planning-s5", "2.5 Lesson Planning — core concepts (5)", ["2.5 Lesson Planning — core concepts (5) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply lesson planning with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in lesson planning."]),
  ]),
  chapter("classroom-management", 3, "Classroom Management", [
      section("classroom-management-s1", "3.1 Classroom Management — core concepts (1)", ["3.1 Classroom Management — core concepts (1) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply classroom management with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in classroom management."]),
      section("classroom-management-s2", "3.2 Classroom Management — core concepts (2)", ["3.2 Classroom Management — core concepts (2) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply classroom management with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in classroom management."]),
      section("classroom-management-s3", "3.3 Classroom Management — core concepts (3)", ["3.3 Classroom Management — core concepts (3) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply classroom management with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in classroom management."]),
      section("classroom-management-s4", "3.4 Classroom Management — core concepts (4)", ["3.4 Classroom Management — core concepts (4) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply classroom management with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in classroom management."]),
      section("classroom-management-s5", "3.5 Classroom Management — core concepts (5)", ["3.5 Classroom Management — core concepts (5) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply classroom management with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in classroom management."]),
  ]),
  chapter("assessment", 4, "Assessment and Feedback", [
      section("assessment-s1", "4.1 Assessment and Feedback — core concepts (1)", ["4.1 Assessment and Feedback — core concepts (1) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply assessment and feedback with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in assessment and feedback."]),
      section("assessment-s2", "4.2 Assessment and Feedback — core concepts (2)", ["4.2 Assessment and Feedback — core concepts (2) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply assessment and feedback with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in assessment and feedback."]),
      section("assessment-s3", "4.3 Assessment and Feedback — core concepts (3)", ["4.3 Assessment and Feedback — core concepts (3) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply assessment and feedback with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in assessment and feedback."]),
      section("assessment-s4", "4.4 Assessment and Feedback — core concepts (4)", ["4.4 Assessment and Feedback — core concepts (4) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply assessment and feedback with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in assessment and feedback."]),
      section("assessment-s5", "4.5 Assessment and Feedback — core concepts (5)", ["4.5 Assessment and Feedback — core concepts (5) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply assessment and feedback with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in assessment and feedback."]),
  ]),
  chapter("differentiation", 5, "Differentiation", [
      section("differentiation-s1", "5.1 Differentiation — core concepts (1)", ["5.1 Differentiation — core concepts (1) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply differentiation with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in differentiation."]),
      section("differentiation-s2", "5.2 Differentiation — core concepts (2)", ["5.2 Differentiation — core concepts (2) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply differentiation with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in differentiation."]),
      section("differentiation-s3", "5.3 Differentiation — core concepts (3)", ["5.3 Differentiation — core concepts (3) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply differentiation with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in differentiation."]),
      section("differentiation-s4", "5.4 Differentiation — core concepts (4)", ["5.4 Differentiation — core concepts (4) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply differentiation with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in differentiation."]),
      section("differentiation-s5", "5.5 Differentiation — core concepts (5)", ["5.5 Differentiation — core concepts (5) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply differentiation with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in differentiation."]),
  ]),
  chapter("edtech", 6, "Educational Technology", [
      section("edtech-s1", "6.1 Educational Technology — core concepts (1)", ["6.1 Educational Technology — core concepts (1) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply educational technology with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in educational technology."]),
      section("edtech-s2", "6.2 Educational Technology — core concepts (2)", ["6.2 Educational Technology — core concepts (2) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply educational technology with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in educational technology."]),
      section("edtech-s3", "6.3 Educational Technology — core concepts (3)", ["6.3 Educational Technology — core concepts (3) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply educational technology with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in educational technology."]),
      section("edtech-s4", "6.4 Educational Technology — core concepts (4)", ["6.4 Educational Technology — core concepts (4) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply educational technology with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in educational technology."]),
      section("edtech-s5", "6.5 Educational Technology — core concepts (5)", ["6.5 Educational Technology — core concepts (5) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply educational technology with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in educational technology."]),
  ]),
  chapter("tutoring", 7, "Tutoring Skills", [
      section("tutoring-s1", "7.1 Tutoring Skills — core concepts (1)", ["7.1 Tutoring Skills — core concepts (1) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply tutoring skills with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in tutoring skills."]),
      section("tutoring-s2", "7.2 Tutoring Skills — core concepts (2)", ["7.2 Tutoring Skills — core concepts (2) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply tutoring skills with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in tutoring skills."]),
      section("tutoring-s3", "7.3 Tutoring Skills — core concepts (3)", ["7.3 Tutoring Skills — core concepts (3) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply tutoring skills with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in tutoring skills."]),
      section("tutoring-s4", "7.4 Tutoring Skills — core concepts (4)", ["7.4 Tutoring Skills — core concepts (4) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply tutoring skills with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in tutoring skills."]),
      section("tutoring-s5", "7.5 Tutoring Skills — core concepts (5)", ["7.5 Tutoring Skills — core concepts (5) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply tutoring skills with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in tutoring skills."]),
  ]),
  chapter("special-needs", 8, "Inclusive Education", [
      section("special-needs-s1", "8.1 Inclusive Education — core concepts (1)", ["8.1 Inclusive Education — core concepts (1) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply inclusive education with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in inclusive education."]),
      section("special-needs-s2", "8.2 Inclusive Education — core concepts (2)", ["8.2 Inclusive Education — core concepts (2) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply inclusive education with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in inclusive education."]),
      section("special-needs-s3", "8.3 Inclusive Education — core concepts (3)", ["8.3 Inclusive Education — core concepts (3) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply inclusive education with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in inclusive education."]),
      section("special-needs-s4", "8.4 Inclusive Education — core concepts (4)", ["8.4 Inclusive Education — core concepts (4) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply inclusive education with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in inclusive education."]),
      section("special-needs-s5", "8.5 Inclusive Education — core concepts (5)", ["8.5 Inclusive Education — core concepts (5) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply inclusive education with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in inclusive education."]),
  ]),
  chapter("professionalism", 9, "Professionalism in Education", [
      section("professionalism-s1", "9.1 Professionalism in Education — core concepts (1)", ["9.1 Professionalism in Education — core concepts (1) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply professionalism in education with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in professionalism in education."]),
      section("professionalism-s2", "9.2 Professionalism in Education — core concepts (2)", ["9.2 Professionalism in Education — core concepts (2) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply professionalism in education with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in professionalism in education."]),
      section("professionalism-s3", "9.3 Professionalism in Education — core concepts (3)", ["9.3 Professionalism in Education — core concepts (3) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply professionalism in education with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in professionalism in education."]),
      section("professionalism-s4", "9.4 Professionalism in Education — core concepts (4)", ["9.4 Professionalism in Education — core concepts (4) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply professionalism in education with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in professionalism in education."]),
      section("professionalism-s5", "9.5 Professionalism in Education — core concepts (5)", ["9.5 Professionalism in Education — core concepts (5) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply professionalism in education with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in professionalism in education."]),
  ]),
  chapter("teaching-careers", 10, "Teaching Careers", [
      section("teaching-careers-s1", "10.1 Teaching Careers — core concepts (1)", ["10.1 Teaching Careers — core concepts (1) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply teaching careers with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in teaching careers."]),
      section("teaching-careers-s2", "10.2 Teaching Careers — core concepts (2)", ["10.2 Teaching Careers — core concepts (2) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply teaching careers with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in teaching careers."]),
      section("teaching-careers-s3", "10.3 Teaching Careers — core concepts (3)", ["10.3 Teaching Careers — core concepts (3) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply teaching careers with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in teaching careers."]),
      section("teaching-careers-s4", "10.4 Teaching Careers — core concepts (4)", ["10.4 Teaching Careers — core concepts (4) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply teaching careers with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in teaching careers."]),
      section("teaching-careers-s5", "10.5 Teaching Careers — core concepts (5)", ["10.5 Teaching Careers — core concepts (5) is a core topic in Teaching Fundamentals. Learners should connect definitions to how professionals apply teaching careers with evidence-based practice.","The textbook emphasizes chapter objectives and section quizzes before advancing. Assessment questions draw from a randomized bank tied to this chapter.","Use this section as a foundation for certifications, workplace decisions, and further specialization in teaching careers."]),
  ])
];
