import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const THREAT_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Threat Awareness",
  subtitle: "ForgEd path course — Threat Awareness",
  paragraphs: [
    "Threat Awareness is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Each chapter includes five sections and section quizzes. Pass chapter quizzes, the course review, and final exam to mark the course complete.",
    "Content is practical workforce education — not licensure, legal, or financial advice.",
  ],
};

export const THREAT_TEXTBOOK: TextbookChapter[] = [
  chapter("threat-landscape", 1, "Threat Landscape", [
      section("threat-landscape-s1", "1.1 Threat Landscape — applied practice (1)", ["1.1 Threat Landscape — applied practice (1) connects Threat Landscape to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("threat-landscape-s2", "1.2 Threat Landscape — applied practice (2)", ["1.2 Threat Landscape — applied practice (2) connects Threat Landscape to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("threat-landscape-s3", "1.3 Threat Landscape — applied practice (3)", ["1.3 Threat Landscape — applied practice (3) connects Threat Landscape to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("threat-landscape-s4", "1.4 Threat Landscape — applied practice (4)", ["1.4 Threat Landscape — applied practice (4) connects Threat Landscape to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("threat-landscape-s5", "1.5 Threat Landscape — applied practice (5)", ["1.5 Threat Landscape — applied practice (5) connects Threat Landscape to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("malware-types", 2, "Malware Types", [
      section("malware-types-s1", "2.1 Malware Types — applied practice (1)", ["2.1 Malware Types — applied practice (1) connects Malware Types to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("malware-types-s2", "2.2 Malware Types — applied practice (2)", ["2.2 Malware Types — applied practice (2) connects Malware Types to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("malware-types-s3", "2.3 Malware Types — applied practice (3)", ["2.3 Malware Types — applied practice (3) connects Malware Types to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("malware-types-s4", "2.4 Malware Types — applied practice (4)", ["2.4 Malware Types — applied practice (4) connects Malware Types to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("malware-types-s5", "2.5 Malware Types — applied practice (5)", ["2.5 Malware Types — applied practice (5) connects Malware Types to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("ransomware", 3, "Ransomware", [
      section("ransomware-s1", "3.1 Ransomware — applied practice (1)", ["3.1 Ransomware — applied practice (1) connects Ransomware to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ransomware-s2", "3.2 Ransomware — applied practice (2)", ["3.2 Ransomware — applied practice (2) connects Ransomware to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ransomware-s3", "3.3 Ransomware — applied practice (3)", ["3.3 Ransomware — applied practice (3) connects Ransomware to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ransomware-s4", "3.4 Ransomware — applied practice (4)", ["3.4 Ransomware — applied practice (4) connects Ransomware to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("ransomware-s5", "3.5 Ransomware — applied practice (5)", ["3.5 Ransomware — applied practice (5) connects Ransomware to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("insider-threats", 4, "Insider Threats", [
      section("insider-threats-s1", "4.1 Insider Threats — applied practice (1)", ["4.1 Insider Threats — applied practice (1) connects Insider Threats to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("insider-threats-s2", "4.2 Insider Threats — applied practice (2)", ["4.2 Insider Threats — applied practice (2) connects Insider Threats to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("insider-threats-s3", "4.3 Insider Threats — applied practice (3)", ["4.3 Insider Threats — applied practice (3) connects Insider Threats to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("insider-threats-s4", "4.4 Insider Threats — applied practice (4)", ["4.4 Insider Threats — applied practice (4) connects Insider Threats to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("insider-threats-s5", "4.5 Insider Threats — applied practice (5)", ["4.5 Insider Threats — applied practice (5) connects Insider Threats to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("supply-chain", 5, "Supply Chain Risk", [
      section("supply-chain-s1", "5.1 Supply Chain Risk — applied practice (1)", ["5.1 Supply Chain Risk — applied practice (1) connects Supply Chain Risk to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("supply-chain-s2", "5.2 Supply Chain Risk — applied practice (2)", ["5.2 Supply Chain Risk — applied practice (2) connects Supply Chain Risk to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("supply-chain-s3", "5.3 Supply Chain Risk — applied practice (3)", ["5.3 Supply Chain Risk — applied practice (3) connects Supply Chain Risk to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("supply-chain-s4", "5.4 Supply Chain Risk — applied practice (4)", ["5.4 Supply Chain Risk — applied practice (4) connects Supply Chain Risk to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("supply-chain-s5", "5.5 Supply Chain Risk — applied practice (5)", ["5.5 Supply Chain Risk — applied practice (5) connects Supply Chain Risk to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("attack-vectors", 6, "Attack Vectors", [
      section("attack-vectors-s1", "6.1 Attack Vectors — applied practice (1)", ["6.1 Attack Vectors — applied practice (1) connects Attack Vectors to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("attack-vectors-s2", "6.2 Attack Vectors — applied practice (2)", ["6.2 Attack Vectors — applied practice (2) connects Attack Vectors to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("attack-vectors-s3", "6.3 Attack Vectors — applied practice (3)", ["6.3 Attack Vectors — applied practice (3) connects Attack Vectors to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("attack-vectors-s4", "6.4 Attack Vectors — applied practice (4)", ["6.4 Attack Vectors — applied practice (4) connects Attack Vectors to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("attack-vectors-s5", "6.5 Attack Vectors — applied practice (5)", ["6.5 Attack Vectors — applied practice (5) connects Attack Vectors to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("threat-intel", 7, "Threat Intelligence Intro", [
      section("threat-intel-s1", "7.1 Threat Intelligence Intro — applied practice (1)", ["7.1 Threat Intelligence Intro — applied practice (1) connects Threat Intelligence Intro to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("threat-intel-s2", "7.2 Threat Intelligence Intro — applied practice (2)", ["7.2 Threat Intelligence Intro — applied practice (2) connects Threat Intelligence Intro to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("threat-intel-s3", "7.3 Threat Intelligence Intro — applied practice (3)", ["7.3 Threat Intelligence Intro — applied practice (3) connects Threat Intelligence Intro to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("threat-intel-s4", "7.4 Threat Intelligence Intro — applied practice (4)", ["7.4 Threat Intelligence Intro — applied practice (4) connects Threat Intelligence Intro to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("threat-intel-s5", "7.5 Threat Intelligence Intro — applied practice (5)", ["7.5 Threat Intelligence Intro — applied practice (5) connects Threat Intelligence Intro to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("reporting-threats", 8, "Reporting Threats", [
      section("reporting-threats-s1", "8.1 Reporting Threats — applied practice (1)", ["8.1 Reporting Threats — applied practice (1) connects Reporting Threats to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("reporting-threats-s2", "8.2 Reporting Threats — applied practice (2)", ["8.2 Reporting Threats — applied practice (2) connects Reporting Threats to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("reporting-threats-s3", "8.3 Reporting Threats — applied practice (3)", ["8.3 Reporting Threats — applied practice (3) connects Reporting Threats to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("reporting-threats-s4", "8.4 Reporting Threats — applied practice (4)", ["8.4 Reporting Threats — applied practice (4) connects Reporting Threats to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("reporting-threats-s5", "8.5 Reporting Threats — applied practice (5)", ["8.5 Reporting Threats — applied practice (5) connects Reporting Threats to real workforce outcomes in Threat Awareness. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ])
];
