import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const THREAT_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Threat Awareness",
  subtitle: "Workforce training — Threat Awareness",
  paragraphs: [
    "Threat Awareness is built for professionals who want usable skill—not trivia. Each chapter moves from why the topic matters, through structured explanation, to quizzes that check judgment rather than memorization.",
    "Threat Awareness is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn ForgEd path completion badges on your profile.",
    "Content is practical workforce education. It does not replace licensure, legal, medical, or employer-specific policy. When your organization has a rule that conflicts with a general lesson, follow your organization's rule and treat this course as context.",
  ],
};

export const THREAT_TEXTBOOK: TextbookChapter[] = [
  chapter("threat-landscape", 1, "Threat Landscape", [
    section("threat-landscape-s1", "1.1 Threat Landscape — foundations and vocabulary", ["foundations and vocabulary is where threat landscape stops being abstract. In Threat Awareness, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("threat-landscape-s2", "1.2 Threat Landscape — how practitioners think", ["Most mistakes in threat landscape happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("threat-landscape-s3", "1.3 Threat Landscape — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("threat-landscape-s4", "1.4 Threat Landscape — common failures and fixes", ["common failures and fixes is where threat landscape stops being abstract. In Threat Awareness, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("threat-landscape-s5", "1.5 Threat Landscape — putting it together", ["Most mistakes in threat landscape happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why threat landscape matters in modern threat awareness work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around threat landscape","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Threat Landscape connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master threat landscape reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("malware-types", 2, "Malware Types", [
    section("malware-types-s1", "2.1 Malware Types — foundations and vocabulary", ["foundations and vocabulary is where malware types stops being abstract. In Threat Awareness, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("malware-types-s2", "2.2 Malware Types — how practitioners think", ["Most mistakes in malware types happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("malware-types-s3", "2.3 Malware Types — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("malware-types-s4", "2.4 Malware Types — common failures and fixes", ["common failures and fixes is where malware types stops being abstract. In Threat Awareness, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("malware-types-s5", "2.5 Malware Types — putting it together", ["Most mistakes in malware types happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why malware types matters in modern threat awareness work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around malware types","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Malware Types connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master malware types reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("ransomware", 3, "Ransomware", [
    section("ransomware-s1", "3.1 Ransomware — foundations and vocabulary", ["foundations and vocabulary is where ransomware stops being abstract. In Threat Awareness, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("ransomware-s2", "3.2 Ransomware — how practitioners think", ["Most mistakes in ransomware happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("ransomware-s3", "3.3 Ransomware — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("ransomware-s4", "3.4 Ransomware — common failures and fixes", ["common failures and fixes is where ransomware stops being abstract. In Threat Awareness, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("ransomware-s5", "3.5 Ransomware — putting it together", ["Most mistakes in ransomware happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why ransomware matters in modern threat awareness work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around ransomware","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Ransomware connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master ransomware reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("insider-threats", 4, "Insider Threats", [
    section("insider-threats-s1", "4.1 Insider Threats — foundations and vocabulary", ["foundations and vocabulary is where insider threats stops being abstract. In Threat Awareness, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("insider-threats-s2", "4.2 Insider Threats — how practitioners think", ["Most mistakes in insider threats happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("insider-threats-s3", "4.3 Insider Threats — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("insider-threats-s4", "4.4 Insider Threats — common failures and fixes", ["common failures and fixes is where insider threats stops being abstract. In Threat Awareness, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("insider-threats-s5", "4.5 Insider Threats — putting it together", ["Most mistakes in insider threats happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why insider threats matters in modern threat awareness work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around insider threats","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Insider Threats connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master insider threats reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("supply-chain", 5, "Supply Chain Risk", [
    section("supply-chain-s1", "5.1 Supply Chain Risk — foundations and vocabulary", ["foundations and vocabulary is where supply chain risk stops being abstract. In Threat Awareness, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("supply-chain-s2", "5.2 Supply Chain Risk — how practitioners think", ["Most mistakes in supply chain risk happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("supply-chain-s3", "5.3 Supply Chain Risk — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("supply-chain-s4", "5.4 Supply Chain Risk — common failures and fixes", ["common failures and fixes is where supply chain risk stops being abstract. In Threat Awareness, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("supply-chain-s5", "5.5 Supply Chain Risk — putting it together", ["Most mistakes in supply chain risk happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why supply chain risk matters in modern threat awareness work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around supply chain risk","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Supply Chain Risk connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master supply chain risk reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("attack-vectors", 6, "Attack Vectors", [
    section("attack-vectors-s1", "6.1 Attack Vectors — foundations and vocabulary", ["foundations and vocabulary is where attack vectors stops being abstract. In Threat Awareness, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("attack-vectors-s2", "6.2 Attack Vectors — how practitioners think", ["Most mistakes in attack vectors happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("attack-vectors-s3", "6.3 Attack Vectors — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("attack-vectors-s4", "6.4 Attack Vectors — common failures and fixes", ["common failures and fixes is where attack vectors stops being abstract. In Threat Awareness, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("attack-vectors-s5", "6.5 Attack Vectors — putting it together", ["Most mistakes in attack vectors happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why attack vectors matters in modern threat awareness work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around attack vectors","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Attack Vectors connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master attack vectors reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("threat-intel", 7, "Threat Intelligence Intro", [
    section("threat-intel-s1", "7.1 Threat Intelligence Intro — foundations and vocabulary", ["foundations and vocabulary is where threat intelligence intro stops being abstract. In Threat Awareness, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("threat-intel-s2", "7.2 Threat Intelligence Intro — how practitioners think", ["Most mistakes in threat intelligence intro happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("threat-intel-s3", "7.3 Threat Intelligence Intro — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("threat-intel-s4", "7.4 Threat Intelligence Intro — common failures and fixes", ["common failures and fixes is where threat intelligence intro stops being abstract. In Threat Awareness, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("threat-intel-s5", "7.5 Threat Intelligence Intro — putting it together", ["Most mistakes in threat intelligence intro happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why threat intelligence intro matters in modern threat awareness work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around threat intelligence intro","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Threat Intelligence Intro connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master threat intelligence intro reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  }),
  chapter("reporting-threats", 8, "Reporting Threats", [
    section("reporting-threats-s1", "8.1 Reporting Threats — foundations and vocabulary", ["foundations and vocabulary is where reporting threats stops being abstract. In Threat Awareness, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("reporting-threats-s2", "8.2 Reporting Threats — how practitioners think", ["Most mistakes in reporting threats happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. how practitioners think gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
    section("reporting-threats-s3", "8.3 Reporting Threats — workplace application", ["Workforce training fails when it only defines terms. This section on workplace application shows how the concept shows up in conversations, systems, and outcomes you are accountable for.","Compare two responses: a vague \"we should improve communication\" versus \"we will confirm approval in writing before ordering parts.\" The second is actionable; the first is noise. workplace application is about making the second kind of statement normal.","Before you leave this section, name one behavior you will try this week and one you will stop. Small, explicit commitments outperform vague \"I learned something\" notes in performance reviews and team standups."]),
    section("reporting-threats-s4", "8.4 Reporting Threats — common failures and fixes", ["common failures and fixes is where reporting threats stops being abstract. In Threat Awareness, this section answers a practical question: what would a competent professional notice, decide, and document in the first ten minutes of a real shift?","A useful habit is to separate facts from interpretations before you act. Facts are observable: what was said, what was measured, what policy applies. Interpretations are conclusions—and they should be labeled that way when you escalate to a manager or customer.","On the job, adapt examples to your shop, team, or organization. Policies, price books, and customer expectations differ—but the reasoning pattern in this section should survive those differences if you keep evidence and courtesy paired together."]),
    section("reporting-threats-s5", "8.5 Reporting Threats — putting it together", ["Most mistakes in reporting threats happen here—not because people lack intelligence, but because they skip the checks that turn opinion into evidence. putting it together gives you those checks in plain language.","When stakes are moderate, write down the decision you are making and what would prove you wrong. That single sentence prevents the most common failure mode: confident answers built on missing context.","If you are learning with ForgEd quizzes, treat wrong answers as signal, not shame. Re-read the paragraph that contradicts your assumption, then explain the correct idea aloud once. That transfer beats rereading bullet lists silently."]),
  ], {
    learningObjectives: ["Explain why reporting threats matters in modern threat awareness work","Apply core ideas from this chapter to realistic workplace decisions","Identify common mistakes professionals make around reporting threats","Use chapter review questions to verify understanding before advancing"],
    chapterSummary: "Reporting Threats connects theory to practice: you learn what to do, what to avoid, and how to explain your choices to customers, managers, or teammates. The sections build in order—skipping ahead usually costs time later.",
    keyConcepts: ["foundations and vocabulary","how practitioners think","workplace application","common failures and fixes","putting it together"],
    realWorldRelevance: "Professionals who master reporting threats reduce rework, protect trust, and move faster on the job. This chapter is written for workforce learners, not academic theorists—every section should change how you act Monday morning.",
  })
];
