import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const TROUB_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Troubleshooting Basics",
  subtitle: "ForgEd path course — Troubleshooting Basics",
  paragraphs: [
    "Troubleshooting Basics is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Each chapter includes five sections and section quizzes. Pass chapter quizzes, the course review, and final exam to mark the course complete.",
    "Content is practical workforce education — not licensure, legal, or financial advice.",
  ],
};

export const TROUB_TEXTBOOK: TextbookChapter[] = [
  chapter("trouble-method", 1, "Troubleshooting Method", [
      section("trouble-method-s1", "1.1 Troubleshooting Method — applied practice (1)", ["1.1 Troubleshooting Method — applied practice (1) connects Troubleshooting Method to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("trouble-method-s2", "1.2 Troubleshooting Method — applied practice (2)", ["1.2 Troubleshooting Method — applied practice (2) connects Troubleshooting Method to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("trouble-method-s3", "1.3 Troubleshooting Method — applied practice (3)", ["1.3 Troubleshooting Method — applied practice (3) connects Troubleshooting Method to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("trouble-method-s4", "1.4 Troubleshooting Method — applied practice (4)", ["1.4 Troubleshooting Method — applied practice (4) connects Troubleshooting Method to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("trouble-method-s5", "1.5 Troubleshooting Method — applied practice (5)", ["1.5 Troubleshooting Method — applied practice (5) connects Troubleshooting Method to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("reproduce", 2, "Reproducing Issues", [
      section("reproduce-s1", "2.1 Reproducing Issues — applied practice (1)", ["2.1 Reproducing Issues — applied practice (1) connects Reproducing Issues to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("reproduce-s2", "2.2 Reproducing Issues — applied practice (2)", ["2.2 Reproducing Issues — applied practice (2) connects Reproducing Issues to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("reproduce-s3", "2.3 Reproducing Issues — applied practice (3)", ["2.3 Reproducing Issues — applied practice (3) connects Reproducing Issues to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("reproduce-s4", "2.4 Reproducing Issues — applied practice (4)", ["2.4 Reproducing Issues — applied practice (4) connects Reproducing Issues to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("reproduce-s5", "2.5 Reproducing Issues — applied practice (5)", ["2.5 Reproducing Issues — applied practice (5) connects Reproducing Issues to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("logs", 3, "Reading Logs", [
      section("logs-s1", "3.1 Reading Logs — applied practice (1)", ["3.1 Reading Logs — applied practice (1) connects Reading Logs to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("logs-s2", "3.2 Reading Logs — applied practice (2)", ["3.2 Reading Logs — applied practice (2) connects Reading Logs to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("logs-s3", "3.3 Reading Logs — applied practice (3)", ["3.3 Reading Logs — applied practice (3) connects Reading Logs to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("logs-s4", "3.4 Reading Logs — applied practice (4)", ["3.4 Reading Logs — applied practice (4) connects Reading Logs to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("logs-s5", "3.5 Reading Logs — applied practice (5)", ["3.5 Reading Logs — applied practice (5) connects Reading Logs to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("hardware-trouble", 4, "Hardware Checks", [
      section("hardware-trouble-s1", "4.1 Hardware Checks — applied practice (1)", ["4.1 Hardware Checks — applied practice (1) connects Hardware Checks to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("hardware-trouble-s2", "4.2 Hardware Checks — applied practice (2)", ["4.2 Hardware Checks — applied practice (2) connects Hardware Checks to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("hardware-trouble-s3", "4.3 Hardware Checks — applied practice (3)", ["4.3 Hardware Checks — applied practice (3) connects Hardware Checks to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("hardware-trouble-s4", "4.4 Hardware Checks — applied practice (4)", ["4.4 Hardware Checks — applied practice (4) connects Hardware Checks to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("hardware-trouble-s5", "4.5 Hardware Checks — applied practice (5)", ["4.5 Hardware Checks — applied practice (5) connects Hardware Checks to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("software-trouble", 5, "Software Checks", [
      section("software-trouble-s1", "5.1 Software Checks — applied practice (1)", ["5.1 Software Checks — applied practice (1) connects Software Checks to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("software-trouble-s2", "5.2 Software Checks — applied practice (2)", ["5.2 Software Checks — applied practice (2) connects Software Checks to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("software-trouble-s3", "5.3 Software Checks — applied practice (3)", ["5.3 Software Checks — applied practice (3) connects Software Checks to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("software-trouble-s4", "5.4 Software Checks — applied practice (4)", ["5.4 Software Checks — applied practice (4) connects Software Checks to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("software-trouble-s5", "5.5 Software Checks — applied practice (5)", ["5.5 Software Checks — applied practice (5) connects Software Checks to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("network-trouble", 6, "Network Checks", [
      section("network-trouble-s1", "6.1 Network Checks — applied practice (1)", ["6.1 Network Checks — applied practice (1) connects Network Checks to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("network-trouble-s2", "6.2 Network Checks — applied practice (2)", ["6.2 Network Checks — applied practice (2) connects Network Checks to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("network-trouble-s3", "6.3 Network Checks — applied practice (3)", ["6.3 Network Checks — applied practice (3) connects Network Checks to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("network-trouble-s4", "6.4 Network Checks — applied practice (4)", ["6.4 Network Checks — applied practice (4) connects Network Checks to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("network-trouble-s5", "6.5 Network Checks — applied practice (5)", ["6.5 Network Checks — applied practice (5) connects Network Checks to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("escalation", 7, "Escalation", [
      section("escalation-s1", "7.1 Escalation — applied practice (1)", ["7.1 Escalation — applied practice (1) connects Escalation to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("escalation-s2", "7.2 Escalation — applied practice (2)", ["7.2 Escalation — applied practice (2) connects Escalation to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("escalation-s3", "7.3 Escalation — applied practice (3)", ["7.3 Escalation — applied practice (3) connects Escalation to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("escalation-s4", "7.4 Escalation — applied practice (4)", ["7.4 Escalation — applied practice (4) connects Escalation to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("escalation-s5", "7.5 Escalation — applied practice (5)", ["7.5 Escalation — applied practice (5) connects Escalation to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("documentation", 8, "Documenting Fixes", [
      section("documentation-s1", "8.1 Documenting Fixes — applied practice (1)", ["8.1 Documenting Fixes — applied practice (1) connects Documenting Fixes to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("documentation-s2", "8.2 Documenting Fixes — applied practice (2)", ["8.2 Documenting Fixes — applied practice (2) connects Documenting Fixes to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("documentation-s3", "8.3 Documenting Fixes — applied practice (3)", ["8.3 Documenting Fixes — applied practice (3) connects Documenting Fixes to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("documentation-s4", "8.4 Documenting Fixes — applied practice (4)", ["8.4 Documenting Fixes — applied practice (4) connects Documenting Fixes to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("documentation-s5", "8.5 Documenting Fixes — applied practice (5)", ["8.5 Documenting Fixes — applied practice (5) connects Documenting Fixes to real workforce outcomes in Troubleshooting Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ])
];
