import type { TextbookChapter, TextbookIntro } from "@/lib/courses/textbook/types";
import { chapter, section } from "@/lib/courses/textbook/factory";

export const WARR_TEXTBOOK_INTRO: TextbookIntro = {
  title: "Warranty Basics",
  subtitle: "ForgEd path course — Warranty Basics",
  paragraphs: [
    "Warranty Basics is part of a structured ForgEd Learning Path. Complete courses in order to unlock the next step and earn path certifications.",
    "Each chapter includes five sections and section quizzes. Pass chapter quizzes, the course review, and final exam to mark the course complete.",
    "Content is practical workforce education — not licensure, legal, or financial advice.",
  ],
};

export const WARR_TEXTBOOK: TextbookChapter[] = [
  chapter("factory-warranty", 1, "Factory Warranty", [
      section("factory-warranty-s1", "1.1 Factory Warranty — applied practice (1)", ["1.1 Factory Warranty — applied practice (1) connects Factory Warranty to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("factory-warranty-s2", "1.2 Factory Warranty — applied practice (2)", ["1.2 Factory Warranty — applied practice (2) connects Factory Warranty to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("factory-warranty-s3", "1.3 Factory Warranty — applied practice (3)", ["1.3 Factory Warranty — applied practice (3) connects Factory Warranty to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("factory-warranty-s4", "1.4 Factory Warranty — applied practice (4)", ["1.4 Factory Warranty — applied practice (4) connects Factory Warranty to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("factory-warranty-s5", "1.5 Factory Warranty — applied practice (5)", ["1.5 Factory Warranty — applied practice (5) connects Factory Warranty to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("extended-warranty", 2, "Extended Coverage", [
      section("extended-warranty-s1", "2.1 Extended Coverage — applied practice (1)", ["2.1 Extended Coverage — applied practice (1) connects Extended Coverage to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("extended-warranty-s2", "2.2 Extended Coverage — applied practice (2)", ["2.2 Extended Coverage — applied practice (2) connects Extended Coverage to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("extended-warranty-s3", "2.3 Extended Coverage — applied practice (3)", ["2.3 Extended Coverage — applied practice (3) connects Extended Coverage to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("extended-warranty-s4", "2.4 Extended Coverage — applied practice (4)", ["2.4 Extended Coverage — applied practice (4) connects Extended Coverage to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("extended-warranty-s5", "2.5 Extended Coverage — applied practice (5)", ["2.5 Extended Coverage — applied practice (5) connects Extended Coverage to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("claims-warranty", 3, "Warranty Claims", [
      section("claims-warranty-s1", "3.1 Warranty Claims — applied practice (1)", ["3.1 Warranty Claims — applied practice (1) connects Warranty Claims to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("claims-warranty-s2", "3.2 Warranty Claims — applied practice (2)", ["3.2 Warranty Claims — applied practice (2) connects Warranty Claims to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("claims-warranty-s3", "3.3 Warranty Claims — applied practice (3)", ["3.3 Warranty Claims — applied practice (3) connects Warranty Claims to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("claims-warranty-s4", "3.4 Warranty Claims — applied practice (4)", ["3.4 Warranty Claims — applied practice (4) connects Warranty Claims to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("claims-warranty-s5", "3.5 Warranty Claims — applied practice (5)", ["3.5 Warranty Claims — applied practice (5) connects Warranty Claims to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("documentation-warranty", 4, "Documentation", [
      section("documentation-warranty-s1", "4.1 Documentation — applied practice (1)", ["4.1 Documentation — applied practice (1) connects Documentation to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("documentation-warranty-s2", "4.2 Documentation — applied practice (2)", ["4.2 Documentation — applied practice (2) connects Documentation to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("documentation-warranty-s3", "4.3 Documentation — applied practice (3)", ["4.3 Documentation — applied practice (3) connects Documentation to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("documentation-warranty-s4", "4.4 Documentation — applied practice (4)", ["4.4 Documentation — applied practice (4) connects Documentation to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("documentation-warranty-s5", "4.5 Documentation — applied practice (5)", ["4.5 Documentation — applied practice (5) connects Documentation to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("denials", 5, "Denials and Appeals", [
      section("denials-s1", "5.1 Denials and Appeals — applied practice (1)", ["5.1 Denials and Appeals — applied practice (1) connects Denials and Appeals to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("denials-s2", "5.2 Denials and Appeals — applied practice (2)", ["5.2 Denials and Appeals — applied practice (2) connects Denials and Appeals to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("denials-s3", "5.3 Denials and Appeals — applied practice (3)", ["5.3 Denials and Appeals — applied practice (3) connects Denials and Appeals to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("denials-s4", "5.4 Denials and Appeals — applied practice (4)", ["5.4 Denials and Appeals — applied practice (4) connects Denials and Appeals to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("denials-s5", "5.5 Denials and Appeals — applied practice (5)", ["5.5 Denials and Appeals — applied practice (5) connects Denials and Appeals to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("goodwill", 6, "Goodwill Repairs", [
      section("goodwill-s1", "6.1 Goodwill Repairs — applied practice (1)", ["6.1 Goodwill Repairs — applied practice (1) connects Goodwill Repairs to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("goodwill-s2", "6.2 Goodwill Repairs — applied practice (2)", ["6.2 Goodwill Repairs — applied practice (2) connects Goodwill Repairs to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("goodwill-s3", "6.3 Goodwill Repairs — applied practice (3)", ["6.3 Goodwill Repairs — applied practice (3) connects Goodwill Repairs to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("goodwill-s4", "6.4 Goodwill Repairs — applied practice (4)", ["6.4 Goodwill Repairs — applied practice (4) connects Goodwill Repairs to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("goodwill-s5", "6.5 Goodwill Repairs — applied practice (5)", ["6.5 Goodwill Repairs — applied practice (5) connects Goodwill Repairs to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("parts-warranty", 7, "Parts Warranty", [
      section("parts-warranty-s1", "7.1 Parts Warranty — applied practice (1)", ["7.1 Parts Warranty — applied practice (1) connects Parts Warranty to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("parts-warranty-s2", "7.2 Parts Warranty — applied practice (2)", ["7.2 Parts Warranty — applied practice (2) connects Parts Warranty to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("parts-warranty-s3", "7.3 Parts Warranty — applied practice (3)", ["7.3 Parts Warranty — applied practice (3) connects Parts Warranty to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("parts-warranty-s4", "7.4 Parts Warranty — applied practice (4)", ["7.4 Parts Warranty — applied practice (4) connects Parts Warranty to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("parts-warranty-s5", "7.5 Parts Warranty — applied practice (5)", ["7.5 Parts Warranty — applied practice (5) connects Parts Warranty to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ]),
  chapter("customer-warranty", 8, "Explaining Coverage", [
      section("customer-warranty-s1", "8.1 Explaining Coverage — applied practice (1)", ["8.1 Explaining Coverage — applied practice (1) connects Explaining Coverage to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("customer-warranty-s2", "8.2 Explaining Coverage — applied practice (2)", ["8.2 Explaining Coverage — applied practice (2) connects Explaining Coverage to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("customer-warranty-s3", "8.3 Explaining Coverage — applied practice (3)", ["8.3 Explaining Coverage — applied practice (3) connects Explaining Coverage to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("customer-warranty-s4", "8.4 Explaining Coverage — applied practice (4)", ["8.4 Explaining Coverage — applied practice (4) connects Explaining Coverage to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
      section("customer-warranty-s5", "8.5 Explaining Coverage — applied practice (5)", ["8.5 Explaining Coverage — applied practice (5) connects Explaining Coverage to real workforce outcomes in Warranty Basics. Learners apply concepts through scenarios, not theory alone.","Progression is sequential: read each section, pass the section quiz, then advance. Assessment items draw from this chapter's question pool.","Use this material to build confidence, employability, and modern skills — verify policies and regulations in your organization before acting."]),
  ])
];
